---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: Ab ONTAP 9.7 kann ONTAP Mediator die MetroCluster-IP-Konfiguration bei der Durchführung einer automatischen ungeplanten Umschaltung unterstützen, indem er ein physisch separates Repository für Statusinformationen bereitstellt. 
---
= Installationsanforderungen für ONTAP Mediator bei MetroCluster IP-Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ihre Umgebung muss bestimmte Anforderungen erfüllen.

Die folgenden Anforderungen gelten für eine Disaster Recovery-Gruppe (DR-Gruppe). Weitere Informationen zu link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR-Gruppen"].

* Wenn Sie Ihre Linux-Version aktualisieren möchten, tun Sie dies, bevor Sie die aktuellste Version von ONTAP Mediator installieren.
* Die ONTAP Mediator- und MetroCluster Tiebreaker-Software sollten nicht beide mit derselben MetroCluster-Konfiguration verwendet werden.
* ONTAP Mediator muss auf einem Linux-Host an einem anderen Standort als den MetroCluster-Sites installiert werden.
+
Die Konnektivität zwischen dem ONTAP Mediator und jedem Standort muss aus zwei separaten Ausfall-Domains bestehen.

* Die automatische ungeplante Umschaltung wird in ONTAP 9.7 und höher unterstützt.
* Ab ONTAP 9.18.1 und ONTAP Mediator 1.11 kann eine einzelne ONTAP Mediator-Instanz bis zu zehn MetroCluster-Konfigurationen gleichzeitig verwalten. In früheren Versionen kann ONTAP Mediator bis zu fünf MetroCluster-Konfigurationen gleichzeitig unterstützen.
* Ab ONTAP 9.18.1 wird IPv6 für ONTAP Mediator 1.11 oder höher in einer MetroCluster IP-Konfiguration unterstützt.




== Netzwerkanforderungen für die Verwendung von ONTAP Mediator in einer MetroCluster-Konfiguration

Um ONTAP Mediator in einer MetroCluster-Konfiguration zu installieren, müssen Sie sicherstellen, dass die Konfiguration mehrere Netzwerkanforderungen erfüllt.

* Latenz
+
Maximale Latenz von weniger als 75 ms (RTT).

+
Jitter darf nicht mehr als 5 ms betragen.

* MTU
+
Die MTU-Größe muss mindestens 1400 betragen.

* Paketverlust
+
Sowohl für das Internet Control Message Protocol (ICMP) als auch für TCP-Datenverkehr muss der Paketverlust unter 0.01 % liegen.

* Bandbreite
+
Die Verbindung zwischen ONTAP Mediator und einer DR-Gruppe muss über eine Bandbreite von mindestens 20 Mbit/s verfügen.

* Unabhängige Konnektivität
+
Es ist eine unabhängige Verbindung zwischen jedem Standort und dem ONTAP Mediator erforderlich. Ein Ausfall an einem Standort darf die IP-Verbindung zwischen den anderen beiden nicht betroffenen Standorten nicht unterbrechen.





== Hostanforderungen für ONTAP Mediator in einer MetroCluster-Konfiguration

Sie müssen sicherstellen, dass die Konfiguration mehrere Host-Anforderungen erfüllt.

* ONTAP Mediator muss an einem externen Standort installiert sein, der physisch von den beiden ONTAP Clustern getrennt ist.
* ONTAP Mediator benötigt nicht mehr als die Mindestanforderungen des Host-Betriebssystems an CPU und Arbeitsspeicher (RAM).
* Zusätzlich zu den Mindestanforderungen des Host-Betriebssystems muss mindestens 30 GB zusätzlicher nutzbarer Festplattenspeicher zur Verfügung stehen.
+
** Jede DR-Gruppe benötigt bis zu 200 MB Festplattenspeicher.






== Firewall-Anforderungen für ONTAP Mediator

ONTAP Mediator nutzt eine Reihe von Ports zur Kommunikation mit bestimmten Diensten.

Wenn Sie eine Firewall eines Drittanbieters verwenden:

* Der HTTPS-Zugriff muss aktiviert sein.
* Es muss so konfiguriert werden, dass der Zugriff auf den Ports 31784 und 3260 erlaubt ist.
+
Bei Verwendung der standardmäßigen Red Hat- oder CentOS-Firewall wird die Firewall während der Mediator-Installation automatisch konfiguriert.



In der folgenden Tabelle sind die Ports aufgeführt, die Sie in Ihrer Firewall zulassen müssen:

[NOTE]
====
* Der iSCSI-Anschluss wird nur in einer MetroCluster IP-Konfiguration benötigt.
* Der 22/tcp-Port wird für den normalen Betrieb nicht benötigt, kann aber für Wartungszwecke vorübergehend aktiviert und nach Abschluss der Wartungssitzung wieder deaktiviert werden.


====
|===


| Port/Services | Quelle | Richtung | Ziel | Zweck 


 a| 
22/tcp
 a| 
Management-Host
 a| 
Eingehend
 a| 
ONTAP Mediator
 a| 
SSH/ONTAP Mediator-Verwaltung



 a| 
31784/tcp
 a| 
Cluster-mgmt- und node-mgmt-LIFs
 a| 
Eingehend
 a| 
ONTAP Mediator Webserver
 a| 
REST API (HTTPS)



 a| 
3260/tcp
 a| 
Node-Management-LIFs
 a| 
Eingehend
 a| 
ONTAP Mediator iSCSI-Ziele
 a| 
iSCSI-Datenverbindung für Mailboxen

|===


== Richtlinien zum Upgrade von ONTAP Mediator in einer MetroCluster-Konfiguration

Wenn Sie ONTAP Mediator aktualisieren, müssen Sie die Linux-Versionsanforderungen erfüllen und die Richtlinien für die Aktualisierung befolgen.

* ONTAP Mediator kann von einer unmittelbar vorhergehenden Version auf die aktuelle Version aktualisiert werden.
* Alle Mediator-Versionen werden von MetroCluster IP-Konfigurationen mit ONTAP 9.7 oder höher unterstützt.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie ONTAP Mediator"^]



== Nach dem Upgrade

Nachdem die Aktualisierung von Mediator und Betriebssystem abgeschlossen ist, sollten Sie den ausgeben `storage iscsi-initiator show` Befehl, um zu bestätigen, dass die Mediator-Verbindungen aktiv sind.
