---
permalink: install-ip/concept_considerations_isls.html 
sidebar: sidebar 
keywords: isl, isls, layer 2, layer 3, shared switch 
summary: Sie sollten die ISL-Anforderungen für Ihre Konfiguration kennen. 
---
= Überlegungen für ISLs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Sie sollten die ISL-Anforderungen für Ihre Konfiguration kennen.



== Grundlegende Anforderungen für MetroCluster-ISL

Für ISLs aller MetroCluster IP Konfigurationen müssen die folgenden Anforderungen erfüllt sein:

* Ein nativer ISL-Switch-Port mit nativer Geschwindigkeit muss eine Verbindung mit einem ISL-Switch-Port mit nativer Geschwindigkeit herstellen.
+
Ein 40-Gbit/s-Port stellt beispielsweise eine Verbindung zu einem Port mit 40 Gbit/s her.

* Ein 10-Gbit/s-Port im einheitlichen Modus (d. h. ohne Breakout-Kabel) kann eine Verbindung zu einem 10-Gbit/s-Port im einheitlichen Modus herstellen.
* Die ISLs zwischen den MetroCluster IP Switches und dem Kundennetzwerk sowie die ISLs zwischen den Zwischenschaltern folgen in puncto Geschwindigkeit den gleichen Regeln.
* Die Anzahl der ISLs zwischen den MetroCluster Switches und Netzwerk-Switches beim Kunden sowie die Anzahl der ISLs zwischen den Netzwerk-Switches des Kunden sind nicht aufeinander abgestimmt.
+
Beispielsweise können MetroCluster-Switches über zwei ISLs mit den Zwischenschaltern verbunden werden, während sich die Zwischenschalter mithilfe von 10 ISLs miteinander verbinden können.

* Die Geschwindigkeit der ISLs zwischen den MetroCluster Switches und Netzwerk-Switches beim Kunden sowie die Geschwindigkeit von ISLs zwischen den Netzwerk-Switches des Kunden sind nicht aufeinander abgestimmt.
+
Beispielsweise können die MetroCluster-Switches über eine 40-Gbit/s-ISL mit den Zwischen-Switches verbunden werden, während sich die Zwischen-Switches mit 100-Gbit/s-ISLs verbinden.

* Die Anzahl und Geschwindigkeit der ISLs, die jeden MetroCluster Switch mit dem Zwischenschalter verbinden, müssen an beiden MetroCluster Standorten identisch sein.




== ISL-Anforderungen in gemeinsam genutzten Layer-2-Netzwerken

Wenn link:../install-ip/concept_considerations_layer_2.html["ISL-Datenverkehr in einem gemeinsam genutzten Netzwerk freigeben"], Sie müssen sicherstellen, dass Sie ausreichende Kapazität und Größe der ISLs angemessen. Eine niedrige Latenz ist für die Replizierung von Daten zwischen den MetroCluster Standorten von großer Bedeutung. Latenzprobleme auf diesen Verbindungen können sich nachteilig auf das Client-I/O auswirken

Sie sollten diese Abschnitte prüfen, um die erforderliche End-to-End-Kapazität der ISLs korrekt zu berechnen. Für MetroCluster Konfigurationen ist ein kontinuierlicher, nicht flüchtiger Cache und die Storage-Replizierung mit niedriger Latenz unerlässlich. Die Latenz im Back-End-Netzwerk wirkt sich auf die Latenz und den Durchsatz aus, die von Client-I/O erkannt werden.



=== Grenzwerte für Latenz und Paketverlust in den ISLs

Die folgenden Anforderungen müssen für Round-Trip-Datenverkehr zwischen den MetroCluster IP-Switches an Site_A und Site_B erfüllt werden. Die MetroCluster-Konfiguration ist dabei im stabilen Betrieb:

* Spezifische Informationen zur Latenz bei und für die maximale Entfernung Ihrer Konfiguration finden Sie im link:https://hwu.netapp.com/["Hardware Universe:"^]
+
Mit zunehmender Entfernung zwischen zwei MetroCluster Standorten steigt die Latenz, in der Regel im Bereich von 1 ms Paketumlaufzeit pro 100 km (62 Meilen). Diese Latenz hängt auch von dem Service Level Agreement (SLA) des Netzwerks ab, bezogen auf die Bandbreite der ISL-Links, die Paketabfallrate und der Jitter auf das Netzwerk. Geringe Bandbreite, hoher Jitter und zufällige Paketverluste führen zu unterschiedlichen Recovery-Mechanismen durch die Switches oder die TCP-Engine auf den Controller-Modulen für eine erfolgreiche Paketzustellung. Diese Recovery-Mechanismen können die Latenz insgesamt erhöhen.

+
Geräte, die zur Latenz beitragen, müssen berücksichtigt werden.

* Paketverlust muss kleiner oder gleich 0.01 % sein.
+
Paketverlust beinhaltet physischen Verlust oder Verlust aufgrund von Überlastung oder Überabonnements.

+
Paketverluste können zu Neuübertragungen und einem Fenster mit verringerter Staus führen.

* Der unterstützte Jitter-Wert beträgt 3 ms für Rundfahrt (bzw. 1.5 ms für eine Richtung).
* Das Netzwerk sollte das SLA für die für den MetroCluster-Datenverkehr erforderliche Bandbreite zuweisen und beibehalten, um Mikrostitze und Spitzen im Datenverkehr zu berücksichtigen.
+
Bei niedriger Bandbreite können es zu Wartezeiten und zu Schwanzfallen bei Switches kommen. Wenn Sie ONTAP 9.7 oder höher verwenden, muss das Netzwerklaufwerk zwischen den beiden Standorten für die MetroCluster-Konfiguration eine minimale Bandbreite von 4.5 Gbit/s bereitstellen.

* MetroCluster-Verkehr sollte nicht die gesamte Bandbreite verbrauchen und hat negative Auswirkungen auf nicht-MetroCluster-Verkehr.
* Das gemeinsam genutzte Netzwerk sollte die Netzwerküberwachung so konfiguriert haben, dass die ISLs auf Auslastung, Fehler (Drops, Verbindungsklappen, Beschädigungen usw.) und Ausfälle überwacht werden.




=== Verbindungsbeschränkungen und Trunking bei den Kunden-Switches

Die vom Kunden bereitgestellten Zwischenschalter müssen die folgenden Anforderungen erfüllen:

* Die Anzahl der Zwischenschalter ist nicht begrenzt und es werden mehr als zwei Schalter zwischen den MetroCluster IP-Switches unterstützt.
+
Die MetroCluster IP-Schalter sollten so nah wie möglich an den Zwischenschaltern für die Langstreckenverbindung platziert werden. Alle ISL-Verbindungen entlang der Route müssen alle Anforderungen für MetroCluster ISL erfüllen.

* Die ISLs im Kundennetzwerk (die ISLs zwischen den Kunden-Switches) müssen so konfiguriert sein, dass genügend Bandbreite vorhanden ist und in der Reihenfolge der Lieferung eingehalten wird.
+
Dies kann durch das Trunking einer ausreichenden Anzahl von Links und durch die Durchsetzung von Richtlinien zur Lastverteilung erfolgen, um die Reihenfolge zu wahren.





=== Andere Netzwerkanforderungen

Die vom Kunden bereitgestellten Zwischenschalter müssen die folgenden Anforderungen erfüllen:

* Das Kundennetzwerk muss zwischen den Standorten dieselben VLANs bereitstellen, die zu den MetroCluster-VLANs wie in der RCF-Datei festgelegt sind.
+
Layer-2-VLANs mit IDs, die zu den MetroCluster-VLAN-IDs passen, müssen das gemeinsam genutzte Netzwerk umfassen.

+
** In ONTAP 9.7 und älteren Systemen erfordern FAS2750 und AFF A220 VLAN 10 und 20.
** In ONTAP 9.8 und höher, FAS2750, AFF A220, FAS500f, AFF A250, FAS8300, AFF A400 und FAS8700 Systeme verwenden standardmäßig VLAN 10 und 20. Sie können andere VLANs während der Schnittstellenerstellung konfigurieren, und sie müssen den Bereich 101-4096 entzogen haben. Für alle zuvor erwähnten Plattformen können Sie das VLAN nur während der Schnittstellenerstellung angeben. Sobald die MetroCluster-Schnittstellen erstellt wurden, kann die VLAN-ID nicht mehr geändert werden. Für alle anderen Plattformen, die zuvor nicht erwähnt wurden, können Sie ein beliebiges VLAN verwenden und die VLAN-ID für diese Plattformen jederzeit ändern. Es ist jedoch erforderlich, dass eine neue RCF-Datei erstellt und angewendet wird.




--
[NOTE]
====
Der RcfFileGenerator erlaubt das Erstellen einer RCF-Datei nicht mit VLANs, die von der Plattform nicht unterstützt werden.

Der RcfFileGenerator kann die Verwendung bestimmter VLAN-IDs einschränken (z. B. wenn sie für die zukünftige Verwendung vorgesehen sind). Im Allgemeinen sind reservierte VLANs bis einschließlich 100.

====
--
* Die MTU-Größe muss auf allen Geräten im End-to-End-Netzwerk auf 9216 eingestellt sein.
* Kein anderer Datenverkehr kann mit höherer Priorität konfiguriert werden als die Service-Klasse (COS) 5.
* ECN (Explicit Congestion Notification) muss auf allen End-to-End-Pfaden konfiguriert werden.




=== Verkabelung der Anforderungen bei der Verwendung von gemeinsam genutzten ISLs

[role="lead"]
Bei der Verwendung von gemeinsam genutzten ISLs in einer MetroCluster IP-Konfiguration müssen Sie sich die Anforderungen für End-to-End MetroCluster ISL bewusst sein, die von Controller-Ports an Standort A zu Controller-Ports an Standort B ausgeführt werden


NOTE: Sie müssen dem folgen <<Grundlegende Anforderungen für MetroCluster-ISL>>.



=== Anzahl der ISLs und Breakout-Kabel im gemeinsam genutzten Netzwerk

Die Anzahl der ISLs, die MetroCluster IP Switches mit dem gemeinsam genutzten Netzwerk verbinden, variiert je nach Switch-Modell und Port-Typ.

|===


| MetroCluster IP-Switch-Modell | Porttyp | Anzahl der ISLs 


 a| 
Von Broadcom unterstützte BES-53248-Switches
 a| 
Native Ports
 a| 
4 ISLs mit 10 oder 25-Gbps-Ports



 a| 
Cisco 3132Q-V
 a| 
Native Ports
 a| 
6 ISLs mit 40-Gbit/s-Ports



 a| 
Cisco 3132Q-V
 a| 
Breakout-Kabel
 a| 
16 x 10 GB/s ISLs



 a| 
Cisco 3232C
 a| 
Native Ports
 a| 
6 ISLs mit 40 oder 100-Gbps-Ports



 a| 
Cisco 3232C
 a| 
Breakout-Kabel
 a| 
16 x 10 GB/s ISLs



 a| 
Cisco 9336C-FX2 (kein Anschluss von NS224-Shelfs)
 a| 
Native Ports
 a| 
6 ISLs mit 40 oder 100 Gbit/s



 a| 
Cisco 9336C-FX2 (kein Anschluss von NS224-Shelfs)
 a| 
Breakout-Kabel
 a| 
16 ISLs mit 10 Gbit/s



 a| 
Cisco 9336C-FX2 (Anschluss von NS224-Shelfs)
 a| 
Native Ports (2)
 a| 
4 ISLs mit 40 oder 100 Gbit/s



 a| 
Cisco 9336C-FX2 (Anschluss von NS224-Shelfs)
 a| 
Breakout-Kabel (2)
 a| 
16 ISLs mit 10 Gbit/s

|===
* Für die Verwendung von 40- oder 100-Gbps-ISL-Ports auf dem BES-53248-Switch ist eine zusätzliche Lizenz erforderlich.
* Wenn Sie die RCF-Dateien für einen Cisco 9336C-FX2 (Anschluss von NS224-Shelves) erstellen, müssen Sie die ISL-Dateien im nativen *oder*-Breakout-Modus konfigurieren.
* Die Verwendung von Breakout-Kabeln (ein physischer Port wird als 4 x 10 Gbps Ports verwendet) wird auf Cisco Switches unterstützt.
* Die RCF-Dateien für die IP-Switches verfügen über Ports im nativen und im Breakout-Modus.
+
Eine Kombination aus ISL-Ports im nativen Port-Speed-Modus und Breakout-Modus wird nicht unterstützt. Alle ISLs der MetroCluster IP Switches zu den Zwischenschaltern in einem Netzwerk müssen dieselbe Geschwindigkeit und Länge haben.

* Die Verwendung externer Verschlüsselungsgeräte (z. B. externe Linkverschlüsselung oder Verschlüsselung über WDM-Geräte) wird unterstützt, solange die Round-Trip-Latenz den oben genannten Anforderungen entspricht.


Für eine optimale Performance sollten Sie mindestens 1 x 40 Gbit/s oder mehrere ISLs mit 10 Gbit/s pro Netzwerk verwenden. Eine einzelne ISL mit 10 Gbit/s pro Netzwerk für AFF A800 Systeme ist stark von der Verwendung abschreckend.

Der maximale theoretische Durchsatz gemeinsam genutzter ISLs (z. B. 240 Gbit/s mit sechs ISLs mit 40 Gbit/s) ist das Szenario für den jeweiligen Fall. Bei Verwendung mehrerer ISLs kann sich statistischer Lastausgleich auf den maximalen Durchsatz auswirken. Es kann zu einer ungleichmäßigen Verteilung kommen und den Durchsatz eines einzelnen ISL verringern.

Wenn bei der Konfiguration L2-VLANs verwendet werden, müssen sie nativ die Standorte umfassen. VLAN-Overlay wie Virtual Extensible LAN (VXLAN) wird nicht unterstützt.

ISLs, die MetroCluster Traffic tragen, müssen native Links zwischen den Switches sein. Link-Sharing-Dienste wie Multiprotocol Label Switching (MPLS)-Links werden nicht unterstützt.



=== Unterstützung für WAN-ISLs auf dem Broadcom BES-53248 Switch

* Mindestanzahl WAN-ISLs pro Fabric: 1 (10 GbE oder 25 GbE oder 40 GbE oder 100 GbE)
* Maximale Anzahl von 10-GbE-WAN-ISLs pro Fabric: 4
* Maximale Anzahl von 25-GbE-WAN-ISLs pro Fabric: 4
* Maximale Anzahl von 40-GbE-WAN-ISLs pro Fabric: 2
* Maximale Anzahl von 100-GbE-WAN-ISLs pro Fabric: 2


Ein 40-GbE- oder 100-GbE-WAN-ISL erfordert eine RCF-Dateiversion 1.40 oder höher.


NOTE: Für zusätzliche Ports sind zusätzliche Lizenzen erforderlich.
