---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: Ab ONTAP 9.7 kann ONTAP Mediator die MetroCluster-IP-Konfiguration bei der Durchführung einer automatischen ungeplanten Umschaltung unterstützen, indem er ein physisch separates Repository für Statusinformationen bereitstellt. 
---
= Installationsanforderungen für ONTAP Mediator bei MetroCluster IP-Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ihre Umgebung muss bestimmte Anforderungen erfüllen.

Die folgenden Anforderungen gelten für eine Disaster Recovery-Gruppe (DR-Gruppe). Weitere Informationen zu link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR-Gruppen"].

* Wenn Sie Ihre Linux-Version aktualisieren möchten, tun Sie dies, bevor Sie die aktuellste Version von ONTAP Mediator installieren.
* Die ONTAP Mediator- und MetroCluster Tiebreaker-Software sollten nicht beide mit derselben MetroCluster-Konfiguration verwendet werden.
* ONTAP Mediator muss auf einem Linux-Host an einem anderen Standort als den MetroCluster-Sites installiert werden.
+
Die Konnektivität zwischen dem ONTAP Mediator und jedem Standort muss aus zwei separaten Ausfall-Domains bestehen.

* Die automatische ungeplante Umschaltung wird in ONTAP 9.7 und höher unterstützt.
* Ab ONTAP 9.19.1 und ONTAP Mediator 1.12 können Sie einen ONTAP Mediator konfigurieren, der HTTPS anstelle von iSCSI für die Kommunikation verwendet. Wenn ONTAP Mediator mit HTTPS konfiguriert ist, kann nur eine MetroCluster IP-Konfiguration pro ONTAP Mediator Instanz überwacht werden. Weitere Informationen finden Sie unter <<Wählen Sie ein Kommunikationsprotokoll für ONTAP Mediator aus.>>.
* Ab ONTAP 9.18.1 und ONTAP Mediator 1.11 kann eine einzelne, mit iSCSI konfigurierte ONTAP Mediator-Instanz bis zu zehn MetroCluster-Konfigurationen gleichzeitig verwalten. In ONTAP 9.17.1 und ONTAP Mediator 1.10 und früher kann ein mit iSCSI konfigurierter ONTAP Mediator bis zu fünf MetroCluster-Konfigurationen gleichzeitig unterstützen.
* Ab ONTAP 9.18.1 wird IPv6 für ONTAP Mediator 1.11 oder höher in einer MetroCluster IP-Konfiguration unterstützt.




== Netzwerkanforderungen für die Verwendung von ONTAP Mediator in einer MetroCluster-Konfiguration

Um ONTAP Mediator in einer MetroCluster-Konfiguration zu installieren, müssen Sie sicherstellen, dass die Konfiguration mehrere Netzwerkanforderungen erfüllt.

* Latenz
+
Maximale Latenz von weniger als 75 ms (RTT).

+
Jitter darf nicht mehr als 5 ms betragen.

* MTU
+
Die MTU-Größe muss mindestens 1400 betragen.

* Paketverlust
+
Sowohl für das Internet Control Message Protocol (ICMP) als auch für TCP-Datenverkehr muss der Paketverlust unter 0.01 % liegen.

* Bandbreite
+
Die Verbindung zwischen ONTAP Mediator und einer DR-Gruppe muss über eine Bandbreite von mindestens 20 Mbit/s verfügen.

* Unabhängige Konnektivität
+
Es ist eine unabhängige Verbindung zwischen jedem Standort und dem ONTAP Mediator erforderlich. Ein Ausfall an einem Standort darf die IP-Verbindung zwischen den anderen beiden nicht betroffenen Standorten nicht unterbrechen.





== Hostanforderungen für ONTAP Mediator in einer MetroCluster-Konfiguration

Sie müssen sicherstellen, dass die Konfiguration mehrere Host-Anforderungen erfüllt.

* ONTAP Mediator muss an einem externen Standort installiert sein, der physisch von den beiden ONTAP Clustern getrennt ist.
* ONTAP Mediator benötigt nicht mehr als die Mindestanforderungen des Host-Betriebssystems an CPU und Arbeitsspeicher (RAM).
* Zusätzlich zu den Mindestanforderungen des Host-Betriebssystems muss mindestens 30 GB zusätzlicher nutzbarer Festplattenspeicher zur Verfügung stehen.
+
** Jede DR-Gruppe benötigt bis zu 200 MB Festplattenspeicher.






== Wählen Sie ein Kommunikationsprotokoll für ONTAP Mediator aus.

Standardmäßig greifen MetroCluster IP-Knoten über iSCSI-Sitzungen auf ONTAP Mediator-Mailbox-LUNs zu. ONTAP Mediator verwendet das SCST-Paket für iSCSI. Die Authentifizierung der iSCSI-Sitzungen erfolgt mittels Challenge Handshake Authentication Protocol (CHAP) mit einem verschleierten, maschinell generierten Pre-Shared Key, jedoch ohne vollständige Verschlüsselung.

Ab ONTAP 9.19.1 und ONTAP Mediator 1.12 können Sie eine ONTAP Mediator-Instanz konfigurieren, die HTTPS anstelle von iSCSI für die Kommunikation verwendet. HTTPS ist ein sicheres Kommunikationsprotokoll, das ganze Sitzungen mit SSL/TLS verschlüsselt und somit im Vergleich zu iSCSI eine höhere Sicherheit bietet.

Ein ONTAP Mediator, der HTTPS verwendet, kann nur über die Befehlszeilenschnittstelle (CLI) konfiguriert werden. System Manager wird nicht unterstützt.

[CAUTION]
====
* Wenn Sie ONTAP Mediator mit HTTPS konfigurieren, kann eine einzelne ONTAP Mediator-Instanz nur eine MetroCluster IP-Konfiguration überwachen. Die Überwachung mehrerer MetroCluster IP-Konfigurationen gleichzeitig wird nicht unterstützt.
* Wenn Sie ONTAP Mediator mit HTTPS zur Überwachung mehrerer MetroCluster IP-Konfigurationen benötigen, müssen Sie separate ONTAP Mediator-Instanzen für jede MetroCluster IP-Konfiguration einrichten. Sie müssen die Anforderungen Ihrer MetroCluster IP-Umgebung sorgfältig prüfen, bevor Sie sich entscheiden, ONTAP Mediator mit HTTPS für MetroCluster IP zu konfigurieren.
* Wenn Sie mit einer einzigen ONTAP Mediator-Instanz mehr als eine MetroCluster IP-Konfiguration überwachen möchten, sollten Sie ONTAP Mediator mit iSCSI anstatt mit HTTPS konfigurieren.


====
Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["HTTPS- und iSCSI-Installationsoptionen für ONTAP Mediator"^].



== Richtlinien zum Upgrade von ONTAP Mediator in einer MetroCluster-Konfiguration

Wenn Sie ONTAP Mediator aktualisieren, müssen Sie die Linux-Versionsanforderungen erfüllen und die Richtlinien für die Aktualisierung befolgen.

* ONTAP Mediator kann von einer unmittelbar vorhergehenden Version auf die aktuelle Version aktualisiert werden.
* Alle Mediator-Versionen werden von MetroCluster IP-Konfigurationen mit ONTAP 9.7 oder höher unterstützt.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie ONTAP Mediator"^]



== Nach dem Upgrade

Nachdem die Aktualisierung von Mediator und Betriebssystem abgeschlossen ist, sollten Sie den ausgeben `storage iscsi-initiator show` Befehl, um zu bestätigen, dass die Mediator-Verbindungen aktiv sind.
