---
permalink: install-ip/concept-network-speeds-and-switchport-modes.html 
sidebar: sidebar 
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed, switch port mode 
summary: Wenn Sie MetroCluster-kompatible Switches verwenden, sollten Sie die plattformspezifischen Netzwerkgeschwindigkeiten und die Anforderungen für den Switch-Port-Modus kennen. 
---
= ONTAP -plattformspezifische Netzwerkgeschwindigkeiten und Switch-Port-Modi für MetroCluster-kompatible Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie MetroCluster-kompatible Switches verwenden, sollten Sie die plattformspezifischen Netzwerkgeschwindigkeiten und die Anforderungen für den Switch-Port-Modus kennen.

Die folgende Tabelle bietet plattformspezifische Netzwerkgeschwindigkeiten und Switch Port-Modi für MetroCluster-konforme Switches. Sie sollten den Switch-Port-Modus gemäß der Tabelle konfigurieren.

[NOTE]
====
* Fehlende Werte geben an, dass die Plattform nicht mit einem MetroCluster-konformen Switch verwendet werden kann.
* AFF A30, AFF C30, AFF C60 und FAS50 Systeme benötigen einen QSFP-zu-SFP+-Adapter in der Karte auf dem Controller, um eine Netzwerkgeschwindigkeit von 25 Gbit/s zu unterstützen.


====
[cols="1,2,2"]
|===
| Plattform | Netzwerkgeschwindigkeit (Gbit/s) | Switch-Port-Modus 


 a| 
FAS9500

AFF A900

ASA A900
 a| 
100Gbps

40 Gbit/s beim Upgrade des PCM von FAS9000 oder AFF A700
 a| 
Trunk-Modus



 a| 
AFF C800

ASA C800

AFF A800

ASA A800
 a| 
40Gbps oder 100Gbps
 a| 
Zugriffsmodus



 a| 
FAS9000

AFF A700
 a| 
40Gbps
 a| 
Zugriffsmodus



 a| 
FAS8300

AFF C400

ASA C400

AFF A400

ASA A400
 a| 
40Gbps oder 100Gbps
 a| 
Trunk-Modus



 a| 
AFF A320
 a| 
40Gbps oder 100Gbps
 a| 
Zugriffsmodus



 a| 
FAS8200

AFF A300
 a| 
25Gbps
 a| 
Zugriffsmodus



 a| 
FAS500f

AFF C250

ASA C250

AFF A250

ASA A250
 a| 
-
 a| 
-



 a| 
FAS2750

AFF A220
 a| 
-
 a| 
-



 a| 
AFF A150

ASA A150
 a| 
-
 a| 
-



 a| 
AFF A20
 a| 
25Gbps
 a| 
Trunk-Modus



 a| 
AFF A30
 a| 
25Gbps oder 100Gbps
 a| 
Trunk-Modus



 a| 
AFF C30
 a| 
25Gbps oder 100Gbps
 a| 
Trunk-Modus



 a| 
AFF C60
 a| 
25Gbps oder 100Gbps
 a| 
Trunk-Modus



 a| 
FAS50
 a| 
25Gbps oder 100Gbps
 a| 
Trunk-Modus



 a| 
AFF A50
 a| 
100Gbps
 a| 
Trunk-Modus



 a| 
AFF A70
 a| 
100Gbps
 a| 
Trunk-Modus



 a| 
AFF A90
 a| 
100Gbps
 a| 
Trunk-Modus



 a| 
AFF A1K
 a| 
100Gbps
 a| 
Trunk-Modus



 a| 
AFF C80
 a| 
100Gbps
 a| 
Trunk-Modus



 a| 
FAS70
 a| 
100Gbps
 a| 
Trunk-Modus



 a| 
FAS90
 a| 
100Gbps
 a| 
Trunk-Modus

|===