---
permalink: install-ip/concept_mediator_requirements.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency 
summary: Ab ONTAP 9.7 kann ONTAP Mediator die MetroCluster-IP-Konfiguration bei der Durchführung einer automatischen ungeplanten Umschaltung unterstützen, indem er ein physisch separates Repository für Statusinformationen bereitstellt. 
---
= Vorbereitung der Installation von ONTAP Mediator in einer MetroCluster -IP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ihre Umgebung muss bestimmte Anforderungen erfüllen.

Die folgenden Anforderungen gelten für eine Disaster Recovery-Gruppe (DR-Gruppe). Weitere Informationen zu link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups["DR-Gruppen"].

* Wenn Sie Ihre Linux-Version aktualisieren möchten, tun Sie dies, bevor Sie die aktuellste Version von ONTAP Mediator installieren.
* Die ONTAP Mediator- und MetroCluster Tiebreaker-Software sollten nicht beide mit derselben MetroCluster-Konfiguration verwendet werden.
* ONTAP Mediator muss auf einem Linux-Host an einem anderen Standort als den MetroCluster-Sites installiert werden.
+
Die Konnektivität zwischen dem ONTAP Mediator und jedem Standort muss aus zwei separaten Ausfall-Domains bestehen.

* ONTAP Mediator kann bis zu fünf MetroCluster-Konfigurationen gleichzeitig unterstützen.
* Die automatische ungeplante Umschaltung wird in ONTAP 9.7 und höher unterstützt.
* IPv6 wird mit ONTAP Mediator nicht unterstützt.




== Netzwerkanforderungen für die Verwendung von ONTAP Mediator in einer MetroCluster-Konfiguration

Um ONTAP Mediator in einer MetroCluster-Konfiguration zu installieren, müssen Sie sicherstellen, dass die Konfiguration mehrere Netzwerkanforderungen erfüllt.

* Latenz
+
Maximale Latenz von weniger als 75 ms (RTT).

+
Jitter darf nicht mehr als 5 ms betragen.

* MTU
+
Die MTU-Größe muss mindestens 1400 betragen.

* Paketverlust
+
Sowohl für das Internet Control Message Protocol (ICMP) als auch für TCP-Datenverkehr muss der Paketverlust unter 0.01 % liegen.

* Bandbreite
+
Die Verbindung zwischen ONTAP Mediator und einer DR-Gruppe muss über eine Bandbreite von mindestens 20 Mbit/s verfügen.

* Unabhängige Konnektivität
+
Es ist eine unabhängige Verbindung zwischen jedem Standort und dem ONTAP Mediator erforderlich. Ein Ausfall an einem Standort darf die IP-Verbindung zwischen den anderen beiden nicht betroffenen Standorten nicht unterbrechen.





== Hostanforderungen für ONTAP Mediator in einer MetroCluster-Konfiguration

Sie müssen sicherstellen, dass die Konfiguration mehrere Host-Anforderungen erfüllt.

* ONTAP Mediator muss an einem externen Standort installiert sein, der physisch von den beiden ONTAP Clustern getrennt ist.
* ONTAP Mediator unterstützt maximal fünf MetroCluster-Konfigurationen.
* ONTAP Mediator benötigt nicht mehr als die Mindestanforderungen des Host-Betriebssystems an CPU und Arbeitsspeicher (RAM).
* Zusätzlich zu den Mindestanforderungen des Host-Betriebssystems muss mindestens 30 GB zusätzlicher nutzbarer Festplattenspeicher zur Verfügung stehen.
+
** Jede DR-Gruppe benötigt bis zu 200 MB Festplattenspeicher.






== Firewall-Anforderungen für ONTAP Mediator

ONTAP Mediator verwendet eine Reihe von Ports für die Kommunikation mit bestimmten Diensten.

Wenn Sie eine Firewall eines Drittanbieters verwenden:

* HTTPS-Zugriff muss aktiviert sein.
* Er muss so konfiguriert sein, dass der Zugriff auf die Ports 31784 und 3260 möglich ist.
+
Bei Verwendung der standardmäßigen Red hat oder CentOS Firewall wird die Firewall während der Mediator-Installation automatisch konfiguriert.



In der folgenden Tabelle sind die Ports aufgeführt, die Sie in Ihrer Firewall zulassen müssen:

[NOTE]
====
* Der iSCSI-Port ist nur in einer MetroCluster-IP-Konfiguration erforderlich.
* Der 22/tcp-Port ist für den normalen Betrieb nicht erforderlich, Sie können ihn jedoch vorübergehend für Wartungsarbeiten aktivieren und deaktivieren, wenn die Wartungssitzung beendet ist.


====
|===


| Port/Services | Quelle | Richtung | Ziel | Zweck 


 a| 
22/tcp
 a| 
Management-Host
 a| 
Eingehend
 a| 
ONTAP Mediator
 a| 
SSH / ONTAP Mediatormanagement



 a| 
31784/tcp
 a| 
Cluster-MGM- und Node-MGM-LIFs
 a| 
Eingehend
 a| 
Web-Server ONTAP Mediator
 a| 
REST-API (HTTPS)



 a| 
3260/tcp
 a| 
Knotenverwaltungs-LIFs
 a| 
Bidirektional
 a| 
ONTAP Mediator iSCSI-Ziele
 a| 
ISCSI-Datenverbindung für Mailboxen

|===


== Richtlinien zum Upgrade von ONTAP Mediator in einer MetroCluster-Konfiguration

Wenn Sie ONTAP Mediator aktualisieren, müssen Sie die Linux-Versionsanforderungen erfüllen und die Richtlinien für die Aktualisierung befolgen.

* ONTAP Mediator kann von einer unmittelbar vorhergehenden Version auf die aktuelle Version aktualisiert werden.
* Alle Mediator-Versionen werden von MetroCluster IP-Konfigurationen mit ONTAP 9.7 oder höher unterstützt.


link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie ONTAP Mediator"^]



== Nach dem Upgrade

Nachdem die Aktualisierung von Mediator und Betriebssystem abgeschlossen ist, sollten Sie den ausgeben `storage iscsi-initiator show` Befehl, um zu bestätigen, dass die Mediator-Verbindungen aktiv sind.
