---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: Wenn Ihre Konfiguration nicht gespiegelte Aggregate umfasst, müssen potenzielle Zugriffsprobleme nach dem Switchover berücksichtigt werden. 
---
= Verwendung von nicht gespiegelten Aggregaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihre Konfiguration nicht gespiegelte Aggregate umfasst, müssen potenzielle Zugriffsprobleme nach dem Switchover berücksichtigt werden.



== Überlegungen für nicht gespiegelte Aggregate und hierarchische Namespaces

Wenn Sie hierarchische Namespaces verwenden, sollten Sie den Verbindungspfad so konfigurieren, dass alle Volumes in diesem Pfad sich entweder nur auf gespiegelten Aggregaten oder nur auf nicht gespiegelten Aggregaten befinden. Wenn Sie eine Kombination aus nicht gespiegelten und gespiegelten Aggregaten im Verbindungspfad konfigurieren, ist möglicherweise nach der Umschaltung der Zugriff auf nicht gespiegelte Aggregate verhindert.



== Überlegungen für nicht gespiegelte Aggregate und CRS-Metadaten-Volume und Root-Volumes der Daten-SVM

Der Configuration Replication Service (CRS) Metadaten-Volume und Daten-SVM-Root-Volumes müssen sich in einem gespiegelten Aggregat befinden. Sie können diese Volumes nicht in ein nicht gespiegeltes Aggregat verschieben. Wenn sie sich auf einem nicht gespiegelten Aggregat befinden, sind über Switchover und Switchback-Vorgänge verhandelt es Vetos. Der befehl MetroCluster Check gibt eine Warnung aus, wenn dies der Fall ist.



== Überlegungen für nicht gespiegelte Aggregate und SVMs

SVMs sollten nur auf gespiegelten Aggregaten oder nur auf nicht gespiegelten Aggregaten konfiguriert werden. Beim Konfigurieren einer Kombination aus nicht gespiegelten und gespiegelten Aggregaten kann ein Switchover von mehr als 120 Sekunden durchgeführt werden. So kann ein Datenausfall auftreten, wenn die nicht gespiegelten Aggregate nicht online geschaltet werden.



== Überlegungen für nicht gespiegelte Aggregate und SAN

Vor ONTAP 9.9 sollte sich eine LUN nicht auf einem nicht gespiegelten Aggregat befinden. Das Konfigurieren einer LUN auf einem nicht gespiegelten Aggregat kann zu einem Switchover von mehr als 120 Sekunden bei einem Ausfall der Daten führen.



== Überlegungen beim Hinzufügen von Storage-Shelfs für nicht gespiegelte Aggregate


NOTE: Wenn Sie Shelves hinzufügen, die in einer MetroCluster IP-Konfiguration für nicht gespiegelte Aggregate verwendet werden, müssen Sie Folgendes tun:

. Bevor Sie das Verfahren zum Hinzufügen der Shelves starten, geben Sie den folgenden Befehl ein:
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`

. Vergewissern Sie sich, dass die automatische Festplattenzuordnung deaktiviert ist:
+
`disk option show`

. Befolgen Sie die Schritte des Verfahrens, um das Regal hinzuzufügen.
. Weisen Sie den Node, der im Besitz des nicht gespiegelten Aggregats oder der Aggregate ist, manuell alle Festplatten aus dem neuen Shelf zu.
. Erstellen Sie die Aggregate:
+
`storage aggregate create`

. Geben Sie nach Abschluss des Verfahrens den folgenden Befehl ein:
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`

. Vergewissern Sie sich, dass die automatische Festplattenzuordnung aktiviert ist:
+
`disk option show`


