---
permalink: install-ip/concept_considerations_differences.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker, all san array, asa 
summary: Die verschiedenen MetroCluster Konfigurationen weisen wesentliche Unterschiede in den erforderlichen Komponenten auf. 
---
= Supportmatrix für ONTAP MetroCluster -Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die verschiedenen MetroCluster Konfigurationen weisen wesentliche Unterschiede in den erforderlichen Komponenten auf.

In allen Konfigurationen ist jeder der beiden MetroCluster-Standorte als ONTAP-Cluster konfiguriert. In einer MetroCluster Konfiguration mit zwei Nodes ist jeder Node als Single-Node-Cluster konfiguriert.

|===


| Merkmal | IP-Konfigurationen 2+| Fabric-Attached-Konfigurationen 2+| Stretch-Konfigurationen 


|  |  | *Vier- oder acht-Knoten* | * Zwei Knoten* | * Zwei-Knoten-Brücke-verbunden* | * Zwei-Knoten direkt verbunden* 


 a| 
Anzahl an Controllern
 a| 
Vier oder acht^1^
 a| 
Vier oder acht
 a| 
Zwei
 a| 
Zwei
 a| 
Zwei



 a| 
Storage Fabric mit FC-Switch
 a| 
Nein
 a| 
Ja.
 a| 
Ja.
 a| 
Nein
 a| 
Nein



 a| 
Verwendet eine IP Switch Storage Fabric
 a| 
Ja.
 a| 
Nein
 a| 
Nein
 a| 
Nein
 a| 
Nein



 a| 
Verwendung von FC-to-SAS-Bridges
 a| 
Nein
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Nein



 a| 
Nutzung von Direct-Attached SAS Storage
 a| 
Ja (nur lokal in Verbindung)
 a| 
Nein
 a| 
Nein
 a| 
Nein
 a| 
Ja.



 a| 
Unterstützt ADP
 a| 
Ja (ab ONTAP 9.4)
 a| 
Nein
 a| 
Nein
 a| 
Nein
 a| 
Nein



 a| 
Unterstützt lokale HA
 a| 
Ja.
 a| 
Ja.
 a| 
Nein
 a| 
Nein
 a| 
Nein



 a| 
Unterstützt ONTAP Automatic ungeplante Switchover (AUSO)
 a| 
Nein
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



 a| 
Unterstützt nicht gespiegelte Aggregate
 a| 
Ja (ab ONTAP 9.8)
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



 a| 
Unterstützt den ONTAP Mediator
 a| 
Ja (ab ONTAP 9.7)
 a| 
Nein
 a| 
Nein
 a| 
Nein
 a| 
Nein



 a| 
Unterstützung von MetroCluster Tiebreaker
 a| 
Ja (nicht in Kombination mit ONTAP Mediator)
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.



| Unterstützt <<Unterstützung für alle SAN-Array-Systeme in MetroCluster Konfigurationen,Rein SAN-basierte Arrays>>  a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.
 a| 
Ja.

|===
*Hinweise*

. Lesen Sie die folgenden Überlegungen für MetroCluster IP-Konfigurationen mit acht Nodes:
+
** Konfigurationen mit acht Nodes werden ab ONTAP 9.9 unterstützt.
** Es werden nur NetApp validierte MetroCluster Switches (bei NetApp bestellt) unterstützt.
** Konfigurationen, die IP-geroutet (Layer 3)-Back-End-Verbindungen verwenden, werden nicht unterstützt.






== Unterstützung für alle SAN-Array-Systeme in MetroCluster Konfigurationen

Einige der All-SAN-Arrays (ASAs) werden in MetroCluster-Konfigurationen unterstützt. In der MetroCluster-Dokumentation gelten die Informationen zu AFF-Modellen auf das entsprechende ASA-System. Beispielsweise gelten alle Kabel und weitere Informationen zum AFF A400 System auch für das ASA AFF A400 System.

Unterstützte Plattformkonfigurationen sind im aufgeführt link:https://hwu.netapp.com["NetApp Hardware Universe"^].
