---
permalink: install-ip/concept_considerations_mediator.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker 
summary: Die verschiedenen MetroCluster Konfigurationen weisen wesentliche Unterschiede in den erforderlichen Komponenten auf. 
---
= Unterschiede zwischen ONTAP Mediator und MetroCluster Tiebreaker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.7 können Sie entweder die ONTAP Mediator-gestützte automatische ungeplante Umschaltung (MAUSO) in der MetroCluster IP-Konfiguration verwenden oder die MetroCluster Tiebreaker Software verwenden. Es ist nicht erforderlich, die MAUSO- oder Tiebreaker-Software zu verwenden; wenn Sie jedoch einen dieser Dienste nicht nutzen möchten, müssen Sie dies tun link:../disaster-recovery/concept_dr_workflow.html["Führen Sie eine manuelle Wiederherstellung durch"] Bei einem Ausfall.

Die verschiedenen MetroCluster Konfigurationen führen unter unterschiedlichen Umständen automatische Umschaltung durch:

* *MetroCluster FC-Konfigurationen mit der AUSO-Fähigkeit (nicht in MetroCluster IP-Konfigurationen vorhanden)*
+
In diesen Konfigurationen wird AUSO initiiert, wenn Controller ausfallen, der Speicher (und ggf. Brücken) jedoch betriebsbereit bleiben.

* *MetroCluster-IP-Konfigurationen mit ONTAP Mediator (ONTAP 9.7 und höher)*
+
In diesen Konfigurationen wird MAUSO unter denselben Umständen wie AUSO wie oben beschrieben initiiert, aber auch nach einem kompletten Standortausfall (Controller, Storage und Switches).

+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Erfahren Sie, wie der ONTAP Mediator die automatische ungeplante Umschaltung unterstützt"].

* *MetroCluster IP- oder FC-Konfigurationen mit der Tiebreaker Software im aktiven Modus*
+
Bei diesen Konfigurationen initiiert der Tiebreaker eine ungeplante Umschaltung nach einem vollständigen Standortausfall.

+
Bevor Sie die Tiebreaker Software verwenden, überprüfen Sie das link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation und Konfiguration der MetroCluster Tiebreaker Software"]





== Interoperabilität von ONTAP Mediator mit anderen Anwendungen und Geräten

Es ist nicht möglich, Applikationen oder Appliances von Drittanbietern zu verwenden, die in Kombination mit ONTAP Mediator eine Umschaltung auslösen können. Darüber hinaus wird das Monitoring einer MetroCluster-Konfiguration mit MetroCluster Tiebreaker Software bei Verwendung des ONTAP Mediator nicht unterstützt.
