---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html 
sidebar: sidebar 
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, mediator, tiebreaker 
summary: Wenn Ihre Konfiguration nicht gespiegelte Aggregate umfasst, müssen potenzielle Zugriffsprobleme nach dem Switchover berücksichtigt werden. 
---
= Erfahren Sie mehr über nicht gespiegelte Aggregate in MetroCluster -IP-Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihre Konfiguration nicht gespiegelte Aggregate umfasst, müssen potenzielle Zugriffsprobleme nach dem Switchover berücksichtigt werden.



== Ungespiegelte Aggregate und hierarchische Namespaces

Wenn Sie hierarchische Namespaces verwenden, sollten Sie den Verbindungspfad so konfigurieren, dass alle Volumes in diesem Pfad sich entweder nur auf gespiegelten Aggregaten oder nur auf nicht gespiegelten Aggregaten befinden. Wenn Sie eine Kombination aus nicht gespiegelten und gespiegelten Aggregaten im Verbindungspfad konfigurieren, ist möglicherweise nach der Umschaltung der Zugriff auf nicht gespiegelte Aggregate verhindert.



== Ungespiegelte Aggregate und Wartung, die eine Stromabschaltung erfordert

Wenn Sie zu Wartungszwecken eine vereinbarte Umschaltung durchführen, die eine standortweite Stromabschaltung erfordert, sollten Sie zunächst alle nicht gespiegelten Aggregate im Besitz des Notfallstandorts manuell offline schalten.

Wenn Sie die nicht gespiegelten Aggregate des Notfallstandorts nicht offline schalten, können Knoten am verbleibenden Standort aufgrund von Multi-Disk-Panics ausfallen. Dies kann passieren, wenn umgeschaltete nicht gespiegelte Aggregate offline gehen oder fehlen, weil die Verbindung zum Speicher am Notfallstandort nach einem Stromausfall oder dem Verlust von ISLs verloren geht.



== Ungespiegelte Aggregate, CRS-Metadatenvolumes und Daten-SVM-Root-Volumes

Der Configuration Replication Service (CRS) Metadaten-Volume und Daten-SVM-Root-Volumes müssen sich in einem gespiegelten Aggregat befinden. Sie können diese Volumes nicht in ein nicht gespiegeltes Aggregat verschieben. Wenn sie sich auf einem nicht gespiegelten Aggregat befinden, werden ausgehandelte Switchover- und Switchback-Operationen blockiert und die  `metrocluster check` Befehl gibt eine Warnung zurück.



== Ungespiegelte Aggregate und SVMs

Sie sollten SVMs nur auf gespiegelten oder nicht gespiegelten Aggregaten konfigurieren. Die Konfiguration von SVMs auf einer Mischung aus nicht gespiegelten und gespiegelten Aggregaten kann zu einem Umschaltvorgang führen, der länger als 120 Sekunden dauert. Dies kann zu einem Datenausfall führen, wenn die nicht gespiegelten Aggregate nicht online gehen.



== Ungespiegelte Aggregate und SAN

Vor ONTAP 9.9.1 sollte sich eine LUN nicht auf einem nicht gespiegelten Aggregat befinden. Das Konfigurieren einer LUN auf einem nicht gespiegelten Aggregat kann zu einem Switchover von mehr als 120 Sekunden bei einem Ausfall der Daten führen.



== Lagerregale für ungespiegelte Aggregate hinzufügen

Wenn Sie Regale hinzufügen und diese für nicht gespiegelte Aggregate in einer MetroCluster -IP-Konfiguration verwenden möchten, müssen Sie Folgendes tun:

. Bevor Sie das Verfahren zum Hinzufügen der Shelves starten, geben Sie den folgenden Befehl ein:
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`

. Vergewissern Sie sich, dass die automatische Festplattenzuordnung deaktiviert ist:
+
`disk option show`

. Befolgen Sie die Schritte des Verfahrens, um das Regal hinzuzufügen.
. Weisen Sie den Node, der im Besitz des nicht gespiegelten Aggregats oder der Aggregate ist, manuell alle Festplatten aus dem neuen Shelf zu.
. Erstellen Sie die Aggregate:
+
`storage aggregate create`

. Geben Sie nach Abschluss des Verfahrens den folgenden Befehl ein:
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`

. Vergewissern Sie sich, dass die automatische Festplattenzuordnung aktiviert ist:
+
`disk option show`


