---
permalink: install-ip/concept_configure_the_mcc_software_in_ontap.html 
sidebar: sidebar 
keywords: metrocluster, configuration, ontap, node-level, configuration, node, site, relationship, configuring, configure, 
summary: Sie müssen jeden Node in der MetroCluster Konfiguration in ONTAP einrichten, einschließlich der Node-Konfiguration und der Konfiguration der Nodes an zwei Standorten. Sie müssen auch die MetroCluster Beziehung zwischen beiden Standorten implementieren. 
---
= Einrichten der ONTAP Knoten und -Cluster in der MetroCluster -IP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen jeden Node in der MetroCluster Konfiguration in ONTAP einrichten, einschließlich der Node-Konfiguration und der Konfiguration der Nodes an zwei Standorten. Sie müssen auch die MetroCluster Beziehung zwischen beiden Standorten implementieren.

Wenn ein Controller-Modul während der Konfiguration ausfällt, lesen Sie link:../disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html#controller-module-failure-scenarios-during-metrocluster-installation["Ausfallszenarien für Controller-Module während der MetroCluster-Installation"].

image::../media/workflow_mcc_ip_high_level_node_and_cluster_configuration_software.svg[Workflow MetroCluster IP-High-Level-Knoten- und Clusterkonfiguration in ONTAP]



== Konfigurieren Sie MetroCluster IP-Konfigurationen mit acht Knoten

Eine MetroCluster Konfiguration mit acht Nodes besteht aus zwei DR-Gruppen. Um die erste DR-Gruppe zu konfigurieren, führen Sie die Aufgaben in diesem Abschnitt aus. Nachdem Sie die erste DR-Gruppe konfiguriert haben, können Sie die folgenden Schritte ausführen: link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html["Erweitern Sie eine MetroCluster IP-Konfiguration mit vier Knoten auf eine Konfiguration mit acht Knoten"] .
