---
permalink: install-ip/configure-cshm-mccip.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, snmp, health, monitoring 
summary: Sie können die IP-Switches so konfigurieren, dass SNMPv3 für die Zustandsüberwachung verwendet wird. 
---
= Übersicht über die Switch-Integritätsüberwachung in einer MetroCluster-IP-Konfiguration
:allow-uri-read: 


[role="lead"]
Die Ethernet-Switch-Integritätsüberwachung (CSHM) ist für die Sicherstellung des Betriebszustands von Cluster- und Speichernetzwerk-Switches und das Sammeln von Switch-Protokollen für Debugging-Zwecke verantwortlich.



== Wichtige Hinweise zur Konfiguration von CSHM in einer MetroCluster-IP-Konfiguration

Dieser Abschnitt enthält die allgemeinen Schritte zur Konfiguration von SNMPv3 und zur Protokollerfassung auf Cisco-, Broadcom- und NVIDIA SN2100-Switches. Sie müssen die Schritte für eine Switch-Firmware-Version befolgen, die in einer MetroCluster-IP-Konfiguration unterstützt wird. Weitere Informationen finden Sie im link:https://hwu.netapp.com/["Hardware Universe"^] um die unterstützten Firmware-Versionen zu überprüfen.

In einer MetroCluster-Konfiguration konfigurieren Sie die Integritätsüberwachung nur auf den lokalen Cluster-Switches.

Für die Protokollerfassung mit Broadcom- und Cisco-Switches muss für jeden Cluster mit aktivierter Protokollerfassung ein neuer Benutzer auf dem Switch erstellt werden. In einer MetroCluster-Konfiguration bedeutet dies, dass für MetroCluster 1, MetroCluster 2, MetroCluster 3 und MetroCluster 4 jeweils ein separater Benutzer auf den Switches konfiguriert werden muss. Diese Switches unterstützen nicht mehrere SSH-Schlüssel für denselben Benutzer. Bei jeder weiteren Einrichtung der Protokollerfassung werden alle bereits vorhandenen SSH-Schlüssel für den Benutzer überschrieben.

Bevor Sie CSHM konfigurieren, sollten Sie nicht verwendete ISLs deaktivieren, um unnötige ISL-Warnmeldungen zu vermeiden.
