---
permalink: install-ip/overview-isl-requirements.html 
sidebar: sidebar 
keywords: isls, ip, layer 2, layer 3, shared switch 
summary: Hier finden Sie die erforderlichen Informationen zur Überprüfung, ob Ihre MetroCluster-Konfiguration und das Netzwerk alle ISL-Anforderungen erfüllen. 
---
= Inter-Switch-Link-Anforderungen für MetroCluster IP-Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Überprüfen Sie, ob Ihre MetroCluster IP-Konfiguration und Ihr Netzwerk alle ISL-Anforderungen (Inter-Switch Link) erfüllen. Obwohl bestimmte Anforderungen nicht auf Ihre Konfiguration zutreffen, sollten Sie dennoch alle ISL-Anforderungen kennen, um ein besseres Verständnis der Gesamtkonfiguration zu erhalten.

Die folgende Tabelle bietet einen Überblick über die in diesem Abschnitt behandelten Themen.

[cols="25,75"]
|===
| Titel | Beschreibung 


| link:mcc-compliant-netapp-validated-switches.html["Von NetApp validierte und MetroCluster-konforme Switches"] | Beschreibt die Switch-Anforderungen.

Gilt für alle in MetroCluster-Konfigurationen verwendeten Switches, einschließlich Backend-Switches. 


| link:concept-requirements-isls.html["Überlegungen für ISLs"] | Beschreibt die ISL-Anforderungen.

Gilt für alle MetroCluster Konfigurationen, unabhängig von der Netzwerktopologie und ob Sie NetApp validierte Switches oder MetroCluster konforme Switches verwenden. 


| link:concept-considerations-layer-2-layer-3.html["Überlegungen bei der Bereitstellung von MetroCluster in einem gemeinsam genutzten Layer-2- oder Layer-3-Netzwerk"] | Beschreibt die Anforderungen für gemeinsam genutzte Layer-2- oder Layer-3-Netzwerke.

Gilt für alle Konfigurationen mit Ausnahme von MetroCluster Konfigurationen mit von NetApp validierten Switches und mit direkt verbundenen ISLs. 


| link:concept-requirement-and-limitations-mcc-compliant-switches.html["Überlegungen beim Einsatz von MetroCluster-kompatiblen Switches"] | Beschreibt die Anforderungen für MetroCluster-konforme Switches.

Gilt für alle MetroCluster Konfigurationen ohne NetApp validierte Switches. 


| link:concept-example-network-topologies.html["Beispiele für MetroCluster Netzwerktopologien"] | Enthält Beispiele verschiedener MetroCluster-Netzwerktopologien.

Gilt für alle MetroCluster Konfigurationen. 
|===