---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: ONTAP Mediator muss auf dem ONTAP-Knoten für die Verwendung in einer MetroCluster-IP-Konfiguration konfiguriert werden. 
---
= Einrichten des ONTAP Mediators für eine MetroCluster -IP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen den ONTAP Mediator auf dem ONTAP Knoten konfigurieren, um ihn in einer MetroCluster -IP-Konfiguration verwenden zu können.

.Bevor Sie beginnen
* ONTAP Mediator muss erfolgreich an einem Netzwerkstandort installiert worden sein, der von beiden MetroCluster-Standorten aus erreichbar ist.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie ONTAP Mediator"^]

* Sie müssen über die IP-Adresse des Hosts verfügen, auf dem ONTAP Mediator ausgeführt wird.
* Sie müssen über den Benutzernamen und das Passwort für ONTAP Mediator verfügen.
* Alle Nodes der MetroCluster IP-Konfiguration müssen online sein.



CAUTION: Ab ONTAP 9.12.1 kann die Funktion zur automatischen erzwungenen Umschaltung von MetroCluster in einer MetroCluster IP Konfiguration aktiviert werden. Diese Funktion ist eine Erweiterung der mediatorgestützten ungeplanten Umschaltung. Bevor Sie diese Funktion aktivieren, überprüfen Sie die link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["Risiken und Einschränkungen bei der automatischen erzwungenen MetroCluster Umschaltung"].

.Über diese Aufgabe
* Diese Aufgabe ermöglicht standardmäßig automatische ungeplante Umschaltung.
* Diese Aufgabe können Sie auf der ONTAP Schnittstelle eines beliebigen Knotens in der MetroCluster IP-Konfiguration ausführen.
* Ab ONTAP 9.18.1 und ONTAP Mediator 1.11 kann eine einzelne, mit iSCSI konfigurierte ONTAP Mediator-Instanz bis zu zehn MetroCluster-Konfigurationen gleichzeitig verwalten. In ONTAP 9.17.1 und ONTAP Mediator 1.10 und früher kann ein mit iSCSI konfigurierter ONTAP Mediator bis zu fünf MetroCluster-Konfigurationen gleichzeitig unterstützen.
* Ab ONTAP 9.19.1 und ONTAP Mediator 1.12 können Sie ONTAP Mediator mit Unterstützung für iSCSI und HTTPS oder nur für HTTPS installieren. Wenn Sie ONTAP Mediator nur für HTTPS installiert haben, können Sie keinen Mediator mit iSCSI konfigurieren.
* Wenn Sie den  `-type` Parameter im  `metrocluster configuration-settings mediator add` Befehl nicht angeben, wird das Standard-iSCSI-Protokoll verwendet.
* Wenn Sie ONTAP Mediator mit HTTPS konfigurieren, kann eine einzelne ONTAP Mediator-Instanz nur eine MetroCluster IP-Konfiguration überwachen. Die Überwachung mehrerer MetroCluster IP-Konfigurationen gleichzeitig wird nicht unterstützt, wenn ONTAP Mediator mit HTTPS konfiguriert ist.
* Wenn Sie ONTAP Mediator mit HTTPS zur Überwachung mehrerer MetroCluster IP-Konfigurationen benötigen, müssen Sie separate ONTAP Mediator-Instanzen für jede MetroCluster IP-Konfiguration einrichten. Sie müssen die Anforderungen Ihrer MetroCluster IP-Umgebung sorgfältig prüfen, bevor Sie sich entscheiden, ONTAP Mediator mit HTTPS für MetroCluster IP zu konfigurieren.
* Wenn Sie mit einer einzigen ONTAP Mediator-Instanz mehr als eine MetroCluster IP-Konfiguration überwachen möchten, sollten Sie ONTAP Mediator mit iSCSI anstatt mit HTTPS konfigurieren.


[role="tabbed-block"]
====
.Konfigurieren Sie einen ONTAP Mediator mit HTTPS
--
Ab ONTAP 9.19.1 und ONTAP Mediator 1.12 können Sie einen ONTAP Mediator konfigurieren, der HTTPS für die Kommunikation in einer MetroCluster IP-Konfiguration verwendet.

.Schritte
. Suchen Sie die ONTAP Mediator CA-Zertifikate im Installationsverzeichnis der ONTAP Mediator Linux VM/Host-Software:
+
`[root@ontap-mediator ~] cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config`

+
Sie sollten eine Ausgabe sehen, die dem folgenden Beispiel ähnelt:

+
[listing]
----
1-ontap-mediator.rules  intermediate.crt   make_self_signed_certs.sh      ontap_mediator_server_chain.crt  ontap_mediator.user_config.yaml  root_ca.crt
config_migration        intermediate.key   netapp_sudoers                 ontap_mediator_server.crt        openssl_ca.cnf                   root_ca.key
config.pyc              intermediate.srl   ontap_mediator.config.yaml     ontap_mediator_server.csr        openssl_intermediate.cnf
__init__.pyc            logging.conf.yaml  ontap_mediator.constants.yaml  ontap_mediator_server.key        openssl_server.cnf
----
. Zeigen Sie den Inhalt des Stammzertifikats der Zertifizierungsstelle an:
+
`[root@ontap-mediator ~] cat root_ca.crt`

+
[listing]
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
----
. Zeigen Sie den Inhalt des Zwischenzertifikats der Zertifizierungsstelle an:
+
`[root@ontap-mediator ~] cat intermediate.crt`

+
[listing]
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
----
. Installieren Sie die Root- und Zwischenzertifikate der Zertifizierungsstelle auf Standort A:
+
.. Installieren Sie das Root-CA-Zertifikat:
+
`security certificate install -type server-ca -vserver <vserver_name>`

+
Geben Sie die  `root_ca.crt` ein, wenn Sie dazu aufgefordert werden, wie im folgenden Beispiel gezeigt:

+
[listing]
----
cluster_A::*> security certificate install -type server-ca -vserver cluster_A

Enter certificate: Press <Enter> when done

-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----


. Installieren Sie das Zwischenzertifikat der Zertifizierungsstelle:
+
`security certificate install -type server-ca -vserver <vserver_name>`

+
Geben Sie die  `intermediate.crt` ein, wenn Sie dazu aufgefordert werden, wie im folgenden Beispiel gezeigt:

+
[listing]
----
cluster_A::*> security certificate install -type server-ca -vserver cluster_A

Enter certificate: Press <Enter> when done

-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----
. Wiederholen Sie den vorherigen Schritt, um die Root- und Zwischenzertifikate der Zertifizierungsstelle auf Standort B zu installieren.
. Zeigen Sie die installierten selbstsignierten CA-Zertifikate mit dem generierten Namen der Zertifikate an:
+
`security certificate show -common-name <common_name>`

+
Sie sollten eine Ausgabe sehen, die dem folgenden Beispiel ähnelt:

+
[listing]
----
security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number      Certificate Name                     Type
---------- ---------------    ------------------------------------ ------------
cluster_A  <serial_value>     ONTAPMediatorCA                      server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

cluster_A  <serial_value>    ONTAPMediatorCA                       server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

2 entries were displayed.
----
. Fügen Sie ONTAP Mediator zu ONTAP hinzu.  Die einzelnen Schritte hängen davon ab, ob Sie eine IPv4- oder eine IPv6-Adresse verwenden möchten.
+
[NOTE]
====
** Sie benötigen ONTAP 9.18.1 oder höher und ONTAP Mediator 1.11 oder höher, um IPv6 nutzen zu können.
** Wenn Sie IPv6 auf einem Cluster aktivieren, können Sie es später nicht mehr deaktivieren.


====
+
.. Wenn Sie IPv6 verwenden möchten, führen Sie die folgenden Schritte aus:
+
Um IPv4 zu verwenden, fahren Sie mit <<https_ipv4_step8b,der IPv4-Schritt>> fort.

+
... Führen Sie auf beiden Clustern folgenden Befehl aus:
+
`network options ipv6 modify -enabled true`

... Konfigurieren Sie die node-mgmt IP-Adresse mit IPv6-Adressen auf allen vier Knoten.
... Fügen Sie den ONTAP Mediator hinzu:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type https-mediator`

+

NOTE: Geben Sie bei Aufforderung den Benutzernamen und das Passwort des Mediator-Administrators ein.



.. [[https_ipv4_step8b]]Wenn Sie IPv4 verwenden möchten, führen Sie den folgenden Schritt aus:
+
... Fügen Sie den ONTAP Mediator hinzu:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type https-mediator`

+

NOTE: Geben Sie bei Aufforderung den Benutzernamen und das Passwort des Mediator-Administrators ein.





. Überprüfen Sie den Verbindungsstatus und den ONTAP Mediator-Typ:
+
`metrocluster configuration-settings mediator show`

+
Sie sollten eine Ausgabe sehen, die dem folgenden Beispiel ähnelt:

+
[listing]
----
cluster_A::*> metrocluster configuration-settings mediator show
        Mediator IP     Port    Type              Node                    Configuration Connection
                                                  Status                  Status
        --------------- ------- ----------------- ----------------------- ------------- -----------
        10.101.101.101
                        31784   https-mediator    cluster1_node_01        true          true
                                                  cluster1_node_02        true          true
                                                  cluster2_node_01        true          true
                                                  cluster2_node_02        true          true
----
+
.. Stellen Sie sicher, dass die automatische Umschaltfunktion aktiviert ist:
+
`metrocluster show`

.. Überprüfen Sie, ob der Mediator jetzt ausgeführt wird.
+
... Zeigen Sie die virtuellen Mediator-Laufwerke an:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
... Überprüfen Sie den Status der AUSO-Fehlerdomäne (Automatic Unplanmäßigen Switchover):
+
`metrocluster show`

+

NOTE: Die folgende Beispielausgabe gilt für ONTAP 9.13.1 und höher. Bei ONTAP 9.12.1 und älteren Versionen sollte der Status der AUSO-Fehlerdomäne sein `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----






--
.Konfigurieren eines ONTAP Mediators mit iSCSI
--
.Schritte
. Fügen Sie ONTAP Mediator zu ONTAP hinzu.  Die einzelnen Schritte hängen davon ab, ob Sie eine IPv4- oder eine IPv6-Adresse verwenden möchten.
+
[NOTE]
====
** Sie benötigen ONTAP 9.18.1 oder höher und ONTAP Mediator 1.11 oder höher, um IPv6 nutzen zu können.
** Wenn Sie IPv6 auf einem Cluster aktivieren, können Sie es später nicht mehr deaktivieren.


====
+
.. Wenn Sie IPv6 verwenden möchten, führen Sie die folgenden Schritte aus:
+
Um IPv4 zu verwenden, fahren Sie mit <<iscsi_ipv4_step8b,der IPv4-Schritt>> fort.

+
... Führen Sie auf beiden Clustern folgenden Befehl aus:
+
`network options ipv6 modify -enabled true`

... Konfigurieren Sie die node-mgmt IP-Adresse mit IPv6-Adressen auf allen vier Knoten.
... Fügen Sie den ONTAP Mediator hinzu:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type iscsi-mediator`

+

NOTE: Geben Sie bei Aufforderung den Benutzernamen und das Passwort des Mediator-Administrators ein.



.. [[iscsi_ipv4_step8b]]Wenn Sie IPv4 verwenden möchten, führen Sie den folgenden Schritt aus:
+
... Fügen Sie den ONTAP Mediator hinzu:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type iscsi-mediator`

+

NOTE: Geben Sie bei Aufforderung den Benutzernamen und das Passwort des Mediator-Administrators ein.



.. Stellen Sie sicher, dass die automatische Umschaltfunktion aktiviert ist:
+
`metrocluster show`

.. Überprüfen Sie, ob der Mediator jetzt ausgeführt wird.
+
... Zeigen Sie die virtuellen Mediator-Laufwerke an:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
... Legen Sie den Berechtigungsmodus auf erweitert fest:
+
`set advanced`

+
....
 cluster_A::> set advanced
....
... Anzeigen der Initiatoren, die als Mediator bezeichnet werden:
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
... Überprüfen Sie den Status der AUSO-Fehlerdomäne (Automatic Unplanmäßigen Switchover):
+
`metrocluster show`

+

NOTE: Die folgende Beispielausgabe gilt für ONTAP 9.13.1 und höher. Bei ONTAP 9.12.1 und älteren Versionen sollte der Status der AUSO-Fehlerdomäne sein `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----






--
====