---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html 
sidebar: sidebar 
keywords: metrocluster, mediator, configure 
summary: ONTAP Mediator muss auf dem ONTAP-Knoten für die Verwendung in einer MetroCluster-IP-Konfiguration konfiguriert werden. 
---
= Konfigurieren Sie ONTAP Mediator über eine MetroCluster-IP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator muss auf dem ONTAP-Knoten für die Verwendung in einer MetroCluster-IP-Konfiguration konfiguriert werden.

.Bevor Sie beginnen
* ONTAP Mediator muss erfolgreich an einem Netzwerkstandort installiert worden sein, der von beiden MetroCluster-Standorten aus erreichbar ist.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie ONTAP Mediator"^]

* Sie müssen über die IP-Adresse des Hosts verfügen, auf dem ONTAP Mediator ausgeführt wird.
* Sie müssen über den Benutzernamen und das Passwort für ONTAP Mediator verfügen.
* Alle Nodes der MetroCluster IP-Konfiguration müssen online sein.



CAUTION: Ab ONTAP 9.12.1 kann die Funktion zur automatischen erzwungenen Umschaltung von MetroCluster in einer MetroCluster IP Konfiguration aktiviert werden. Diese Funktion ist eine Erweiterung der mediatorgestützten ungeplanten Umschaltung. Bevor Sie diese Funktion aktivieren, überprüfen Sie die link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["Risiken und Einschränkungen bei der automatischen erzwungenen MetroCluster Umschaltung"].

.Über diese Aufgabe
* Diese Aufgabe ermöglicht standardmäßig automatische ungeplante Umschaltung.
* Diese Aufgabe kann auf der ONTAP-Schnittstelle eines beliebigen Knotens der MetroCluster IP-Konfiguration ausgeführt werden.
* Eine einzelne Installation von ONTAP Mediator kann mit bis zu fünf MetroCluster-IP-Konfigurationen konfiguriert werden.


.Schritte
. Fügen Sie ONTAP Mediator zu ONTAP hinzu:
+
`metrocluster configuration-settings mediator add -mediator-address _ip-address-of-mediator-host_`

+

NOTE: Sie werden aufgefordert, den Benutzernamen und das Kennwort für das Mediator Admin-Benutzerkonto einzugeben.

. Stellen Sie sicher, dass die automatische Umschaltfunktion aktiviert ist:
+
`metrocluster show`

. Überprüfen Sie, ob der Mediator jetzt ausgeführt wird.
+
.. Zeigen Sie die virtuellen Mediator-Laufwerke an:
+
`storage disk show -container-type mediator`

+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....
.. Legen Sie den Berechtigungsmodus auf erweitert fest:
+
`set advanced`

+
....
 cluster_A::> set advanced
....
.. Anzeigen der Initiatoren, die als Mediator bezeichnet werden:
+
`storage iscsi-initiator show -label mediator`

+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. Überprüfen Sie den Status der AUSO-Fehlerdomäne (Automatic Unplanmäßigen Switchover):
+
`metrocluster show`

+

NOTE: Die folgende Beispielausgabe gilt für ONTAP 9.13.1 und höher. Bei ONTAP 9.12.1 und älteren Versionen sollte der Status der AUSO-Fehlerdomäne sein `auso-on-cluster-disaster`.

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster
----


. Optional können Sie die automatische erzwungene Umschaltung von MetroCluster konfigurieren.
+
Sie können den folgenden Befehl nur auf der erweiterten Berechtigungsebene verwenden.

+

IMPORTANT: Bevor Sie diesen Befehl verwenden, überprüfen Sie die link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1["Risiken und Einschränkungen bei der automatischen erzwungenen MetroCluster Umschaltung"].

+
`metrocluster modify -allow-auto-forced-switchover true`

+
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

