---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Sie können den ONTAP-Mediator aus der MetroCluster-IP-Konfiguration entfernen. 
---
= Entfernen Sie den ONTAP Mediator aus einer MetroCluster -IP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP Mediator aus der MetroCluster-IP-Konfiguration dekonfigurieren.

.Bevor Sie beginnen
Sie müssen ONTAP Mediator erfolgreich an einem Netzwerkstandort installiert und konfiguriert haben, der von beiden MetroCluster-Sites aus erreichbar ist.

.Schritte
. Dekonfigurieren Sie ONTAP Mediator mit dem folgenden Befehl:
+
`metrocluster configuration-settings mediator remove`

+
Sie werden aufgefordert, den Benutzernamen und das Passwort für das Administratorkonto des ONTAP Mediators einzugeben.

+

NOTE: Wenn der ONTAP Mediator ausfällt,  `metrocluster configuration-settings mediator remove` Der Befehl fordert Sie weiterhin auf, den Benutzernamen und das Kennwort für das ONTAP Mediator-Administratorbenutzerkonto einzugeben, und entfernt ONTAP Mediator aus der MetroCluster-Konfiguration.

+
.. Überprüfen Sie mit dem folgenden Befehl, ob beschädigte Festplatten vorhanden sind:
+
`disk show -broken`

+
*Beispiel*

+
....
There are no entries matching your query.
....


. Bestätigen Sie, dass ONTAP Mediator aus der MetroCluster-Konfiguration entfernt wurde, indem Sie die folgenden Befehle auf beiden Clustern ausführen:
+
.. `metrocluster configuration-settings mediator show`
+
*Beispiel*

+
[listing]
----
This table is currently empty.
----
.. `storage iscsi-initiator show -label mediator`
+
*Beispiel*

+
[listing]
----
There are no entries matching your query.
----



