---
permalink: install-ip/task_switch_config_broadcom.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, factory defaults 
summary: Sie müssen die Broadcom IP-Switches für die Verwendung als Cluster-Interconnect und für die Back-End-MetroCluster-IP-Konnektivität konfigurieren. 
---
= Konfigurieren von Broadcom IP-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Broadcom IP-Switches für die Verwendung als Cluster-Interconnect und für die Back-End-MetroCluster-IP-Konnektivität konfigurieren.


NOTE: Ihre Konfiguration erfordert zusätzliche Lizenzen (6 x 100-GB-Port-Lizenz) in den folgenden Szenarien:

* Die Ports 53 und 54 werden als MetroCluster-ISL mit 40 Gbit/s oder 100 Gbit/s verwendet.
* Sie verwenden eine Plattform, die das lokale Cluster und MetroCluster-Schnittstellen mit den Ports 49 - 52 verbindet.




== Zurücksetzen des Broadcom IP-Switches auf die Werkseinstellungen

Bevor Sie eine neue Switch-Softwareversion und RCFs installieren, müssen Sie die Broadcom-Switch-Einstellungen löschen und eine grundlegende Konfiguration durchführen.

.Über diese Aufgabe
* Sie müssen diese Schritte bei jedem der IP-Switches in der MetroCluster IP-Konfiguration wiederholen.
* Sie müssen über die serielle Konsole mit dem Switch verbunden sein.
* Mit dieser Aufgabe wird die Konfiguration des Managementnetzwerks zurückgesetzt.


.Schritte
. Wechseln Sie zur erhöhten Eingabeaufforderung (`#`): `enable`
+
[listing]
----
(IP_switch_A_1)> enable
(IP_switch_A_1) #
----
. Löschen Sie die Startkonfiguration, und entfernen Sie das Banner
+
.. Löschen der Startkonfiguration:
+
*`erase startup-config`*

+
[listing]
----
(IP_switch_A_1) #erase startup-config

Are you sure you want to clear the configuration? (y/n) y

(IP_switch_A_1) #
----
+
Dieser Befehl löscht das Banner nicht.

.. Entfernen Sie das Banner:
+
*`no set clibanner`*

+
[listing]
----
(IP_switch_A_1) #configure
(IP_switch_A_1)(Config) # no set clibanner
(IP_switch_A_1)(Config) #
----


. Starten Sie den Switch neu:*`(IP_switch_A_1) #reload*`
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: Wenn das System fragt, ob die nicht gespeicherte oder geänderte Konfiguration vor dem erneuten Laden des Switches gespeichert werden soll, wählen Sie *Nein* aus.

. Warten Sie, bis der Schalter neu geladen wurde, und melden Sie sich dann am Switch an.
+
Der Standardbenutzer lautet „`admin`“, und es ist kein Passwort festgelegt. Es wird eine Eingabeaufforderung wie die folgende angezeigt:

+
[listing]
----
(Routing)>
----
. Zur erhöhten Eingabeaufforderung wechseln:
+
`enable`

+
[listing]
----
Routing)> enable
(Routing) #
----
. Legen Sie das Service-Port-Protokoll auf fest `none`:
+
`serviceport protocol none`

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. Weisen Sie die IP-Adresse dem Service-Port zu:
+
`serviceport ip _ip-address_ _netmask_ _gateway_`

+
Das folgende Beispiel zeigt eine dem Service-Port zugewiesene IP-Adresse „10.10.10.10“ mit dem Subnetz „255.255.255.0“ und dem Gateway „10.10.10.1“:

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. Überprüfen Sie, ob der Service-Port ordnungsgemäß konfiguriert ist:
+
`show serviceport`

+
Das folgende Beispiel zeigt, dass der Port als aktiv ist und die richtigen Adressen zugewiesen wurden:

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. Konfigurieren Sie auf Wunsch den SSH-Server.
+

NOTE: Die RCF-Datei deaktiviert das Telnet-Protokoll. Wenn Sie den SSH-Server nicht konfigurieren, können Sie nur über die serielle Port-Verbindung auf die Bridge zugreifen.

+
.. Generieren von RSA-Schlüsseln.
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. DSA-Schlüssel generieren (optional)
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. Wenn Sie die FIPS-konforme Version von EFOS verwenden, generieren Sie die ECDSA-Schlüssel. Im folgenden Beispiel werden die Schlüssel mit einer Länge von 256 erstellt. Gültige Werte sind 256, 384 oder 521.
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. Aktivieren Sie den SSH-Server.
+
Schließen Sie bei Bedarf den Konfigurationskontext.

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: Wenn Schlüssel bereits vorhanden sind, werden Sie möglicherweise aufgefordert, sie zu überschreiben.



. Konfigurieren Sie bei Bedarf die Domäne und den Namensserver:
+
`configure`

+
Das folgende Beispiel zeigt die `ip domain` Und `ip name server` Befehl:

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. Konfigurieren Sie auf Wunsch die Zeitzone und die Zeitsynchronisierung (SNTP).
+
Das folgende Beispiel zeigt die `sntp` Befehle, die IP-Adresse des SNTP-Servers und der relativen Zeitzone angeben.

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
+
Verwenden Sie für EFOS Version 3.10.0.3 und höher den `ntp` Befehl, wie im folgenden Beispiel dargestellt:

+
[listing]
----
> (Config)# ntp ?

authenticate             Enables NTP authentication.
authentication-key       Configure NTP authentication key.
broadcast                Enables NTP broadcast mode.
broadcastdelay           Configure NTP broadcast delay in microseconds.
server                   Configure NTP server.
source-interface         Configure the NTP source-interface.
trusted-key              Configure NTP authentication key number for trusted time source.
vrf                      Configure the NTP VRF.

>(Config)# ntp server ?

ip-address|ipv6-address|hostname  Enter a valid IPv4/IPv6 address or hostname.

>(Config)# ntp server 10.99.99.5
----
. Konfigurieren Sie den Switch-Namen:
+
`hostname IP_switch_A_1`

+
In der Switch-Eingabeaufforderung wird der neue Name angezeigt:

+
[listing]
----
(Routing) # hostname IP_switch_A_1

(IP_switch_A_1) #
----
. Konfiguration speichern:
+
`write memory`

+
Sie erhalten Eingabeaufforderungen und Ausgabe ähnlich dem folgenden Beispiel:

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(IP_switch_A_1) #
----
. Wiederholen Sie die vorherigen Schritte auf den anderen drei Switches in der MetroCluster IP-Konfiguration.




== Herunterladen und Installieren der Broadcom-Switch EFOS-Software

Sie müssen die Betriebssystemdatei und die RCF-Datei auf jeden Switch in der MetroCluster IP-Konfiguration herunterladen.

.Über diese Aufgabe
Diese Aufgabe muss bei jedem Switch in der MetroCluster IP-Konfiguration wiederholt werden.

[]
====
*Beachten Sie Folgendes:*

* Beim Upgrade von EFOS 3.4.x.x auf EFOS 3.7.x.x oder höher muss auf dem Switch EFOS 3.4.4.6 (oder höher 3.4.x.x-Version) ausgeführt werden. Wenn Sie vor dieser Version eine Version ausführen, aktualisieren Sie zuerst den Switch auf EFOS 3.4.4.6 (oder höher 3.4.x.x Version), und aktualisieren Sie dann den Switch auf EFOS 3.7.x.x oder höher.
* Die Konfiguration für EFOS 3.4.x.x und 3.7.x.x oder höher ist unterschiedlich. Wenn Sie die EFOS-Version von 3.4.x.x auf 3.7.x.x oder höher ändern oder umgekehrt, müssen Sie den Switch auf die Werkseinstellungen zurücksetzen und die RCF-Dateien für die entsprechende EFOS-Version werden (neu) angewendet. Für dieses Verfahren ist ein Zugriff über den seriellen Konsolen-Port erforderlich.
* Ab EFOS Version 3.7.x.x oder höher ist eine FIPS-konforme Version und eine FIPS-konforme Version verfügbar. Verschiedene Schritte gelten für den Wechsel von einem nicht FIPS-konformen auf eine FIPS-konforme Version oder umgekehrt. Wenn EFOS von einer nicht FIPS-konformen Version oder umgekehrt geändert wird, wird der Switch auf die Werkseinstellungen zurückgesetzt. Für dieses Verfahren ist ein Zugriff über den seriellen Konsolen-Port erforderlich.


====
.Schritte
. Überprüfen Sie, ob Ihre EFOS-Version FIPS-konform oder nicht-FIPS-konform ist, indem Sie die verwenden `show fips status` Befehl. In den folgenden Beispielen: `IP_switch_A_1` Verwendet FIPS-konformes EFOS und `IP_switch_A_2` Verwendet ein nicht FIPS-konformes EFOS.
+
*Beispiel 1*

+
[listing]
----
IP_switch_A_1 #show fips status

System running in FIPS mode

IP_switch_A_1 #
----
+
*Beispiel 2*

+
[listing]
----
IP_switch_A_2 #show fips status
                     ^
% Invalid input detected at `^` marker.

IP_switch_A_2 #
----
. Bestimmen Sie anhand der folgenden Tabelle, welche Methode Sie befolgen müssen:
+
|===


| *Verfahren* | *Aktuelle EFOS-Version* | * Neue EFOS-Version* | *Hohe Stufen* 


 a| 
Schritte zur Aktualisierung von EFOS zwischen zwei (nicht) FIPS-konformen Versionen
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
Installieren Sie das neue EFOS-Image mit Methode 1) die Konfigurations- und Lizenzinformationen bleiben erhalten



 a| 
3.4.4.6 (oder höher 3.4.x.x)
 a| 
3.7.x.x oder höher ohne FIPS-konform
 a| 
EFOS mit Methode 1 aktualisieren. Setzen Sie den Schalter auf die Werkseinstellungen zurück, und wenden Sie die RCF-Datei für EFOS 3.7.x.x oder höher an



.2+| 3.7.x.x oder höher ohne FIPS-konform  a| 
3.4.4.6 (oder höher 3.4.x.x)
 a| 
EFOS mit Methode 1 abstufen. Setzen Sie den Schalter auf die Werkseinstellungen zurück, und wenden Sie die RCF-Datei für EFOS 3.4.x.x an



 a| 
3.7.x.x oder höher ohne FIPS-konform
 a| 
Installieren Sie das neue EFOS-Image mit Methode 1. Die Konfigurations- und Lizenzdaten bleiben erhalten



 a| 
3.7.x.x oder höher FIPS-konform
 a| 
3.7.x.x oder höher FIPS-konform
 a| 
Installieren Sie das neue EFOS-Image mit Methode 1. Die Konfigurations- und Lizenzdaten bleiben erhalten



 a| 
Schritte zum Upgrade auf/von einer FIPS-konformen EFOS-Version
 a| 
Nicht FIPS-konform
 a| 
FIPS-konform
 a| 
Installation des EFOS-Images unter Verwendung von Methode 2. Informationen zur Switch-Konfiguration und -Lizenz gehen verloren.



 a| 
FIPS-konform
 a| 
Nicht FIPS-konform

|===
+
** Methode 1: <<Schritte zum Aktualisieren von EFOS beim Herunterladen des Software-Images auf die Backup-Boot-Partition>>
** Methode 2: <<Schritte zum Aktualisieren von EFOS mit der ONIE OS-Installation>>






=== Schritte zum Aktualisieren von EFOS beim Herunterladen des Software-Images auf die Backup-Boot-Partition

Die folgenden Schritte können nur ausgeführt werden, wenn beide EFOS-Versionen nicht FIPS-konform sind oder beide EFOS-Versionen FIPS-konform sind.


NOTE: Führen Sie diese Schritte nicht aus, wenn eine Version FIPS-konform ist und die andere Version nicht FIPS-konform ist.

.Schritte
. Kopieren Sie die Switch-Software auf den Switch: `+copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup+`
+
In diesem Beispiel wird die betriebssystemdatei efos-3.4.4.6.stk vom SFTP-Server unter 50.50.50.50 auf die Sicherungspartition kopiert. Sie müssen die IP-Adresse Ihres TFTP/SFTP-Servers und den Dateinamen der RCF-Datei verwenden, die Sie installieren müssen.

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/switchsoftware/efos-3.4.4.6.stk backup
Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /switchsoftware/
Filename....................................... efos-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... backup

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
SFTP Code transfer starting...


File transfer operation completed successfully.

(IP_switch_A_1) #
----
. Legen Sie beim nächsten Neustart des Switches den Switch fest, der von der Backup-Partition aus gestartet werden soll:
+
`boot system backup`

+
[listing]
----
(IP_switch_A_1) #boot system backup
Activating image backup ..

(IP_switch_A_1) #
----
. Vergewissern Sie sich, dass das neue Startabbild beim nächsten Start aktiv ist:
+
`show bootvar`

+
[listing]
----
(IP_switch_A_1) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

 ----  -----------  --------  ---------------  ------------
 unit       active    backup   current-active   next-active
 ----  -----------  --------  ---------------  ------------

	1       3.4.4.2    3.4.4.6      3.4.4.2        3.4.4.6

(IP_switch_A_1) #
----
. Konfiguration speichern:
+
`write memory`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
. Starten Sie den Switch neu:
+
`reload`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
. Warten Sie, bis der Schalter neu gestartet wurde.
+

NOTE: In seltenen Fällen kann der Switch nicht booten. Folgen Sie den <<Schritte zum Aktualisieren von EFOS mit der ONIE OS-Installation>> Um das neue Image zu installieren.

. Wenn Sie den Switch von EFOS 3.4.x.x auf EFOS 3.7.x.x oder umgekehrt umstellen, befolgen Sie die folgenden beiden Verfahren, um die korrekte Konfiguration (RCF) anzuwenden:
+
.. <<Zurücksetzen des Broadcom IP-Switches auf die Werkseinstellungen>>
.. <<Herunterladen und Installieren der Broadcom RCF-Dateien>>


. Wiederholen Sie diese Schritte für die verbleibenden drei IP-Switches in der MetroCluster IP-Konfiguration.




=== Schritte zum Aktualisieren von EFOS mit der ONIE OS-Installation

Sie können die folgenden Schritte durchführen, wenn eine EFOS-Version FIPS-konform ist und die andere EFOS-Version nicht FIPS-konform ist. Mit diesen Schritten kann das nicht-FIPS- oder FIPS-konforme EFOS 3.7.x.x-Image von ONIE installiert werden, wenn der Switch nicht startet.

.Schritte
. Starten Sie den Schalter in den ONIE-Installationsmodus.
+
Wählen Sie während des Startvorgangs ONIE aus, wenn der folgende Bildschirm angezeigt wird:

+
[listing]
----
 +--------------------------------------------------------------------+
 |EFOS                                                                |
 |*ONIE                                                               |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
Nach der Auswahl von „ONIE“ wird der Schalter geladen und Ihnen folgende Auswahlmöglichkeiten zur Verfügung stehen:

+
[listing]
----
 +--------------------------------------------------------------------+
 |*ONIE: Install OS                                                   |
 | ONIE: Rescue                                                       |
 | ONIE: Uninstall OS                                                 |
 | ONIE: Update ONIE                                                  |
 | ONIE: Embed ONIE                                                   |
 | DIAG: Diagnostic Mode                                              |
 | DIAG: Burn-In Mode                                                 |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 |                                                                    |
 +--------------------------------------------------------------------+

----
+
Der Schalter startet nun in den ONIE-Installationsmodus.

. Beenden Sie die ONIE-Erkennung, und konfigurieren Sie die ethernet-Schnittstelle
+
Sobald die folgende Meldung angezeigt wird, drücken Sie <ENTER>, um die ONIE-Konsole zu öffnen:

+
[listing]
----
 Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: Die ONIE-Erkennung wird fortgesetzt, und Meldungen werden auf die Konsole gedruckt.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. Konfigurieren Sie die ethernet-Schnittstelle und fügen Sie die Route mit hinzu `ifconfig eth0 <ipAddress> netmask <netmask> up` Und `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. Stellen Sie sicher, dass der Server, der die ONIE-Installationsdatei hostet, erreichbar ist:
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. Installieren Sie die neue Switch-Software
+
[listing]
----

ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
Die Software wird installiert und startet den Switch dann neu. Lassen Sie den Switch normal in die neue EFOS-Version neu starten.

. Vergewissern Sie sich, dass die neue Switch-Software installiert ist
+
*`show bootvar`*

+
[listing]
----

(Routing) #show bootvar
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	   backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(Routing) #
----
. Schließen Sie die Installation ab
+
Der Switch wird neu gestartet, ohne dass die Konfiguration angewendet wurde, und setzt die Werkseinstellungen zurück. Befolgen Sie die beiden Verfahren, um die Grundeinstellungen des Switches zu konfigurieren und die RCF-Datei anzuwenden, wie in den folgenden beiden Dokumenten beschrieben:

+
.. Konfigurieren Sie die Grundeinstellungen des Switches. Befolgen Sie Schritt 4 und höher: <<Zurücksetzen des Broadcom IP-Switches auf die Werkseinstellungen>>
.. Erstellen und wenden Sie die RCF-Datei wie in beschrieben an <<Herunterladen und Installieren der Broadcom RCF-Dateien>>






== Herunterladen und Installieren der Broadcom RCF-Dateien

Sie müssen die RCF-Datei des Switch auf jedem Switch der MetroCluster IP-Konfiguration herunterladen und installieren.

.Bevor Sie beginnen
Diese Aufgabe erfordert Dateiübertragungssoftware, wie FTP, TFTP, SFTP oder SCP, Um die Dateien auf die Switches zu kopieren.

.Über diese Aufgabe
Diese Schritte müssen bei jedem der IP-Switches in der MetroCluster IP-Konfiguration wiederholt werden.

Es gibt vier RCF-Dateien, eine für jeden der vier Schalter in der MetroCluster IP-Konfiguration. Sie müssen die richtigen RCF-Dateien für das Switch-Modell verwenden, das Sie verwenden.

|===


| Switch | RCF-Datei 


 a| 
IP_Switch_A_1
 a| 
v1.32_Switch-A1.txt



 a| 
IP_Switch_A_2
 a| 
v1.32_Switch-A2.txt



 a| 
IP_Switch_B_1
 a| 
v1.32_Switch-B1.txt



 a| 
IP_Switch_B_2
 a| 
v1.32_Switch-B2.txt

|===

NOTE: Die RCF-Dateien für EFOS Version 3.4.4.6 oder höher 3.4.x.x Version und EFOS Version 3.7.0.4 sind unterschiedlich. Sie müssen sicherstellen, dass Sie die richtigen RCF-Dateien für die EFOS-Version erstellt haben, auf der der Switch ausgeführt wird.

|===


| EFOS-Version | RCF-Dateiversion 


| 3.4.x.x | V1.3x, v1.4x 


| 3.7.x.x | v2.x 
|===
.Schritte
. Generieren Sie die Broadcom RCF-Dateien für die MetroCluster-IP.
+
.. Laden Sie die herunter https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RCfFileGenerator für MetroCluster-IP"]
.. Generieren Sie die RCF-Datei für Ihre Konfiguration mit dem RcfFileGenerator für MetroCluster IP.
+

NOTE: Änderungen an den RCF-Dateien nach dem Download werden nicht unterstützt.



. Kopieren Sie die RCF-Dateien auf die Switches:
+
.. Kopieren Sie die RCF-Dateien auf den ersten Switch:
`copy sftp://user@FTP-server-IP-address/RcfFiles/switch-specific-RCF/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr`
+
In diesem Beispiel wird die RCF-Datei „BES-53248_v1.32_Switch-A1.txt“ vom SFTP-Server unter „50.50.50.50“ in den lokalen Bootflash kopiert. Sie müssen die IP-Adresse Ihres TFTP/SFTP-Servers und den Dateinamen der RCF-Datei verwenden, die Sie installieren müssen.

+
[listing]
----
(IP_switch_A_1) #copy sftp://user@50.50.50.50/RcfFiles/BES-53248_v1.32_Switch-A1.txt nvram:script BES-53248_v1.32_Switch-A1.scr

Remote Password:*************

Mode........................................... SFTP
Set Server IP.................................. 50.50.50.50
Path........................................... /RcfFiles/
Filename....................................... BES-53248_v1.32_Switch-A1.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_v1.32_Switch-A1.scr

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...
File transfer operation completed successfully.


Validating configuration script...

config

set clibanner "***************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248


...
The downloaded RCF is validated. Some output is being logged here.
...


Configuration script validated.
File transfer operation completed successfully.

(IP_switch_A_1) #
----
.. Überprüfen Sie, ob die RCF-Datei als Skript gespeichert ist:
+
`script list`

+
[listing]
----
(IP_switch_A_1) #script list

Configuration Script Name        Size(Bytes)  Date of Modification
-------------------------------  -----------  --------------------
BES-53248_v1.32_Switch-A1.scr             852   2019 01 29 18:41:25

1 configuration script(s) found.
2046 Kbytes free.
(IP_switch_A_1) #
----
.. Anwenden des RCF-Skripts:
+
`script apply BES-53248_v1.32_Switch-A1.scr`

+
[listing]
----
(IP_switch_A_1) #script apply BES-53248_v1.32_Switch-A1.scr

Are you sure you want to apply the configuration script? (y/n) y


config

set clibanner "********************************************************************************

* NetApp Reference Configuration File (RCF)

*

* Switch    : BES-53248

...
The downloaded RCF is validated. Some output is being logged here.
...

Configuration script 'BES-53248_v1.32_Switch-A1.scr' applied.

(IP_switch_A_1) #
----
.. Konfiguration speichern:
+
`write memory`

+
[listing]
----
(IP_switch_A_1) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y


Configuration Saved!

(IP_switch_A_1) #
----
.. Starten Sie den Switch neu:
+
`reload`

+
[listing]
----
(IP_switch_A_1) #reload

Are you sure you would like to reset the system? (y/n) y
----
.. Wiederholen Sie die vorherigen Schritte für jeden der anderen drei Schalter, wobei Sie sicherstellen müssen, dass die entsprechende RCF-Datei auf den entsprechenden Switch kopiert wird.


. Schalter neu laden:
+
`reload`

+
[listing]
----
IP_switch_A_1# reload
----
. Wiederholen Sie die vorherigen Schritte auf den anderen drei Switches in der MetroCluster IP-Konfiguration.




== Deaktivieren Sie nicht verwendete ISL-Ports und Port-Kanäle

NetApp empfiehlt, nicht verwendete ISL-Ports und Port-Kanäle zu deaktivieren, um unnötige Integritätswarnungen zu vermeiden.

. Identifizieren Sie die nicht verwendeten ISL-Ports und Port-Kanäle mithilfe des RCF-Datei-Banners:
+

NOTE: Wenn sich der Port im Breakout-Modus befindet, kann der im Befehl angegebene Portname von dem im RCF-Banner angegebenen Namen abweichen. Sie können auch die RCF-Verkabelungsdateien verwenden, um den Portnamen zu finden.

+
[role="tabbed-block"]
====
.Für Details zum ISL-Port
--
Führen Sie den Befehl aus `show port all`.

--
.Für Port-Channel-Details
--
Führen Sie den Befehl aus `show port-channel all`.

--
====
. Deaktivieren Sie die nicht verwendeten ISL-Ports und Port-Kanäle.
+
Sie müssen die folgenden Befehle für jeden identifizierten nicht verwendeten Port oder Port-Kanal ausführen.

+
[listing]
----
(SwtichA_1)> enable
(SwtichA_1)# configure
(SwtichA_1)(Config)# <port_name>
(SwtichA_1)(Interface 0/15)# shutdown
(SwtichA_1)(Interface 0/15)# end
(SwtichA_1)# write memory
----

