---
permalink: install-ip/task_sw_config_configure_mediator.html 
sidebar: sidebar 
keywords: metrocluster ip, ontap, mediator, tiebreaker 
summary: Sie können entweder die MetroCluster Tiebreaker Software auf einem dritten Standort herunterladen und installieren oder, beginnend mit ONTAP 9.7, dem ONTAP Mediator. 
---
= Konfigurieren der MetroCluster Tiebreaker- oder ONTAP Mediator-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können entweder die MetroCluster Tiebreaker Software auf einem dritten Standort herunterladen und installieren oder, beginnend mit ONTAP 9.7, dem ONTAP Mediator.

.Bevor Sie beginnen
Der verfügbare Linux-Host mit Netzwerkkonnektivität zu beiden Clustern in der MetroCluster-Konfiguration muss über einen Linux-Host verfügen. Die spezifischen Anforderungen sind in der Dokumentation MetroCluster Tiebreaker oder ONTAP Mediator enthalten.

Wenn Sie eine Verbindung zu einer vorhandenen Tiebreaker- oder ONTAP Mediator-Instanz herstellen, benötigen Sie den Benutzernamen, das Kennwort und die IP-Adresse des Tiebreakers oder Mediators.

Wenn Sie eine neue Instanz des ONTAP Mediators installieren müssen, befolgen Sie die Anweisungen, um die Software zu installieren und zu konfigurieren.

link:concept_mediator_requirements.html["Konfigurieren Sie ONTAP Mediator für ungeplante automatische Umschaltung"]

Wenn Sie eine neue Instanz der Tiebreaker Software installieren müssen, befolgen Sie die link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Anweisungen zur Installation und Konfiguration der Software"].

.Über diese Aufgabe
Sie können die MetroCluster Tiebreaker Software und den ONTAP Mediator nicht mit derselben MetroCluster Konfiguration verwenden.

link:../install-ip/concept_considerations_mediator.html["Überlegungen zur Verwendung von ONTAP Mediator oder MetroCluster Tiebreaker"]

.Schritt
. Konfigurieren Sie ONTAP Mediator oder die Tiebreaker-Software:
+
** Wenn Sie eine vorhandene Instanz des ONTAP Mediators verwenden, fügen Sie ONTAP Mediator zu ONTAP hinzu:
+
`metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host`

** Wenn Sie die Tiebreaker Software verwenden, lesen Sie die link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Tiebreaker Dokumentation"].



