---
permalink: install-ip/task_config_switch_health.html 
sidebar: sidebar 
keywords: ip, switch, connection, configuring, configure, broadcom, snmp, health, monitoring 
summary: Sie können die IP-Switches so konfigurieren, dass SNMPv3 für die Zustandsüberwachung verwendet wird. 
---
= Konfigurieren Sie MetroCluster IP-Switches für die Zustandsüberwachung
:allow-uri-read: 


[role="lead"]
In MetroCluster IP-Konfigurationen können Sie SNMPv3 zur Überwachung des Funktionszustands von IP-Switches konfigurieren.



== Schritt 1: Konfigurieren Sie den SNMPv3-Benutzer auf MetroCluster IP-Switches

Führen Sie die folgenden Schritte aus, um den SNMPv3-Benutzer auf den MetroCluster IP-Switches zu konfigurieren.


IMPORTANT: Sie müssen in den Befehlen sowohl die Authentifizierungs- als auch die Datenschutzprotokolle verwenden. Die Verwendung von Authentifizierung ohne Datenschutz wird nicht unterstützt.

[role="tabbed-block"]
====
.Für Broadcom IP-Switches
--
.Schritte
. Wenn die Benutzergruppe „Network-admin“ nicht bereits vorhanden ist, erstellen Sie sie:
+
`(IP_switch_1) (Config)# snmp-server group network-admin v3 auth read "Default"`

. Bestätigen Sie, dass die Gruppe „Network-admin“ erstellt wurde:
+
`(IP_switch_1) (Config)# show snmp group`

. Konfigurieren Sie den SNMPv3-Benutzer auf Broadcom IP-Switches:
+
[listing]
----
(IP_switch_1)# config
(IP_switch_1) (Config)# snmp-server user <user_name> network-admin [auth-md5/auth-sha/noauth] "<auth_password>" [priv-aes128/priv-des] "<priv_password>"
----
+
Sie müssen Anführungszeichen für die Authentifizierungs- und Datenschutzkennwörter verwenden, wie im folgenden Beispiel gezeigt:

+
[listing]
----
snmp-server user admin1 network-admin auth-md5 "password" priv-des "password"
----


--
.Für Cisco IP-Switches
--
.Schritte
. Führen Sie die folgenden Befehle aus, um den SNMPv3-Benutzer auf einem Cisco IP-Switch zu konfigurieren:
+
[listing]
----
IP_switch_A_1 # configure terminal
IP_switch_A_1 (config) # snmp-server user <user_name>  auth [md5/sha/sha-256] <auth_password> priv (aes-128) <priv_password>
----
. Überprüfen Sie, ob der SNMPv3-Benutzer auf dem Switch konfiguriert ist:
+
`IP_switch_A_1(config) # show snmp user <user_name>`

+
Das folgende Beispiel zeigt, dass der Benutzer `admin` Ist für SNMPv3 konfiguriert:

+
[listing]
----
IP_switch_A_1(config)# show snmp user admin
User                Auth      Priv(enforce) Groups              acl_filter

____                ____      _____________ ______              __________

admin               md5       aes-128(no)   network-admin
----


--
====


== Schritt 2: Konfigurieren Sie den SNMPv3-Benutzer in ONTAP

Führen Sie die folgenden Schritte aus, um den SNMPv3-Benutzer in ONTAP zu konfigurieren.

. Konfigurieren Sie den SNMPv3-Benutzer in ONTAP:
+
`security login create -user-or-group-name <user_name> -application snmp -authentication-method usm -remote-switch-ipaddress <ip_address>`

. Konfigurieren Sie die Switch-Statusüberwachung, um den Switch mithilfe des neuen SNMPv3-Benutzers zu überwachen:
+
`system switch ethernet modify -device <device_id> -snmp-version SNMPv3 -community-or-username <user_name>`

. Überprüfen Sie, ob die Seriennummer des Geräts, die mit dem neu erstellten SNMPv3-Benutzer überwacht wird, korrekt ist:
+
.. Den Abfragezeitraum für die Überwachung des Switch-Funktionszustands anzeigen:
+
`system switch ethernet polling-interval show`

.. Führen Sie den folgenden Befehl aus, nachdem der Abfragezeitraum abgelaufen ist:
+
`system switch ethernet show-all -instance -device <device_serial_number>`




