---
permalink: install-ip/task_remove_unconfigure_mediator.html 
sidebar: sidebar 
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements 
summary: Sie können den ONTAP-Mediator aus der MetroCluster-IP-Konfiguration entfernen. 
---
= Entfernen Sie den ONTAP Mediator aus einer MetroCluster -IP-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ONTAP Mediator aus der MetroCluster-IP-Konfiguration dekonfigurieren.

.Bevor Sie beginnen
Sie müssen ONTAP Mediator erfolgreich an einem Netzwerkstandort installiert und konfiguriert haben, der von beiden MetroCluster-Sites aus erreichbar ist.

.Schritte
. Dekonfigurieren Sie ONTAP Mediator mit dem folgenden Befehl:
+
`metrocluster configuration-settings mediator remove`

+
Sie werden aufgefordert, den Benutzernamen und das Passwort für das Administratorkonto des ONTAP Mediators einzugeben.

+

NOTE: Wenn der ONTAP Mediator ausfällt,  `metrocluster configuration-settings mediator remove` Der Befehl fordert Sie weiterhin auf, den Benutzernamen und das Kennwort für das ONTAP Mediator-Administratorbenutzerkonto einzugeben, und entfernt ONTAP Mediator aus der MetroCluster-Konfiguration.

+
.. Überprüfen Sie mit dem folgenden Befehl, ob beschädigte Festplatten vorhanden sind:
+
`disk show -broken`

+
*Beispiel*

+
....
There are no entries matching your query.
....


. Wenn Sie einen ONTAP Mediator verwenden, der HTTPS für die Kommunikation nutzt, löschen Sie die CA-Zertifikate, nachdem Sie den ONTAP Mediator entfernt haben:
+
.. Die installierten CA-Zertifikate anzeigen:
+
`security certificate show -common-name ONTAPMediatorCA`

.. Entfernen Sie die installierten Stamm- und Zwischenzertifikate:
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`

+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`



. Bestätigen Sie, dass ONTAP Mediator aus der MetroCluster-Konfiguration entfernt wurde, indem Sie den folgenden Befehl auf beiden Clustern ausführen:
+
.. `metrocluster configuration-settings mediator show`
+
*Beispiel*

+
[listing]
----
This table is currently empty.
----



