---
permalink: install-ip/task_rack_hw_components.html 
sidebar: sidebar 
keywords: metrocluster ip, rack hardware, components, racking 
summary: Wenn Sie noch nicht die bereits in den Schränken installierten Geräte erhalten haben, müssen Sie die Komponenten in einem Rack unterbringen. 
---
= Rack der MetroCluster IP-Konfigurationshardwarekomponenten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie noch nicht die bereits in den Schränken installierten Geräte erhalten haben, müssen Sie die Komponenten in einem Rack unterbringen.

.Über diese Aufgabe
Dieser Task muss auf beiden MetroCluster-Sites ausgeführt werden.

.Schritte
. Planen der Positionierung der MetroCluster Komponenten
+
Die Rack-Fläche hängt vom Plattformmodell der Controller-Module, den Switch-Typen und der Anzahl der Festplatten-Shelf-Stacks in Ihrer Konfiguration ab.

. Richtig gemahlen.
. Installieren Sie die Controller-Module im Rack oder Schrank.
+
Folgen Sie den Schritten zur _Installation der Hardware_ unter den _Installations- und Setup-Anweisungen_ für Ihr Plattformmodell imlink:https://docs.netapp.com/us-en/ontap-systems/index.html["Dokumentation zu ONTAP -Hardwaresystemen"^] .

. Installieren Sie die IP-Switches im Rack oder Schrank.
. Installieren Sie die Festplatten-Shelfs, schalten Sie sie ein und legen Sie die Shelf-IDs fest.
+
** Sie müssen jedes Festplatten-Shelf aus- und wieder einschalten.
** Um die Fehlerbehebung zu unterstützen, werden für jedes SAS-Platten-Shelf in jeder MetroCluster DR-Gruppe eindeutige Shelf-IDs empfohlen.


+

IMPORTANT: Verkabeln Sie zum jetzigen Zeitpunkt keine Festplatten-Shelfs, die nicht gespiegelte Aggregate enthalten sollen. Sie müssen warten, bis die für nicht gespiegelte Aggregate vorgesehenen Shelfs implementiert sind, bevor die MetroCluster-Konfiguration abgeschlossen ist und diese erst nach Verwendung der implementiert werden `metrocluster modify -enable-unmirrored-aggr-deployment true` Befehl.


