---
permalink: install-ip/task_sw_config_restore_defaults.html 
sidebar: sidebar 
keywords: metrocluster, controller, restore defaults 
summary: Sie müssen die Standardeinstellungen der Controller-Module zurücksetzen und wiederherstellen, um eine saubere Konfiguration zu gewährleisten. 
---
= Stellen Sie die Systemstandards auf einem Controllermodul wieder her, bevor Sie eine MetroCluster IP-Konfiguration einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
Setzen Sie die Standardeinstellungen der Controller-Module zurück und stellen Sie sie wieder her.

. Geben Sie an der LOADER-Eingabeaufforderung Umgebungsvariablen auf ihre Standardeinstellung zurück: `set-defaults`
. Starten Sie den Knoten im Startmenü: `boot_ontap menu`
+
Warten Sie, bis das Startmenü angezeigt wird, nachdem Sie diesen Befehl ausgeführt haben.

. Löschen Sie die Node-Konfiguration:
+
--
** Wenn Sie Systeme verwenden, die für ADP konfiguriert sind, wählen Sie Option `9a` Über das Startmenü und antworten `no` Wenn Sie dazu aufgefordert werden.
+

NOTE: Dieser Prozess ist störend.

+
Auf dem folgenden Bildschirm wird die Eingabeaufforderung des Startmenüs angezeigt:

+
[listing]
----

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 9a
...

########## WARNING: AGGREGATES WILL BE DESTROYED ##########
This is a disruptive operation that applies to all the disks
that are attached and visible to this node.

Before proceeding further, make sure that:

The aggregates visible from this node do not contain
data that needs to be preserved.
This option (9a) has been executed or will be executed
on the HA partner node (and DR/DR-AUX partner nodes if
applicable), prior to reinitializing any system in the
HA-pair or MetroCluster configuration.
The HA partner node (and DR/DR-AUX partner nodes if
applicable) is currently waiting at the boot menu.
Do you want to abort this operation (yes/no)? no
----


--
+
** Wenn Ihr System nicht für ADP konfiguriert ist, geben Sie ein `wipeconfig` Drücken Sie an der Eingabeaufforderung des Startmenüs die Eingabetaste.
+
Auf dem folgenden Bildschirm wird die Eingabeaufforderung des Startmenüs angezeigt:

+
[listing]
----

Please choose one of the following:

    (1) Normal Boot.
    (2) Boot without /etc/rc.
    (3) Change password.
    (4) Clean configuration and initialize all disks.
    (5) Maintenance mode boot.
    (6) Update flash from backup config.
    (7) Install new software first.
    (8) Reboot node.
    (9) Configure Advanced Drive Partitioning.
    Selection (1-9)?  wipeconfig
This option deletes critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?: yes
Rebooting to finish wipeconfig request.
----



