---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: MetroCluster Dokumentation
    url: "/index.html"
  - section: releasenotes
  - section: install-fc
  - section: install-ip
  - section: install-stretch
  - section: tiebreaker
  - title: MetroCluster Datensicherung und Disaster Recovery verstehen
    entries:
    - title: So sichert MetroCluster Daten und bietet Disaster Recovery
      url: "/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html"
  - section: manage
  - section: maintain
  - section: transition
  - section: upgrade
  - section: disaster-recovery
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
