---
permalink: transition/concept_requirements_for_fc_to_ip_transition_mcc.html 
sidebar: sidebar 
keywords: start, transition, process, configuration, requirement, nondisruptive, fc-to-ip 
summary: Bevor Sie mit dem Umstieg beginnen, müssen Sie sicherstellen, dass die Konfiguration die Anforderungen erfüllt. 
---
= Anforderungen für einen unterbrechungsfreien FC-to-IP Umstieg
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit dem Umstieg beginnen, müssen Sie sicherstellen, dass die Konfiguration die Anforderungen erfüllt.

* Sie muss eine Konfiguration mit vier Nodes sein, und alle Nodes müssen ONTAP 9.8 oder höher ausführen.
* Die bestehenden und neuen Plattformen müssen eine unterstützte Kombination für den Umstieg sein.
+
link:concept_supported_platforms_for_transition.html["Unterstützte Plattformen für unterbrechungsfreien Übergang"]

* Er muss eine Switch-Cluster-Konfiguration unterstützen.
+
https://hwu.netapp.com["NetApp Hardware Universe"]

* Er muss alle Anforderungen und Verkabelung erfüllen, wie in den Verfahren _MetroCluster Installation and Configuration_ beschrieben.
+
link:../install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"]

+
link:../install-stretch/concept_considerations_differences.html["Installation und Konfiguration von Stretch MetroCluster"]


