---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: Ab ONTAP 9.8 wird der unterbrechungsfreie Übergang von Workloads und Daten von einer bestehenden MetroCluster FC Konfiguration mit vier Nodes in eine neue MetroCluster IP Konfiguration unterstützt. 
---
= Unterbrechungsfreier Übergang von einer MetroCluster FC- zu einer MetroCluster IP-Konfiguration (ONTAP 9.8 und höher)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.8 wird der unterbrechungsfreie Übergang von Workloads und Daten von einer bestehenden MetroCluster FC Konfiguration mit vier Nodes in eine neue MetroCluster IP Konfiguration unterstützt.

* Dieses Verfahren wird auf Systemen mit ONTAP 9.8 und höher unterstützt.
* Dieses Verfahren ist unterbrechungsfrei.
+
Die MetroCluster Konfiguration kann während des Vorgangs weiterhin Daten bereitstellen.

* Dieses Verfahren gilt nur für MetroCluster FC-Konfigurationen mit vier Nodes.
+
Wenn Sie über eine MetroCluster-FC-Konfiguration mit zwei Nodes verfügen, finden Sie Informationen unter link:concept_choosing_your_transition_procedure_mcc_transition.html["Auswahl des Migrationsverfahrens"].

* Sie müssen alle Anforderungen erfüllen und alle Schritte des Verfahrens befolgen.

