---
permalink: transition/concept_mcc_operation_during_transition.html 
sidebar: sidebar 
keywords: notice, alert, message, transition, alert, safe, ignore, tool, transition 
summary: Sie können während der Umstellung Warnmeldungen bemerken. Diese Warnmeldungen können ohne Bedenken ignoriert werden. Außerdem stehen einige Tools während der Transition nicht zur Verfügung. 
---
= Warnmeldungen und Tool-Unterstützung während der Transition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können während der Umstellung Warnmeldungen bemerken. Diese Warnmeldungen können ohne Bedenken ignoriert werden. Außerdem stehen einige Tools während der Transition nicht zur Verfügung.

* ARS können während des Übergangs warnen.
+
Diese Warnmeldungen können ignoriert werden und sollten nach Abschluss der Transition verschwinden.

* OnCommand Unified Manager gibt während der Transition möglicherweise eine Warnmeldung aus.
+
Diese Warnmeldungen können ignoriert werden und sollten nach Abschluss der Transition verschwinden.

* Config Advisor wird während der Umstellung nicht unterstützt.
* System Manager wird während der Umstellung nicht unterstützt.

