---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html 
sidebar: sidebar 
keywords: nondisruptive, transition, fc, ip 
summary: Ab ONTAP 9.13.1 lassen sich Workloads und Daten unterbrechungsfrei von einer bestehenden MetroCluster FC Konfiguration mit acht Nodes auf eine neue MetroCluster IP Konfiguration übertragen. 
---
= Unterbrechungsfreier Übergang von einer MetroCluster FC- zu einer MetroCluster IP-Konfiguration (ONTAP 9.8 und höher)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können unterbrechungsfreie Übergänge von Workloads und Daten von einer bestehenden MetroCluster FC Konfiguration in eine neue MetroCluster IP Konfiguration durchführen.

Ab ONTAP 9.13.1 wird dieses Verfahren in MetroCluster IP-Konfigurationen unterstützt, bei denen die MetroCluster und die Festplatten-Shelfs mit denselben IP-Switches verbunden sind (eine Konfiguration mit einem Shared Storage Switch).

Ab ONTAP 9.13.1 lassen sich Workloads und Daten unterbrechungsfrei von einer bestehenden MetroCluster FC Konfiguration mit acht Nodes auf eine neue MetroCluster IP Konfiguration übertragen.

Ab ONTAP 9.8 lassen sich unterbrechungsfreie Workloads und Daten von einer bestehenden MetroCluster FC Konfiguration mit vier Nodes auf eine neue MetroCluster IP Konfiguration übertragen.

* Dieses Verfahren ist unterbrechungsfrei.
+
Die MetroCluster Konfiguration kann während des Vorgangs weiterhin Daten bereitstellen.

* Dieses Verfahren gilt nur für MetroCluster FC-Konfigurationen mit vier und acht Nodes.
+
Wenn Sie über eine MetroCluster-FC-Konfiguration mit zwei Nodes verfügen, finden Sie Informationen unter link:concept_choosing_your_transition_procedure_mcc_transition.html["Auswahl des Migrationsverfahrens"].

* In diesem Verfahren werden die Schritte beschrieben, die für den Übergang einer FC-DR-Gruppe mit vier Nodes erforderlich sind. Wenn Sie über eine Konfiguration mit acht Nodes (zwei FC DR-Gruppen) verfügen, müssen Sie den gesamten Vorgang für jede FC DR-Gruppe wiederholen.
* Sie müssen alle Anforderungen erfüllen und alle Schritte des Verfahrens befolgen.


.Wichtige Informationen
Während der Umstellungs-, Aktualisierungs- und Erweiterungsvorgänge können Sie Ihrer MetroCluster-Konfiguration ein neues Plattformmodell hinzufügen. Wenn Ihre vorhandene MetroCluster-Konfiguration zu irgendeinem Zeitpunkt eine Plattform mit *gemeinsamen Cluster-/HA-Ports* enthält, können Sie der Konfiguration keine Plattform mit *gemeinsamen MetroCluster-/HA-Ports* hinzufügen, ohne Ihre ONTAP-Version auf ONTAP 9.15.1P11 oder ONTAP 9.16.1P4 oder höher zu aktualisieren.

Bevor Sie sich für dieses Verfahren entscheiden, lesen Sie die Informationen in der folgenden Tabelle sorgfältig durch. Wenn Ihre vorhandene Plattform in der ersten Spalte und die Plattform, die Sie der Konfiguration hinzufügen möchten, in der zweiten Spalte aufgeführt ist, müssen alle Knoten in der Konfiguration ONTAP 9.15.1P11 oder ONTAP 9.16.1P4 oder höher ausführen, um dieses Verfahren zu unterstützen.


CAUTION: Sowohl die vorhandene Plattform als auch die Plattform, die Sie der Konfiguration hinzufügen möchten, müssen ONTAP 9.15.1P11 oder ONTAP 9.16.1P4 oder höher ausführen.

[cols="20,20,20,20,20"]
|===
2+| Wenn Ihr vorhandener MetroCluster Folgendes enthält: 2+| Und die Plattform, die Sie hinzufügen, ist ... | Dann... 


 a| 
Ein AFF-System, das *gemeinsam genutzte Cluster-/HA-Ports* verwendet:

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K

 a| 
Ein FAS-System, das *gemeinsam genutzte Cluster-/HA-Ports* verwendet:

* FAS50
* FAS70
* FAS90

 a| 
Ein AFF-System, das *gemeinsam genutzte MetroCluster/HA-Ports* verwendet:

* AFF A150, ASA A150
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900

 a| 
Ein FAS-System, das *gemeinsam genutzte MetroCluster/HA-Ports* verwendet:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500

| Bevor Sie die neue Plattform zu Ihrer vorhandenen MetroCluster-Konfiguration hinzufügen, aktualisieren Sie alle Knoten in der vorhandenen und neuen Konfiguration auf ONTAP 9.15.1P11 oder ONTAP 9.16.1P4 oder höher. 
|===