---
permalink: transition/task_remove_mc_fc_controllers.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Um die Konfiguration für den Umstieg vorzubereiten, fügen Sie die neuen Nodes zur bestehenden MetroCluster Konfiguration hinzu und verschieben Sie dann Daten zu den neuen Nodes. 
---
= Entfernen der MetroCluster FC-Controller
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen eine Bereinigung durchführen und die alten Controller-Module aus der MetroCluster-Konfiguration entfernen.

. Um eine automatische Erstellung von Support-Cases zu verhindern, senden Sie eine AutoSupport Meldung, damit die Wartung läuft.
+
.. Geben Sie den folgenden Befehl ein: `system node autosupport invoke -node * -type all -message MAINT=maintenance-window-in-hours`
+
Maintenance-Fenster in Stunden gibt die Länge des Wartungsfensters an, mit maximal 72 Stunden. Wenn die Wartung vor dem Vergehen der Zeit abgeschlossen ist, können Sie eine AutoSupport-Meldung mit dem Ende des Wartungszeitraums aufrufen:``system node autosupport invoke -node * -type all -message MAINT=end``

.. Wiederholen Sie den Befehl im Partner-Cluster.


. Legen Sie die Aggregate fest, die auf der MetroCluster FC-Konfiguration gehostet werden sollen, die gelöscht werden müssen.
+
In diesem Beispiel werden die folgenden Datenaggregate vom MetroCluster FC Cluster_B gehostet und müssen gelöscht werden: aggr_Data_a1 und aggr_Data_a2.

+

NOTE: Sie müssen die Schritte durchführen, um die Datenaggregate auf beiden Clustern zu identifizieren, offline und zu löschen. Das Beispiel gilt nur für ein Cluster.

+
....
cluster_B::> aggr show

Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_node_A_1-FC
           349.0GB   16.83GB   95% online       1 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_2-FC
           349.0GB   16.83GB   95% online       1 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.63GB   95% online       1 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr0_node_A_3-IP
           467.6GB   22.62GB   95% online       1 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a1
            1.02TB    1.02TB    0% online       0 node_A_1-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a2
            1.02TB    1.02TB    0% online       0 node_A_2-FC      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a3
            1.37TB    1.35TB    1% online       3 node_A_3-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
aggr_data_a4
            1.25TB    1.24TB    1% online       2 node_A_4-IP      raid_dp,
                                                                   mirrored,
                                                                   normal
8 entries were displayed.

cluster_B::>
....
. Überprüfen Sie, ob die Datenaggregate auf den FC-Knoten über MDV_aud-Volumes verfügen und löschen Sie sie vor dem Löschen der Aggregate.
+
Sie müssen die MDV_aud-Volumes löschen, da sie nicht verschoben werden können.

. Nehmen Sie alle Datenaggregate offline und löschen Sie sie anschließend:
+
.. Versetzen Sie das Aggregat in den Offline-Modus: `storage aggregate offline -aggregate aggregate-name`
+
Das folgende Beispiel zeigt, dass das Aggregat aggr_Data_a1 offline geschaltet wird:

+
....
cluster_B::> storage aggregate offline -aggregate aggr_data_a1

Aggregate offline successful on aggregate: aggr_data_a1
....
.. Löschen Sie das Aggregat: `storage aggregate delete -aggregate aggregate-name`
+
Sie können den Plex zerstören, wenn Sie dazu aufgefordert werden.

+
Das folgende Beispiel zeigt, dass das Aggregat aggr_Data_a1 gelöscht wird.

+
....
cluster_B::> storage aggregate delete -aggregate aggr_data_a1
Warning: Are you sure you want to destroy aggregate "aggr_data_a1"? {y|n}: y
[Job 123] Job succeeded: DONE

cluster_B::>
....


. Identifizieren Sie die MetroCluster FC DR-Gruppe, die entfernt werden muss.
+
Im folgenden Beispiel befinden sich die MetroCluster FC Nodes in der DR-Gruppe '1', und dies ist die DR-Gruppe, die entfernt werden muss.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        configured     enabled   normal
              node_A_2-FC        configured     enabled   normal
      cluster_B
              node_B_1-FC        configured     enabled   normal
              node_B_2-FC        configured     enabled   normal
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_3-IP        configured     enabled   normal
8 entries were displayed.

cluster_B::>
....
. Verschieben Sie die Cluster-Management-LIF von einem MetroCluster FC Node zu einem MetroCluster IP Node: `cluster_B::> network interface migrate -vserver svm-name -lif cluster_mgmt -destination-node node-in-metrocluster-ip-dr-group -destination-port available-port`
. Ändern Sie den Home Node und den Home Port der Cluster-Management-LIF: `cluster_B::> network interface modify -vserver svm-name -lif cluster_mgmt -service-policy default-management -home-node node-in-metrocluster-ip-dr-group -home-port lif-port`
. Verschieben Sie Epsilon von einem MetroCluster-FC-Node auf einen MetroCluster-IP-Node:
+
.. Identifizieren Sie, welcher Knoten derzeit über Epsilon verfügt: `cluster show -fields epsilon`
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      true
node_A_2-FC      false
node_A_1-IP      false
node_A_2-IP      false
4 entries were displayed.
....
.. Setzen Sie Epsilon auf „false“ auf den MetroCluster-FC-Node (Node_A_1-FC): `cluster modify -node fc-node -epsilon false`
.. Setzen Sie das Epsilon auf „true“ auf dem MetroCluster-IP-Knoten (Node_A_1-IP): `cluster modify -node ip-node -epsilon true`
.. Vergewissern Sie sich, dass sich das Epsilon auf den richtigen Knoten bewegt hat: `cluster show -fields epsilon`
+
....
cluster_B::> cluster show -fields epsilon
node             epsilon
---------------- -------
node_A_1-FC      false
node_A_2-FC      false
node_A_1-IP      true
node_A_2-IP      false
4 entries were displayed.
....


. Ändern Sie die IP-Adresse für den Cluster-Peer der migrierten IP-Nodes für jedes Cluster:
+
.. Identifizieren Sie den Cluster_A-Peer mithilfe der `cluster peer show` Befehl:
+
[listing]
----
cluster_A::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
cluster_B         1-80-000011           Unavailable    absent
----
+
... Peer-IP-Adresse „Cluster_A“ ändern:
+
`cluster peer modify -cluster cluster_A -peer-addrs node_A_3_IP -address-family ipv4`



.. Identifizieren Sie den Cluster_B-Peer mithilfe der `cluster peer show` Befehl:
+
[listing]
----
cluster_B::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
cluster_A         1-80-000011           Unavailable    absent
----
+
... Peer-IP-Adresse für Cluster_B ändern:
+
`cluster peer modify -cluster cluster_B -peer-addrs node_B_3_IP -address-family ipv4`



.. Überprüfen Sie, ob die Cluster-Peer-IP-Adresse für jedes Cluster aktualisiert wurde:
+
... Überprüfen Sie mithilfe der, ob die IP-Adresse für jedes Cluster aktualisiert wurde `cluster peer show -instance` Befehl.
+
Der `Remote Intercluster Addresses` In den folgenden Beispielen wird die aktualisierte IP-Adresse angezeigt.

+
Beispiel für Cluster_A:

+
[listing]
----
cluster_A::> cluster peer show -instance

Peer Cluster Name: cluster_B
           Remote Intercluster Addresses: 172.21.178.204, 172.21.178.212
      Availability of the Remote Cluster: Available
                     Remote Cluster Name: cluster_B
                     Active IP Addresses: 172.21.178.212, 172.21.178.204
                   Cluster Serial Number: 1-80-000011
                    Remote Cluster Nodes: node_B_3-IP,
                                          node_B_4-IP
                   Remote Cluster Health: true
                 Unreachable Local Nodes: -
          Address Family of Relationship: ipv4
    Authentication Status Administrative: use-authentication
       Authentication Status Operational: ok
                        Last Update Time: 4/20/2023 18:23:53
            IPspace for the Relationship: Default
Proposed Setting for Encryption of Inter-Cluster Communication: -
Encryption Protocol For Inter-Cluster Communication: tls-psk
  Algorithm By Which the PSK Was Derived: jpake

cluster_A::>

----
+
Beispiel für „Cluster_B“

+
[listing]
----
cluster_B::> cluster peer show -instance

                       Peer Cluster Name: cluster_A
           Remote Intercluster Addresses: 172.21.178.188, 172.21.178.196 <<<<<<<< Should reflect the modified address
      Availability of the Remote Cluster: Available
                     Remote Cluster Name: cluster_A
                     Active IP Addresses: 172.21.178.196, 172.21.178.188
                   Cluster Serial Number: 1-80-000011
                    Remote Cluster Nodes: node_A_3-IP,
                                          node_A_4-IP
                   Remote Cluster Health: true
                 Unreachable Local Nodes: -
          Address Family of Relationship: ipv4
    Authentication Status Administrative: use-authentication
       Authentication Status Operational: ok
                        Last Update Time: 4/20/2023 18:23:53
            IPspace for the Relationship: Default
Proposed Setting for Encryption of Inter-Cluster Communication: -
Encryption Protocol For Inter-Cluster Communication: tls-psk
  Algorithm By Which the PSK Was Derived: jpake

cluster_B::>
----




. Entfernen Sie auf jedem Cluster die DR-Gruppe, die die alten Nodes enthält, aus der MetroCluster-FC-Konfiguration.
+
Sie müssen diesen Schritt nacheinander für beide Cluster ausführen.

+
....
cluster_B::> metrocluster remove-dr-group -dr-group-id 1

Warning: Nodes in the DR group that are removed from the MetroCluster
         configuration will lose their disaster recovery protection.

         Local nodes "node_A_1-FC, node_A_2-FC" will be removed from the
         MetroCluster configuration. You must repeat the operation on the
         partner cluster "cluster_B" to remove the remote nodes in the DR group.
Do you want to continue? {y|n}: y

Info: The following preparation steps must be completed on the local and partner
      clusters before removing a DR group.

      1. Move all data volumes to another DR group.
      2. Move all MDV_CRS metadata volumes to another DR group.
      3. Delete all MDV_aud metadata volumes that may exist in the DR group to
      be removed.
      4. Delete all data aggregates in the DR group to be removed. Root
      aggregates are not deleted.
      5. Migrate all data LIFs to home nodes in another DR group.
      6. Migrate the cluster management LIF to a home node in another DR group.
      Node management and inter-cluster LIFs are not migrated.
      7. Transfer epsilon to a node in another DR group.

      The command is vetoed ifthe preparation steps are not completed on the
      local and partner clusters.
Do you want to continue? {y|n}: y
[Job 513] Job succeeded: Remove DR Group is successful.

cluster_B::>
....
. Vergewissern Sie sich, dass die Nodes bereit sind, aus den Clustern zu entfernen.
+
Sie müssen diesen Schritt auf beiden Clustern durchführen.

+

NOTE: An diesem Punkt, der `metrocluster node show` Mit dem Befehl werden nur die lokalen MetroCluster FC-Nodes angezeigt und nicht mehr die Nodes angezeigt, die Teil des Partner-Clusters sind.

+
....
cluster_B::> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1-FC        ready to configure
                                                -         -
              node_A_2-FC        ready to configure
                                                -         -
2     cluster_A
              node_A_3-IP        configured     enabled   normal
              node_A_4-IP        configured     enabled   normal
      cluster_B
              node_B_3-IP        configured     enabled   normal
              node_B_4-IP        configured     enabled   normal
6 entries were displayed.

cluster_B::>
....
. Deaktivieren Sie das Storage-Failover für die MetroCluster-FC-Nodes.
+
Sie müssen diesen Schritt für jeden Knoten durchführen.

+
....
cluster_A::> storage failover modify -node node_A_1-FC -enabled false
cluster_A::> storage failover modify -node node_A_2-FC -enabled false
cluster_A::>
....
. Heben Sie die Verbindung der MetroCluster FC-Nodes vom Cluster ab: `cluster unjoin -node node-name`
+
Sie müssen diesen Schritt für jeden Knoten durchführen.

+
....
cluster_A::> cluster unjoin -node node_A_1-FC

Warning: This command will remove node "node_A_1-FC"from the cluster. You must
         remove the failover partner as well. After the node is removed, erase
         its configuration and initialize all disks by usingthe "Clean
         configuration and initialize all disks (4)" option from the boot menu.
Do you want to continue? {y|n}: y
[Job 553] Job is queued: Cluster remove-node of Node:node_A_1-FC with UUID:6c87de7e-ff54-11e9-8371
[Job 553] Checking prerequisites
[Job 553] Cleaning cluster database
[Job 553] Job succeeded: Node remove succeeded
If applicable, also remove the node's HA partner, and then clean its configuration and initialize all disks with the boot menu.
Run "debug vreport show" to address remaining aggregate or volume issues.

cluster_B::>
....
. Schalten Sie die MetroCluster FC Controller-Module und Storage Shelfs aus.
. Trennen Sie die MetroCluster FC-Controller-Module und Storage-Shelfs, und entfernen Sie sie.

