---
permalink: transition/task_apply_rcfs.html 
sidebar: sidebar 
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing 
summary: Wenn Sie neue IP-Schalter für die MetroCluster IP-Konfiguration verwenden, müssen Sie die Switches mit einer benutzerdefinierten RCF-Datei konfigurieren. 
---
= Erstellen und Anwenden von RCFs auf die neuen IP-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie neue IP-Schalter für die MetroCluster IP-Konfiguration verwenden, müssen Sie die Switches mit einer benutzerdefinierten RCF-Datei konfigurieren.

Diese Aufgabe ist erforderlich, wenn Sie neue Switches verwenden.

Wenn Sie vorhandene Switches verwenden, fahren Sie mit fort link:task_move_cluster_connections.html["Verschieben der lokalen Cluster-Verbindungen"].

. Installieren und Rack der neuen IP-Switches.
. Bereiten Sie die IP-Schalter für die Anwendung der neuen RCF-Dateien vor.
+
Befolgen Sie die Schritte im Abschnitt für Ihren Switch-Anbieter:

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Setzen Sie den Broadcom IP-Switch auf die Werkseinstellungen zurück"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Setzen Sie den Cisco IP-Switch auf die Werkseinstellungen zurück"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Setzen Sie den NVIDIA IP SN2100-Switch auf die Werkseinstellungen zurück"]


. Aktualisieren Sie die Firmware auf dem Switch auf eine unterstützte Version, falls erforderlich.
. Verwenden Sie das RCF-Generator-Tool, um die RCF-Datei abhängig vom Switch-Anbieter und den Plattformmodellen zu erstellen und dann die Switches mit der Datei zu aktualisieren.
+
Befolgen Sie die Schritte im Abschnitt für Ihren Switch-Anbieter:

+
** link:../install-ip/task_switch_config_broadcom.html["Laden Sie die Broadcom IP RCF-Dateien herunter, und installieren Sie sie"]
** link:../install-ip/task_switch_config_cisco.html["Laden Sie die Cisco IP RCF-Dateien herunter, und installieren Sie sie"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Laden Sie die NVIDIA RCF-Dateien herunter, und installieren Sie sie"]



