---
permalink: transition/task_move_cluster_connections.html 
sidebar: sidebar 
keywords: transition, cluster connections 
summary: Nachdem Sie alle Anforderungen geprüft und sich auf den Umstieg vorbereitet haben, führen Sie das Übergangsverfahren durch. Sie müssen jede Aufgabe in der Reihenfolge ausführen und alle Schritte in jeder Aufgabe ausführen, bevor Sie zum nächsten wechseln. Sie sollten die neuen Controller oder Storage Shelves nicht mit der vorhandenen Konfiguration verbinden, bis sie weitergeleitet werden. 
---
= Verschieben Sie die lokalen Cluster-Verbindungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Cluster-Schnittstellen der MetroCluster FC-Konfiguration auf die IP-Switches verschieben.



== Verschieben Sie die Cluster-Verbindungen auf den MetroCluster FC-Nodes

[role="lead"]
Sie müssen die Cluster-Verbindungen auf den MetroCluster-FC-Nodes zu den IP-Switches verschieben. Die Schritte hängen davon ab, ob Sie die vorhandenen IP-Switches verwenden oder neue IP-Switches verwenden.

Sie müssen diese Aufgabe auf beiden MetroCluster-Sites ausführen.



=== Welche Verbindungen zu verschieben sind

Bei der folgenden Aufgabe wird von einem Controller-Modul ausgegangen, in dem zwei Ports für die Cluster-Verbindungen verwendet werden. Einige Controller-Modulmodelle verwenden vier oder mehr Ports für die Cluster-Verbindung. In diesem Fall werden die Ports für die Zwecke dieses Beispiels in zwei Gruppen unterteilt, die abwechselnd Ports zwischen den beiden Gruppen

In der folgenden Tabelle sind die Beispielports aufgeführt, die in dieser Aufgabe verwendet werden.

|===


| Anzahl der Cluster-Verbindungen am Controller-Modul | Ports gruppieren | Gruppen-B-Ports 


 a| 
Zwei
 a| 
e0a
 a| 
e0b



 a| 
Vier
 a| 
e0a, e0c
 a| 
e0b, e0d

|===
* Ports gruppieren A verbinden sich mit lokalem Switch_x_1-IP.
* Gruppen-B-Ports verbinden sich mit dem lokalen Switch_x_2-IP.


In der folgenden Tabelle wird gezeigt, mit welchen Switch-Ports die FC-Nodes verbunden werden. Für den Broadcom BES-53248-Switch hängt die Portnutzung vom Modell der MetroCluster-IP-Nodes ab.

|===


| Switch-Modell | MetroCluster IP-Node-Modell | Switch-Port(e) | Stellt eine Verbindung her 


.2+| Cisco 3132Q-V, 3232C oder 9336C-FX2 .2+| Alle  a| 
5
 a| 
Lokale Cluster-Schnittstelle am FC-Node



 a| 
6
 a| 
Lokale Cluster-Schnittstelle am FC-Node



.6+| Broadcom BES-53248  a| 
FAS500f/A250
 a| 
1 - 6
 a| 
Lokale Cluster-Schnittstelle am FC-Node



 a| 
FAS8200/A300
 a| 
3, 4, 9, 10, 11 12
 a| 
Lokale Cluster-Schnittstelle am FC-Node



 a| 
FAS8300/A400/FAS8700
 a| 
1 - 6
 a| 
Lokale Cluster-Schnittstelle am FC-Node

|===


=== Verschieben der lokalen Cluster-Verbindungen bei Verwendung neuer IP-Switches

Bei Verwendung neuer IP-Switches müssen die Cluster-Verbindungen der vorhandenen MetroCluster FC-Nodes physisch auf die neuen Switches verschoben werden.

. Verschieben Sie die Cluster-Verbindungen der MetroCluster-FC-Node-Gruppe A zu den neuen IP-Switches.
+
Verwenden Sie die in beschriebenen Ports <<Welche Verbindungen zu verschieben sind>>.

+
.. Trennen Sie alle Ports der Gruppe A vom Switch, oder trennen Sie die Ports der MetroCluster-FC-Konfiguration als Switch-freien Cluster vom Partner-Node.
.. Trennen Sie die Ports der Gruppe A von Node_A_1-FC und Node_A_2-FC.
.. Verbinden Sie die Ports der Gruppe A von Node_A_1-FC mit den Switch-Ports für den FC-Node auf Switch_A_1-IP
.. Verbinden Sie die Gruppen-A-Ports von Node_A_2-FC mit den Switch-Ports für den FC-Node auf Switch_A_1-IP


. Vergewissern Sie sich, dass alle Cluster-Ports aktiv sind:
+
`network port show -ipspace Cluster`

+
....
cluster_A::*> network port show -ipspace Cluster

Node: node_A_1-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

cluster_A::*>
....
. Stellen Sie sicher, dass die Inter-Switch Links (ISLs) zwischen Standorten verfügbar sind und die Port-Kanäle betriebsbereit sind:
+
`show interface brief`

+
Im folgenden Beispiel werden ISL-Ports „eth1/15“ zu „eth1/20“ als „Po10“ für die Remote-Site-Verbindung konfiguriert und „eth1/7“ bis „eth1/8“ als „PO1“ für den lokalen Cluster ISL konfiguriert. Der Zustand von „eth1/15“ bis „eth1/20“, „eth1/7“ bis „eth1/8“, „Po10“ und „PO1“ sollte „up“ sein.

+
[listing]
----
IP_switch_A_1# show interface brief

--------------------------------------------------------------
Port   VRF          Status   IP Address        Speed      MTU
--------------------------------------------------------------
mgmt0  --            up        100.10.200.20    1000      1500
--------------------------------------------------------------------------------
Ethernet     VLAN   Type Mode    Status     Reason              Speed    Port
Interface                                    Ch #
--------------------------------------------------------------------------------

...

Eth1/7        1     eth  trunk    up        none                100G(D)    1
Eth1/8        1     eth  trunk    up        none                100G(D)    1

...

Eth1/15       1     eth  trunk    up        none                100G(D)    10
Eth1/16       1     eth  trunk    up        none                100G(D)    10
Eth1/17       1     eth  trunk    up        none                100G(D)    10
Eth1/18       1     eth  trunk    up        none                100G(D)    10
Eth1/19       1     eth  trunk    up        none                100G(D)    10
Eth1/20       1     eth  trunk    up        none                100G(D)    10

--------------------------------------------------------------------------------
Port-channel VLAN  Type Mode   Status   Reason         Speed    Protocol
Interface
--------------------------------------------------------------------------------
Po1          1     eth  trunk   up      none            a-100G(D) lacp
Po10         1     eth  trunk   up      none            a-100G(D) lacp
Po11         1     eth  trunk   down    No operational  auto(D)   lacp
                                        members
IP_switch_A_1#
----
. Vergewissern Sie sich, dass in der Spalte „`is Home`“ alle Schnittstellen wahr angezeigt werden:
+
`network interface show -vserver cluster`

+
Dies kann einige Minuten dauern.

+
....
cluster_A::*> network interface show -vserver cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1_FC_clus1
                       up/up      169.254.209.69/16  node_A_1_FC   e0a     true
            node_A_1-FC_clus2
                       up/up      169.254.49.125/16  node_A_1-FC   e0b     true
            node_A_2-FC_clus1
                       up/up      169.254.47.194/16  node_A_2-FC   e0a     true
            node_A_2-FC_clus2
                       up/up      169.254.19.183/16  node_A_2-FC   e0b     true

4 entries were displayed.

cluster_A::*>
....
. Führen Sie die oben genannten Schritte auf beiden Knoten (Node_A_1-FC und Node_A_2-FC) durch, um die Gruppen-B-Ports der Clusterschnittstellen zu verschieben.
. Wiederholen Sie die oben genannten Schritte im Partner-Cluster „`Cluster_B`“.




=== Verschieben der lokalen Cluster-Verbindungen bei erneuter Nutzung vorhandener IP-Switches

Wenn Sie vorhandene IP-Switches erneut verwenden, müssen Sie die Firmware aktualisieren, die Switches mit dem korrekten Reference Configure Files (RCFs) neu konfigurieren und die Verbindungen jeweils an die richtigen Ports verschieben.

Diese Aufgabe ist nur erforderlich, wenn die FC-Knoten mit vorhandenen IP-Switches verbunden sind und Sie die Switches erneut verwenden.

. Trennen Sie die lokalen Cluster-Verbindungen, die sich mit Switch_A_1_IP verbinden
+
.. Trennen Sie die Ports der Gruppe A vom vorhandenen IP-Switch.
.. Trennen Sie die ISL-Ports auf Switch_A_1_IP.
+
Sie finden die Installations- und Setup-Anleitung für die Plattform, um die Verwendung des Cluster-Ports anzuzeigen.

+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html["AFF A320-Systeme: Installation und Einrichtung"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666["Installations- und Setup-Anleitung für AFF A220/FAS2700 Systeme"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668["Installations- und Setup-Anleitung für AFF A800 Systeme"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722["Installations- und Setup-Anleitung für AFF A300 Systeme"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769["FAS8200 Systems Installation and Setup instructions"^]



. Konfigurieren Sie Switch_A_1_IP mit RCF-Dateien neu, die für die Kombination und den Übergang Ihrer Plattform generiert wurden.
+
Befolgen Sie die Schritte im Verfahren für Ihren Switch-Anbieter von _MetroCluster IP Installation and Configuration_:

+
link:../install-ip/concept_considerations_differences.html["Installation und Konfiguration von MetroCluster IP"]

+
.. Laden Sie bei Bedarf die neue Switch-Firmware herunter und installieren Sie sie.
+
Sie sollten die neueste Firmware verwenden, die die MetroCluster IP Nodes unterstützen.

+
*** link:../install-ip/task_switch_config_broadcom.html["Herunterladen und Installieren der Broadcom-Switch EFOS-Software"]
*** link:../install-ip/task_switch_config_cisco.html["Herunterladen und Installieren der Cisco Switch NX-OS-Software"]


.. Bereiten Sie die IP-Schalter für die Anwendung der neuen RCF-Dateien vor.
+
*** link:../install-ip/task_switch_config_broadcom.html["Zurücksetzen des Broadcom IP-Switches auf die Werkseinstellungen"] **
*** link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_switch_config_broadcom.html["Zurücksetzen des Cisco IP-Switches auf die Werkseinstellungen"]


.. Laden Sie die IP RCF-Datei je nach Switch-Anbieter herunter und installieren Sie sie.
+
*** link:../install-ip/task_switch_config_broadcom.html["Herunterladen und Installieren der Broadcom IP RCF-Dateien"]
*** link:../install-ip/task_switch_config_cisco.html["Herunterladen und Installieren der Cisco IP RCF-Dateien"]




. Schließen Sie die Ports der Gruppe A wieder an Switch_A_1_IP an.
+
Verwenden Sie die in beschriebenen Ports <<Welche Verbindungen zu verschieben sind>>.

. Vergewissern Sie sich, dass alle Cluster-Ports aktiv sind:
+
`network port show -ipspace cluster`

+
....
Cluster-A::*> network port show -ipspace cluster

Node: node_A_1_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node_A_2_FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

Cluster-A::*>
....
. Vergewissern Sie sich, dass sich alle Schnittstellen auf ihrem Home-Port befinden:
+
`network interface show -vserver Cluster`

+
....
Cluster-A::*> network interface show -vserver Cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node_A_1_FC_clus1
                       up/up      169.254.209.69/16  node_A_1_FC   e0a     true
            node_A_1_FC_clus2
                       up/up      169.254.49.125/16  node_A_1_FC   e0b     true
            node_A_2_FC_clus1
                       up/up      169.254.47.194/16  node_A_2_FC   e0a     true
            node_A_2_FC_clus2
                       up/up      169.254.19.183/16  node_A_2_FC   e0b     true

4 entries were displayed.

Cluster-A::*>
....
. Wiederholen Sie alle vorherigen Schritte auf Switch_A_2_IP.
. Schließen Sie die lokalen Cluster-ISL-Ports wieder an.
. Wiederholen Sie die oben genannten Schritte an Standort_B für Schalter B_1_IP und Schalter B_2_IP.
. Verbinden Sie die Remote-ISLs zwischen den Standorten.




== Überprüfen, ob die Cluster-Verbindungen verschoben und das Cluster in einem ordnungsgemäßen Zustand ist

Um sicherzustellen, dass die Konnektivität korrekt ist und die Konfiguration bereit ist, den Transitionsprozess fortzusetzen, müssen Sie überprüfen, ob die Cluster-Verbindungen ordnungsgemäß verschoben werden, die Cluster-Switches erkannt und der Cluster in einem ordnungsgemäßen Zustand ist.

. Vergewissern Sie sich, dass alle Cluster-Ports betriebsbereit sind:
+
`network port show -ipspace Cluster`

+
....
Cluster-A::*> network port show -ipspace Cluster

Node: Node-A-1-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: Node-A-2-FC

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.

Cluster-A::*>
....
. Vergewissern Sie sich, dass sich alle Schnittstellen auf ihrem Home-Port befinden:
+
`network interface show -vserver Cluster`

+
Dies kann einige Minuten dauern.

+
Das folgende Beispiel zeigt, dass alle Schnittstellen in der Spalte „`is Home`“ den Status „true“ aufweisen.

+
....
Cluster-A::*> network interface show -vserver Cluster

            Logical      Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            Node-A-1_FC_clus1
                       up/up      169.254.209.69/16  Node-A-1_FC   e0a     true
            Node-A-1-FC_clus2
                       up/up      169.254.49.125/16  Node-A-1-FC   e0b     true
            Node-A-2-FC_clus1
                       up/up      169.254.47.194/16  Node-A-2-FC   e0a     true
            Node-A-2-FC_clus2
                       up/up      169.254.19.183/16  Node-A-2-FC   e0b     true

4 entries were displayed.

Cluster-A::*>
....
. Vergewissern Sie sich, dass die beiden lokalen IP-Switches von den Knoten erkannt werden:
+
`network device-discovery show -protocol cdp`

+
....
Cluster-A::*> network device-discovery show -protocol cdp

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
Node-A-1-FC
           /cdp
            e0a    Switch-A-3-IP             1/5/1             N3K-C3232C
            e0b    Switch-A-4-IP             0/5/1             N3K-C3232C
Node-A-2-FC
           /cdp
            e0a    Switch-A-3-IP             1/6/1             N3K-C3232C
            e0b    Switch-A-4-IP             0/6/1             N3K-C3232C

4 entries were displayed.

Cluster-A::*>
....
. Überprüfen Sie am IP-Switch, ob die MetroCluster-IP-Knoten von beiden lokalen IP-Switches erkannt wurden:
+
`show cdp neighbors`

+
Sie müssen diesen Schritt bei jedem Schalter ausführen.

+
In diesem Beispiel wird gezeigt, wie Sie überprüfen, ob die Knoten auf Switch-A-3-IP erkannt werden.

+
....
(Switch-A-3-IP)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Node-A-1-FC         Eth1/5/1       133    H         FAS8200       e0a
Node-A-2-FC         Eth1/6/1       133    H         FAS8200       e0a
Switch-A-4-IP(FDO220329A4)
                    Eth1/7         175    R S I s   N3K-C3232C    Eth1/7
Switch-A-4-IP(FDO220329A4)
                    Eth1/8         175    R S I s   N3K-C3232C    Eth1/8
Switch-B-3-IP(FDO220329B3)
                    Eth1/20        173    R S I s   N3K-C3232C    Eth1/20
Switch-B-3-IP(FDO220329B3)
                    Eth1/21        173    R S I s   N3K-C3232C    Eth1/21

Total entries displayed: 4

(Switch-A-3-IP)#
....
+
In diesem Beispiel wird gezeigt, wie Sie überprüfen, ob die Knoten bei Switch-A-4-IP erkannt werden.

+
....
(Switch-A-4-IP)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Node-A-1-FC         Eth1/5/1       133    H         FAS8200       e0b
Node-A-2-FC         Eth1/6/1       133    H         FAS8200       e0b
Switch-A-3-IP(FDO220329A3)
                    Eth1/7         175    R S I s   N3K-C3232C    Eth1/7
Switch-A-3-IP(FDO220329A3)
                    Eth1/8         175    R S I s   N3K-C3232C    Eth1/8
Switch-B-4-IP(FDO220329B4)
                    Eth1/20        169    R S I s   N3K-C3232C    Eth1/20
Switch-B-4-IP(FDO220329B4)
                    Eth1/21        169    R S I s   N3K-C3232C    Eth1/21

Total entries displayed: 4

(Switch-A-4-IP)#
....

