---
permalink: transition/task_move_an_fc_san_workload_from_mcc_fc_to_mcc_ip_nodes.html 
sidebar: sidebar 
keywords: non-disruptively, transition, metrocluster, fc, ip, node, san, host, moving, move 
summary: Für den unterbrechungsfreien Wechsel von MetroCluster FC zu IP Nodes müssen Sie FC SAN Host-Objekte unterbrechungsfrei von MetroCluster FC auf IP Nodes verschieben. 
---
= Verschieben eines FC SAN-Workloads von MetroCluster FC- zu MetroCluster IP-Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für den unterbrechungsfreien Wechsel von MetroCluster FC zu IP Nodes müssen Sie FC SAN Host-Objekte unterbrechungsfrei von MetroCluster FC auf IP Nodes verschieben.

. Neue FC-Schnittstellen (LIFS) an MetroCluster IP-Nodes einrichten:
+
.. Ändern Sie bei MetroCluster IP-Nodes gegebenenfalls FC-Ports, die für die Client-Verbindung zu FC-Zielpersönlichkeit verwendet werden sollen.
+
Hierfür ist möglicherweise ein Neustart der Nodes erforderlich.

.. FC-LIFS/Schnittstellen auf IP-Nodes für alle SAN SVMs erstellen Optional können Sie überprüfen, ob die WWPNs von neu erstellten FC LIFs am FC SAN-Switch angemeldet sind


. Aktualisieren Sie die SAN-Zoning-Konfiguration für neu hinzugefügte FC LIFs auf MetroCluster IP Nodes.
+
Um die Verschiebung von Volumes zu vereinfachen, in denen LUNs aktiv Daten für FC SAN-Clients bereitstellen, sollten Sie die vorhandenen FC Switch-Zonen aktualisieren, damit FC SAN-Clients auf LUNs in MetroCluster IP-Nodes zugreifen können.

+
.. Fügen Sie am FC SAN-Switch (Cisco oder Brocade) der Zone die WWPNs neu hinzugefügter FC SAN LIFs hinzu.
.. Aktualisieren, speichern und Übergeben der Änderungen am Zoning
.. Überprüfen Sie vom Client auf FC-Initiator-Anmeldungen zu den neuen SAN-LIFs auf den MetroCluster IP-Nodes: `sanlun lun show -p`
+
Derzeit sollte der Client sehen und bei den FC-Schnittstellen sowohl auf den MetroCluster-FC- als auch auf den MetroCluster-IP-Nodes angemeldet sein. LUNs und Volumes werden weiterhin physisch auf den MetroCluster FC-Nodes gehostet.

+
Da LUNs nur auf MetroCluster FC Node-Schnittstellen gemeldet werden, zeigt der Client nur Pfade über FC Nodes an. Dies kann in der Ausgabe des angezeigt werden `sanlun lun show -p` Und `multipath -ll -d` Befehle.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_

[root@stemgr]# multipath -ll -d
3600a098038304646513f4f674e52774b dm-5 NETAPP ,LUN C-Mode
size=2.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 3:0:0:4 sdk 8:160 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
 `- 2:0:0:4 sdh 8:112 active ready running
----


. Ändern Sie die Berichtsknoten, um die MetroCluster-IP-Knoten hinzuzufügen
+
.. Liste der Reporting-Nodes für LUNs auf der SVM: `lun mapping show -vserver svm-name -fields reporting-nodes -ostype linux`
+
Als Nodes für die Berichterstellung werden lokale Nodes angezeigt, da sich LUNs physisch auf FC-Nodes A_1 und A_2 befinden.

+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver  path                        igroup         reporting-nodes
-------  --------------------------- ------------   -------------------------------------
vsa_1    /vol/vsa_1_vol1/lun_linux_2 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol1/lun_linux_3 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol2/lun_linux_4 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol3/lun_linux_7 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_8 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol4/lun_linux_9 igroup_linux   A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_12 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol6/lun_linux_13 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol7/lun_linux_14 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol8/lun_linux_17 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_18 igroup_linux  A_1,A_2
vsa_1    /vol/vsa_1_vol9/lun_linux_19 igroup_linux  A_1,A_2
12 entries were displayed.
----
.. Fügen Sie Reporting-Nodes hinzu, um MetroCluster IP-Nodes einzubeziehen.
+
[listing]
----
cluster_A::> lun mapping add-reporting-nodes -vserver vsa_1 -path /vol/vsa_1_vol*/lun_linux_* -nodes B_1,B_2 -igroup igroup_linux

12 entries were acted on.
----
.. Listen Sie die Reporting-Knoten auf, und überprüfen Sie die Anwesenheit der neuen Knoten:
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path                          igroup          reporting-nodes
------- ---------------------------   ------------    -------------------------------------------------------------------------------

vsa_1   /vol/vsa_1_vol1/lun_linux_2   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol1/lun_linux_3   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol2/lun_linux_4   igroup_linux    A_1,A_2,B_1,B_2
vsa_1   /vol/vsa_1_vol3/lun_linux_7   igroup_linux    A_1,A_2,B_1,B_2
...

12 entries were displayed.
----
.. Überprüfen Sie das `sg3-utils` Das Paket wird auf dem Linux-Host installiert. Dies vermeidet ein `rescan-scsi-bus.sh utility not found` Fehler beim erneuten Scannen des Linux-Hosts für die neu zugeordneten LUNs mithilfe des `rescan-scsi-bus` Befehl.
.. Scannen Sie den SCSI-Bus auf dem Host erneut, um die neu hinzugefügten Pfade zu erkennen: `/usr/bin/rescan-scsi-bus.sh -a`
+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -a
Scanning SCSI subsystem for new devices
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
 Scanning for device 2 0 0 0 ...
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
0 device(s) removed.
----
.. Anzeigen der neu hinzugefügten Pfade: `sanlun lun show -p`
+
Jede LUN hat vier Pfade.

+
[listing]
----
[root@stemgr]# sanlun lun show -p
ONTAP Path: vsa_1:/vol/vsa_1_vol6/lun_linux_12
 LUN: 4
 LUN Size: 2g
 Product: cDOT
 Host Device: 3600a098038304646513f4f674e52774b
 Multipath Policy: service-time 0
 Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host vserver
path path /dev/ host vserver
state type node adapter LIF
--------- ---------- ------- ------------ ----------------------------------------------
up primary sdk host3 iscsi_lf__n2_p1_
up secondary sdh host2 iscsi_lf__n1_p1_
up secondary sdag host4 iscsi_lf__n4_p1_
up secondary sdah host5 iscsi_lf__n3_p1_
----
.. Verschieben Sie auf den Controllern die Volumes, die LUNs enthalten, von MetroCluster FC zu den MetroCluster IP-Nodes.
+
[listing]
----
cluster_A::> vol move start -vserver vsa_1 -volume vsa_1_vol1 -destination-aggregate A_1_htp_005_aggr1
[Job 1877] Job is queued: Move "vsa_1_vol1" in Vserver "vsa_1" to aggregate "A_1_htp_005_aggr1". Use the "volume move show -vserver vsa_1 -volume vsa_1_vol1"
command to view the status of this operation.
cluster_A::> volume move show
Vserver    Volume    State    Move Phase   Percent-Complete Time-To-Complete
--------- ---------- -------- ----------   ---------------- ----------------
vsa_1     vsa_1_vol1 healthy  initializing
 - -
----
.. Zeigen Sie auf dem FC SAN-Client die LUN-Informationen an: `sanlun lun show -p`
+
Die FC-Schnittstellen auf den MetroCluster IP Nodes, in denen sich die LUN nun befindet, werden als primäre Pfade aktualisiert. Wenn der primäre Pfad nach der Volume-Verschiebung nicht aktualisiert wird, führen Sie /usr/bin/rescan-scsi-bus.sh -a aus oder warten Sie einfach, bis Multipath-Rescanning stattfindet.

+
Der primäre Pfad im folgenden Beispiel ist die LIF auf dem MetroCluster IP Node.

+
[listing]
----
[root@localhost ~]# sanlun lun show -p

                    ONTAP Path: vsa_1:/vol/vsa_1_vol1/lun_linux_2
                           LUN: 22
                      LUN Size: 2g
                       Product: cDOT
                   Host Device: 3600a098038302d324e5d50305063546e
              Multipath Policy: service-time 0
            Multipath Provider: Native
--------- ---------- ------- ------------ ----------------------------------------------
host      vserver
path      path       /dev/   host         vserver
state     type       node    adapter      LIF
--------- ---------- ------- ------------ ----------------------------------------------
up        primary    sddv    host6        fc_5
up        primary    sdjx    host7        fc_6
up        secondary  sdgv    host6        fc_8
up        secondary  sdkr    host7        fc_8
----
.. Wiederholen Sie die oben genannten Schritte für alle Volumes, LUNs und FC-Schnittstellen, die zu einem FC-SAN-Host gehören.
+
Nach Abschluss dieser Fertigstellung sollten sich alle LUNs für eine bestimmte SVM und ein FC-SAN-Host auf MetroCluster IP-Nodes befinden.



. Entfernen Sie die Knoten für die Berichterstellung und scannen Sie Pfade vom Client erneut.
+
.. Entfernen Sie die Remote Reporting Nodes (die MetroCluster FC Nodes) für die linux LUNs: `lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true`
+
[listing]
----
cluster_A::> lun mapping remove-reporting-nodes -vserver vsa_1 -path * -igroup igroup_linux -remote-nodes true
12 entries were acted on.
----
.. Überprüfen Sie die Reporting-Nodes für die LUNs: `lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux`
+
[listing]
----
cluster_A::> lun mapping show -vserver vsa_1 -fields reporting-nodes -ostype linux

vserver path igroup reporting-nodes
------- --------------------------- ------------ -----------------------------------------
vsa_1 /vol/vsa_1_vol1/lun_linux_2 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol1/lun_linux_3 igroup_linux B_1,B_2
vsa_1 /vol/vsa_1_vol2/lun_linux_4 igroup_linux B_1,B_2
...

12 entries were displayed.
----
.. SCSI-Bus auf dem Client erneut scannen: `/usr/bin/rescan-scsi-bus.sh -r`
+
Die Pfade aus den MetroCluster FC-Knoten werden entfernt:

+
[listing]
----
[root@stemgr]# /usr/bin/rescan-scsi-bus.sh -r
Syncing file systems
Scanning SCSI subsystem for new devices and remove devices that have disappeared
Scanning host 0 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 1 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
Scanning host 2 for SCSI target IDs 0 1 2 3 4 5 6 7, all LUNs
sg0 changed: LU not available (PQual 1)
REM: Host: scsi2 Channel: 00 Id: 00 Lun: 00
DEL: Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
sg2 changed: LU not available (PQual 1)
.
.
.
OLD: Host: scsi5 Channel: 00 Id: 00 Lun: 09
 Vendor: NETAPP Model: LUN C-Mode Rev: 9800
 Type: Direct-Access ANSI SCSI revision: 05
0 new or changed device(s) found.
0 remapped or resized device(s) found.
24 device(s) removed.
 [2:0:0:0]
 [2:0:0:1]
...
----
.. Vergewissern Sie sich, dass vom Host nur Pfade von den MetroCluster IP-Nodes sichtbar sind: `sanlun lun show -p`
.. Entfernen Sie bei Bedarf iSCSI LIFs von den MetroCluster FC-Nodes.
+
Dies sollte geschehen, wenn andere LUNs auf den Nodes anderen Clients zugeordnet sind.




