---
permalink: upgrade/concept_choosing_tech_refresh_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, choose, upgrade, refresh, method 
summary: Das von Ihnen verwendete Aktualisierungsverfahren hängt vom Plattformmodell, dem Umfang des Upgrades und dem Typ der MetroCluster-Konfiguration ab. 
---
= Auswahl der Methode zur Systemaktualisierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das von Ihnen verwendete Verfahren zur Systemaktualisierung hängt vom Plattformmodell, dem Umfang des Upgrades und dem Typ der MetroCluster-Konfiguration ab.

[cols="2,1,1,2"]
|===
| Umfang | Konfigurationstyp | ONTAP Support | Gehe zu... 


 a| 
* Umfang: Plattform (Controller-Module) und Storage-Shelfs
* Methode: Erweitern Sie die MetroCluster-Konfiguration, und entfernen Sie dann die alten Knoten

 a| 
FC
 a| 
9.6 und höher
 a| 
link:task_refresh_4n_mcc_fc.html["Aktualisieren einer MetroCluster FC-Konfiguration mit vier Nodes"]



 a| 
* Umfang: Plattform (Controller-Module) und Storage-Shelfs
* Methode: Erweitern Sie die MetroCluster-Konfiguration, und entfernen Sie dann die alten Knoten

 a| 
IP
 a| 
9.8
 a| 
link:task_refresh_4n_mcc_ip.html["Aktualisieren einer MetroCluster IP-Konfiguration mit vier Nodes (ONTAP 9.8 und höher)"]

|===