---
permalink: upgrade/reference_where_to_find_additional_information_mcc_ug.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, additional, information 
summary: Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier.



== MetroCluster und sonstige Informationen

|===


| Informationsdaten | Betreff 


 a| 
link:../index.html["MetroCluster-Dokumentation"]
 a| 
* Alle MetroCluster-Informationen




 a| 
link:../install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"]
 a| 
* Fabric-Attached MetroCluster-Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der FC-Switches
* Konfigurieren der MetroCluster in ONTAP




 a| 
link:../install-stretch/concept_considerations_differences.html["Installation und Konfiguration von Stretch MetroCluster"]
 a| 
* Stretch-MetroCluster Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der MetroCluster in ONTAP




 a| 
link:../disaster-recovery/concept_dr_workflow.html["MetroCluster Management und Disaster Recovery"]
 a| 
* Allgemeines zur MetroCluster-Konfiguration
* Umschaltung, Heilen und zurückwechseln
* Disaster Recovery




 a| 
link:../maintain/index.html["Warten von MetroCluster-Komponenten"]
 a| 
* Richtlinien für die Wartung in einer MetroCluster FC-Konfiguration
* Verfahren zum Austausch oder Upgrade von Hardware und Firmware-Upgrades für FC-to-SAS-Bridges und FC-Switches
* Hot-hinzufügen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Hot-entfernen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Austausch von Hardware an einem Disaster-Standort in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster FC-Konfiguration mit zwei Nodes auf eine MetroCluster Konfiguration mit vier Nodes.
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster FC-Konfiguration mit vier Nodes auf eine MetroCluster FC-Konfiguration mit acht Nodes




 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster: Upgrade, Transition und Erweiterung"]
 a| 
* Aktualisierung oder Aktualisierung einer MetroCluster Konfiguration
* Umstellung von einer MetroCluster FC-Konfiguration auf eine MetroCluster IP-Konfiguration
* Erweitern einer MetroCluster Konfiguration durch Hinzufügen weiterer Nodes




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation und Konfiguration der MetroCluster Tiebreaker Software"]
 a| 
* Monitoring der MetroCluster Konfiguration mit der MetroCluster Tiebreaker Software




 a| 
https://["AFF and FAS Documentation Center"^]


NOTE: In MetroCluster IP-Konfigurationen können Standardwartungsverfahren für Storage Shelves verwendet werden.
 a| 
* Hot-Adding eines Festplatten-Shelfs
* Hot-entfernen eines Festplatten-Shelfs




 a| 
http://["Kopienbasierte Transition"^]
 a| 
* Migration von Daten von 7-Mode Storage-Systemen zu geclusterten Storage-Systemen




 a| 
https://["ONTAP-Konzepte"^]
 a| 
* Funktionsweise der gespiegelten Aggregate


|===