---
permalink: upgrade/task_verify_that_the_ha_state_of_components_is_mcc_dr_smok_crater_or_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, verify, ha, config, component, state 
summary: In einer MetroCluster-Konfiguration muss der HA-Konfigurationszustand des Controller-Moduls und der Chassis-Komponenten auf mcc festgelegt sein, damit sie ordnungsgemäß hochfahren. 
---
= Überprüfen des HA-Konfigurationsstatus von Komponenten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In einer MetroCluster-Konfiguration muss der HA-Konfigurationszustand des Controller-Moduls und der Gehäusekomponenten auf *mcc* eingestellt sein, damit sie ordnungsgemäß hochfahren.

.Über diese Aufgabe
* Das System muss sich im Wartungsmodus befinden.
* Diese Aufgabe muss an jedem neuen Controller-Modul ausgeführt werden.


.Schritte
. Zeigen Sie im Wartungsmodus den HA-Status des Controller-Moduls und des Chassis an:
+
`ha-config show`

+
Der HA-Status für alle Komponenten sollte „mcc“ sein.

. Wenn der angezeigte Systemzustand des Controllers nicht korrekt ist, setzen Sie den HA-Status für das Controller-Modul ein:
+
`ha-config modify controller mcc`

. Wenn der angezeigte Systemzustand des Chassis nicht korrekt ist, setzen Sie den HA-Status für das Chassis ein:
+
`ha-config modify chassis mcc`

. Wiederholen Sie diese Schritte auf dem anderen Ersatzknoten.

