---
permalink: upgrade/task_check_for_mcc_configuration_errors_with_config_advisor.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, check, configuration, errors, config, advisor 
summary: Sie können die NetApp Support-Website besuchen und das Config Advisor-Tool herunterladen, um häufige Konfigurationsfehler zu überprüfen. 
---
= Überprüfen auf MetroCluster-Konfigurationsfehler mit Config Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die NetApp Support-Website besuchen und das Config Advisor-Tool herunterladen, um häufige Konfigurationsfehler zu überprüfen.

.Über diese Aufgabe
Config Advisor ist ein Tool zur Konfigurationsvalidierung und Statusüberprüfung. Sie können die Lösung sowohl an sicheren Standorten als auch an nicht sicheren Standorten zur Datenerfassung und Systemanalyse einsetzen.


NOTE: Der Support für Config Advisor ist begrenzt und steht nur online zur Verfügung.

.Schritte
. Rufen Sie die Config Advisor Download-Seite auf und laden Sie das Tool herunter.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"]

. Führen Sie Config Advisor aus, überprüfen Sie die Ausgabe des Tools und folgen Sie den Empfehlungen in der Ausgabe, um erkannte Probleme zu beheben.

