---
permalink: upgrade/task_move_a_metadata_volume_in_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, move, metadata, volume, configuration 
summary: Sie können ein Metadaten-Volume in eine MetroCluster Konfiguration von einem Aggregat zu einem anderen Aggregat verschieben. Unter Umständen möchten Sie ein Metadaten-Volume verschieben, wenn das Quellaggregat deaktiviert oder nicht gespiegelt wird, oder aus anderen Gründen, aus denen das Aggregat nicht mehr berechtigt ist. 
---
= Verschieben eines Metadaten-Volumes in MetroCluster Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Metadaten-Volume in eine MetroCluster Konfiguration von einem Aggregat zu einem anderen Aggregat verschieben. Unter Umständen möchten Sie ein Metadaten-Volume verschieben, wenn das Quellaggregat deaktiviert oder nicht gespiegelt wird, oder aus anderen Gründen, aus denen das Aggregat nicht mehr berechtigt ist.

.Über diese Aufgabe
* Um diese Aufgabe ausführen zu können, müssen Sie über Cluster-Administratorrechte verfügen.
* Das Zielaggregat muss gespiegelt werden und darf nicht im eingeschränkten Zustand sein.
* Der verfügbare Speicherplatz im Zielaggregat muss größer sein als das zu bewegende Metadaten-Volume.


.Schritte
. Legen Sie die Berechtigungsebene auf erweitert fest:
+
`set -privilege advanced`

. Identifizierung des zu verschiebenden Metadaten-Volumes:
+
`volume show MDV_CRS*`

+
[listing]
----
Cluster_A::*> volume show MDV_CRS*
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
Cluster_A
          MDV_CRS_14c00d4ac9f311e7922800a0984395f1_A
                       Node_A_1_aggr1
                                    online     RW         10GB     9.50GB    5%
Cluster_A
          MDV_CRS_14c00d4ac9f311e7922800a0984395f1_B
                       Node_A_2_aggr1
                                    online     RW         10GB     9.50GB    5%
Cluster_A
          MDV_CRS_15035e66c9f311e7902700a098439625_A
                       Node_B_1_aggr1
                                    -          RW            -          -     -
Cluster_A
          MDV_CRS_15035e66c9f311e7902700a098439625_B
                       Node_B_2_aggr1
                                    -          RW            -          -     -
4 entries were displayed.

Cluster_A::>
----
. Ermittlung eines geeigneten Zielaggregats:
+
`metrocluster check config-replication show-aggregate-eligibility`

+
Mit dem folgenden Befehl werden die Aggregate in „Cluster_A“ identifiziert, die zum Hosten von Metadaten-Volumes geeignet sind:

+
[listing]
----

Cluster_A::*> metrocluster check config-replication show-aggregate-eligibility

Aggregate Hosted Config Replication Vols Host Addl Vols Comments
------------ ------------------------------------------ -------------- --------
Node_A_1_aggr0 - false Root Aggregate
Node_A_2_aggr0 - false Root Aggregate
Node_A_1_aggr1 MDV_CRS_1bc7134a5ddf11e3b63f123478563412_A true -
Node_A_2_aggr1 MDV_CRS_1bc7134a5ddf11e3b63f123478563412_B true -
Node_A_1_aggr2 - true
Node_A_2_aggr2 - true
Node_A_1_Aggr3 - false Unable to determine available space of aggregate
Node_A_1_aggr5 - false Unable to determine mirror configuration
Node_A_2_aggr6 - false Mirror configuration does not match requirement
Node_B_1_aggr4 - false NonLocal Aggregate
----
+

NOTE: In dem vorherigen Beispiel können Node_A_1_aggr2 und Node_A_2_aggr2 ausgewählt werden.

. Starten Sie die Volume-Verschiebung:
+
`volume move start -vserver _svm_name_ -volume _metadata_volume_name_ -destination-aggregate _destination_aggregate_name_*`

+
Der folgende Befehl verschiebt Metadaten-Volume „MDV_CRS_14c00d4ac9f311e7922800a0984395f1“ von „Aggregate Node_A_1_aggr1“ in „Aggregate Node_A_1_aggr2“:

+
[listing]
----
Cluster_A::*> volume move start -vserver svm_cluster_A -volume MDV_CRS_14c00d4ac9f311e7922800a0984395f1
-destination-aggregate aggr_cluster_A_02_01

Warning: You are about to modify the system volume
         "MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A".  This may cause severe
         performance or stability problems.  Do not proceed unless directed to
         do so by support.  Do you want to proceed? {y|n}: y
[Job 109] Job is queued: Move "MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A" in Vserver
"svm_cluster_A" to aggregate "aggr_cluster_A_02_01".
Use the "volume move show -vserver svm_cluster_A -volume
MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A" command to view the status of this operation.
----
. Überprüfung des Status der Verschiebung eines Volumes:
+
`volume move show -volume vol_constituent_name`

. Zurück zur Administratorberechtigungsebene:
+
`set -privilege admin`


