---
permalink: upgrade/task_determin_the_new_cable_layout_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, determine, new, cabling, layout 
summary: Sie müssen die Verkabelung der neuen Controller-Module und aller neuen Platten-Shelfs zu den vorhandenen FC-Switches bestimmen. 
---
= Bestimmen des neuen Verkabelungslayouts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Verkabelung der neuen Controller-Module und aller neuen Platten-Shelfs zu den vorhandenen FC-Switches bestimmen.

.Über diese Aufgabe
Diese Aufgabe muss an jedem MetroCluster Standort ausgeführt werden.

.Schritte
. Verwenden Sie das Verfahren unter link:../install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"] Um ein Verkabelungslayout für Ihren Switch-Typ zu erstellen, verwenden Sie die Portnutzung für eine MetroCluster-Konfiguration mit acht Nodes.
+
Die Verwendung des FC-Switch-Ports muss mit der in dem Verfahren beschriebenen Verwendung übereinstimmen, sodass die RCFs (Reference Configuration Files) verwendet werden können.

+

NOTE: Wenn Ihre Umgebung nicht so verkabelt werden kann, dass RCF-Dateien verwendet werden können, müssen Sie das System manuell gemäß den Anweisungen in konfigurieren link:../install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"]. Verwenden Sie dieses Verfahren nicht, wenn die Verkabelung keine RCF-Dateien verwenden kann.


