---
permalink: upgrade/task-enable-console-logging-expand-fc.html 
sidebar: sidebar 
keywords: enable, console, logging, devices, maintenance, autosupport, cli, 
summary: Aktivieren Sie die Konsolenprotokollierung auf Ihren Geräten. 
---
= Aktivieren Sie die Konsolenprotokollierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aktivieren Sie die Konsolenprotokollierung auf Ihren Geräten, bevor Sie diese Aufgabe ausführen.

NetApp empfiehlt dringend, die Konsolenprotokollierung auf den von Ihnen verwendeten Geräten zu aktivieren und folgende Aktionen durchzuführen:

* Lassen Sie AutoSupport während der Wartung aktiviert.
* Lösen Sie vor und nach der Wartung eine Wartungs-AutoSupport-Meldung aus, um die Case-Erstellung für die Dauer der Wartungsaktivität zu deaktivieren.
+
Siehe Knowledge Base-Artikel link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Wie kann die automatische Case-Erstellung während geplanter Wartungszeiträume unterdrückt werden"^].

* Aktivieren Sie die Sitzungsprotokollierung für jede CLI-Sitzung. Anweisungen zum Aktivieren der Sitzungsprotokollierung finden Sie im Abschnitt „Protokollierung der Sitzungsausgabe“ im Knowledge Base-Artikel link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["So konfigurieren Sie PuTTY für optimale Konnektivität zu ONTAP-Systemen"^].

