---
permalink: upgrade/task_refresh_the_mcc_configuration_mcc_configure_refresh.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, refresh, configuration, new, controller 
summary: Sie müssen die MetroCluster Konfiguration aktualisieren, wenn Sie sie von einer Konfiguration mit zwei Nodes auf eine Konfiguration mit vier Nodes erweitern. 
---
= Aktualisierung der MetroCluster Konfiguration durch neue Controller
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die MetroCluster Konfiguration aktualisieren, wenn Sie sie von einer Konfiguration mit zwei Nodes auf eine Konfiguration mit vier Nodes erweitern.



== Aktivieren Sie die Konsolenprotokollierung

NetApp empfiehlt dringend, die Konsolenprotokollierung auf den von Ihnen verwendeten Geräten zu aktivieren und folgende Aktionen durchzuführen:

* Lassen Sie AutoSupport während der Wartung aktiviert.
* Lösen Sie vor und nach der Wartung eine Wartungs-AutoSupport-Meldung aus, um die Case-Erstellung für die Dauer der Wartungsaktivität zu deaktivieren.
+
Siehe Knowledge Base-Artikel link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["Wie kann die automatische Case-Erstellung während geplanter Wartungszeiträume unterdrückt werden"^].

* Aktivieren Sie die Sitzungsprotokollierung für jede CLI-Sitzung. Anweisungen zum Aktivieren der Sitzungsprotokollierung finden Sie im Abschnitt „Protokollierung der Sitzungsausgabe“ im Knowledge Base-Artikel link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["So konfigurieren Sie PuTTY für optimale Konnektivität zu ONTAP-Systemen"^].




== Führen Sie das Aktualisierungsverfahren durch

.Schritte
. Aktualisieren Sie die MetroCluster-Konfiguration:
+
.. Rufen Sie den erweiterten Berechtigungsmodus auf: +
`set -privilege advanced`
.. Aktualisieren Sie die MetroCluster-Konfiguration: +
`metrocluster configure -refresh true -allow-with-one-aggregate true`
+
Mit dem folgenden Befehl wird die MetroCluster-Konfiguration auf allen Nodes in der DR-Gruppe aktualisiert, die Controller_A_1 enthält:

+
[listing]
----
controller_A_1::*> metrocluster configure -refresh true -allow-with-one-aggregate true

[Job 726] Job succeeded: Configure is successful.
----
.. Zurück zum Admin-Berechtigungsmodus:
+
`set -privilege admin`



. Überprüfen Sie den Netzwerkstatus auf Standort A:
+
`network port show`

+
Im folgenden Beispiel wird die Verwendung von Netzwerkports in einer MetroCluster Konfiguration mit vier Nodes angezeigt:

+
[listing]
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----
. Überprüfen Sie die MetroCluster Konfiguration von beiden Standorten in der MetroCluster Konfiguration.
+
.. Überprüfen Sie die Konfiguration von Standort A:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Überprüfen Sie die Konfiguration von Standort B:
+
`metrocluster show`

+
[listing]
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Überprüfen Sie, ob die DR-Beziehungen korrekt erstellt wurden:
+
`metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner`

+
[listing]
----
metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner
dr-group-id cluster     node    ha-partner dr-cluster  dr-partner   dr-auxiliary  node-object-limit automatic-uso
----------- ---------   ----    ---------- ----------  ----------   ------------  ----------------- -------------
2           cluster_A   node_A_1 node_A_2    cluster_B  node_B_1     node_B_2      on                true
2           cluster_A   node_A_2 node_A_1    cluster_B  node_B_2     node_B_1      on                true
2           cluster_B   node_B_1 node_B_2    cluster_A  node_A_1     node_A_2      on                true
2           cluster_B   node_B_2 node_B_1    cluster_A  node_A_2     node_A_1      on                true
4 entries were displayed.
----



