---
permalink: upgrade/task_verify_the_state_of_the_mcc_configuration_mcc_expansion.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, verify, state, configuration 
summary: 'Sie sollten die vorhandenen Controller identifizieren und die Disaster-Recovery- \(DR\)-Beziehungen zwischen ihnen bestätigen, dass sich die Controller im normalen Modus befinden und die Aggregate gespiegelt werden.' 
---
= Überprüfen des Status der MetroCluster-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die vorhandenen Controller identifizieren und die Disaster Recovery (DR)-Beziehungen zwischen ihnen bestätigen, dass sich die Controller im normalen Modus befinden und die Aggregate gespiegelt werden.

.Schritte
. Zeigt die Details der Nodes in der MetroCluster-Konfiguration von jedem beliebigen Node in der Konfiguration an:
+
`metrocluster node show -fields node,dr-partner,dr-partner-systemid`

+
Die folgenden Ausgaben zeigen, dass diese MetroCluster Konfiguration über eine einzelne DR-Gruppe und einen Node pro Cluster verfügt.

+
[listing]
----
cluster_A::> metrocluster node show -fields node,dr-partner,dr-partner-systemid

dr-group-id  cluster         node            dr-partner      dr-partner-systemid
-----------  -------------   -------         ----------      -------------------
1            cluster_A       controller_A_1  controller_B_1  536946192
1            cluster_B       controller_B_1  controller_A_1  536946165
2 entries were displayed.
----
. Zeigt den Status der MetroCluster-Konfiguration an:
+
`metrocluster show`

+
Die folgende Ausgabe zeigt, dass sich die vorhandenen Nodes in der MetroCluster Konfiguration im normalen Modus befinden:

+
[listing]
----

cluster_A::> metrocluster show

Configuration: two-node-fabric

Cluster                        Entry Name             State
------------------------------ ---------------------- ---------------------
Local: cluster_A               Configuration State    configured
                               Mode                   normal
                               AUSO Failure Domain    auso-on-cluster-disaster
Remote: controller_B_1_siteB
                               Configuration State    configured
                               Mode                   normal
                               AUSO Failure Domain    auso-on-cluster-disaster
----
. Überprüfen Sie den Status der Aggregate auf jedem Node in der MetroCluster Konfiguration:
+
`storage aggregate show`

+
Die folgende Ausgabe zeigt, dass die Aggregate auf Cluster_A online und gespiegelt sind:

+
[listing]
----
cluster_A::> storage aggregate show


Aggregate                Size     Available Used%  State   #Vols  Nodes            RAID Status
---------                -------- --------- -----  ------- ------ ---------------- ------------
aggr0_controller_A_1_0   1.38TB   68.63GB   95%    online    1    controller_A_1   raid_dp,mirrored
controller_A_1_aggr1     4.15TB   4.14TB    0%     online    2    controller_A_1   raid_dp,mirrored
controller_A_1_aggr2     4.15TB   4.14TB    0%     online    1    controller_A_1   raid_dp,mirrored
3 entries were displayed.

cluster_A::>
----

