---
permalink: upgrade/task-configure-intercluster-lifs-4node.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, dedicated, ports, shared 
summary: Es können Intercluster LIFs auf dedizierten oder gemeinsam genutzten Ports konfiguriert werden. 
---
= Konfigurieren Sie Intercluster LIFs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie Sie Intercluster LIFs auf dedizierten und gemeinsam genutzten Ports konfigurieren.

[role="tabbed-block"]
====
.Konfigurieren Sie Intercluster-LIFs auf dedizierten Ports
--
Es können Intercluster LIFs an dedizierten Ports konfiguriert werden, um die verfügbare Bandbreite für den Replizierungsdatenverkehr zu erhöhen.

.Schritte
. Liste der Ports im Cluster:
+
`network port show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden die Netzwerkports in cluster01 angezeigt:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. Bestimmen Sie, welche Ports für die Intercluster-Kommunikation verfügbar sind:
+
`network interface show -fields home-port,curr-port`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Das folgende Beispiel zeigt, dass den Ports „e0e“ und „e0f“ keine LIFs zugewiesen wurden:

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01-01_clus1   e0a       e0a
Cluster cluster01-01_clus2   e0b       e0b
Cluster cluster01-02_clus1   e0a       e0a
Cluster cluster01-02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. Erstellen Sie eine Failover-Gruppe für die dedizierten Ports:
+
`network interface failover-groups create -vserver <system_SVM> -failover-group <failover_group> -targets <physical_or_logical_ports>`

+
Das folgende Beispiel weist den Failover-Gruppe „intercluster01“ auf der System-SVM „cluster01“ die Ports „e0e“ und „e0f“ zu:

+
[listing]
----
cluster01::> network interface failover-groups create -vserver cluster01 -failover-group
intercluster01 -targets
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. Vergewissern Sie sich, dass die Failover-Gruppe erstellt wurde:
+
`network interface failover-groups show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster01::> network interface failover-groups show
                                  Failover
Vserver          Group            Targets
---------------- ---------------- --------------------------------------------
Cluster
                 Cluster
                                  cluster01-01:e0a, cluster01-01:e0b,
                                  cluster01-02:e0a, cluster01-02:e0b
cluster01
                 Default
                                  cluster01-01:e0c, cluster01-01:e0d,
                                  cluster01-02:e0c, cluster01-02:e0d,
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
                 intercluster01
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
----
. Erstellen Sie Intercluster-LIFs auf der System-SVM und weisen Sie sie der Failover-Gruppe zu.
+
[cols="1,3"]
|===


| ONTAP-Version | Befehl 


 a| 
9.6 und höher
 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`



 a| 
9.5 und früher
 a| 
`network interface create -vserver system_SVM -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask> -failover-group <failover_group>`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden Intercluster-LIFs „cluster01_ic.01“ und „cluster01_ic02“ in der Failover-Gruppe „intercluster01“ erstellt:

+
[listing]
----
cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0 -failover-group intercluster01

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0 -failover-group intercluster01
----
. Überprüfen Sie, ob die Intercluster-LIFs erstellt wurden:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface show -service-policy default-intercluster`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface show -role intercluster`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. Vergewissern Sie sich, dass die Intercluster-LIFs redundant sind:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface show -service-policy default-intercluster -failover`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Das folgende Beispiel zeigt, dass der Intercluster LIFs „cluster01_ic.01“ und „cluster01_ic.02“ auf dem SVM „e0e“-Port an den „e0f“-Port scheitern.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----


--
.Konfigurieren Sie Intercluster-LIFs an gemeinsam genutzten Datenports
--
Es können Intercluster LIFs an Ports konfiguriert werden, die mit dem Datennetzwerk gemeinsam genutzt werden, um die Anzahl der Ports zu reduzieren, die Sie für ein Intercluster-Netzwerk benötigen.

.Schritte
. Liste der Ports im Cluster:
+
`network port show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden die Netzwerkports in cluster01 angezeigt:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. Intercluster-LIFs auf der System-SVM erstellen:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -service-policy default-intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface create -vserver <system_SVM> -lif <LIF_name> -role intercluster -home-node <node> -home-port <port> -address <port_IP> -netmask <netmask>`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden Intercluster-LIFs erstellt `cluster01_icl01` Und `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. Überprüfen Sie, ob die Intercluster-LIFs erstellt wurden:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface show -service-policy default-intercluster`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface show -role intercluster`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Vergewissern Sie sich, dass die Intercluster-LIFs redundant sind:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface show –service-policy default-intercluster -failover`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Das folgende Beispiel zeigt, dass der Intercluster LIFs „cluster01_ic.01“ und „cluster01_ic.02“ auf dem „e0c“-Port an den „e0d“-Port scheitern wird.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----


--
====