---
permalink: upgrade/task-expand-four-to-eight-mcc-fc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, create, mirrored, data, aggregate, node 
summary: Sie müssen auf jedem Knoten in der DR-Gruppe ein gespiegeltes Datenaggregat erstellen. 
---
= Erstellen Sie auf jedem MetroCluster FC-Knoten ein gespiegeltes Datenaggregat
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen auf jedem Knoten in der DR-Gruppe ein gespiegeltes Datenaggregat erstellen.

.Über diese Aufgabe
* Sie sollten wissen, welche Laufwerke in dem neuen Aggregat verwendet werden.
* Wenn Sie in Ihrem System mehrere Laufwerkstypen verwenden (heterogene Speicher), sollten Sie wissen, wie Sie sicherstellen können, dass der richtige Laufwerkstyp ausgewählt wird.
* Laufwerke sind Eigentum eines bestimmten Nodes. Wenn Sie ein Aggregat erstellen, müssen alle Laufwerke in diesem Aggregat im Besitz desselben Nodes sein, der zum Home-Node für das Aggregat wird.
+
In Systemen mit ADP werden Aggregate mithilfe von Partitionen erstellt, in denen jedes Laufwerk in die Partitionen P1, P2 und P3 partitioniert wird.

* Aggregatnamen sollten dem Benennungsschema entsprechen, das Sie beim Planen Ihrer MetroCluster-Konfiguration ermittelt haben.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Festplatten- und Aggregatmanagement"]

* Die Namen der Aggregate müssen auf allen MetroCluster-Standorten eindeutig sein. Das bedeutet, dass Sie nicht zwei verschiedene Aggregate mit demselben Namen auf Standort A und Standort B haben können.



NOTE: Für optimale Speicherleistung und -verfügbarkeit wird empfohlen, mindestens 20 % freien Speicherplatz für gespiegelte Aggregate vorzuhalten. Obwohl für nicht gespiegelte Aggregate 10 % empfohlen werden, können die zusätzlichen 10 % vom Dateisystem genutzt werden, um inkrementelle Änderungen aufzufangen. Inkrementelle Änderungen erhöhen die Speicherauslastung für gespiegelte Aggregate aufgrund der Copy-on-Write-Snapshot-basierten Architektur von ONTAP. Die Nichtbeachtung dieser Best Practices kann sich negativ auf die Leistung auswirken.

.Schritte
. Liste der verfügbaren Ersatzteile anzeigen:
+
`storage disk show -spare -owner <node_name>`

. Erstellen Sie das Aggregat:
+
`storage aggregate create -mirror true`

+
Wenn Sie am Cluster über die Managementoberfläche angemeldet sind, können Sie auf jedem Knoten im Cluster ein Aggregat erstellen. Um zu überprüfen, ob das Aggregat auf einem bestimmten Knoten erstellt wurde, verwenden Sie den  `-node` Parameter oder geben Sie Laufwerke an, die diesem Knoten gehören.

+
Sie können die folgenden Optionen angeben:

+
** Der Home Node des Aggregats (d. h. der Knoten, der das Aggregat im normalen Betrieb besitzt)
** Liste spezifischer Laufwerke, die dem Aggregat hinzugefügt werden sollen
** Anzahl der zu einführenden Laufwerke
+

NOTE: In der unterstützten Minimalkonfiguration, bei der eine begrenzte Anzahl an Laufwerken verfügbar ist, müssen Sie die Force-Small-Aggregate Option verwenden, um das Erstellen eines drei Festplatten-RAID-DP Aggregats zu ermöglichen.

** Prüfsummenstil, den Sie für das Aggregat verwenden möchten
** Typ der zu verwendenden Laufwerke
** Die Größe der zu verwendenden Laufwerke
** Fahrgeschwindigkeit zu verwenden
** RAID-Typ für RAID-Gruppen auf dem Aggregat
** Maximale Anzahl an Laufwerken, die in eine RAID-Gruppe aufgenommen werden können
** Gibt an, ob Laufwerke mit unterschiedlichen U/min zulässig sind
+
Weitere Informationen zu diesen Optionen finden Sie im `storage aggregate create` Man-Page.

+
Mit dem folgenden Befehl wird ein gespiegeltes Aggregat mit 10 Festplatten erstellt:

+
[listing]
----
cluster_A::> storage aggregate create aggr1_node_A_1 -diskcount 10 -node node_A_1 -mirror true
[Job 15] Job is queued: Create aggr1_node_A_1.
[Job 15] The job is starting.
[Job 15] Job succeeded: DONE
----


. Überprüfen Sie die RAID-Gruppe und die Laufwerke Ihres neuen Aggregats:
+
`storage aggregate show-status -aggregate <aggregate-name>`


