---
permalink: upgrade/task_configure_intercluster_lifs_to_share_data_ports.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, configure, intercluster, lif, shared, data, ports 
summary: Sie können Intercluster-LIFs an Ports konfigurieren, die gemeinsam mit dem Datennetzwerk verwendet werden. Auf diese Weise wird die Anzahl der Ports reduziert, die Sie für Intercluster-Netzwerke benötigen. 
---
= Konfigurieren von Intercluster-LIFs auf gemeinsam genutzten Datenports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Intercluster-LIFs an Ports konfigurieren, die gemeinsam mit dem Datennetzwerk verwendet werden. Auf diese Weise wird die Anzahl der Ports reduziert, die Sie für Intercluster-Netzwerke benötigen.

.Schritte
. Liste der Ports im Cluster:
+
`network port show`

+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden die Netzwerkports in cluster01 angezeigt:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. Intercluster-LIFs auf der System-SVM erstellen:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -role intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Im folgenden Beispiel werden Intercluster-LIFs erstellt `cluster01_icl01` Und `cluster01_icl02`:

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. Überprüfen Sie, ob die Intercluster-LIFs erstellt wurden:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface show -service-policy default-intercluster`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface show -role intercluster`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. Vergewissern Sie sich, dass die Intercluster-LIFs redundant sind:
+
|===


| *Im ONTAP 9.6 und höher:* 


 a| 
`network interface show –service-policy default-intercluster -failover`



| *In ONTAP 9.5 und früher:* 


 a| 
`network interface show -role intercluster -failover`

|===
+
Eine vollständige Befehlssyntax finden Sie in der man-Page.

+
Das folgende Beispiel zeigt, dass der Intercluster LIFs „cluster01_ic.01“ und „cluster01_ic.02“ auf dem „e0c“-Port an den „e0d“-Port scheitern wird.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

