---
permalink: upgrade/task_clear_the_configuration_on_a_controller_module_mcc.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, clear, configuration, controller, module 
summary: Bevor Sie ein neues Controller-Modul in der MetroCluster-Konfiguration verwenden, müssen Sie die Konfiguration löschen. 
---
= Löschen der Konfiguration auf einem Controller-Modul
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie in der MetroCluster-Konfiguration ein neues Controller-Modul verwenden, müssen Sie die vorhandene Konfiguration löschen.

.Schritte
. Halten Sie gegebenenfalls den Node an, um die LOADER-Eingabeaufforderung anzuzeigen:
+
`halt`

. Legen Sie an der Loader-Eingabeaufforderung die Umgebungsvariablen auf Standardwerte fest:
+
`set-defaults`

. Umgebung speichern:
+
`saveenv`

. Starten Sie an der LOADER-Eingabeaufforderung das Boot-Menü:
+
`boot_ontap menu`

. Löschen Sie an der Eingabeaufforderung des Startmenüs die Konfiguration:
+
`wipeconfig`

+
Antworten `yes` An die Bestätigungsaufforderung.

+
Der Node wird neu gebootet, und das Startmenü wird erneut angezeigt.

. Wählen Sie im Startmenü die Option *5*, um das System im Wartungsmodus zu booten.
+
Antworten `yes` An die Bestätigungsaufforderung.


