---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc, bootarg 
summary: Für Upgrades von Systemen, die in ONTAP 9.15.1 oder höher eingeführt wurden, müssen Sie ein Boot-ARG einrichten, bevor Sie mit dem Controller-Upgrade fortfahren können. 
---
= Legen Sie den erforderlichen Bootarg fest (für MetroCluster IP-Upgrades auf Systemen ab ONTAP 9.15.1).
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie auf ein System aktualisieren, das in ONTAP 9.15.1 oder höher eingeführt wurde, müssen Sie normalerweise ein Bootarg auf den alten Controllern festlegen, bevor Sie mit dem Upgrade beginnen können.


NOTE: Wenn Ihre Upgrade-Kombination betroffen ist, ist für ein erfolgreiches Upgrade das Festlegen eines Bootarg auf allen alten Controllern erforderlich.  Lesen Sie die Informationen in diesem Abschnitt sorgfältig durch, um zu prüfen, ob für Ihre Upgrade-Kombination die Festlegung eines Bootargs erforderlich ist und wie Sie das richtige Bootarg für Ihre Kombination festlegen.



== Schritt 1: Bestimmen Sie, ob Sie auf den alten Controllern ein Bootarg festlegen müssen

Verwenden Sie die folgenden Informationen, um zu überprüfen, ob Sie vor dem Starten des Upgrades ein erforderliches Bootarg festlegen müssen:

* Sie *müssen* auf den alten Controllern ein Bootarg für unterstützte Upgrades auf die folgenden Systeme festlegen, sofern nicht anders angegeben:
+
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60
** FAS50


* Sie müssen auf den alten Controllern *kein* Bootarg festlegen, wenn Ihr Upgrade eine der folgenden Kombinationen ist:
+
** Von einem AFF A70 -System zu einem AFF A90 -System
** Von einem FAS70-System zu einem FAS90-System





CAUTION: Wenn Sie für Ihr Upgrade kein Bootarg festlegen müssen, können Sie diese Aufgabe überspringen und direkt zulink:upgrade-mcc-ip-prepare-system.html["Bereiten Sie das System für das Upgrade vor"] .



== Schritt 2: Bestimmen Sie das Bootarg, das Sie auf den alten Controllern einstellen müssen

Bei den meisten betroffenen Upgrades müssen Sie Folgendes einstellen: `hw.cxgbe.toe_keepalive_disable` Bootarg auf den alten Controllern.  Für bestimmte Upgrade-Pfade müssen Sie jedoch die `bootarg.siw.interop_enabled` bootarg stattdessen.

Verwenden Sie die folgende Tabelle, um zu bestimmen, welche Bootarg Sie für Ihre spezifische Upgrade-Kombination einstellen müssen.

[cols="2*"]
|===
| Für dieses Upgrade... | Bootarg festlegen... 


| Von AFF A250 nach AFF A30 | `bootarg.siw.interop_enabled` 


| Von AFF C250 nach AFF C30 | `bootarg.siw.interop_enabled` 


| Von AFF A150 nach AFF A20 | `bootarg.siw.interop_enabled` 


| Von AFF A220 nach AFF A20 | `bootarg.siw.interop_enabled` 


 a| 
Alle anderen Upgrades für AFF A70, AFF A90, AFF A1K, FAS70-, FAS90-, AFF C80-, AFF A50-, AFF A30-, AFF C30-, AFF C60- oder FAS50-Systeme

*Hinweis:* Sie müssen kein Bootarg festlegen, wenn Ihr Upgrade von einem AFF A70 auf ein AFF A90 -System oder von einem FAS70- auf ein FAS90-System erfolgt.
| `hw.cxgbe.toe_keepalive_disable` 
|===


== Schritt 3: Stellen Sie das erforderliche Bootarg auf den alten Controllern ein

Nachdem Sie das für Ihre Upgrade-Kombination erforderliche Bootarg ermittelt haben, befolgen Sie die Schritte zum Festlegen des Bootarg auf den alten Controllern.  Diese Aufgabe ist *nur* für betroffene Upgrades erforderlich.


NOTE: Sie müssen das Bootarg auf allen alten Knoten an beiden Standorten festlegen, bevor Sie mit dem Upgrade beginnen.

.Schritte
. Halten Sie einen Node an beiden Standorten an und erlauben Sie dem HA-Partner, einen Storage-Takeover des Node durchzuführen:
+
`halt  -node <node_name>`

. Stellen Sie den erforderlichen Bootarg für Ihre Upgrade-Kombination ein. Sie haben bereits den Bootarg festgelegt, den Sie mithilfe der Tabelle in festlegen müssen<<upgrade_paths_bootarg_manual,Bestimmen Sie, welchen Bootarg Sie einstellen müssen>>.
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
.. Geben Sie an `LOADER` der Eingabeaufforderung des angehaltenen Node Folgendes ein:
+
`setenv hw.cxgbe.toe_keepalive_disable 1`

+
`saveenv`

+
`printenv hw.cxgbe.toe_keepalive_disable`



--
.bootarg.siw.interop_enabled
--
.. Geben Sie an `LOADER` der Eingabeaufforderung des angehaltenen Node Folgendes ein:
+
`setenv bootarg.siw.interop_enabled 1`

+
`saveenv`

+
`printenv bootarg.siw.interop_enabled`



--
====
. Booten des Node:
+
`boot_ontap`

. Führen Sie beim Booten des Node ein Giveback für den Node durch, um folgende Eingabeaufforderung zu erhalten:
+
`storage failover giveback -ofnode <node_name>`

. Wiederholen Sie die Schritte für alle Nodes in der DR-Gruppe oder DR-Gruppen, die Sie aktualisieren.


.Was kommt als Nächstes?
link:upgrade-mcc-ip-prepare-system.html["Bereiten Sie das System für das Upgrade vor"].
