---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-reassign-root-agg.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Weisen Sie die Festplatten des Stammaggregats dem neuen Controller-Modul unter Verwendung der zuvor zusammengetragenen System-IDs neu zu. 
---
= Weisen Sie die Festplatten des Root-Aggregats dem neuen MetroCluster IP-Controller-Modul neu zu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weisen Sie die Festplatten des Stammaggregats dem neuen Controller-Modul unter Verwendung der zuvor zusammengetragenen System-IDs neu zu.

.Über diese Aufgabe
Diese Aufgabe wird im Wartungsmodus ausgeführt.

Die alten System-IDs wurden in identifiziert link:upgrade-mcc-ip-system-controller-replace-prechecks.html#gather-information-before-the-upgrade["Sammeln Sie vor dem Upgrade Informationen"].

Die Beispiele in diesem Verfahren verwenden Controller mit den folgenden System-IDs:

|===


| Knoten | Alte System-ID | Neue System-ID 


 a| 
Knoten_B_1
 a| 
4068741254
 a| 
1574774970

|===
.Schritte
. Verkabeln Sie alle anderen Verbindungen mit den neuen Controller-Modulen (FC-VI, Storage, Cluster Interconnect usw.).
. Halten Sie das System an und starten Sie von der in den Wartungsmodus `LOADER` Eingabeaufforderung:
+
`boot_ontap maint`

. Zeigen Sie die Datenträger von Node_B_1-old an:
+
`disk show -a`

+
Die Befehlsausgabe zeigt die System-ID des neuen Controller-Moduls (1574774970). Allerdings sind die Root-Aggregat-Festplatten immer noch im Besitz der alten System-ID (4068741254). Dieses Beispiel zeigt keine Laufwerke an, die anderen Nodes in der MetroCluster-Konfiguration gehören.

+

CAUTION: Bevor Sie mit der Neuzuweisung der Festplatte fortfahren, überprüfen Sie, ob die zum Root-Aggregat des Node gehörenden Pool0- und Pool1-Festplatten in der Ausgabe angezeigt werden `disk show`. Im folgenden Beispiel werden in der Ausgabe die Laufwerke pool0 und pool1 aufgelistet, die sich im Besitz von Node_B_1-old befinden.

+
[listing]
----
*> disk show -a
Local System ID: 1574774970

  DISK         OWNER                     POOL   SERIAL NUMBER    HOME                      DR HOME
------------   -------------             -----  -------------    -------------             -------------
...
rr18:9.126L44 node_B_1-old(4068741254)   Pool1  PZHYN0MD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L49 node_B_1-old(4068741254)   Pool1  PPG3J5HA         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L21 node_B_1-old(4068741254)   Pool1  PZHTDSZD         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L2  node_B_1-old(4068741254)   Pool0  S0M1J2CF         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:8.126L3  node_B_1-old(4068741254)   Pool0  S0M0CQM5         node_B_1-old(4068741254)  node_B_1-old(4068741254)
rr18:9.126L27 node_B_1-old(4068741254)   Pool0  S0M1PSDW         node_B_1-old(4068741254)  node_B_1-old(4068741254)
...
----
. Weisen Sie die Root-Aggregat-Festplatten auf den Laufwerk-Shelfs dem neuen Controller zu:
+
`disk reassign -s <old-sysid> -d <new-sysid>`

+

NOTE: Wenn Ihr MetroCluster IP-System mit erweiterter Festplattenpartitionierung konfiguriert ist, müssen Sie die ID des DR-Partnersystems angeben, indem Sie den Befehl ausführen `disk reassign -s old-sysid -d new-sysid -r dr-partner-sysid`.

+
Das folgende Beispiel zeigt die Neuzuweisung von Laufwerken:

+
[listing]
----
*> disk reassign -s 4068741254 -d 1574774970
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? Jul 14 19:23:49 [localhost:config.bridge.extra.port:error]: Both FC ports of FC-to-SAS bridge rtp-fc02-41-rr18:9.126L0 S/N [FB7500N107692] are attached to this controller.
y
Disk ownership will be updated on all disks previously belonging to Filer with sysid 4068741254.
Do you want to continue (y/n)? y
----
. Überprüfen Sie, ob alle Festplatten wie erwartet neu zugewiesen wurden:
+
`disk show`

+
[listing]
----
*> disk show
Local System ID: 1574774970

  DISK        OWNER                      POOL   SERIAL NUMBER   HOME                      DR HOME
------------  -------------              -----  -------------   -------------             -------------
rr18:8.126L18 node_B_1-new(1574774970)   Pool1  PZHYN0MD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L49 node_B_1-new(1574774970)   Pool1  PPG3J5HA        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L21 node_B_1-new(1574774970)   Pool1  PZHTDSZD        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L2  node_B_1-new(1574774970)   Pool0  S0M1J2CF        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:9.126L29 node_B_1-new(1574774970)   Pool0  S0M0CQM5        node_B_1-new(1574774970)  node_B_1-new(1574774970)
rr18:8.126L1  node_B_1-new(1574774970)   Pool0  S0M1PSDW        node_B_1-new(1574774970)  node_B_1-new(1574774970)
*>
----
. Zeigt den Aggregatstatus an:
+
`aggr status`

+
[listing]
----
*> aggr status
           Aggr            State       Status           Options
aggr0_node_b_1-root        online      raid_dp, aggr    root, nosnap=on,
                           mirrored                     mirror_resync_priority=high(fixed)
                           fast zeroed
                           64-bit
----
. Wiederholen Sie die oben genannten Schritte auf dem Partner-Node (Node_B_2-New).


.Was kommt als Nächstes?
link:upgrade-mcc-ip-system-controller-replace-boot-new-controllers.html["Booten der neuen Controller und Wiederherstellen der LIF-Konfiguration"].
