---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-prepare-network-configuration.html 
sidebar: sidebar 
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc 
summary: Nachdem Sie Informationen gesammelt und den Vorgang fortgesetzt haben, wird die Umschaltung fortgesetzt. 
---
= Bereiten Sie die Netzwerkkonfiguration der alten MetroCluster IP-Controller vor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie Informationen gesammelt und den Vorgang fortgesetzt haben, wird die Umschaltung fortgesetzt.

.Bevor Sie beginnen
Vor dem Starten der Umschaltung hält der Automatisierungsvorgang pausiert, sodass Sie manuell überprüfen können, ob alle LIFs „`up`“ an Standort B. sind Ggf. Beliebige LIFs mit „`deigenen`“ bis „`up`“ bereitstellen und den Automatisierungsvorgang mit dem fortsetzen `system controller replace resume` Befehl.

Der Automatisierungsvorgang initiiert die Umschaltvorgänge. Nach Abschluss dieser Vorgänge wird der Vorgang bei *pausiert für Benutzereingriff* angehalten, sodass Sie die Controller racken und installieren können, die Partner-Controller starten und die Root-Aggregat-Festplatten dem neuen Controller-Modul aus Flash-Backup mit dem zuvor gesammelten zuweisen können `sysids`.

.Über diese Aufgabe
* Diese Aufgabe muss an jedem der alten Knoten ausgeführt werden.
* Sie verwenden die in gesammelten Informationenlink:upgrade-mcc-ip-system-controller-replace-prechecks.html#gather-information-before-the-upgrade["Sammeln Sie vor dem Upgrade Informationen"].


.Schritte
. Booten Sie die alten Nodes, und melden Sie sich dann bei den Nodes an:
+
`boot_ontap`

. Wenn das System, auf das Sie aktualisieren, *Shared Cluster/HA-Ports* verwendet, überprüfen Sie, ob die MetroCluster-IP-Schnittstellen unterstützte IP-Adressen verwenden.
+
Verwenden Sie die folgenden Informationen, um zu bestimmen, ob das neue System gemeinsam genutzte Cluster/HA-Ports verwendet:

+
[role="tabbed-block"]
====
.Shared-Cluster-/HA-Ports
--
Die in der folgenden Tabelle aufgeführten Systeme verwenden gemeinsam genutzte Cluster-/HA-Ports:

[cols="2*"]
|===
| AFF und ASA Systeme | FAS Systeme 


 a| 
** AFF A20
** AFF A30
** AFF C30
** AFF A50
** AFF C60
** AFF C80
** AFF A70
** AFF A90
** AFF A1K

 a| 
** FAS70
** FAS90


|===
--
.Shared-MetroCluster/HA-Ports
--
Die in der folgenden Tabelle aufgeführten Systeme verwenden gemeinsam genutzte MetroCluster/HA-Ports:

[cols="2*"]
|===
| AFF und ASA Systeme | FAS Systeme 


 a| 
** AFF A150, ASA A150
** AFF A220
** AFF C250, ASA C250
** AFF A250, ASA A250
** AFF A300
** AFF A320
** AFF C400, ASA C400
** AFF A400, ASA A400
** AFF A700
** AFF C800, ASA C800
** AFF A800, ASA A800
** AFF A900, ASA A900

 a| 
** FAS2750
** FAS500f
** FAS8200
** FAS8300
** FAS8700
** FAS9000
** FAS9500


|===
--
====
+
.. Überprüfen Sie die IP-Adressen der MetroCluster-Schnittstellen auf den alten Controllern:
+
`metrocluster configuration-settings interface show`

.. Wenn die MetroCluster-Schnittstellen 169.254.17.x- oder 169.254.18.x-IP-Adressen verwenden, finden Sie unter link:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/How_to_modify_the_properties_of_a_MetroCluster_IP_interface["Der Knowledge Base-Artikel „Ändern der Eigenschaften einer MetroCluster IP-Schnittstelle“"^] Informationen zum Ändern der Schnittstellen-IP-Adressen, bevor Sie mit dem Upgrade fortfahren.
+

CAUTION: Ein Upgrade auf ein System mit *Shared Cluster/HA-Ports* wird nicht unterstützt, wenn die MetroCluster-Schnittstellen mit 169.254.17.x- oder 169.254.18.x-IP-Adressen konfiguriert sind.



. Ändern Sie die Intercluster LIFs auf den alten Controllern, um einen anderen Home Port zu verwenden als die Ports, die für HA Interconnect oder MetroCluster IP DR Interconnect auf den neuen Controllern verwendet werden.
+

NOTE: Dieser Schritt ist für ein erfolgreiches Upgrade erforderlich.

+
Die Intercluster LIFs auf den alten Controllern müssen einen anderen Home Port verwenden als die Ports, die für HA Interconnect oder MetroCluster IP DR Interconnect auf den neuen Controllern verwendet werden. Wenn Sie beispielsweise auf AFF A90 Controller aktualisieren, sind die HA Interconnect-Ports e1a und e7a und die MetroCluster IP DR Interconnect-Ports e2b und e3b. Sie müssen die Intercluster LIFs auf den alten Controllern verschieben, wenn sie auf den Ports e1a, e7a, e2b oder e3b gehostet werden.

+
Informationen zur Portverteilung und -Zuweisung auf den neuen Knoten finden Sie im https://hwu.netapp.com["Hardware Universe"].

+
.. Sehen Sie sich auf den alten Controllern die Intercluster LIFs an:
+
`network interface show  -role intercluster`

+
Je nachdem, ob die Intercluster LIFs auf den alten Controllern die gleichen Ports verwenden, wie die Ports für HA Interconnect oder den MetroCluster IP DR Interconnect auf den neuen Controllern.

+
[cols="2*"]
|===
| Wenn die Intercluster LIFs... | Gehe zu... 


| Verwenden Sie denselben Home-Port | <<controller_replace_upgrade_prepare_network_ports_2b,Unterschritt b>> 


| Verwenden Sie einen anderen Home-Port | <<controller_replace_upgrade_prepare_network_ports_3,Schritt 4>> 
|===
.. [[Controller_replace_Upgrade_prepare_Network_Ports_2b]]Ändern Sie die Intercluster LIFs, um einen anderen Home Port zu verwenden:
+
`network interface modify -vserver <vserver> -lif <intercluster_lif> -home-port <port-not-used-for-ha-interconnect-or-mcc-ip-dr-interconnect-on-new-nodes>`

.. Überprüfen Sie, ob sich alle Intercluster LIFs an ihren neuen Home Ports befinden:
+
`network interface show -role intercluster -is-home  false`

+
Die Befehlsausgabe sollte leer sein und bedeutet, dass sich alle Intercluster LIFs auf ihren jeweiligen Home Ports befinden.

.. Setzen Sie alle LIFs zurück, die sich nicht auf ihrem Home Port befinden:
+
`network interface revert -lif <intercluster_lif>`

+
Wiederholen Sie den Befehl für jede Intercluster LIF, die sich nicht im Home Port befindet.



. [[Controller_replace_Upgrade_prepare_Network_Ports_3]]Zuweisen Sie den Home-Port aller Daten-LIFs auf dem alten Controller einem gemeinsamen Port, der sowohl auf den alten als auch auf den neuen Controller-Modulen identisch ist.
+

CAUTION: Wenn die alten und neuen Controller keinen gemeinsamen Port haben, müssen Sie die Daten-LIFs nicht ändern. Überspringen Sie diesen Schritt und gehen Sie direkt zu <<upgrades_assisted_without_matching_ports,Schritt 5>>.

+
.. Anzeigen der LIFs:
+
`network interface show`

+
Alle Daten-LIFs wie SAN und NAS sind admin „` up`“ und operativ „`down`“, da diese sich am Umschaltstandort befinden (Cluster_A).

.. Überprüfen Sie die Ausgabe, um einen gemeinsamen physischen Netzwerk-Port zu finden, der auf den alten und den neuen Controllern identisch ist, die nicht als Cluster-Port verwendet werden.
+
„`e0d`“ ist zum Beispiel ein physischer Port an alten Controllern und ist auch auf neuen Controllern vorhanden. „`e0d`“ wird nicht als Cluster-Port oder anderweitig auf den neuen Controllern verwendet.

+
Informationen zur Portnutzung der einzelnen Plattformmodelle finden Sie imlink:https://hwu.netapp.com/["Hardware Universe"^].

.. Ändern Sie alle Daten-LIFS, um den gemeinsamen Port als Home-Port zu verwenden:
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`

+
Im folgenden Beispiel lautet „`e0d`“.

+
Beispiel:

+
[listing]
----
network interface modify -vserver vs0 -lif datalif1 -home-port e0d
----


. [[Upgrades_Assisted_without_Matching_Ports]] Ändern Sie Broadcast-Domänen, um das zu löschende VLAN und die physischen Ports zu entfernen:
+
`broadcast-domain remove-ports -broadcast-domain <broadcast-domain-name>-ports <node-name:port-id>`

+
Wiederholen Sie diesen Schritt für alle VLAN- und physischen Ports.

. Entfernen Sie alle VLAN-Ports mithilfe von Cluster-Ports als Mitgliedsports und Schnittstellengruppen, die Cluster-Ports als Mitgliedsports verwenden.
+
.. VLAN-Ports löschen:
+
`network port vlan delete -node <node-name> -vlan-name <portid-vlandid>`

+
Beispiel:

+
[listing]
----
network port vlan delete -node node1 -vlan-name e1c-80
----
.. Entfernen Sie physische Ports aus den Schnittstellengruppen:
+
`network port ifgrp remove-port -node <node-name> -ifgrp <interface-group-name> -port <portid>`

+
Beispiel:

+
[listing]
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----
.. VLAN- und Schnittstellengruppen-Ports aus der Broadcast-Domäne entfernen:
+
`network port broadcast-domain remove-ports -ipspace <ipspace> -broadcast-domain <broadcast-domain-name>-ports <nodename:portname,nodename:portname>,..`

.. Ändern Sie die Ports der Schnittstellengruppe, um andere physische Ports als Mitglied zu verwenden:
+
`ifgrp add-port -node <node-name> -ifgrp <interface-group-name> -port <port-id>`



. Anhalten der Knoten:
+
`halt -inhibit-takeover true -node <node-name>`

+
Dieser Schritt muss auf beiden Knoten durchgeführt werden.

. Überprüfen Sie, ob die Nodes an der `LOADER` Eingabeaufforderung angezeigt werden, und sammeln und erhalten Sie die aktuellen Umgebungsvariablen.
. Ermitteln Sie die Bootarg-Werte:
+
`printenv`

. Schalten Sie die Nodes und Shelfs an dem Standort aus, an dem der Controller aktualisiert wird.


.Was kommt als Nächstes?
link:upgrade-mcc-ip-system-controller-replace-setup-new-controllers.html["Richten Sie die neuen Controller ein und booten Sie sie über das Netzwerk"].
