---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html 
sidebar: sidebar 
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing 
summary: Nach der Installation der Tiebreaker Software können MetroCluster Konfigurationen hinzugefügt oder geändert oder aus der Tiebreaker Software entfernt werden. 
---
= Konfigurieren Sie die MetroCluster Tiebreaker-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Installation der Tiebreaker Software können MetroCluster Konfigurationen hinzugefügt oder geändert oder aus der Tiebreaker Software entfernt werden.



== Starten Sie die Tiebreaker-Software-Befehlszeilenschnittstelle.

Nach der Installation der Tiebreaker Software müssen Sie die CLI starten, um die Software zu konfigurieren.

. Starten Sie die CLI von der Eingabeaufforderung des Hosts, auf dem Sie die Software installiert haben:
+
`netapp-metrocluster-tiebreaker-software-cli`

. Geben Sie nach der Installation und während des ersten Startvorgangs das Kennwort für den Tiebreaker-Benutzer ein, um auf die Datenbank zuzugreifen. Dies ist das Kennwort, das Sie während der Installation für den Datenbankbenutzer angegeben haben.




== Fügen Sie MetroCluster-Konfigurationen hinzu

Nach der Installation der NetApp MetroCluster Tiebreaker Software können mehrere MetroCluster Konfigurationen gleichzeitig hinzugefügt werden.

.Über diese Aufgabe
* Sie müssen die MetroCluster-Konfiguration in einer ONTAP-Umgebung installiert und die Einstellungen in der Software aktiviert haben.
* Die einzelnen Schritte und die zu erwartende Befehlsausgabe hängen von der Version von Tiebreaker ab, die Sie verwenden.


[role="tabbed-block"]
====
.Tiebreaker 1.5 oder früher
--
.Schritte
. Über die Tiebreaker Befehlszeilenschnittstelle (CLI) können Sie mit dem Hinzufügungs-Befehl MetroCluster-Konfigurationen hinzufügen.
+
Wenn Sie den Hostnamen verwenden, muss dieser der vollständig qualifizierte Domänenname (FQDN) sein.

+
Im folgenden Beispiel wird die Konfiguration von Cluster_A gezeigt:

+
.Beispiel
[%collapsible]
=====
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: <monitor_name>
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----
=====
. Überprüfen Sie, ob die MetroCluster-Konfiguration ordnungsgemäß mit der Tiebreaker CLI hinzugefügt wurde `monitor show -status` Befehl.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Deaktivieren Sie den Observer-Modus für die Tiebreaker-Software, um eine Umschaltung automatisch zu starten, nachdem ein Standortfehler erkannt wurde:
+
`monitor modify -monitor-name <monitor_name> -observer-mode false`

+
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----


--
.Tiebreak 1.6 oder höher
--
.Schritte
. Über die Tiebreaker Befehlszeilenschnittstelle (CLI) können Sie mit dem Hinzufügungs-Befehl MetroCluster-Konfigurationen hinzufügen.
+
Wenn Sie den Hostnamen verwenden, muss dieser der vollständig qualifizierte Domänenname (FQDN) sein.

+
Im folgenden Beispiel wird die Konfiguration von Cluster_A gezeigt:

+
.Beispiel
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter Monitor Name: cluster_A
Enter Cluster IP Address: <cluster_ip_value>
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: <peer_cluster_ip_value>
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:

 NOTE: Before enabling automatic switchover capability, make sure to review the 'risks and limitations' as described in the MetroCluster Tiebreaker Installation and Configuration Guide.

Do you want to enable automatic switchover capability for monitor(Y/N): y
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
Verifying SSL certificate chain from cluster_A...

===============================================
Warning missing SSL certificates
===============================================

Cluster: cluster_A

IP Address: <cluster_ip_value>

Result:

The MetroCluster Tiebreaker is unable to verify the SSL certificate chain.

Recommended Actions:

Run the following command to identify missing certificates:

monitor switchover-simulate

Import any missing certificates as indicated by the command output.

For detailed instructions, please refer to the MetroCluster Tiebreaker documentation, or contact NetApp Support for assistance.

Note:

Missing certificates will prevent the MetroCluster Tiebreaker from issuing a switchover request in the event of a site failure.

================================================================================================================================
Verifying SSL certificate chain from cluster_B...

SSL certificate chain is valid
----
=====
. Überprüfen Sie, ob die MetroCluster-Konfiguration ordnungsgemäß mit der Tiebreaker CLI hinzugefügt wurde `monitor show -status` Befehl.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
. Importieren Sie die fehlenden Zertifikate, indem Sie die Schritte für Ihre Tiebreaker-Version ausführen in<<import-certificates-tb17,Importzertifikate>> Die


--
====
.Verwandte Informationen
link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["Risiken und Einschränkungen bei der Verwendung von MetroCluster Tiebreaker im aktiven Modus"]



== Importzertifikate

Um eine nahtlose Überwachung in Tiebreaker 1.6 oder höher zu ermöglichen, müssen Sie das Server-SSL-Zertifikat (Secure Sockets Layer), das Zwischenzertifikat (falls vorhanden) und das Stammzertifikat von ONTAP in den Schlüsselspeicher der Java Virtual Machine (JVM) importieren.

.Über diese Aufgabe
* Diese Aufgabe ist in Tiebreaker 1.6 oder höher erforderlich.
* Diese Aufgabe führen Sie aus, nachdem Sie eine MetroCluster -Konfiguration erfolgreich zu Tiebreaker hinzugefügt haben oder wenn Ihre Zertifikate ablaufen.
* In Tiebreaker 1.7 oder höher können Sie eine Switchover-Simulation durchführen, um zu prüfen, ob Sie ein Zertifikat importieren müssen.  Falls die Umstellungssimulation fehlschlägt, müssen Sie Zertifikate von ONTAP in den Schlüsselspeicher der Java Virtual Machine (JVM) importieren.


[role="tabbed-block"]
====
.Tiebreaker 1.7 oder später
--
.Schritte
. Führen Sie eine Umstellungssimulation durch, um zu prüfen, ob Sie Zertifikate importieren müssen.
+
.. Überprüfen Sie den Überwachungsstatus des Tiebreakers:
`monitor show -status`
+
.Beispiel
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Eine Umschaltsimulation auslösen:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
Der Befehl liefert die folgende Ausgabe, wenn Sie Zertifikate in die JVM importieren müssen:

+
[listing]
----
Failed to trigger Switchover Simulation. Please check Metrocluster Tiebreaker logs for further information or contact NetApp support.
----


. Führen Sie für jedes Zertifikat, das Sie importieren müssen (SSL-Server-, Zwischen- oder Stammzertifikat), den folgenden Befehl aus.
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** Der `<certificate_file_name>` Der Wert gibt den Dateinamen des Zertifikats an, das Sie importieren möchten.
** Der `-alias <certificate>` Der Wert gibt den Namen an, unter dem das Zertifikat nach dem Import in die JVM gespeichert werden soll.
+
Das folgende Beispiel zeigt, wie man ein Stammzertifikat mit dem Dateinamen importiert `root.crt` und ein SSL-Serverzertifikat mit dem Dateinamen `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Starten Sie die Tiebreaker-Software neu:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. Führen Sie die Umschaltsimulationsprüfungen erneut durch:
+
.. Überprüfen Sie den Überwachungsstatus des Tiebreakers:
`monitor show -status`
+
.Beispiel
[%collapsible]
=====
[listing]
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Eine Umschaltsimulation auslösen:
+
`monitor switchover-simulate -monitor-name <monitor_name> -cluster <cluster_name>`

+
[listing]
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----




--
.Tiebreaker 1.6 oder 1.6P1
--
.Schritte
. Alle Zertifikate aus ONTAP importieren. Führen Sie für jedes Zertifikat, das Sie importieren müssen (SSL-Server-, Zwischen- oder Stammzertifikat), den folgenden Befehl aus.
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`

+
** Der `<certificate_file_name>` Der Wert gibt den Dateinamen des Zertifikats an, das Sie importieren möchten.
** Der `-alias <certificate>` Der Wert gibt den Namen an, unter dem das Zertifikat nach dem Import in die JVM gespeichert werden soll.
+
Das folgende Beispiel zeigt, wie man ein Stammzertifikat mit dem Dateinamen importiert `root.crt` und ein SSL-Serverzertifikat mit dem Dateinamen `ssl_cert.crt`:

+
[listing]
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----


. Starten Sie die Tiebreaker-Software neu:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`



--
====


== Befehle zum Ändern von MetroCluster Tiebreaker Konfigurationen

Sie können die MetroCluster-Konfiguration jederzeit ändern, wenn Sie die Einstellungen ändern möchten.

Der Tiebreaker CLI-Monitor-Änderungsbefehl kann mit einer der folgenden Optionen verwendet werden. Mit dem Befehl Monitor show -Status können Sie Ihre Änderungen bestätigen.

[cols="30,70"]
|===


| Option | Beschreibung 


 a| 
-Monitor-Name
 a| 
Name der MetroCluster-Konfiguration



 a| 
-Monitor aktivieren
 a| 
Aktiviert und deaktiviert die Überwachung der MetroCluster-Konfiguration



 a| 
-Stumm-Periode
 a| 
Zeitraum in Sekunden, für die die MetroCluster Tiebreaker Software nach der Erkennung einen Standortausfall bestätigt



 a| 
-Observer-Modus
 a| 
Der Observer-Modus (True) bietet nur Überwachung und löst bei einem Standortunfall keine Umschaltung aus. Der Online-Modus (false) löst bei einem Standortausfall eine Umschaltung aus.

* link:concept_overview_of_the_tiebreaker_software.html["Wie die Tiebreaker Software Standortausfällen erkennt"]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html["Risiken und Einschränkungen bei der Verwendung von MetroCluster Tiebreaker im aktiven Modus"]


|===
Im folgenden Beispiel wird der Silent Period für die Konfiguration geändert.

[listing]
----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----
Über die Tiebreaker CLI `debug` Mit dem Befehl kann der Protokollierungsmodus geändert werden.

[cols="30,70"]
|===


| Befehl | Beschreibung 


 a| 
Debug-Status
 a| 
Zeigt den Status des Debug-Modus an



 a| 
Debug aktivieren
 a| 
Aktiviert den Debug-Modus für die Protokollierung



 a| 
Debug deaktivieren
 a| 
Deaktiviert den Debug-Modus für die Protokollierung

|===
Bei Systemen mit Tiebreaker 1.4 und älteren Versionen bietet die Tiebreaker CLI `update-mcctb-password` Mit dem Befehl kann das Benutzerpasswort aktualisiert werden. Dieser Befehl ist in Tiebreak 1.5 und höher veraltet.

[cols="30,70"]
|===


| Befehl | Beschreibung 


 a| 
Update-mcctb-password
 a| 
Das Benutzerpasswort wurde erfolgreich aktualisiert

|===


== MetroCluster-Konfigurationen entfernen

Sie können die MetroCluster-Konfiguration entfernen, die von der Tiebreaker Software überwacht wird, wenn Sie keine MetroCluster-Konfiguration mehr überwachen möchten.

. Verwenden Sie die Tiebreaker CLI `monitor remove` Befehl zum Entfernen der MetroCluster-Konfiguration.
+
Im folgenden Beispiel wird „`Cluster_A`“ aus der Software entfernt:

+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----
. Überprüfen Sie, ob die MetroCluster-Konfiguration ordnungsgemäß mithilfe der Tiebreaker CLI entfernt wird `monitor show -status` Befehl.
+
[listing]
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

