---
permalink: tiebreaker/reference_where_to_find_additional_information_tb_icg.html 
sidebar: sidebar 
keywords: metrocluster, configuration, operation, netapp, documentation, additional, information, miscellaneous, guide 
summary: Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier.



== MetroCluster und sonstige Informationen

|===


| Informationsdaten | Betreff 


 a| 
link:../index.html["MetroCluster-Dokumentation"]
 a| 
* Alle MetroCluster-Informationen




 a| 
http://["Technischer Bericht 4375 zu NetApp MetroCluster für ONTAP 9.3"^]
 a| 
* Eine technische Übersicht über Konfiguration und Betrieb von MetroCluster
* Best Practices für die Konfiguration von MetroCluster.




 a| 
https://["Installation und Konfiguration von Fabric-Attached MetroCluster"]
 a| 
* Fabric-Attached MetroCluster-Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der FC-Switches
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://["Installation und Konfiguration von Stretch MetroCluster"]
 a| 
* Stretch-MetroCluster Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://["Installation und Konfiguration von MetroCluster IP"]
 a| 
* MetroCluster IP Architektur
* Verkabelung der MetroCluster IP-Konfiguration
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://["Warten der MetroCluster-Komponenten"]
 a| 
* Richtlinien für die Wartung in einer MetroCluster-Konfiguration
* Verfahren zum Austausch oder Upgrade von Hardware und Firmware-Upgrades für FC-to-SAS-Bridges und FC-Switches
* Hot-hinzufügen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster Konfiguration
* Entfernen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster-Konfiguration
* Austausch von Hardware an einem Disaster-Standort in einer Fabric-Attached- oder Stretch-MetroCluster Konfiguration
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster Konfiguration mit zwei Nodes auf eine MetroCluster Konfiguration mit vier Nodes.
* Erweiterung einer Fabric-Attached oder Stretch MetroCluster Konfiguration mit vier Nodes auf eine MetroCluster Konfiguration mit acht Nodes




 a| 
Active IQ Unified Manager-Dokumentation

https://["NetApp Dokumentation: Produktleitfäden und Ressourcen"^]
 a| 
* Monitoring der MetroCluster Konfiguration und Performance




 a| 
https://["Kopienbasierte Transition"]
 a| 
* Migration von Daten von 7-Mode Storage-Systemen zu geclusterten Storage-Systemen


|===