---
permalink: install-fc/brocade-fc-port-config-bridges.html 
sidebar: sidebar 
keywords: ONTAP, FAS, FC, Brocade, metrocluster 
summary: Die folgenden Tabellen zeigen die Portnutzung auf Brocade -Switches. 
---
= Brocade -Port-Nutzung für FC-zu-SAS-Brücken in einer MetroCluster FC-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die erforderlichen Portzuweisungen für die Verkabelung von Brocade FC-Switches mit FC-zu-SAS-Brücken. Die Portzuweisungen variieren je nachdem, ob die Brücken einen oder zwei FC-Ports verwenden.


NOTE: Brocade 7810-Switches unterstützen nur eine DR-Gruppe.



== Shelf-Konfigurationen mit FibreBridge 7500N- oder 7600N-Brücken unter Verwendung beider FC-Ports (FC1 und FC2)



=== MetroCluster 1 oder DR-Gruppe 1

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 1 oder DR-Gruppe 1 für FibreBridge 7500N- oder 7600N-Bridges unter Verwendung beider FC-Ports (FC1 und FC2) auf Brocade Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Bei den Switches Brocade 6505, G610, G710, G620, G620-1, G630 und G630-1 können Sie zusätzliche Bridges an die Ports 12–15 anschließen.
* Bei Brocade 6510- und DCX 8510-8-Switches können Sie zusätzliche Bridges an die Ports 12–19 anschließen.
* Bei Brocade 6520-Switches können Sie zusätzliche Bridges an die Ports 12–21 und 24–45 anschließen.
* Auf Brocade 7810- und 7840-Switches unterstützt MetroCluster 1 oder DR-Gruppe 1 nur zwei Bridge-Stacks.
* Bei Brocade G720- und G730-Switches können Sie zusätzliche Bridges an die Ports 16–21 anschließen.


[cols="2a,2a,2a,2a,2a,2a,2a,2a,2a,2a,2a"]
|===
2+| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *6505-, G610-, G710-Anschluss* | *6510, DCX 8510-8-Anschluss* | *6520-Anschluss* | *7810-Anschluss* | *7840-Anschluss* | *G620-, G620-1-, G630-, G630-1-Anschluss* | *G720, G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
FC1
 a| 
1
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
10



 a| 
FC2
 a| 
2
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
10



 a| 
Bridge_x_1b
 a| 
FC1
 a| 
1
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
11



 a| 
FC2
 a| 
2
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
11



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
FC1
 a| 
1
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
14



 a| 
FC2
 a| 
2
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
14



 a| 
Bridge_x_2b
 a| 
FC1
 a| 
1
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
15



 a| 
FC2
 a| 
2
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
15

|===


=== MetroCluster 2 oder DR-Gruppe 2

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 2 oder DR-Gruppe 2 für FibreBridge 7500N- oder 7600N-Bridges unter Verwendung beider FC-Ports (FC1 und FC2) auf Brocade Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Auf den Switches Brocade 6510, DCX 8510-8 und 7840 unterstützt MetroCluster 2 oder DR-Gruppe 2 nur zwei Bridge-Stacks.
* Bei Brocade 6520-Switches können Sie zusätzliche Bridges an die Ports 60–69 und 72–93 anschließen.
* Bei den Switches Brocade G620, G620-1, G630 und G630-1 können Sie zusätzliche Bridges an die Ports 32–35 anschließen.
* Bei Brocade G720- und G730-Switches können Sie zusätzliche Bridges an die Ports 36–39 anschließen.
* Die Portnutzung für die Brocade 6505-, G610- und G710-Switches in einer MetroCluster Konfiguration mit acht Knoten wird nicht angezeigt. Aufgrund der begrenzten Anzahl von Ports weisen Sie die Ports je nach Controllermodell und Anzahl der verwendeten ISLs und Bridge-Paare Site für Site zu.


[cols="2a,2a,2a,2a,2a,2a,2a,2a,2a,2a,2a"]
|===
2+| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *6505-, G610-, G710-Anschluss* | *6510, DCX 8510-8-Anschluss* | *6520-Anschluss* | *7810-Anschluss* | *7840-Anschluss* | *G620-, G620-1-, G630-, G630-1-Anschluss* | *G720, G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
FC1
 a| 
1
 a| 
n/a
 a| 
32
 a| 
56
 a| 
n/a
 a| 
20
 a| 
26
 a| 
32



 a| 
FC2
 a| 
2
 a| 
n/a
 a| 
32
 a| 
56
 a| 
n/a
 a| 
20
 a| 
26
 a| 
32



 a| 
Bridge_x_1b
 a| 
FC1
 a| 
1
 a| 
n/a
 a| 
33
 a| 
57
 a| 
n/a
 a| 
21
 a| 
27
 a| 
33



 a| 
FC2
 a| 
2
 a| 
n/a
 a| 
33
 a| 
57
 a| 
n/a
 a| 
21
 a| 
27
 a| 
33



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
FC1
 a| 
1
 a| 
n/a
 a| 
34
 a| 
58
 a| 
n/a
 a| 
22
 a| 
30
 a| 
34



 a| 
FC2
 a| 
2
 a| 
n/a
 a| 
34
 a| 
58
 a| 
n/a
 a| 
22
 a| 
30
 a| 
34



 a| 
Bridge_x_2b
 a| 
FC1
 a| 
1
 a| 
n/a
 a| 
35
 a| 
59
 a| 
n/a
 a| 
23
 a| 
31
 a| 
35



 a| 
FC2
 a| 
2
 a| 
n/a
 a| 
35
 a| 
59
 a| 
n/a
 a| 
23
 a| 
31
 a| 
35

|===


=== MetroCluster 3 oder DR-Gruppe 3

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 3 oder DR-Gruppe 3 für FibreBridge 7500N- oder 7600N-Bridges unter Verwendung beider FC-Ports (FC1 und FC2) auf Brocade Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Bei Brocade G630- und G630-1-Switches können Sie zusätzliche Bridges an die Ports 60–63 anschließen.
* Bei Brocade G730-Switches können Sie zusätzliche Bridges an die Ports 64, 65, 68 und 69 anschließen.


[cols="2a,2a,2a,2a,2a,2a"]
|===
2+| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *G630, G630-1-Anschluss* | *G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
FC1
 a| 
1
 a| 
56
 a| 
58



 a| 
FC2
 a| 
2
 a| 
56
 a| 
58



 a| 
Bridge_x_1b
 a| 
FC1
 a| 
1
 a| 
57
 a| 
59



 a| 
FC2
 a| 
2
 a| 
57
 a| 
59



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
FC1
 a| 
1
 a| 
58
 a| 
62



 a| 
FC2
 a| 
2
 a| 
58
 a| 
62



 a| 
Bridge_x_2b
 a| 
FC1
 a| 
1
 a| 
59
 a| 
63



 a| 
FC2
 a| 
2
 a| 
59
 a| 
63

|===


=== MetroCluster 4 oder DR-Gruppe 4

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 4 oder DR-Gruppe 4 für FibreBridge 7500N- oder 7600N-Bridges unter Verwendung beider FC-Ports (FC1 und FC2) auf Brocade Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Bei Brocade G630- und G630-1-Switches können Sie zusätzliche Bridges an die Ports 80–83 anschließen.
* Auf Brocade G730-Switches können Sie zusätzliche Bridges an die Ports 84–95 anschließen.


[cols="2a,2a,2a,2a,2a,2a"]
|===
2+| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *G630, G630-1-Anschluss* | *G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
FC1
 a| 
1
 a| 
74
 a| 
80



 a| 
FC2
 a| 
2
 a| 
74
 a| 
80



 a| 
Bridge_x_1b
 a| 
FC1
 a| 
1
 a| 
75
 a| 
81



 a| 
FC2
 a| 
2
 a| 
75
 a| 
81



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
FC1
 a| 
1
 a| 
78
 a| 
82



 a| 
FC2
 a| 
2
 a| 
78
 a| 
82



 a| 
Bridge_x_2b
 a| 
FC1
 a| 
1
 a| 
79
 a| 
83



 a| 
FC2
 a| 
2
 a| 
79
 a| 
83

|===


== Shelf-Konfigurationen mit FibreBridge 7500N oder 7600N und nur einem FC-Port (FC1 oder FC2)



=== MetroCluster 1 oder DR-Gruppe 1

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 1 oder DR-Gruppe 1 mit FibreBridge 7500N oder 7600N und nur einem FC-Port (FC1 oder FC2) auf Brocade Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Auf den Switches Brocade 6505, G610, G710, G620, G620-1, G630 und G630-1 werden die Ports 12–15 zusätzlich überbrückt.
* Bei Brocade 6510- und DCX 8510-8-Switches können Sie zusätzliche Bridges an die Ports 12–19 anschließen.
* Bei Brocade 6520-Switches können Sie zusätzliche Bridges an die Ports 16–21 und 24–45 anschließen.
* Bei Brocade G720- und G730-Switches können Sie zusätzliche Bridges an die Ports 16–21 anschließen.


[cols="2a,2a,2a,2a,2a,2a,2a,2a,2a,2a"]
|===
| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *6505-, G610-, G710-Anschluss* | *6510, DCX 8510-8-Anschluss* | *6520-Anschluss* | *7810-Anschluss* | *7840-Anschluss* | *G620-, G620-1-, G630-, G630-1-Anschluss* | *G720, G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
1
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
10



 a| 
Bridge_x_1b
 a| 
2
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
10



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
1
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
11



 a| 
Bridge_x_2b
 a| 
2
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
9
 a| 
11



 a| 
Stapel 3
 a| 
Bridge_x_3a
 a| 
1
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
14



 a| 
Bridge_x_3b
 a| 
2
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
10
 a| 
14



 a| 
Stapel 4
 a| 
Bridge_x_4a
 a| 
1
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
15



 a| 
Bridge_x_4b
 a| 
2
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
11
 a| 
15

|===


=== MetroCluster 2 oder DR-Gruppe 2

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 2 oder DR-Gruppe 2 für FibreBridge 7500N- oder 7600N-Bridges mit einem FC-Port (FC1 oder FC2) auf Brocade -Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Bei Brocade 6520-Switches können Sie zusätzliche Bridges an die Ports 60–69 und 72–93 anschließen.
* Bei den Switches Brocade G620, G620-1, G630 und G630-1 können Sie zusätzliche Bridges an die Ports 32–35 anschließen.
* Bei Brocade G720- und G730-Switches können Sie zusätzliche Bridges an die Ports 36–39 anschließen.
* Die Portnutzung für die Brocade 6505-, G610- und G710-Switches in einer MetroCluster Konfiguration mit acht Knoten wird nicht angezeigt. Aufgrund der begrenzten Anzahl von Ports weisen Sie die Ports je nach Controllermodell und Anzahl der verwendeten ISLs und Bridge-Paare Site für Site zu.


[cols="2a,2a,2a,2a,2a,2a,2a,2a,2a,2a"]
|===
| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *6505-, G610-, G710-Anschluss* | *6510, DCX 8510-8-Anschluss* | *6520-Anschluss* | *7810-Anschluss* | *7840-Anschluss* | *G620-, G620-1-, G630-, G630-1-Anschluss* | *G720, G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
1
 a| 
n/a
 a| 
32
 a| 
56
 a| 
n/a
 a| 
20
 a| 
26
 a| 
32



 a| 
Bridge_x_1b
 a| 
2
 a| 
n/a
 a| 
32
 a| 
56
 a| 
n/a
 a| 
20
 a| 
26
 a| 
32



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
1
 a| 
n/a
 a| 
33
 a| 
57
 a| 
n/a
 a| 
21
 a| 
27
 a| 
33



 a| 
Bridge_x_2b
 a| 
2
 a| 
n/a
 a| 
33
 a| 
57
 a| 
n/a
 a| 
21
 a| 
27
 a| 
33



 a| 
Stapel 3
 a| 
Bridge_x_3a
 a| 
1
 a| 
n/a
 a| 
34
 a| 
58
 a| 
n/a
 a| 
22
 a| 
30
 a| 
34



 a| 
Bridge_x_3b
 a| 
2
 a| 
n/a
 a| 
34
 a| 
58
 a| 
n/a
 a| 
22
 a| 
30
 a| 
34



 a| 
Stapel 4
 a| 
Bridge_x_4a
 a| 
1
 a| 
n/a
 a| 
35
 a| 
59
 a| 
n/a
 a| 
23
 a| 
31
 a| 
35



 a| 
Bridge_x_4b
 a| 
2
 a| 
n/a
 a| 
35
 a| 
59
 a| 
n/a
 a| 
23
 a| 
31
 a| 
35

|===


=== MetroCluster 3 oder DR-Gruppe 3

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 3 oder DR-Gruppe 3 für FibreBridge 7500N- oder 7600N-Bridges mit einem FC-Port (FC1 oder FC2) auf Brocade -Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Bei Brocade G630- und G630-1-Switches können Sie zusätzliche Bridges an die Ports 60–63 anschließen.
* Bei Brocade G730-Switches können Sie zusätzliche Bridges an die Ports 64, 65, 68 und 69 anschließen.


[cols="2a,2a,2a,2a,2a"]
|===
| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *G630, G630-1-Anschluss* | *G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
1
 a| 
56
 a| 
58



 a| 
Bridge_x_1b
 a| 
2
 a| 
56
 a| 
58



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
1
 a| 
57
 a| 
59



 a| 
Bridge_x_2b
 a| 
2
 a| 
57
 a| 
59



 a| 
Stapel 3
 a| 
Bridge_x_3a
 a| 
1
 a| 
58
 a| 
62



 a| 
Bridge_x_3b
 a| 
2
 a| 
58
 a| 
62



 a| 
Stapel 4
 a| 
Bridge_x_4a
 a| 
1
 a| 
59
 a| 
63



 a| 
Bridge_x_4b
 a| 
2
 a| 
59
 a| 
63

|===


=== MetroCluster 4 oder DR-Gruppe 4

Die folgende Tabelle zeigt die unterstützten Shelf-Konfigurationen in MetroCluster 4 oder DR-Gruppe 4 für FibreBridge 7500N- oder 7600N-Bridges mit einem FC-Port (FC1 oder FC2) auf Brocade -Switches. Beachten Sie bei der Verwendung dieser Konfigurationstabelle Folgendes:

* Bei Brocade G630- und G630-1-Switches können Sie zusätzliche Bridges an die Ports 80–83 anschließen.
* Auf Brocade G730-Switches können Sie zusätzliche Bridges an die Ports 84–95 anschließen.


[cols="2a,2a,2a,2a,2a"]
|===
| * Komponente* | *Port* | *Anschluss an FC-Switch...* | *G630, G630-1-Anschluss* | *G730-Anschluss* 


 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
1
 a| 
74
 a| 
80



 a| 
Bridge_x_1b
 a| 
2
 a| 
74
 a| 
80



 a| 
Stack 2
 a| 
Bridge_x_2a
 a| 
1
 a| 
75
 a| 
81



 a| 
Bridge_x_2b
 a| 
2
 a| 
75
 a| 
81



 a| 
Stapel 3
 a| 
Bridge_x_3a
 a| 
1
 a| 
78
 a| 
82



 a| 
Bridge_x_3b
 a| 
2
 a| 
78
 a| 
82



 a| 
Stapel 4
 a| 
Bridge_x_4a
 a| 
1
 a| 
79
 a| 
83



 a| 
Bridge_x_4b
 a| 
2
 a| 
79
 a| 
83

|===