---
permalink: install-fc/concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, example, eight, node, array, luns, mcc 
summary: Das Switch-Zoning definiert Pfade zwischen verbundenen Nodes. Beim Konfigurieren des Zoning können Sie festlegen, welche Array LUNs von bestimmten ONTAP Systemen angezeigt werden können. 
---
= Beispiel für das Switch-Zoning in einer MetroCluster-Konfiguration mit acht Nodes und den Array-LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Switch-Zoning definiert Pfade zwischen verbundenen Nodes. Beim Konfigurieren des Zoning können Sie festlegen, welche Array LUNs von bestimmten ONTAP Systemen angezeigt werden können.

Eine MetroCluster Konfiguration mit acht Nodes besteht aus zwei DR-Gruppen mit vier Nodes. Die erste DR-Gruppe besteht aus den folgenden Knoten:

* Controller_A_1
* Controller_A_2
* Controller_B_1
* Controller_B_2


Die zweite DR-Gruppe besteht aus den folgenden Knoten:

* Controller_A_3
* Controller_A_4
* Controller_B_3
* Controller_B_4


Zum Konfigurieren des Switch-Zoning können Sie die Zoning-Beispiele für eine MetroCluster-Konfiguration mit vier Nodes für die erste DR-Gruppe verwenden.

link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch Zoning in einer MetroCluster-Konfiguration mit vier Nodes und Array LUNs"]

Befolgen Sie zum Konfigurieren des Zoning für die zweite DR-Gruppe die gleichen Beispiele und Anforderungen für die FC-Initiator-Ports und die Array-LUNs, die zu den Controllern in der zweiten DR-Gruppe gehören.

.Verwandte Informationen
* Das Switch-Zoning definiert Pfade zwischen verbundenen Nodes. Beim Konfigurieren des Zoning können Sie festlegen, welche Array LUNs von bestimmten ONTAP Systemen angezeigt werden können.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch-Zoning in einer MetroCluster-Konfiguration mit zwei Nodes mit Array LUNs"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch Zoning in einer MetroCluster-Konfiguration mit vier Nodes und Array LUNs"]

* Bei der Verwendung von Switch Zoning in einer MetroCluster Konfiguration mit Array LUNs müssen Sie sicherstellen, dass bestimmte grundlegende Anforderungen erfüllt werden.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["Anforderungen für das Switch-Zoning in einer MetroCluster-Konfiguration mit Array LUNs"]


