---
permalink: install-fc/concept_fcsw_brocade_reviewing_brocade_license_requirements.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, review, brocade, license, requirements 
summary: Sie benötigen bestimmte Lizenzen für die Switches in einer MetroCluster-Konfiguration. Sie müssen diese Lizenzen auf allen vier Switches installieren. 
---
= Überprüfung der Brocade Lizenzanforderungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie benötigen bestimmte Lizenzen für die Switches in einer MetroCluster-Konfiguration. Sie müssen diese Lizenzen auf allen vier Switches installieren.

Die MetroCluster-Konfiguration erfüllt die folgenden Anforderungen an die Brocade-Lizenz:

* Trunking-Lizenz für Systeme mit mehr als einer ISL, wie empfohlen.
* Erweiterte Fabric-Lizenz (für ISL-Entfernungen über 6 km)
* Enterprise-Lizenz für Standorte mit mehr als einem ISL und einer ISL-Entfernung von mehr als 6 km
+
Die Enterprise-Lizenz umfasst Brocade Network Advisor und alle Lizenzen, mit Ausnahme zusätzlicher Port-Lizenzen.



Sie können überprüfen, ob die Lizenzen mithilfe der installiert wurden `licenseshow` Befehl. Wenn Sie diese Lizenzen nicht besitzen, wenden Sie sich an Ihren Vertriebsmitarbeiter, bevor Sie fortfahren.
