---
permalink: install-fc/concept_implementing_a_mcc_configuration_with_both_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, implement, configuration, disks, array, luns 
summary: Um eine MetroCluster-Konfiguration mit nativen Festplatten und Array-LUNs zu implementieren, müssen Sie sicherstellen, dass die in der Konfiguration verwendeten ONTAP-Systeme mit Speicher-Arrays verknüpft werden können. 
---
= Implementieren einer MetroCluster-Konfiguration mit Festplatten und Array LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um eine MetroCluster-Konfiguration mit nativen Festplatten und Array-LUNs zu implementieren, müssen Sie sicherstellen, dass die in der Konfiguration verwendeten ONTAP-Systeme mit Speicher-Arrays verknüpft werden können.

Eine MetroCluster-Konfiguration mit Festplatten und Array-LUNs kann zwei oder vier Nodes haben. Obwohl die MetroCluster Konfiguration mit vier Nodes Fabric-Attached sein muss, kann die Konfiguration mit zwei Nodes entweder Stretch oder Fabric-Attached sein.

Im https://["NetApp Interoperabilitäts-Matrix-Tool (IMT)"], Sie können im Feld Storage-Lösung die MetroCluster-Lösung auswählen. Sie verwenden den *Komponenten-Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.

.Verwandte Informationen
Zum Einrichten einer Fabric-Attached MetroCluster Konfiguration mit zwei Nodes oder einer MetroCluster Konfiguration mit vier Nodes mit nativen Festplatten und Array-LUNs müssen Sie die ONTAP Systeme über FC-to-SAS Bridges mit den Festplatten-Shelfs verbinden. Sie können Array-LUNs über die FC-Switches mit den ONTAP-Systemen verbinden.

link:reference_example_of_a_two_node_fabric_attached_mcc_configuration_with_disks_and_array_luns.html["Beispiel einer Fabric-Attached MetroCluster-Konfiguration mit zwei Nodes mit Festplatten und Array-LUNs"]

link:concept_example_of_a_four_node_mcc_configuration_with_disks_and_array_luns.html["Beispiel einer MetroCluster-Konfiguration mit vier Nodes und Festplatten und Array LUNs"]
