---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html 
sidebar: sidebar 
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster 
summary: Sie müssen überprüfen, ob Sie die angegebenen Portzuweisungen verwenden, wenn Sie die FC-Switches mit ONTAP 9.1 und höher verkabeln. 
---
= Port-Zuweisungen für FC Switches bei Verwendung von AFF A900- oder FAS9500-Systemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen überprüfen, ob Sie die angegebenen Portzuweisungen verwenden, wenn Sie die FC-Switches mit ONTAP 9.10.1 und höher verkabeln.

Ports, die nicht zum Anschließen von Initiator-Ports, FC-VI-Ports oder ISLs verwendet werden, können neu konfiguriert werden, um als Storage Ports zu fungieren. Wenn jedoch die unterstützten RCFs verwendet werden, muss das Zoning entsprechend geändert werden.

Bei Verwendung der unterstützten RCFs können ISL-Ports keine Verbindung zu denselben Ports herstellen und müssen möglicherweise manuell neu konfiguriert werden.

Wenn Sie Ihre Switches mit den Portzuweisungen für ONTAP 9 konfiguriert haben, können Sie die älteren Zuweisungen weiterhin verwenden. Neue Konfigurationen mit ONTAP 9.1 oder höheren Versionen sollten jedoch die hier gezeigten Port-Zuweisungen verwenden.



== Allgemeine Verkabelungsrichtlinien

Beachten Sie bei der Verwendung der Verkabelungstabellen die folgenden Richtlinien:

* Für AFF A900 oder FAS9500 Storage-Systeme sind acht FC-VI-Ports erforderlich. Wenn Sie ein AFF A900 oder FAS9500 verwenden, müssen Sie die Konfiguration mit acht Ports verwenden. Wenn die Konfiguration die anderen Modelle des Storage-Systems umfasst, verwenden Sie die in den Tabellen dargestellte Verkabelung, ignorieren Sie jedoch die Verkabelung für nicht benötigte FC-VI-Ports.
* Wenn zwei MetroCluster-Konfigurationen ISLs gemeinsam nutzen, verwenden Sie für eine MetroCluster-Verkabelung mit acht Nodes die gleichen Port-Zuweisungen wie diese.
* Die Anzahl der KabelISLs kann je nach Anforderungen des Standorts variieren.
* Weitere Informationen zu den Überlegungen zu ISL finden Sie im Abschnitt.
+
link:concept_considerations_isls_mcfc.html["Überlegungen für ISLs"]


