---
permalink: install-fc/concept_considerations_7mt.html 
sidebar: sidebar 
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa 
summary: Wenn Sie sich auf die MetroCluster Installation vorbereiten, sollten Sie sich mit der MetroCluster Hardwarearchitektur und den erforderlichen Komponenten vertraut machen. 
---
= Überlegungen beim Wechsel von 7-Mode zu ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die neue MetroCluster Konfiguration vollständig konfigurieren und in Betrieb nehmen, bevor Sie die Umstiegstools verwenden, um Daten von einer 7-Mode MetroCluster Konfiguration in eine ONTAP Konfiguration zu verschieben. Wenn die 7-Mode Konfiguration Brocade 6510-Switches verwendet, kann die neue Konfiguration die vorhandenen Fabrics gemeinsam nutzen, um die Hardwareanforderungen zu reduzieren.

Wenn Sie Brocade 6510 Switches haben und die Switch-Fabrics zwischen dem 7-Mode Fabric MetroCluster und dem MetroCluster, das in ONTAP ausgeführt wird, gemeinsam nutzen Sie das spezifische Verfahren zur Konfiguration der MetroCluster Komponenten.

link:task_fmc_mcc_transition_configure_the_mcc_hardware_for_share_a_7_mode_brocade_6510_fc_fabric_dure_transition.html["Konfiguration der MetroCluster Hardware für die gemeinsame Nutzung einer 7-Mode Brocade 6510 FC Fabric während der Transition"]
