---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns 
summary: Bei der Planung Ihrer MetroCluster Konfiguration für Festplatten und Array-LUNs müssen Sie verschiedene Faktoren berücksichtigen, z. B. die Reihenfolge der Einrichtung von Zugriff auf Storage, das Root-Aggregatverzeichnis und die Verwendung von FC Initiator-Ports, Switches und FC-to-SAS-Bridges. 
---
= Überlegungen bei der Implementierung einer MetroCluster Konfiguration mit Festplatten und Array LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Planung Ihrer MetroCluster Konfiguration für Festplatten und Array-LUNs müssen Sie verschiedene Faktoren berücksichtigen, z. B. die Reihenfolge der Einrichtung von Zugriff auf Storage, das Root-Aggregatverzeichnis und die Verwendung von FC Initiator-Ports, Switches und FC-to-SAS-Bridges.

Berücksichtigen Sie bei der Planung der Konfiguration die Informationen in der folgenden Tabelle:

|===


| Überlegungen | Richtlinie 


 a| 
Reihenfolge der Einrichtung des Zugriffs auf den Speicher
 a| 
Sie können zuerst den Zugriff auf Festplatten- oder Array-LUNs einrichten. Sie müssen die gesamte Einrichtung für diesen Storage-Typ abschließen und vor der Einrichtung des anderen Storage-Typs überprüfen, ob er korrekt eingerichtet ist.



 a| 
Speicherort des Root-Aggregats
 a| 
* Wenn Sie eine _neue_ MetroCluster-Bereitstellung mit Festplatten und Array LUNs einrichten, müssen Sie das Root-Aggregat auf nativen Festplatten erstellen.
+
Stellen Sie dabei sicher, dass _mindestens ein_ Festplatten-Shelf (mit 24 Festplatten) an jedem Standort eingerichtet ist.

* Wenn Sie einer _vorhandenen_ MetroCluster Konfiguration native Festplatten hinzufügen, die Array LUNs verwendet, kann das Root-Aggregat auf einer Array LUN verbleiben.




 a| 
Verwendung von Switches und FC-to-SAS-Bridges
 a| 
Für Konfigurationen mit vier Nodes sind FC-to-SAS-Bridges und Fabric-Attached-Konfigurationen mit zwei Nodes erforderlich, um die ONTAP Systeme über die Switches mit den Festplatten-Shelfs zu verbinden.

Sie müssen dieselben Switches verwenden, um eine Verbindung zu den Storage Arrays und den FC-to-SAS-Bridges herzustellen.



 a| 
Verwenden von FC Initiator-Ports
 a| 
Die Initiator-Ports, die für die Verbindung zu einer FC-to-SAS-Bridge verwendet werden, müssen sich von den Ports unterscheiden, die für die Verbindung mit den Switches verwendet werden.

Mindestens acht Initiator-Ports sind erforderlich, um ein ONTAP-System mit Festplatten und Array-LUNs zu verbinden.

|===
.Verwandte Informationen
* Switch-Konfigurationsverfahren und -Befehle unterscheiden sich je nach Switch-Anbieter.
+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Konfigurieren der Brocade FC-Switches manuell"]

+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html["Konfigurieren Sie Cisco FC-Switches manuell"]

* Wenn Sie der Konfiguration neuen Speicher hinzufügen, installieren und verkabeln Sie ATTO FibreBridge Bridges und SAS-Platten-Shelves.
+
link:task_fb_new_install.html["Installation von FC-to-SAS-Bridges und SAS-Platten-Shelves"]

* Das Switch-Zoning definiert Pfade zwischen verbundenen Nodes. Beim Konfigurieren des Zoning können Sie festlegen, welche Array LUNs von einem bestimmten ONTAP System angezeigt werden können.
+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch Zoning in einer MetroCluster-Konfiguration mit vier Nodes und Array LUNs"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch-Zoning in einer MetroCluster-Konfiguration mit acht Nodes und den Array-LUNs"]

* https://hwu.netapp.com["NetApp Hardware Universe"]

