---
permalink: install-fc/concept_port_assignments_for_systems_using_two_initiator_ports.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, port, assignments, systems, two, initiator, ports 
summary: Sie können FAS8020, AFF8020, FAS8200 und AFF A300 Systeme über einen einzelnen Initiator-Port für jede Fabric und zwei Initiator-Ports für jeden Controller konfigurieren. 
---
= Port-Zuweisungen für Systeme mit zwei Initiator-Ports
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können FAS8200 und AFF A300 -Systeme mit einem einzelnen Initiator-Port für jede Fabric und zwei Initiator-Ports für jeden Controller konfigurieren.

Sie können die Verkabelung für die FibreBridge 7600N-Bridge mit nur einem FC-Port (FC1 oder FC2) durchführen. Schließen Sie statt vier Initiatoren nur zwei an und lassen Sie die beiden anderen, die mit dem Switch-Port verbunden sind, leer.

Bei manueller Zoneneinteilung folgen Sie der Zoneneinteilung für eine FibreBridge 7600N-Bridge mit einem FC-Port (FC1 oder FC2). In diesem Szenario wird jedem Zonenmitglied pro Fabric ein Initiator-Port (statt zwei) hinzugefügt.

Sie können das Zoning ändern oder ein Upgrade von einer FibreBridge 6500N auf eine FibreBridge 7500N durchführen. Gehen Sie dazu wie unter beschrieben vor link:../maintain/task_replace_a_sle_fc_to_sas_bridge.html#hot_swap_6500n["Hot-Swap einer FibreBridge 6500N-Bridge mit FibreBridge 7600N oder 7500N-Brücke"].

Die folgende Tabelle zeigt die Portzuweisungen für Brocade FC-Switches bei Verwendung eines einzelnen Initiator-Ports für jedes Fabric und zweier Initiator-Ports für jeden Controller.

[cols="2a,2a,2a,2a"]
|===
4+| Konfigurationen mit FibreBridge 7500N oder 7600N mit nur einem FC-Port (FC1 oder FC2) 


 a| 
*MetroCluster 1 oder DR Gruppe 1*



 a| 
* Komponente*
 a| 
*Port*
 a| 
*6505, 6510, 6520, 7840, G620, G630, G610, G710, G720, G730 und DCX 8510-8*



 a| 
*Anschluss an FC-Switch...*
 a| 
*Verbindet den Switch-Port...*



 a| 
Controller_x_1
 a| 
FC-VI-Port A
 a| 
1
 a| 
0



 a| 
FC-VI-Port b
 a| 
2
 a| 
0



 a| 
FC-VI-Port c
 a| 
1
 a| 
1



 a| 
FC-VI-Port d
 a| 
2
 a| 
1



 a| 
HBA-Port A
 a| 
1
 a| 
2



 a| 
HBA-Port b
 a| 
2
 a| 
2



 a| 
HBA-Port c
 a| 
-
 a| 
-



 a| 
HBA-Port d
 a| 
-
 a| 
-



 a| 
Stack 1
 a| 
Bridge_x_1a
 a| 
1
 a| 
8



 a| 
Bridge_x_1b
 a| 
2
 a| 
8



 a| 
Stapel Y
 a| 
Bridge_x_ya
 a| 
1
 a| 
11



 a| 
Bridge_x_yb
 a| 
2
 a| 
11

|===