---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, requirements, array, luns, mcc 
summary: Die in MetroCluster Konfigurationen verwendeten ONTAP Systeme, Storage Arrays und FC Switches müssen die Anforderungen für solche Konfigurationen erfüllen. Zudem müssen die SyncMirror-Anforderungen für MetroCluster Konfigurationen mit Array LUNs berücksichtigt werden. 
---
= Anforderungen für eine MetroCluster-Konfiguration mit Array-LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die in MetroCluster Konfigurationen verwendeten ONTAP Systeme, Storage Arrays und FC Switches müssen die Anforderungen für solche Konfigurationen erfüllen. Zudem müssen die SyncMirror-Anforderungen für MetroCluster Konfigurationen mit Array LUNs berücksichtigt werden.



== Anforderungen für ONTAP Systeme

* Die ONTAP Systeme müssen als unterstützt für MetroCluster Konfigurationen identifiziert werden.
+
Im https://["NetApp Interoperabilitäts-Matrix-Tool (IMT)"], Sie können im Feld Storage-Lösung die MetroCluster-Lösung auswählen. Sie verwenden den *Komponenten-Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.

+

NOTE: Sie müssen die Warndetails beachten, die mit jeder Konfiguration verknüpft sind, die Sie in der Interoperabilitäts-Matrix auswählen.

* Alle ONTAP Systeme in einer MetroCluster Konfiguration müssen aus dem gleichen Modell stammen.
* FC-VI-Adapter müssen je nach Modell in den entsprechenden Steckplätzen für jedes ONTAP-System installiert werden.
+
https://["NetApp Hardware Universe"]





== Anforderungen für Storage Arrays erfüllt

* Die Storage Arrays müssen als Unterstützung für MetroCluster-Konfigurationen identifiziert werden.
+
https://["NetApp Interoperabilitäts-Matrix-Tool"]

* Die Speicher-Arrays in der MetroCluster Konfiguration müssen symmetrisch sein:
+
** Die beiden Speicher-Arrays müssen von derselben unterstützten Anbieterfamilie stammen und dieselbe Firmware-Version installiert sein.
+
https://["FlexArray Virtualisierungs-Implementierung für NetApp E-Series Storage"]

+
https://["FlexArray Virtualisierungs-Implementierung für Storage von Drittanbietern"]

** Festplattentypen (z. B. SATA, SSD oder SAS) für gespiegelten Storage müssen auf beiden Storage Arrays identisch sein.
** Die Parameter für die Konfiguration von Speicher-Arrays, z. B. RAID-Typ und Tiering, müssen an beiden Standorten dieselben sein.






== Anforderungen für FC Switches

* Die Switches und die Switch-Firmware müssen als unterstützt für MetroCluster-Konfigurationen identifiziert werden.
+
https://["NetApp Interoperabilitäts-Matrix-Tool"]

* Jede Fabric muss über zwei FC-Switches verfügen.
* Jedes ONTAP System muss über redundante Komponenten an den Storage angeschlossen werden, damit bei Geräte- und Pfadausfällen Redundanz gewährleistet ist.
* Die AFF Storage-Systeme A700, FAS9000, AFF A900 und FAS9500 unterstützen bis zu acht ISLs pro Fabric. Andere Storage-System-Modelle unterstützen bis zu vier ISLs pro Fabric.


Die Switches müssen die Basis-Switch-Konfiguration des MetroCluster, ISL-Einstellungen und FC-VI-Konfigurationen verwenden.

link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Konfigurieren der Cisco oder Brocade FC Switches manuell"]



== SyncMirror-Anforderungen erfüllt

* Für eine MetroCluster Konfiguration ist SyncMirror erforderlich.
* Für den gespiegelten Storage sind zwei separate Storage-Arrays erforderlich – eine an jedem Standort.
* Es sind zwei Gruppen von Array-LUNs erforderlich.
+
Für das Aggregat auf dem lokalen Storage Array (Pool0) ist ein Satz erforderlich und ein weiterer Satz ist am Remote Storage Array für die Spiegelung des Aggregats erforderlich (der andere Plex des Aggregats, Pool1).

+
Die Array LUNs müssen für die Spiegelung des Aggregats dieselbe Größe haben.

* Nicht gespiegelte Aggregate werden auch in der MetroCluster Konfiguration unterstützt.
+
Sie sind im Falle eines Standortausfalls nicht geschützt.


