---
permalink: install-fc/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, additional, information 
summary: Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster finden Sie in der NetApp Dokumentation. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier.



== MetroCluster und sonstige Informationen

|===


| Informationsdaten | Betreff 


 a| 
link:https://docs.netapp.com/us-en/ontap/index.html["ONTAP 9-Dokumentation"^]
 a| 
* Alle MetroCluster-Informationen




| link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["NetApp MetroCluster Lösungsarchitektur und Design, TR-4705"^]  a| 
* Technische Übersicht über Konfiguration und Betrieb von MetroCluster FC
* Best Practices für die MetroCluster FC-Konfiguration.




| link:https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf["Architektur und Design der MetroCluster IP-Lösung, TR-4689"^]  a| 
* Eine technische Übersicht über die Konfiguration und den Betrieb der MetroCluster IP-Adresse.
* Best Practices für die MetroCluster IP-Konfiguration.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["Installation und Konfiguration von Stretch MetroCluster"]
 a| 
* Stretch-MetroCluster Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["MetroCluster IP-Installation und -Konfiguration: Unterschiede zwischen den ONTAP MetroCluster-Konfigurationen"]
 a| 
* MetroCluster IP Architektur
* Verkabelung der Konfiguration
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html["MetroCluster Management und Disaster Recovery"]
 a| 
* Allgemeines zur MetroCluster-Konfiguration
* Umschaltung, Heilen und zurückwechseln
* Disaster Recovery




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html["Warten der MetroCluster-Komponenten"]
 a| 
* Richtlinien für die Wartung in einer MetroCluster FC-Konfiguration
* Verfahren zum Austausch oder Upgrade von Hardware und Firmware-Upgrades für FC-to-SAS-Bridges und FC-Switches
* Hot-hinzufügen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Hot-entfernen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Austausch von Hardware an einem Disaster-Standort in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster FC-Konfiguration mit zwei Nodes auf eine MetroCluster Konfiguration mit vier Nodes.
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster FC-Konfiguration mit vier Nodes auf eine MetroCluster FC-Konfiguration mit acht Nodes




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html["Umstellung von MetroCluster FC auf MetroCluster IP"]

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster Upgrade- und Erweiterungsleitfaden"]
 a| 
* Aktualisierung oder Aktualisierung einer MetroCluster Konfiguration
* Umstellung von einer MetroCluster FC-Konfiguration auf eine MetroCluster IP-Konfiguration
* Erweitern einer MetroCluster Konfiguration durch Hinzufügen weiterer Nodes




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html["Installation und Konfiguration der MetroCluster Tiebreaker Software"]
 a| 
* Monitoring der MetroCluster Konfiguration mit der MetroCluster Tiebreaker Software




 a| 
Active IQ Digital Advisor Dokumentation

https://www.netapp.com/support-and-training/documentation/["NetApp Dokumentation: Produktleitfäden und Ressourcen"^]
 a| 
* Monitoring der MetroCluster Konfiguration und Performance




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Kopienbasierte Transition"^]
 a| 
* Migration von Daten von 7-Mode Storage-Systemen zu geclusterten Storage-Systemen




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html["ONTAP-Konzepte"^]
 a| 
* Funktionsweise der gespiegelten Aggregate


|===