---
permalink: install-fc/reference_where_to_find_additional_information_icg.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, additional, information 
summary: Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster finden Sie in der NetApp Dokumentation. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier.



== MetroCluster und sonstige Informationen

|===


| Informationsdaten | Betreff 


 a| 
https://["ONTAP 9-Dokumentation"^]
 a| 
* Alle MetroCluster-Informationen




| https://["NetApp MetroCluster Lösungsarchitektur und Design, TR-4705"^]  a| 
* Technische Übersicht über Konfiguration und Betrieb von MetroCluster FC
* Best Practices für die MetroCluster FC-Konfiguration.




| https://["Architektur und Design der MetroCluster IP-Lösung, TR-4689"^]  a| 
* Eine technische Übersicht über die Konfiguration und den Betrieb der MetroCluster IP-Adresse.
* Best Practices für die MetroCluster IP-Konfiguration.




 a| 
https://["Installation und Konfiguration von Stretch MetroCluster"]
 a| 
* Stretch-MetroCluster Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://["MetroCluster IP-Installation und -Konfiguration: Unterschiede zwischen den ONTAP MetroCluster-Konfigurationen"]
 a| 
* MetroCluster IP Architektur
* Verkabelung der Konfiguration
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://["MetroCluster Management und Disaster Recovery"]
 a| 
* Allgemeines zur MetroCluster-Konfiguration
* Umschaltung, Heilen und zurückwechseln
* Disaster Recovery




 a| 
https://["Warten der MetroCluster-Komponenten"]
 a| 
* Richtlinien für die Wartung in einer MetroCluster FC-Konfiguration
* Verfahren zum Austausch oder Upgrade von Hardware und Firmware-Upgrades für FC-to-SAS-Bridges und FC-Switches
* Hot-hinzufügen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Hot-entfernen eines Festplatten-Shelfs in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Austausch von Hardware an einem Disaster-Standort in einer Fabric-Attached- oder Stretch-MetroCluster FC-Konfiguration
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster FC-Konfiguration mit zwei Nodes auf eine MetroCluster Konfiguration mit vier Nodes.
* Erweitern einer Fabric-Attached oder Stretch-MetroCluster FC-Konfiguration mit vier Nodes auf eine MetroCluster FC-Konfiguration mit acht Nodes




 a| 
https://["Umstellung von MetroCluster FC auf MetroCluster IP"]

https://["MetroCluster Upgrade- und Erweiterungsleitfaden"]
 a| 
* Aktualisierung oder Aktualisierung einer MetroCluster Konfiguration
* Umstellung von einer MetroCluster FC-Konfiguration auf eine MetroCluster IP-Konfiguration
* Erweitern einer MetroCluster Konfiguration durch Hinzufügen weiterer Nodes




 a| 
https://["Installation und Konfiguration der MetroCluster Tiebreaker Software"]
 a| 
* Monitoring der MetroCluster Konfiguration mit der MetroCluster Tiebreaker Software




 a| 
Active IQ Digital Advisor Dokumentation

https://["NetApp Dokumentation: Produktleitfäden und Ressourcen"^]
 a| 
* Monitoring der MetroCluster Konfiguration und Performance




 a| 
https://["Kopienbasierte Transition"^]
 a| 
* Migration von Daten von 7-Mode Storage-Systemen zu geclusterten Storage-Systemen




 a| 
https://["ONTAP-Konzepte"^]
 a| 
* Funktionsweise der gespiegelten Aggregate


|===