---
permalink: install-fc/reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, switch, zoning, array, luns, requirements 
summary: Bei der Verwendung von Switch Zoning in einer MetroCluster Konfiguration mit Array LUNs müssen Sie sicherstellen, dass bestimmte grundlegende Anforderungen erfüllt werden. 
---
= Anforderungen für das Switch-Zoning in einer MetroCluster-Konfiguration mit Array LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Verwendung von Switch Zoning in einer MetroCluster Konfiguration mit Array LUNs müssen Sie sicherstellen, dass bestimmte grundlegende Anforderungen erfüllt werden.

Folgende Anforderungen gelten für das Switch-Zoning in einer MetroCluster-Konfiguration mit Array LUNs:

* Die MetroCluster-Konfiguration muss dem Einzel-Initiator- zum Einzel-Ziel-Zoning-Schema folgen.
+
Einzel-Initiator auf Einzel-Ziel-Zoning beschränkt jede Zone auf einen einzelnen FC-Initiator-Port und einen einzelnen Ziel-Port.

* Die FC-VI-Ports müssen über die Fabric hinweg begrenzt werden.
* Die gemeinsame Nutzung mehrerer Initiator-Ports mit einem einzelnen Ziel-Port kann zu Performance-Problemen führen.
+
Ebenso kann die gemeinsame Nutzung mehrerer Ziel-Ports mit einem einzelnen Initiator-Port zu Performance-Problemen führen.

* Sie müssen eine Basiskonfiguration der in der MetroCluster-Konfiguration verwendeten FC-Switches durchgeführt haben.
+
link:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.html["Konfigurieren der Cisco oder Brocade FC Switches manuell"]





== Shared Initiator- und Shared Target-Unterstützung für MetroCluster-Konfiguration mit Array LUNs

Die Möglichkeit, einen bestimmten FC-Initiator-Port oder Ziel-Ports gemeinsam zu nutzen, ist für Unternehmen nützlich, die die Anzahl der verwendeten Initiator- oder Ziel-Ports minimieren möchten. Ein Unternehmen, das beispielsweise eine geringe I/O-Nutzung über einen FC-Initiator-Port oder Ziel-Ports erwartet, möchte FC-Initiator-Port oder Ziel-Ports möglicherweise lieber gemeinsam nutzen, anstatt jeden FC-Initiator-Port einem einzelnen Ziel-Port zuzuweisen.

Allerdings kann die gemeinsame Nutzung von Initiator- oder Ziel-Ports negative Auswirkungen auf die Performance haben.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_support_Shared_Initiator_and_Shared_Target_configuration_with_Array_LUNs_in_a_MetroCluster_environment["So unterstützen Sie die Konfiguration von Shared Initiator und Shared Target mit Array LUNs in einer MetroCluster-Umgebung"]

* Das Switch-Zoning definiert Pfade zwischen verbundenen Nodes. Beim Konfigurieren des Zoning können Sie festlegen, welche Array LUNs von bestimmten ONTAP Systemen angezeigt werden können.
+
link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch-Zoning in einer MetroCluster-Konfiguration mit zwei Nodes mit Array LUNs"]

+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch Zoning in einer MetroCluster-Konfiguration mit vier Nodes und Array LUNs"]

+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html["Beispiel für das Switch-Zoning in einer MetroCluster-Konfiguration mit acht Nodes und den Array-LUNs"]


