---
permalink: install-fc/task_configure_ontap_on_a_system_that_uses_only_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, array luns, ontap 
summary: Wenn Sie ONTAP für die Verwendung mit Array-LUNs konfigurieren möchten, müssen Sie das Root-Aggregat und das Root-Volume, den reservierten Speicherplatz für Diagnose- und Recovery-Vorgänge konfigurieren und das Cluster einrichten. 
---
= Konfigurieren von ONTAP auf einem System, das nur Array-LUNs verwendet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ONTAP für die Verwendung mit Array-LUNs konfigurieren möchten, müssen Sie das Root-Aggregat und das Root-Volume, den reservierten Speicherplatz für Diagnose- und Recovery-Vorgänge konfigurieren und das Cluster einrichten.

.Bevor Sie beginnen
* Das ONTAP System muss mit dem Storage-Array verbunden sein.
* Der Administrator des Storage Arrays muss LUNs erstellt und ONTAP zur Verfügung gestellt haben.
* Der Administrator des Speicherarrays muss die LUN-Sicherheit konfiguriert haben.


.Über diese Aufgabe
Sie müssen jeden Node konfigurieren, den Sie mit Array LUNs verwenden möchten. Wenn sich der Node in einem HA-Paar befindet, müssen Sie den Konfigurationsprozess auf einem Node abschließen, bevor Sie mit der Konfiguration auf dem Partner-Node fortfahren.

.Schritte
. Schalten Sie den primären Node ein und unterbrechen Sie den Boot-Prozess, indem Sie Strg-C drücken, wenn auf der Konsole die folgende Meldung angezeigt wird:
+
`Press CTRL-C for special boot menu.`

. Wählen Sie im Startmenü die Option *4 (Konfiguration reinigen und alle Festplatten initialisieren)* aus.
+
Die Liste der Array-LUNs, die ONTAP zur Verfügung gestellt werden, wird angezeigt. Außerdem wird die für die Erstellung des Root-Volumes erforderliche Array-LUN-Größe angegeben. Die für die Erstellung des Root-Volumes erforderliche Größe unterscheidet sich von einem ONTAP System zu einem anderen.

+
** Wenn zuvor keine Array-LUNs zugewiesen wurden, erkennt ONTAP die verfügbaren Array-LUNs und zeigt sie an, wie im folgenden Beispiel dargestellt:
+
[listing]
----
mcc8040-ams1::> disk show  NET-1.6 -instance
                  Disk: NET-1.6
        Container Type: aggregate
            Owner/Home: mcc8040-ams1-01 / mcc8040-ams1-01
               DR Home: -
    Stack ID/Shelf/Bay: -  / -  / -
                   LUN: 0
                 Array: NETAPP_INF_1
                Vendor: NETAPP
                 Model: INF-01-00
         Serial Number: 60080E50004317B4000003B158E35974
                   UID: 60080E50:004317B4:000003B1:58E35974:00000000:00000000:00000000:00000000:00000000:00000000
                   BPS: 512
         Physical Size: 87.50GB
              Position: data
Checksum Compatibility: block
             Aggregate: eseries
                  Plex: plex0
Paths:
                                LUN  Initiator Side        Target Side                                                        Link
Controller         Initiator     ID  Switch Port           Switch Port           Acc Use  Target Port                TPGN    Speed      I/O KB/s          IOPS
------------------ ---------  -----  --------------------  --------------------  --- ---  -----------------------  ------  -------  ------------  ------------
mcc8040-ams1-01    2c             0  mccb6505-ams1:16      mccb6505-ams1:18      AO  INU  20330080e54317b4              1   4 Gb/S             0             0
mcc8040-ams1-01    2a             0  mccb6505-ams1:17      mccb6505-ams1:19      ANO RDY  20320080e54317b4              0   4 Gb/S             0             0

Errors:
-
----
** Wenn Array LUNs zuvor zugewiesen wurden, beispielsweise im Wartungsmodus, werden sie entweder als lokal oder als Partner in der Liste der verfügbaren Array LUNs gekennzeichnet, je nachdem, ob die Array LUNs auf dem Node ausgewählt wurden, auf dem Sie ONTAP oder seinen HA-Partner installieren:
+
In diesem Beispiel werden Array-LUNs mit den Indexnummern 3 und 6 als „lokal“ markiert, da sie zuvor diesem Knoten zugewiesen waren:

+
[listing]
----

**********************************************************************
* No disks are owned by this node, but array LUNs are assigned.      *
* You can use the following information to verify connectivity from  *
* HBAs to switch ports.  If the connectivity of HBAs to switch ports *
* does not match your expectations, configure your SAN and rescan.   *
* You can rescan by entering 'r' at the prompt for selecting         *
* array LUNs below.

**********************************************************************
             HBA  HBA WWPN           Switch port      Switch port WWPN
              ---  --------           -----------      ----------------
              0e 500a098001baf8e0  vgbr6510s203:25      20190027f88948dd
              0f 500a098101baf8e0 vgci9710s202:1-17      2011547feeead680
              0g 500a098201baf8e0  vgbr6510s203:27      201b0027f88948dd
              0h 500a098301baf8e0 vgci9710s202:1-18      2012547feeead680


No native disks were detected, but array LUNs were detected.
You will need to select an array LUN to be used to create the root aggregate and root volume.

The array LUNs visible to the system are listed below.  Select one array LUN to be used to
create the root aggregate and root volume.  **The root volume requires 350.0 GB of space.**

 Warning: The contents of the array LUN you select will be erased by ONTAP prior to their use.

Index  Array LUN Name           Model   Vendor    Size    Owner   Checksum  Serial Number
-----  -----------------------  ------  ------  --------  ------  --------  ------------------------
   0   vgci9710s202:2-24.0L19   RAID5   DGC     217.3 GB          Block     6006016083402B0048E576D7
   1   vgbr6510s203:30.126L20   RAID5   DGC     217.3 GB          Block     6006016083402B0049E576D7
   2   vgci9710s202:2-24.0L21   RAID5   DGC     217.3 GB          Block     6006016083402B004AE576D7
   3   vgbr6510s203:30.126L22   RAID5   DGC     405.4 GB  local   Block     6006016083402B004BE576D7
   4   vgci9710s202:2-24.0L23   RAID5   DGC     217.3 GB          Block     6006016083402B004CE576D7
   5   vgbr6510s203:30.126L24   RAID5   DGC     217.3 GB          Block     6006016083402B004DE576D7
   6   vgbr6510s203:30.126L25   RAID5   DGC     423.5 GB  local   Block     6006016083402B003CF93694
   7   vgci9710s202:2-24.0L26   RAID5   DGC     423.5 GB          Block     6006016083402B003DF93694
----


. Wählen Sie die Indexnummer für die Array-LUN aus, die Sie als Root-Volume zuweisen möchten.
+
Die Array-LUN muss ausreichend groß sein, um das Root-Volume zu erstellen.

+
Die für die Erstellung des Root-Volumes ausgewählte Array-LUN ist mit „local (root)“ gekennzeichnet.

+
Im folgenden Beispiel ist die Array-LUN mit Indexnummer 3 für die Erstellung des Root-Volumes markiert:

+
[listing]
----

The root volume will be created on switch 0:5.183L33.

**ONTAP requires that 11.0 GB of space be reserved for use in diagnostic and recovery
operations.**  Select one array LUN to be used as spare for diagnostic and recovery operations.

Index Array LUN Name    Model       Vendor    Size   Owner           Checksum  Serial Number
----- ----------------- ----------  ------  -------- --------------  --------  ------------------------
   0  switch0:5.183L1   SYMMETRIX   EMC     266.1 GB                 Block     600604803436313734316631
   1  switch0:5.183L3   SYMMETRIX   EMC     266.1 GB                 Block     600604803436316333353837
   2  switch0:5.183L31  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237643666
   3  switch0:5.183L33  SYMMETRIX   EMC     658.3 GB local  (root)   Block     600604803436316263613066
   4  switch0:7.183L0   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313261356235
   5  switch0:7.183L2   SYMMETRIX   EMC     173.6 GB                 Block     600604803436313438396431
   6  switch0:7.183L4   SYMMETRIX   EMC     658.3 GB                 Block     600604803436313161663031
   7  switch0:7.183L30  SYMMETRIX   EMC     173.6 GB                 Block     600604803436316538353834
   8  switch0:7.183L32  SYMMETRIX   EMC     266.1 GB                 Block     600604803436313237353738
   9  switch0:7.183L34  SYMMETRIX   EMC     658.3 GB                 Block     600604803436313737333662
----
. Wählen Sie die Indexnummer für die Array-LUN aus, die Sie für die Diagnose- und Wiederherstellungsoptionen zuweisen möchten.
+
Die Array-LUN muss für die Verwendung in Diagnose- und Recovery-Optionen ausreichend groß sein. Bei Bedarf können Sie auch mehrere Array-LUNs mit einer kombinierten Größe auswählen, die größer oder gleich der angegebenen Größe ist. Um mehrere Einträge auszuwählen, müssen Sie die kommagetrennten Werte aller Indexnummern eingeben, die den Array-LUNs entsprechen, die Sie für Diagnose- und Wiederherstellungsoptionen auswählen möchten.

+
Das folgende Beispiel zeigt eine Liste der Array-LUNs, die für die Erstellung des Root-Volumes sowie für Diagnose- und Recovery-Optionen ausgewählt wurden:

+
[listing]
----

Here is a list of the selected array LUNs
Index Array LUN Name     Model      Vendor    Size    Owner          Checksum  Serial Number
----- -----------------  ---------  ------  --------  -------------  --------  ------------------------
   2  switch0:5.183L31   SYMMETRIX  EMC     266.1 GB  local          Block     600604803436313237643666
   3  switch0:5.183L33   SYMMETRIX  EMC     658.3 GB  local   (root) Block     600604803436316263613066
   4  switch0:7.183L0    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313261356235
   5  switch0:7.183L2    SYMMETRIX  EMC     173.6 GB  local          Block     600604803436313438396431
Do you want to continue (yes|no)?
----
+

NOTE: Durch Auswahl von „`no`“ wird die LUN-Auswahl gelöscht.

. Eingabe `*y*` Wenn Sie vom System aufgefordert werden, den Installationsvorgang fortzusetzen.
+
Das Root-Aggregat und das Root-Volume werden erstellt und der Rest des Installationsvorgangs wird fortgesetzt.

. Geben Sie die zum Erstellen der Node-Managementoberfläche erforderlichen Details ein.
+
Im folgenden Beispiel wird der Bildschirm der Node-Managementoberfläche mit einer Meldung angezeigt, die das Erstellen der Node-Managementoberfläche bestätigt:

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
Enter the node management interface IP address: 192.0.2.66

Enter the node management interface netmask: 255.255.255.192
Enter the node management interface default gateway: 192.0.2.7
A node management interface on port e0M with IP address 192.0.2.66 has been created.

This node has its management address assigned and is ready for cluster setup.
----


.Nachdem Sie fertig sind
Nach der Konfiguration von ONTAP für alle Nodes, die Sie mit den Array LUNs verwenden möchten, sollten Sie die abgeschlossen habenhttps://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html["Für die Cluster-Einrichtung"]

.Verwandte Informationen
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["Installationsanforderungen für FlexArray Virtualisierung und Referenz"]
