---
permalink: install-fc/task_reset_the_brocade_fc_switch_to_factory_defaults.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reset, brocade, fc, switch, factory, defaults 
summary: Bevor Sie eine neue Softwareversion und RCF-Dateien installieren, müssen Sie die aktuelle Switch-Konfiguration löschen und eine grundlegende Konfiguration durchführen. 
---
= Zurücksetzen des Brocade FC-Switch auf die Werkseinstellungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine neue Softwareversion und RCF-Dateien installieren, müssen Sie die aktuelle Switch-Konfiguration löschen und eine grundlegende Konfiguration durchführen.

Sie müssen diese Schritte bei jedem der FC-Switches in der MetroCluster Fabric-Konfiguration wiederholen.

.Schritte
. Melden Sie sich als Administrator beim Switch an.
. Deaktivieren Sie die Brocade Virtual Fabrics (VF) Funktion:
+
`fosconfig options`

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
WARNING:  This is a disruptive operation that requires a reboot to take effect.
Would you like to continue  [Y/N]: y
----
. Trennen Sie die ISL-Kabel von den Ports am Switch.
. Deaktivieren Sie den Schalter:
+
`switchcfgpersistentdisable`

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentdisable
----
. Deaktivieren der Konfiguration:
+
`cfgDisable`

+
[listing]
----
FC_switch_A_1:admin> cfgDisable
You are about to disable zoning configuration. This action will disable any previous zoning configuration enabled.
Do you want to disable zoning configuration? (yes, y, no, n): [no] y
Updating flash ...
Effective configuration is empty. "No  Access" default zone mode is ON.
----
. Löschen Sie die Konfiguration:
+
`cfgClear`

+
[listing]
----
FC_switch_A_1:admin> cfgClear
The Clear All action will clear all Aliases, Zones, FA Zones
and configurations in the Defined configuration.
Run cfgSave to commit the transaction or cfgTransAbort to
cancel the transaction.
Do you really want to clear all configurations?  (yes, y, no, n): [no] y
----
. Konfiguration speichern:
+
`cfgSave`

+
[listing]
----
FC_switch_A_1:admin> cfgSave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] y
Updating flash ...
----
. Legen Sie die Standardkonfiguration fest:
+
`configDefault`

+
[listing]
----
FC_switch_A_1:admin> configDefault
WARNING:  This is a disruptive operation that requires a switch reboot.
Would you like to continue [Y/N]: y
Executing configdefault...Please wait
2020/10/05-08:04:08, [FCR-1069], 1016, FID 128, INFO, FC_switch_A_1, The FC Routing service is enabled.
2020/10/05-08:04:08, [FCR-1068], 1017, FID 128, INFO, FC_switch_A_1, The FC Routing service is disabled.
2020/10/05-08:04:08, [FCR-1070], 1018, FID 128, INFO, FC_switch_A_1, The FC Routing configuration is set to default.
Committing configuration ... done.
2020/10/05-08:04:12, [MAPS-1113], 1019, FID 128, INFO, FC_switch_A_1, Policy dflt_conservative_policy activated.
2020/10/05-08:04:12, [MAPS-1145], 1020, FID 128, INFO, FC_switch_A_1, FPI Profile dflt_fpi_profile is activated for E-Ports.
2020/10/05-08:04:12, [MAPS-1144], 1021, FID 128, INFO, FC_switch_A_1, FPI Profile dflt_fpi_profile is activated for F-Ports.
The switch has to be rebooted to allow the changes to take effect.
2020/10/05-08:04:12, [CONF-1031], 1022, FID 128, INFO, FC_switch_A_1, configDefault completed successfully for switch.
----
. Setzen Sie für alle Ports die Portkonfiguration auf Standard:
+
`portcfgdefault _port-number_`

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault <port number>
----
+
Diesen Schritt müssen Sie für jeden Port abschließen.

. Vergewissern Sie sich, dass der Switch die dynamische Port-On-Demand-Methode (POD) verwendet.
+

NOTE: Bei Brocade Fabric OS-Versionen vor 8.0 führen Sie die folgenden Befehle als admin aus, für Versionen 8.0 und höher führen Sie sie als root aus.

+
.. Führen Sie den Lizenzbefehl aus:
+
`licenseport --show`

+
[listing]
----
FC_switch_A_1:admin> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Aktivieren Sie den Root-Benutzer, wenn er von Brocade deaktiviert ist.
+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. Führen Sie den Lizenzbefehl aus:
+
`licenseport --show`

+
[listing]
----
FC_switch_A_1:root> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Ändern Sie die Lizenzmethode in dynamisch:
+
`licenseport --method dynamic`

+

NOTE: Wenn die dynamische POD-Methode nicht verwendet wird (wenn DIE POD-Methode statisch ist), müssen Sie die Methode der Lizenzzuweisung in dynamisch ändern. Überspringen Sie diesen Schritt, wenn die dynamische POD-Methode verwendet wird.

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----


. Starten Sie den Switch neu:
+
`fastBoot`

+
[listing]
----
FC_switch_A_1:admin> fastboot
Warning: This command would cause the switch to reboot
and result in traffic disruption.
Are you sure you want to reboot the switch [y/n]?y
----
. Vergewissern Sie sich, dass die Standardeinstellungen implementiert wurden:
+
`switchShow`

. Überprüfen Sie, ob die IP-Adresse korrekt eingestellt ist:
+
`ipAddrShow`

+
Sie können die IP-Adresse bei Bedarf mit dem folgenden Befehl einstellen:

+
`ipAddrSet`


