---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, brocade, fc, switch, rcf, file 
summary: 'Sie müssen die Referenzkonfigurationsdatei \(RCF\) auf jeden Switch der MetroCluster-Fabric-Konfiguration herunterladen.' 
---
= Herunterladen der RCF-Datei des Brocade FC-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Referenzkonfigurationsdatei (RCF) auf jeden Switch der MetroCluster Fabric-Konfiguration herunterladen.

.Über diese Aufgabe
Um diese RCF-Dateien zu verwenden, muss das System ONTAP 9.1 oder höher ausführen und Sie müssen das Portlayout für ONTAP 9.1 oder höher verwenden.

Wenn Sie planen, nur einen der FC-Ports auf den FibreBridge-Bridges zu verwenden, konfigurieren Sie die Back-End-Fibre-Channel-Switches manuell anhand der Anweisungen im Abschnitt. link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Port-Zuweisungen für FC-Switches bei Verwendung von ONTAP 9.1 und höher"].

.Schritte
. Sehen Sie sich die RCF-Dateitabelle auf der Brocade RCF-Downloadseite an und identifizieren Sie für jeden Switch Ihrer Konfiguration die richtige RCF-Datei.
+
Die RCF-Dateien müssen auf die richtigen Schalter angewendet werden.

. Laden Sie die RCF-Dateien für die Schalter von herunter https://["MetroCluster RCF-Download"] Seite.
+
Die Dateien müssen an einem Speicherort abgelegt werden, an dem sie auf den Switch übertragen werden können. Es gibt für jeden der vier Switches eine separate Datei, aus der sich die zwei-Switch-Fabric besteht.

. Wiederholen Sie diese Schritte bei jedem Switch in der Konfiguration.

