---
permalink: install-fc/task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html 
sidebar: sidebar 
keywords: MetroCluster configurations 
summary: Sie müssen die einzelnen Brocade Switch-Fabrics in der MetroCluster Konfiguration konfigurieren. 
---
= Konfigurieren der Brocade FC-Switches manuell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die einzelnen Brocade Switch-Fabrics in der MetroCluster Konfiguration konfigurieren.

.Bevor Sie beginnen
* Sie müssen über eine PC- oder UNIX-Arbeitsstation mit Telnet- oder Secure Shell-Zugriff auf die FC-Switches verfügen.
* Sie müssen vier unterstützte Brocade Switches desselben Modells mit derselben Brocade Fabric Betriebssystemversion und derselben Lizenzierung verwenden.
+
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"]

+
Im IMT können Sie im Feld Storage-Lösung die Auswahl Ihrer MetroCluster Lösung verwenden. Sie verwenden den *Komponenten-Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.

* Die vier unterstützten Brocade-Switches müssen mit jeweils zwei Fabrics von je zwei Switches verbunden sein, wobei jede Fabric beide Standorte umfasst.
* Jeder Storage-Controller muss vier Initiator-Ports besitzen, um mit den Switch-Fabrics verbunden zu werden. Von jedem Storage Controller müssen zwei Initiator-Ports mit jeder Fabric verbunden sein.
+

NOTE: Sie können FAS8020, AFF8020, FAS8200 und AFF A300 Systeme mit zwei Initiatoren-Ports pro Controller (ein einzelner Initiator-Port zu jedem Fabric) konfigurieren, wenn alle folgenden Kriterien erfüllt sind:

+
** Es sind weniger als vier FC-Initiator-Ports zum Verbinden des Festplatten-Storage verfügbar, und keine zusätzlichen Ports können als FC-Initiatoren konfiguriert werden.
** Alle Steckplätze werden verwendet und es kann keine FC-Initiatorgruppe hinzugefügt werden.




.Über diese Aufgabe
* Sie sollten Inter-Switch Link (ISL) Trunking aktivieren, wenn es von den Links unterstützt wird.
+
link:concept_tdm_wdm.html["Überlegungen bei der Verwendung von TDM/WDM-Geräten mit Fabric-Attached MetroCluster-Konfigurationen"]

* Alle ISLs müssen in einem Fabric dieselbe Länge und dieselbe Geschwindigkeit aufweisen.
+
Verschiedene Längen können in den verschiedenen Stoffen verwendet werden. Die gleiche Geschwindigkeit muss in allen Stoffen verwendet werden.

* Metro-E und TDM (SONET/SDH) werden nicht unterstützt, und keine systemeigene Framing- oder Signalgebung, die nicht FC-Systeme sind, wird nicht unterstützt.
+
Metro-E bedeutet, dass Ethernet-Framing oder -Signalisierung entweder nativ über eine Metro-Entfernung oder durch Zeitdivision-Multiplexing (TDM), Multiprotocol Label Switching (MPLS) oder Wavelength-Division Multiplexing (WDM) erfolgt.

* TDMS, FCR (natives FC-Routing) oder FCIP-Erweiterungen werden von der MetroCluster FC-Switch-Fabric nicht unterstützt.
* Bestimmte Switches im MetroCluster FC Switch Fabric unterstützen Verschlüsselung oder Komprimierung. Manchmal werden beide unterstützt.
+
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool (IMT)"]

+
Im IMT können Sie im Feld Storage-Lösung die Auswahl Ihrer MetroCluster Lösung verwenden. Sie verwenden den *Komponenten-Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.

* Die Funktion Brocade Virtual Fabric (VF) wird nicht unterstützt.
* FC-Zoning auf Basis des Domain-Ports wird unterstützt, aber das Zoning auf Basis des weltweiten Namens (WWN) wird nicht unterstützt.




== Überprüfung der Brocade Lizenzanforderungen

Sie benötigen bestimmte Lizenzen für die Switches in einer MetroCluster-Konfiguration. Sie müssen diese Lizenzen auf allen vier Switches installieren.

Die MetroCluster-Konfiguration erfüllt die folgenden Anforderungen an die Brocade-Lizenz:

* Trunking-Lizenz für Systeme mit mehr als einer ISL, wie empfohlen.
* Erweiterte Fabric-Lizenz (für ISL-Entfernungen über 6 km)
* Enterprise-Lizenz für Standorte mit mehr als einem ISL und einer ISL-Entfernung von mehr als 6 km
+
Die Enterprise-Lizenz umfasst Brocade Network Advisor und alle Lizenzen, mit Ausnahme zusätzlicher Port-Lizenzen.



.Schritt
. Vergewissern Sie sich, dass die Lizenzen installiert sind:
+
`licenseshow`

+
Wenn Sie diese Lizenzen nicht besitzen, wenden Sie sich an Ihren Vertriebsmitarbeiter, bevor Sie fortfahren.





== Einstellen der Brocade FC-Switch-Werte auf die Werkseinstellungen

Sie müssen den Schalter auf die werkseitigen Standardeinstellungen setzen, um eine erfolgreiche Konfiguration zu gewährleisten. Außerdem müssen Sie jedem Switch einen eindeutigen Namen zuweisen.

In den Beispielen dieses Verfahrens besteht das Gewebe aus BrocadeSwitchA und BrocadeSwitchB.

.Schritte
. Verbinden Sie die Konsole und melden Sie sich bei beiden Switches in einer Fabric an.
. Deaktivieren Sie den Switch dauerhaft:
+
`switchcfgpersistentdisable`

+
Dadurch wird sichergestellt, dass der Schalter nach einem Neustart oder einem Fastboot deaktiviert bleibt. Wenn dieser Befehl nicht verfügbar ist, verwenden Sie den `switchdisable` Befehl.

+
Im folgenden Beispiel wird der Befehl auf BrocadeSwitchA angezeigt:

+
[listing]
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
Im folgenden Beispiel wird der Befehl auf BrocadeSwitchB angezeigt:

+
[listing]
----
BrocadeSwitchB:admin> switchcfgpersistentdisable
----
. Den Switch-Namen festlegen:
+
`switchname switch_name`

+
Die Schalter sollten jeweils einen eindeutigen Namen haben. Nach Festlegen des Namens ändert sich die Eingabeaufforderung entsprechend.

+
Im folgenden Beispiel wird der Befehl auf BrocadeSwitchA angezeigt:

+
[listing]
----
BrocadeSwitchA:admin> switchname "FC_switch_A_1"
FC_switch_A_1:admin>
----
+
Im folgenden Beispiel wird der Befehl auf BrocadeSwitchB angezeigt:

+
[listing]
----
BrocadeSwitchB:admin> switchname "FC_Switch_B_1"
FC_switch_B_1:admin>
----
. Legen Sie für alle Ports die Standardwerte fest:
+
`portcfgdefault`

+
Dies muss für alle Ports auf dem Switch durchgeführt werden.

+
Im folgenden Beispiel werden die Befehle an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> portcfgdefault 0
FC_switch_A_1:admin> portcfgdefault 1
...
FC_switch_A_1:admin> portcfgdefault 39
----
+
Im folgenden Beispiel werden die Befehle an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> portcfgdefault 0
FC_switch_B_1:admin> portcfgdefault 1
...
FC_switch_B_1:admin> portcfgdefault 39
----
. Löschen Sie die Zoning-Informationen:
+
`cfgdisable`

+
`cfgclear`

+
`cfgsave`

+
Im folgenden Beispiel werden die Befehle an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> cfgdisable
FC_switch_A_1:admin> cfgclear
FC_switch_A_1:admin> cfgsave
----
+
Im folgenden Beispiel werden die Befehle an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> cfgdisable
FC_switch_B_1:admin> cfgclear
FC_switch_B_1:admin> cfgsave
----
. Legen Sie die allgemeinen Switch-Einstellungen auf Standard fest:
+
`configdefault`

+
Im folgenden Beispiel wird der Befehl an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> configdefault
----
+
Im folgenden Beispiel wird der Befehl an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> configdefault
----
. Legen Sie für alle Ports den nicht-Trunking-Modus fest:
+
`switchcfgtrunk 0`

+
Im folgenden Beispiel wird der Befehl an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> switchcfgtrunk 0
----
+
Im folgenden Beispiel wird der Befehl an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> switchcfgtrunk 0
----
. Deaktivieren Sie bei Brocade 6510 Switches die Funktion Brocade Virtual Fabrics (VF):
+
`fosconfig options`

+
Im folgenden Beispiel wird der Befehl an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> fosconfig --disable vf
----
+
Im folgenden Beispiel wird der Befehl an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> fosconfig --disable vf
----
. Löschen Sie die Administrator-Domänenkonfiguration (AD):
+
`ad options`

+
Im folgenden Beispiel werden die Befehle an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> switch:admin> ad --select AD0
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
FC_switch_A_1:admin> ad --clear -f
FC_switch_A_1:admin> ad --apply
FC_switch_A_1:admin> ad --save
FC_switch_A_1:admin> exit
----
+
Im folgenden Beispiel werden die Befehle an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> switch:admin> ad --select AD0
FC_switch_A_1:> defzone --noaccess
FC_switch_A_1:> cfgsave
FC_switch_A_1:> exit
FC_switch_B_1:admin> ad --clear -f
FC_switch_B_1:admin> ad --apply
FC_switch_B_1:admin> ad --save
FC_switch_B_1:admin> exit
----
. Starten Sie den Switch neu:
+
`reboot`

+
Im folgenden Beispiel wird der Befehl an FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
Im folgenden Beispiel wird der Befehl an FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:admin> reboot
----




== Konfigurieren der grundlegenden Switch-Einstellungen

Für Brocade Switches müssen Sie die globalen Grundeinstellungen, einschließlich der Domänen-ID, konfigurieren.

Diese Aufgabe enthält Schritte, die auf jedem Switch an beiden MetroCluster-Standorten ausgeführt werden müssen.

In diesem Verfahren legen Sie die eindeutige Domänen-ID für jeden Switch fest, wie im folgenden Beispiel dargestellt. Im Beispiel bilden die Domänen-IDs 5 und 7 Fabric_1 und die Domänen-IDs 6 und 8 Form Fabric_2.

* FC_Switch_A_1 ist der Domänen-ID 5 zugewiesen
* FC_Switch_A_2 ist der Domänen-ID 6 zugewiesen
* FC_Switch_B_1 ist der Domänen-ID 7 zugewiesen
* FC_Switch_B_2 ist der Domänen-ID 8 zugewiesen


.Schritte
. Konfigurationsmodus aufrufen:
+
`configure`

. Gehen Sie die Eingabeaufforderungen durch:
+
.. Legen Sie die Domänen-ID für den Switch fest.
.. Drücken Sie als Antwort auf die Eingabeaufforderungen *Enter*, bis Sie auf "RDP-Polling-Zyklus" gelangen, und setzen Sie diesen Wert dann auf `0` So deaktivieren Sie die Abfrage.
.. Drücken Sie *Enter*, bis Sie zur Switch-Eingabeaufforderung zurückkehren.
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = 5
.
.

RSCN Transmission Mode [yes, y, no, no: [no] y

End-device RSCN Transmission Mode
 (0 = RSCN with single PID, 1 = RSCN with multiple PIDs, 2 = Fabric RSCN): (0..2) [1]
Domain RSCN To End-device for switch IP address or name change
 (0 = disabled, 1 = enabled): (0..1) [0] 1

.
.
RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
----


. Wenn Sie zwei oder mehr ISLs pro Fabric verwenden, können Sie entweder in-Order Delivery (IOD) von Frames oder Out-of-Order (OOD) Lieferung von Frames konfigurieren.
+

NOTE: Die Standard-IOD-Einstellungen werden empfohlen. Sie sollten OOD nur bei Bedarf konfigurieren.

+
link:concept_prepare_for_the_mcc_installation.html["Überlegungen bei der Verwendung von TDM/WDM-Geräten mit Fabric-Attached MetroCluster-Konfigurationen"]

+
.. Zur Konfiguration von IOD der Frames müssen die folgenden Schritte auf jeder Switch-Fabric durchgeführt werden:
+
... IOD aktivieren:
+
`iodset`

... Setzen Sie die Advanced Performance Tuning-Richtlinie (APT) auf 1:
+
`aptpolicy 1`

... Deaktivieren der DLS (Dynamic Load Sharing):
+
`dlsreset`

... Überprüfen Sie die IOD-Einstellungen mithilfe des `iodshow`, `aptpolicy`, und `dlsshow` Befehle.
+
Geben Sie beispielsweise die folgenden Befehle an FC_Switch_A_1 aus:

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 1 0(ap)

    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
         0: AP Shared Link Policy
         1: AP Dedicated Link Policy
    command aptpolicy completed

    FC_switch_A_1:admin> dlsshow
    DLS is not set
----
... Wiederholen Sie diese Schritte auf der zweiten Switch Fabric.


.. Die folgenden Schritte müssen auf jeder Switch-Fabric ausgeführt werden, um OOD von Frames zu konfigurieren:
+
... OOD aktivieren:
+
`iodreset`

... Setzen Sie die Advanced Performance Tuning-Richtlinie (APT) auf 3:
+
`aptpolicy 3`

... Deaktivieren der DLS (Dynamic Load Sharing):
+
`dlsreset`

... Überprüfen Sie die OOD-Einstellungen:
+
`iodshow`

+
`aptpolicy`

+
`dlsshow`

+
Geben Sie beispielsweise die folgenden Befehle an FC_Switch_A_1 aus:

+
[listing]
----
FC_switch_A_1:admin> iodshow
    IOD is not set

    FC_switch_A_1:admin> aptpolicy
    Current Policy: 3 0(ap)
    3 0(ap) : Default Policy
    1: Port Based Routing Policy
    3: Exchange Based Routing Policy
    0: AP Shared Link Policy
    1: AP Dedicated Link Policy
    command aptpolicy completed


    FC_switch_A_1:admin> dlsshow
    DLS is set by default with current routing policy
----
... Wiederholen Sie diese Schritte auf der zweiten Switch Fabric.
+

NOTE: Bei der Konfiguration von ONTAP auf den Controller-Modulen muss OOD explizit auf jedem Controller-Modul in der MetroCluster-Konfiguration konfiguriert sein.

+
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software["Konfigurieren von in-Order-Lieferung oder Lieferung von Frames auf ONTAP Software außerhalb der Reihenfolge"]





. Vergewissern Sie sich, dass der Switch die dynamische Port-Lizenzmethode verwendet.
+
.. Führen Sie den Lizenzbefehl aus:
+
--
`licensePort --show`

[listing]
----
FC_switch_A_1:admin> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----

NOTE: Brocade FabricPool Versionen vor 8.0 führen die folgenden Befehle als Administrator und Version 8.0 aus und führen sie später als „root“ aus.

--
.. Aktivieren Sie den Root-Benutzer.
+
Wenn der Root-Benutzer bereits von Brocade deaktiviert ist, aktivieren Sie den Root-Benutzer wie im folgenden Beispiel dargestellt:

+
[listing]
----
FC_switch_A_1:admin> userconfig --change root -e yes
FC_switch_A_1:admin> rootaccess --set consoleonly
----
.. Führen Sie den Lizenzbefehl aus:
+
`licensePort --show`

+
[listing]
----
FC_switch_A_1:root> licenseport -show
24 ports are available in this switch
Full POD license is installed
Dynamic POD method is in use
----
.. Ändern Sie die Lizenzmethode in dynamisch:
+
`licenseport --method dynamic`

+

NOTE: Wenn die dynamische Lizenzmethode nicht verwendet wird (wenn die Methode statisch ist), müssen Sie die Lizenzmethode in dynamisch ändern. Überspringen Sie diesen Schritt, wenn die dynamische Lizenzmethode verwendet wird.

+
[listing]
----
FC_switch_A_1:admin> licenseport --method dynamic
The POD method has been changed to dynamic.
Please reboot the switch now for this change to take effect
----


. Aktivieren Sie Trap für T11-FC-ZONE-SERVER-MIB für die erfolgreiche Integritätsüberwachung der Switches in ONTAP:
+
.. Aktivieren Sie die T11-FC-ZONE-SERVER-MIB:
+
`snmpconfig --set mibCapability -mib_name T11-FC-ZONE-SERVER-MIB -bitmask 0x3f`

.. Aktivieren Sie den T11-FC-ZONE-SERVER-MIB-Trap:
+
`snmpconfig --enable mibcapability -mib_name SW-MIB -trap_name swZoneConfigChangeTrap`

.. Wiederholen Sie die vorherigen Schritte auf der zweiten Switch Fabric.


. *Optional*: Wenn Sie die Community-Zeichenkette auf einen anderen Wert als „öffentlich“ setzen, müssen Sie die ONTAP Health Monitore mit der von Ihnen angegebenen Community-Zeichenfolge konfigurieren:
+
.. Vorhandene Community-Zeichenfolge ändern:
+
`snmpconfig --set snmpv1`

.. Drücken Sie *Enter*, bis der Text „Community (ro): [Public]“ angezeigt wird.
.. Geben Sie die gewünschte Community-Zeichenfolge ein.
+
Am FC_Switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm     <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]    in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_A_1:admin>
----
+
Am FC_Switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> snmpconfig --set snmpv1
SNMP community and trap recipient configuration:
Community (rw): [Secret C0de]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [OrigEquipMfr]
Trap Recipient's IP address : [0.0.0.0]
Community (rw): [private]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [public] mcchm      <<<<<< change the community string to the desired value,
Trap Recipient's IP address : [0.0.0.0]     in this example it is set to "mcchm"
Community (ro): [common]
Trap Recipient's IP address : [0.0.0.0]
Community (ro): [FibreChannel]
Trap Recipient's IP address : [0.0.0.0]
Committing configuration.....done.
FC_switch_B_1:admin>
----


. Starten Sie den Switch neu:
+
`reboot`

+
Am FC_Switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> reboot
----
+
Am FC_Switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> reboot
----
. Dauerhaft aktivieren Sie den Switch:
+
`switchcfgpersistentenable`

+
Am FC_Switch_A_1:

+
[listing]
----
FC_switch_A_1:admin> switchcfgpersistentenable
----
+
Am FC_Switch_B_1:

+
[listing]
----
FC_switch_B_1:admin> switchcfgpersistentenable
----




== Konfigurieren der grundlegenden Switch-Einstellungen bei einem Brocade DCX 8510-8 Switch

Für Brocade Switches müssen Sie die globalen Grundeinstellungen, einschließlich der Domänen-ID, konfigurieren.

Sie müssen die einzelnen Schritte auf jedem Switch an beiden MetroCluster Standorten durchführen. In diesem Verfahren legen Sie die Domänen-ID für jeden Switch fest, wie in den folgenden Beispielen dargestellt:

* FC_Switch_A_1 ist der Domänen-ID 5 zugewiesen
* FC_Switch_A_2 ist der Domänen-ID 6 zugewiesen
* FC_Switch_B_1 ist der Domänen-ID 7 zugewiesen
* FC_Switch_B_2 ist der Domänen-ID 8 zugewiesen


Im vorherigen Beispiel bilden die Domänen-IDs 5 und 7 Fabric_1 sowie die Domänen-IDs 6 und 8 Form Fabric_2.


NOTE: Mit diesem Verfahren können Sie die Switches auch konfigurieren, wenn Sie nur einen DCX 8510-8-Switch pro Standort verwenden.

Mit diesem Verfahren sollten Sie auf jedem Brocade DCX 8510-8 Switch zwei logische Switches erstellen. Die beiden logischen Switches, die auf beiden Brocade DCX8510-8 Switches erstellt wurden, bilden wie in den folgenden Beispielen dargestellt zwei logische Fabrics:

* LOGISCHE STRUKTUR 1: Switch 1/Blade1 und Switch 2 Blade 1
* LOGISCHES GEWEBE 2: Switch1/Blade2 und Switch 2 Blade 2


.Schritte
. Wechseln Sie in den Befehlsmodus:
+
`configure`

. Gehen Sie die Eingabeaufforderungen durch:
+
.. Legen Sie die Domänen-ID für den Switch fest.
.. Wählen Sie weiter *Enter*, bis Sie auf "RDP-Polling Cycle" gelangen, und setzen Sie dann den Wert auf `0` So deaktivieren Sie die Abfrage.
.. Wählen Sie *Enter*, bis Sie zur Switch-Eingabeaufforderung zurückkehren.
+
[listing]
----
FC_switch_A_1:admin> configure
Fabric parameters = y
Domain_id = `5


RDP Polling Cycle(hours)[0 = Disable Polling]: (0..24) [1] 0
`
----


. Wiederholen Sie diese Schritte bei allen Schaltern in Fabric_1 und Fabric_2.
. Konfigurieren Sie die virtuellen Fabrics.
+
.. Aktivieren Sie virtuelle Fabrics auf dem Switch:
+
`fosconfig --enablevf`

.. Konfigurieren Sie das System so, dass es auf allen logischen Switches dieselbe Basiskonfiguration verwendet:
+
`configurechassis`

+
Das folgende Beispiel zeigt die Ausgabe für das `configurechassis` Befehl:

+
[listing]
----
System (yes, y, no, n): [no] n
cfgload attributes (yes, y, no, n): [no] n
Custom attributes (yes, y, no, n): [no] y
Config Index (0 to ignore): (0..1000) [3]:
----


. Logischen Switch erstellen und konfigurieren:
+
`scfg --create fabricID`

. Fügen Sie alle Ports von einem Blade zur virtuellen Fabric hinzu:
+
`lscfg --config fabricID -slot slot -port lowest-port - highest-port`

+

NOTE: Die Blades bilden eine logische Struktur (z.B. Switch 1 Blade 1 und Switch 3 Blade 1) müssen dieselbe Fabric-ID haben.

+
[listing]
----
setcontext fabricid
switchdisable
configure
<configure the switch per the above settings>
switchname unique switch name
switchenable
----


link:concept_prepare_for_the_mcc_installation.html["Anforderungen für die Verwendung eines Brocade DCX 8510-8 Switches"]



== Konfigurieren von E-Ports an Brocade FC Switches über FC-Ports

Für Brocade Switches, auf denen die Inter-Switch-Links (ISL) über FC-Ports konfiguriert sind, müssen Sie die Switch-Ports an jedem Switch-Fabric mit ISL konfigurieren. Diese ISL-Ports werden auch als E-Ports bezeichnet.

.Bevor Sie beginnen
* Alle ISLs in einer FC Switch Fabric müssen mit derselben Geschwindigkeit und Entfernung konfiguriert sein.
* Die Kombination aus Switch-Port und Small Form-Factor Pluggable (SFP) muss die Geschwindigkeit unterstützen.
* Die unterstützte ISL-Entfernung hängt vom FC-Switch-Modell ab.
+
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"]

+
Im IMT können Sie im Feld Storage-Lösung die Auswahl Ihrer MetroCluster Lösung verwenden. Sie verwenden den *Komponenten-Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.

* Der ISL-Link muss über eine dedizierte Lambda verfügen, und der Link muss von Brocade für die Entfernung, den Switch-Typ und das Fabric-Betriebssystem (FOS) unterstützt werden.


Sie dürfen die L0-Einstellung nicht verwenden, wenn Sie die ausgeben `portCfgLongDistance` Befehl. Stattdessen sollten Sie die EINSTELLUNG LE oder LS verwenden, um die Entfernung auf den Brocade-Switches mit einer Mindestentfernungsstufe VON LE zu konfigurieren.

Sie dürfen die LD-Einstellung nicht verwenden, wenn Sie die ausgeben `portCfgLongDistance` Befehl beim Arbeiten mit xWDM/TDM-Geräten. Verwenden Sie stattdessen die EINSTELLUNG LE oder LS, um die Entfernung der Brocade-Switches zu konfigurieren.

Diese Aufgabe müssen Sie für jede FC-Switch-Fabric durchführen.

In den folgenden Tabellen werden die ISL-Ports für verschiedene Switches und verschiedene ISLs in einer Konfiguration mit ONTAP 9.1 oder 9.2 angezeigt. Die in diesem Abschnitt gezeigten Beispiele gelten für einen Brocade 6505-Switch. Sie sollten die Beispiele ändern, um Ports zu verwenden, die für den Switch-Typ gelten.

Wenn Ihre Konfiguration ONTAP 9.0 oder eine frühere Version ausführt, lesen Sie den link:concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["Port-Zuweisungen für FC-Switches bei Verwendung von ONTAP 9.0"].

Sie müssen die erforderliche Anzahl von ISLs für Ihre Konfiguration verwenden.

|===


| Switch-Modell | ISL-Port | Switch-Port 


.4+| Brocade 6520 | ISL-Port 1 | 23 


| ISL-Port 2 | 47 


| ISL-Port 3 | 71 


| ISL-Port 4 | 95 


.4+| Brocade 6505 | ISL-Port 1 | 20 


| ISL-Port 2 | 21 


| ISL-Port 3 | 22 


| ISL-Port 4 | 23 


.8+| Brocade 6510 und Brocade DCX 8510-8 | ISL-Port 1 | 40 


| ISL-Port 2 | 41 


| ISL-Port 3 | 42 


| ISL-Port 4 | 43 


| ISL-Port 5 | 44 


| ISL-Port 6 | 45 


| ISL-Port 7 | 46 


| ISL-Port 8 | 47 


.6+| Brocade 7810  a| 
ISL-Port 1
 a| 
ge2 (10 Gbit/s)



 a| 
ISL-Port 2
 a| 
ge3 (10 Gbit/s)



 a| 
ISL-Port 3
 a| 
ge4 (10 Gbit/s)



 a| 
ISL-Port 4
 a| 
Ge5 (10 Gbit/s)



 a| 
ISL-Port 5
 a| 
ge6 (10 Gbit/s)



 a| 
ISL-Port 6
 a| 
Ge7 (10 Gbit/s)



.4+| Brocade 7840 *Hinweis:* der Brocade 7840 Switch unterstützt entweder zwei VE-Ports mit 40 Gbit/s oder bis zu vier VE-Ports mit 10 Gbit/s pro Switch zur Erstellung von FCIP-ISLs.  a| 
ISL-Port 1
 a| 
ge0 (40 Gbit/s) oder ge2 (10 Gbit/s)



 a| 
ISL-Port 2
 a| 
ge1 (40 Gbit/s) oder ge3 (10 Gbit/s)



 a| 
ISL-Port 3
 a| 
ge10 (10 Gbit/s)



 a| 
ISL-Port 4
 a| 
Ge11 (10 Gbit/s)



.4+| Brocade G610  a| 
ISL-Port 1
 a| 
20



 a| 
ISL-Port 2
 a| 
21



 a| 
ISL-Port 3
 a| 
22



 a| 
ISL-Port 4
 a| 
23



.7+| BROCADE G620, G620-1, G630, G630-1, G720  a| 
ISL-Port 1
 a| 
40



 a| 
ISL-Port 2
 a| 
41



 a| 
ISL-Port 3
 a| 
42



 a| 
ISL-Port 4
 a| 
43



 a| 
ISL-Port 5
 a| 
44



 a| 
ISL-Port 6
 a| 
45



 a| 
ISL-Port 7
 a| 
46

|===
.Schritte
. [[ste1_brocade_config]] Konfigurieren der Portgeschwindigkeit:
+
`portcfgspeed port-numberspeed`

+
Sie müssen die höchste gemeinsame Geschwindigkeit verwenden, die von den Komponenten im Pfad unterstützt wird.

+
Im folgenden Beispiel sind zwei ISLs für jede Fabric verfügbar:

+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 20 16
FC_switch_A_1:admin> portcfgspeed 21 16

FC_switch_B_1:admin> portcfgspeed 20 16
FC_switch_B_1:admin> portcfgspeed 21 16
----
. Konfigurieren Sie den Trunking-Modus für jede ISL:
+
`portcfgtrunkport port-number`

+
** Wenn Sie die ISLs für Trunking (IOD) konfigurieren, stellen Sie die Port-numberport-Nummer von portcfgTrunk auf 1 ein, wie im folgenden Beispiel dargestellt:
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 1
FC_switch_A_1:admin> portcfgtrunkport 21 1
FC_switch_B_1:admin> portcfgtrunkport 20 1
FC_switch_B_1:admin> portcfgtrunkport 21 1
----
** Wenn Sie die ISL for Trunking (OOD) nicht konfigurieren möchten, setzen Sie die Portcfgtrunkport-Nummer auf 0, wie im folgenden Beispiel dargestellt:
+
[listing]
----
FC_switch_A_1:admin> portcfgtrunkport 20 0
FC_switch_A_1:admin> portcfgtrunkport 21 0
FC_switch_B_1:admin> portcfgtrunkport 20 0
FC_switch_B_1:admin> portcfgtrunkport 21 0
----


. QoS-Datenverkehr für jeden ISL-Port aktivieren:
+
`portcfgqos --enable port-number`

+
Im folgenden Beispiel gibt es zwei ISLs pro Switch Fabric:

+
[listing]
----
FC_switch_A_1:admin> portcfgqos --enable 20
FC_switch_A_1:admin> portcfgqos --enable 21

FC_switch_B_1:admin> portcfgqos --enable 20
FC_switch_B_1:admin> portcfgqos --enable 21
----
. Überprüfen Sie die Einstellungen:
+
`portCfgShow command`

+
Das folgende Beispiel zeigt die Ausgabe für eine Konfiguration, die zwei mit Port 20 und Port 21 verkabelte ISLs verwendet. Die Einstellung für den Trunk-Port sollte FÜR IOD und OOD AUS aktiviert sein:

+
[listing]
----

Ports of Slot 0   12  13   14 15    16  17  18  19   20  21 22  23    24  25  26  27
----------------+---+---+---+---+-----+---+---+---+----+---+---+---+-----+---+---+---
Speed             AN  AN  AN  AN    AN  AN  8G  AN   AN  AN  16G  16G    AN  AN  AN  AN
Fill Word         0   0   0   0     0   0   3   0    0   0   3   3     3   0   0   0
AL_PA Offset 13   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Trunk Port        ..  ..  ..  ..    ..  ..  ..  ..   ON  ON  ..  ..    ..  ..  ..  ..
Long Distance     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
VC Link Init      ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked L_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked G_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Disabled E_Port   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Locked E_Port     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
ISL R_RDY Mode    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
RSCN Suppressed   ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Persistent Disable..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
LOS TOV enable    ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
NPIV capability   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
NPIV PP Limit    126 126 126 126   126 126 126 126  126 126 126 126   126 126 126 126
QOS E_Port        AE  AE  AE  AE    AE  AE  AE  AE   AE  AE  AE  AE    AE  AE  AE  AE
Mirror Port       ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Rate Limit        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Credit Recovery   ON  ON  ON  ON    ON  ON  ON  ON   ON  ON  ON  ON    ON  ON  ON  ON
Fport Buffers     ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
Port Auto Disable ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..
CSCTL mode        ..  ..  ..  ..    ..  ..  ..  ..   ..  ..  ..  ..    ..  ..  ..  ..

Fault Delay       0  0  0  0    0  0  0  0   0  0  0  0    0  0  0  0
----
. Berechnen der ISL-Entfernung.
+
Aufgrund des Verhaltens von FC-VI muss die Entfernung auf das 1.5-fache der realen Entfernung mit einer Mindestentfernung von 10 km (über DIE LE-Entfernungsebene) eingestellt werden.

+
Der Abstand für die ISL wird wie folgt berechnet, gerundet auf den nächsten vollen Kilometer:

+
1.5 × Real_distance = Entfernung

+
Wenn die Entfernung 3 km beträgt, dann 1.5 × 3 km = 4.5 km Dies ist weniger als 10 km, daher muss die ISL auf DIE LE-Distanzebene eingestellt werden.

+
Wenn die Entfernung 20 km beträgt, dann 1.5 × 20 km = 30 km Die ISL muss auf 30 km eingestellt sein und die LS-Abstandsebene verwenden.

. Legen Sie die Entfernung an jedem ISL-Port fest:
+
`portcfglongdistance _portdistance-level_ vc_link_init _distance_`

+
A `vc_link_init` Der Wert von `1` Verwendet das ARB-Füllwort (Standard). Der Wert von `0` Nutzt DEN LEERLAUF. Der erforderliche Wert hängt von der verwendeten Verbindung ab. Für jeden ISL-Port müssen die Befehle wiederholt werden.

+
Bei einer ISL-Entfernung von 3 km, wie im Beispiel im vorherigen Schritt angegeben, beträgt die Einstellung 4.5 km mit der Standardeinstellung `vc_link_init` Der Wert von `1`. Da die Einstellung von 4.5 km weniger als 10 km beträgt, muss der Hafen auf DIE LE-Distanzebene eingestellt werden:

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LE 1

FC_switch_B_1:admin> portcfglongdistance 20 LE 1
----
+
Bei einer ISL-Entfernung von 20 km, wie im Beispiel im vorherigen Schritt angegeben, beträgt die Einstellung 30 km mit dem Standardwert vc_Link_init `1`:

+
[listing]
----
FC_switch_A_1:admin> portcfglongdistance 20 LS 1 -distance 30

FC_switch_B_1:admin> portcfglongdistance 20 LS 1 -distance 30
----
. Überprüfen Sie die Distanzeinstellung:
+
`portbuffershow`

+
Eine Entfernung von LE erscheint als 10 km

+
Das folgende Beispiel zeigt die Ausgabe für eine Konfiguration, die ISLs an Port 20 und Port 21 verwendet:

+
[listing]
----
FC_switch_A_1:admin> portbuffershow

User  Port     Lx      Max/Resv    Buffer Needed    Link      Remaining
Port  Type    Mode     Buffers     Usage  Buffers   Distance  Buffers
----  ----    ----     -------     ------ -------   --------- ---------
...
 20     E      -          8         67      67       30km
 21     E      -          8         67      67       30km
...
 23            -          8          0      -        -        466
----
. Vergewissern Sie sich, dass beide Switches eine Struktur bilden:
+
`switchshow`

+
Das folgende Beispiel zeigt die Ausgabe für eine Konfiguration, die ISLs an Port 20 und Port 21 verwendet:

+
[listing]
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Subordinate
switchDomain:       5
switchId:   fffc01
switchWwn:  10:00:00:05:33:86:89:cb
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
===========================================
...
20   20  010C00   id    16G  Online FC  LE E-Port  10:00:00:05:33:8c:2e:9a "FC_switch_B_1" (downstream)(trunk master)
21   21  010D00   id    16G  Online FC  LE E-Port  (Trunk port, master is Port 20)
...

FC_switch_B_1:admin> switchshow
switchName: FC_switch_B_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       7
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State Proto
==============================================
...
20   20  030C00   id    16G  Online  FC  LE E-Port  10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)(Trunk master)
21   21  030D00   id    16G  Online  FC  LE E-Port  (Trunk port, master is Port 20)
...
----
. Bestätigen Sie die Konfiguration der Fabrics:
+
`fabricshow`

+
[listing]
----
FC_switch_A_1:admin> fabricshow
   Switch ID   Worldwide Name      Enet IP Addr FC IP Addr Name
-----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0    "FC_switch_A_1"
3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0   >"FC_switch_B_1"
----
+
[listing]
----
FC_switch_B_1:admin> fabricshow
   Switch ID   Worldwide Name     Enet IP Addr FC IP Addr   Name
----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0     "FC_switch_A_1"

3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0    >"FC_switch_B_1
----
. [[ste10_brocade_config]]Bestätigen Sie das Trunking der ISLs:
+
`trunkshow`

+
** Wenn Sie die ISLs für Trunking (IOD) konfigurieren, sollte die Ausgabe ähnlich wie die folgenden angezeigt werden:
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16
 FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
    21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16
----
** Wenn Sie die ISLs für Trunking (OOD) nicht konfigurieren, sollte die Ausgabe ähnlich wie die folgenden angezeigt werden:
+
[listing]
----
FC_switch_A_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:ac:2b:13 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:8c:2e:9a 3 deskew 16 MASTER
FC_switch_B_1:admin> trunkshow
 1: 20-> 20 10:00:00:05:33:86:89:cb 3 deskew 15 MASTER
 2: 21-> 21 10:00:00:05:33:86:89:cb 3 deskew 16 MASTER
----


. Wiederholen ,Schritt 1 Bis ,Schritt 10 Für das zweite FC Switch Fabric.


link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Port-Zuweisungen für FC-Switches bei Verwendung von ONTAP 9.1 und höher"]



== Konfigurieren von 10 Gbps VE-Ports an Brocade FC 7840-Switches

Wenn Sie die 10-Gbit/s-VE-Ports (die FCIP verwenden) für ISLs verwenden, müssen Sie an jedem Port IP-Schnittstellen erstellen und FCIP-Tunnel und -Leitungen in jedem Tunnel konfigurieren.

Dieses Verfahren muss an jeder Switch-Fabric in der MetroCluster Konfiguration durchgeführt werden.

Die Beispiele in diesem Verfahren gehen davon aus, dass die beiden Brocade 7840-Switches die folgenden IP-Adressen haben:

* FC_Switch_A_1 ist lokal.
* FC_Switch_B_1 ist Remote.


.Schritte
. IP-Schnittstellenadressen für die 10-Gbit/s-Ports auf beiden Switches in der Fabric erstellen:
+
`portcfg ipif FC_switch1_namefirst_port_name create FC_switch1_IP_address netmask netmask_number vlan 2 mtu auto`

+
Mit dem folgenden Befehl werden ipif-Adressen an den Ports ge2.dp0 und ge3.dp0 von FC_Switch_A_1 erstellt:

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.71 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.71 netmask 255.255.0.0 vlan 2 mtu auto
----
+
Mit dem folgenden Befehl werden ipif-Adressen an den Ports ge2.dp0 und ge3.dp0 von FC_Switch_B_1 erstellt:

+
[listing]
----
portcfg ipif  ge2.dp0 create  10.10.20.72 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge3.dp0 create  10.10.21.72 netmask 255.255.0.0 vlan 2 mtu auto
----
. Überprüfen Sie, ob die ipif-Adressen auf beiden Switches erfolgreich erstellt wurden:
+
`portshow ipif all`

+
Mit dem folgenden Befehl werden die ipif-Adressen auf Switch FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.71                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.71                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
Mit dem folgenden Befehl werden die ipif-Adressen auf Switch FC_Switch_B_1 angezeigt:

+
[listing]
----
FC_switch_B_1:root> portshow ipif all

 Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge2.dp0      10.10.20.72                    / 24   AUTO  2     U R M I
 ge3.dp0      10.10.21.72                    / 20   AUTO  2     U R M I
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. Erstellen Sie den ersten der beiden FCIP-Tunnel unter Verwendung der Ports auf dp0:
+
`portcfg fciptunnel`

+
Mit diesem Befehl wird ein Tunnel mit einer einzigen Schaltung erstellt.

+
Mit dem folgenden Befehl wird der Tunnel auf Switch FC_Switch_A_1 erstellt:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.71  -D 10.10.20.72 -b 10000000 -B 10000000
----
+
Mit dem folgenden Befehl wird der Tunnel auf Switch FC_Switch_B_1 erstellt:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.20.72  -D 10.10.20.71 -b 10000000 -B 10000000
----
. Überprüfen Sie, ob die FCIP-Tunnel erfolgreich erstellt wurden:
+
`portshow fciptunnel all`

+
Das folgende Beispiel zeigt, dass die Tunnel erstellt wurden und die Stromkreise aktiv sind:

+
[listing]
----
FC_switch_B_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
--------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. Erstellen Sie einen zusätzlichen Stromkreis für dp0.
+
Mit dem folgenden Befehl wird ein Schaltkreis auf Switch FC_Switch_A_1 für dp0 erzeugt:

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.71 -D 10.10.21.72  --min-comm-rate 5000000 --max-comm-rate 5000000
----
+
Mit dem folgenden Befehl wird ein Schaltkreis auf Schalter FC_Switch_B_1 für dp0 erzeugt:

+
[listing]
----
portcfg fcipcircuit 24 create 1 -S 10.10.21.72 -D 10.10.21.71  --min-comm-rate 5000000 --max-comm-rate 5000000
----
. Vergewissern Sie sich, dass alle Stromkreise erfolgreich erstellt wurden:
+
`portshow fcipcircuit all`

+
Mit dem folgenden Befehl werden die Schaltkreise und deren Status angezeigt:

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge2     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge3     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
--------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Konfigurieren von 40-Gbps-VE-Ports auf Brocade 7810- und 7840-FC-Switches

Wenn Sie die zwei 40-GbE-VE-Ports (die FCIP verwenden) für ISLs verwenden, müssen Sie an jedem Port IP-Schnittstellen erstellen und FCIP-Tunnel und -Leitungen in jedem Tunnel konfigurieren.

Dieses Verfahren muss an jeder Switch-Fabric in der MetroCluster Konfiguration durchgeführt werden.

Die Beispiele in diesem Verfahren verwenden zwei Schalter:

* FC_Switch_A_1 ist lokal.
* FC_Switch_B_1 ist Remote.


.Schritte
. IP-Schnittstellenadressen für die 40-Gbit/s-Ports auf beiden Switches in der Fabric erstellen:
+
`portcfg ipif FC_switch_namefirst_port_name create FC_switch_IP_address netmask netmask_number vlan 2 mtu auto`

+
Mit dem folgenden Befehl werden ipif-Adressen an den Ports ge0.dp0 und ge1.dp0 von FC_Switch_A_1 erstellt:

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.82.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.82.11 netmask 255.255.0.0 vlan 2 mtu auto
----
+
Mit dem folgenden Befehl werden ipif-Adressen an den Ports ge0.dp0 und ge1.dp0 von FC_Switch_B_1 erstellt:

+
[listing]
----
portcfg ipif  ge0.dp0 create  10.10.83.10 netmask 255.255.0.0 vlan 2 mtu auto
portcfg ipif  ge1.dp0 create  10.10.83.11 netmask 255.255.0.0 vlan 2 mtu auto
----
. Überprüfen Sie, ob die ipif-Adressen auf beiden Switches erfolgreich erstellt wurden:
+
`portshow ipif all`

+
Im folgenden Beispiel werden die IP-Schnittstellen an FC_Switch_A_1 angezeigt:

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
---------------------------------------------------------------------------
-----
 ge0.dp0      10.10.82.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.82.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
+
Im folgenden Beispiel werden die IP-Schnittstellen an FC_Switch_B_1 angezeigt:

+
[listing]
----
Port         IP Address                     / Pfx  MTU   VLAN  Flags
--------------------------------------------------------------------------------
 ge0.dp0      10.10.83.10                    / 16   AUTO  2     U R M
 ge1.dp0      10.10.83.11                    / 16   AUTO  2     U R M
--------------------------------------------------------------------------------
Flags: U=Up B=Broadcast D=Debug L=Loopback P=Point2Point R=Running I=InUse
       N=NoArp PR=Promisc M=Multicast S=StaticArp LU=LinkUp X=Crossport
----
. Erstellen Sie den FCIP-Tunnel an beiden Switches:
+
`portcfig fciptunnel`

+
Mit dem folgenden Befehl wird der Tunnel auf FC_Switch_A_1 erstellt:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.82.10  -D 10.10.83.10 -b 10000000 -B 10000000
----
+
Mit dem folgenden Befehl wird der Tunnel auf FC_Switch_B_1 erstellt:

+
[listing]
----
portcfg fciptunnel 24 create -S 10.10.83.10  -D 10.10.82.10 -b 10000000 -B 10000000
----
. Überprüfen Sie, ob der FCIP-Tunnel erfolgreich erstellt wurde:
+
`portshow fciptunnel all`

+
Das folgende Beispiel zeigt, dass der Tunnel erstellt wurde und die Stromkreise aktiv sind:

+
[listing]
----
FC_switch_A_1:root>

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    -         Up      ---------     2d8m    0.05    0.41   3      -       -
 --------------------------------------------------------------------------------
 Flags (tunnel): i=IPSec f=Fastwrite T=TapePipelining F=FICON r=ReservedBW
                 a=FastDeflate d=Deflate D=AggrDeflate P=Protocol
                 I=IP-Ext
----
. Erstellen Sie einen zusätzlichen Stromkreis an jedem Schalter:
+
`portcfg fcipcircuit 24 create 1 -S source-IP-address -D destination-IP-address --min-comm-rate 10000000 --max-comm-rate 10000000`

+
Mit dem folgenden Befehl wird ein Schaltkreis auf Switch FC_Switch_A_1 für dp0 erzeugt:

+
[listing]
----
portcfg fcipcircuit 24  create 1 -S 10.10.82.11 -D 10.10.83.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
+
Mit dem folgenden Befehl wird ein Schaltkreis am Schalter FC_Switch_B_1 für dp1 erzeugt:

+
[listing]
----
portcfg fcipcircuit 24 create 1  -S 10.10.83.11 -D 10.10.82.11  --min-comm-rate 10000000 --max-comm-rate 10000000
----
. Vergewissern Sie sich, dass alle Stromkreise erfolgreich erstellt wurden:
+
`portshow fcipcircuit all`

+
Im folgenden Beispiel werden die Schaltkreise aufgeführt und der OpStatus angezeigt:

+
[listing]
----
FC_switch_A_1:root> portshow fcipcircuit all

 Tunnel Circuit  OpStatus  Flags    Uptime  TxMBps  RxMBps ConnCnt CommRt Met/G
--------------------------------------------------------------------------------
 24    0 ge0     Up      ---va---4    2d12m    0.02    0.03   3 10000/10000 0/-
 24    1 ge1     Up      ---va---4    2d12m    0.02    0.04   3 10000/10000 0/-
 --------------------------------------------------------------------------------
 Flags (circuit): h=HA-Configured v=VLAN-Tagged p=PMTU i=IPSec 4=IPv4 6=IPv6
                 ARL a=Auto r=Reset s=StepDown t=TimedStepDown  S=SLA
----




== Konfigurieren der nicht-E-Ports auf dem Brocade-Switch

Sie müssen die nicht-E-Ports auf dem FC-Switch konfigurieren. In einer MetroCluster-Konfiguration sind dies die Ports, die den Switch mit den HBA-Initiatoren, FC-VI-Interconnects und FC-to-SAS-Bridges verbinden. Diese Schritte müssen für jeden Port durchgeführt werden.

Im folgenden Beispiel verbinden die Ports eine FC-to-SAS-Bridge:

--
* Port 6 auf FC_FC_Switch_A_1 an Site_A
* Port 6 auf FC_FC_Switch_B_1 an Standort_B


--
.Schritte
. Konfigurieren Sie die Portgeschwindigkeit für jeden nicht-E-Port:
+
`portcfgspeed portspeed`

+
Sie sollten die höchste allgemeine Geschwindigkeit verwenden, die von allen Komponenten im Datenpfad unterstützt wird: Dem SFP, dem Switch-Port, auf dem der SFP installiert ist, und dem angeschlossenen Gerät (HBA, Bridge usw.).

+
Für die Komponenten werden u. U. die folgenden unterstützten Geschwindigkeiten unterstützt:

+
** Das SFP-Modul kann 4, 8 oder 16 GB betragen.
** Der Switch-Port kann 4, 8 oder 16 GB betragen.
** Die maximale Geschwindigkeit des angeschlossenen HBA beträgt 16 GB. Die höchste übliche Geschwindigkeit in diesem Fall ist 16 GB, daher sollte der Port für eine Geschwindigkeit von 16 GB konfiguriert werden.
+
[listing]
----
FC_switch_A_1:admin> portcfgspeed 6 16

FC_switch_B_1:admin> portcfgspeed 6 16
----


. Überprüfen Sie die Einstellungen:
+
`portcfgshow`

+
[listing]
----
FC_switch_A_1:admin> portcfgshow

FC_switch_B_1:admin> portcfgshow
----
+
In der Beispielausgabe hat Port 6 die folgenden Einstellungen; die Geschwindigkeit ist auf 16G festgelegt:

+
[listing]
----
Ports of Slot 0                     0   1   2   3   4   5   6   7   8
-------------------------------------+---+---+---+--+---+---+---+---+--
Speed                               16G 16G 16G 16G 16G 16G 16G 16G 16G
AL_PA Offset 13                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Trunk Port                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Long Distance                       ..  ..  ..  ..  ..  ..  ..  ..  ..
VC Link Init                        ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked L_Port                       -   -   -   -   -  -   -   -   -
Locked G_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Disabled E_Port                     ..  ..  ..  ..  ..  ..  ..  ..  ..
Locked E_Port                       ..  ..  ..  ..  ..  ..  ..  ..  ..
ISL R_RDY Mode                      ..  ..  ..  ..  ..  ..  ..  .. ..
RSCN Suppressed                     ..  ..  ..  ..  ..  ..  ..  .. ..
Persistent Disable                  ..  ..  ..  ..  ..  ..  ..  .. ..
LOS TOV enable                      ..  ..  ..  ..  ..  ..  ..  .. ..
NPIV capability                     ON  ON  ON  ON  ON  ON  ON  ON  ON
NPIV PP Limit                       126 126 126 126 126 126 126 126 126
QOS Port                            AE  AE  AE  AE  AE  AE  AE  AE  ON
EX Port                             ..  ..  ..  ..  ..  ..  ..  ..  ..
Mirror Port                         ..  ..  ..  ..  ..  ..  ..  ..  ..
Rate Limit                          ..  ..  ..  ..  ..  ..  ..  ..  ..
Credit Recovery                     ON  ON  ON  ON  ON  ON  ON  ON  ON
Fport Buffers                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Eport Credits                       ..  ..  ..  ..  ..  ..  ..  ..  ..
Port Auto Disable                   ..  ..  ..  ..  ..  ..  ..  ..  ..
CSCTL mode                          ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port mode                         ..  ..  ..  ..  ..  ..  ..  ..  ..
D-Port over DWDM                    ..  ..  ..  ..  ..  ..  ..  ..  ..
FEC                                 ON  ON  ON  ON  ON  ON  ON  ON  ON
Fault Delay                         0   0   0   0   0   0   0   0   0
Non-DFE                             ..  ..  ..  ..  ..  ..  ..  ..  ..
----




== Konfigurieren der Komprimierung auf ISL-Ports auf einem Brocade G620 Switch

Wenn Sie Brocade G620 Switches verwenden und die Komprimierung für die ISLs aktivieren, müssen Sie diese an jedem E-Port der Switches konfigurieren.

Diese Aufgabe muss an den ISL-Ports beider Switches mit ISL ausgeführt werden.

.Schritte
. Deaktivieren Sie den Port, auf dem die Komprimierung konfiguriert werden soll:
+
`portdisable port-id`

. Aktivieren Sie die Komprimierung am Port:
+
`portCfgCompress --enable port-id`

. Aktivieren Sie den Port, um die Konfiguration mit Komprimierung zu aktivieren:
+
`portenable port-id`

. Bestätigen Sie, dass die Einstellung geändert wurde:
+
`portcfgshow port-id`



Im folgenden Beispiel wird die Komprimierung für Port 0 aktiviert.

[listing]
----
FC_switch_A_1:admin> portdisable 0
FC_switch_A_1:admin> portcfgcompress --enable 0
FC_switch_A_1:admin> portenable 0
FC_switch_A_1:admin> portcfgshow 0
Area Number: 0
Octet Speed Combo: 3(16G,10G)
(output truncated)
D-Port mode: OFF
D-Port over DWDM ..
Compression: ON
Encryption: ON
----
Mit dem Befehl islShow können Sie überprüfen, ob der E_Port mit konfigurierter und aktiver Verschlüsselung oder Komprimierung online geschaltet wurde.

[listing]
----
FC_switch_A_1:admin> islshow
  1: 0-> 0 10:00:c4:f5:7c:8b:29:86   5 FC_switch_B_1
sp: 16.000G bw: 16.000G TRUNK QOS CR_RECOV ENCRYPTION COMPRESSION
----
Mit dem Befehl portEncCompShow können Sie feststellen, welche Ports aktiv sind. In diesem Beispiel sehen Sie, dass Verschlüsselung und Komprimierung für Port 0 konfiguriert und aktiv sind.

[listing]
----
FC_switch_A_1:admin> portenccompshow
User	  Encryption		           Compression	         Config
Port   Configured    Active   Configured   Active  Speed
----   ----------    -------  ----------   ------  -----
  0	   Yes	          Yes	     Yes	         Yes	    16G
----


== Konfigurieren des Zoning auf Brocade FC-Switches

Sie müssen die Switch-Ports separaten Zonen zuweisen, sodass der Controller- und Storage-Datenverkehr voneinander getrennt ist. Das Verfahren unterscheidet sich je nachdem, ob Sie eine FibreBridge 7500N oder FibreBridge 6500N verwenden.



=== Zoning für FC-VI-Ports

Sie müssen für jede DR-Gruppe in der MetroCluster zwei Zonen für die FC-VI-Verbindungen konfigurieren, die den Controller-zu-Controller-Datenverkehr ermöglichen. Diese Zonen enthalten die FC-Switch-Ports, die mit den FC-VI-Ports des Controller-Moduls verbunden sind. Diese Zonen sind Quality of Service (QoS)-Zonen.

Ein QoS-Zonenname beginnt mit dem Präfix QOSHid_, gefolgt von einem benutzerdefinierten String, um ihn von einer regulären Zone zu unterscheiden. Diese QoS-Zonen sind unabhängig vom verwendeten Modell der FibreBridge Bridge identisch.

Jede Zone enthält alle FC-VI-Ports, einen für jedes FC-VI-Kabel von jedem Controller. Diese Zonen werden für eine hohe Priorität konfiguriert.

In den folgenden Tabellen werden die FC-VI-Zonen für zwei DR-Gruppen angezeigt.

*DR-Gruppe 1 : QOSH1 FC-VI-Zone für FC-VI-Port A / c*

|===
| FC Switch | Standort | Switch-Domäne | 6505 / 6510 Anschlüsse | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 5 | 0 | 0 | 0 | Controller_A_1-Port FC-VI A 


| FC_Switch_A_1 | A | 5 | 1 | 1 | 1 | Controller_A_1-Port FC-VI c 


| FC_Switch_A_1 | A | 5 | 4 | 4 | 4 | Controller_A_2-Port FC-VI A 


| FC_Switch_A_1 | A | 5 | 5 | 5 | 5 | Controller_A_2-Port FC-VI c 


| FC_Switch_B_1 | B | 7 | 0 | 0 | 0 | Controller_B_1-Port FC-VI A 


| FC_Switch_B_1 | B | 7 | 1 | 1 | 1 | Controller_B_1-Port FC-VI c 


| FC_Switch_B_1 | B | 7 | 4 | 4 | 4 | Controller_B_2-Port FC-VI A 


| FC_Switch_B_1 | B | 7 | 5 | 5 | 5 | Controller_B_2-Port FC-VI c 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| QOSH1_MC1_FAB_1_FCVI | 5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5 
|===
*DR-Gruppe 1 : QOSH1 FC-VI-Zone für FC-VI-Port b / d*

|===
| FC Switch | Standort | Switch-Domäne | 6505 / 6510 Anschlüsse | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


| FC_Switch_A_2 | A | 6 | 0 | 0 | 0 | Controller_A_1-Port FC-VI b 


|  |  |  | 1 | 1 | 1 | Controller_A_1-Port FC-VI D 


|  |  |  | 4 | 4 | 4 | Controller_A_2-Port FC-VI b 


|  |  |  | 5 | 5 | 5 | Controller_A_2-Port FC-VI D 


| FC_Switch_B_2 | B | 8 | 0 | 0 | 0 | Controller_B_1-Port FC-VI b 


|  |  |  | 1 | 1 | 1 | Controller_B_1-Port FC-VI D 


|  |  |  | 4 | 4 | 4 | Controller_B_2-Port FC-VI b 


|  |  |  | 5 | 5 | 5 | Controller_B_2-Port FC-VI D 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| QOSH1_MC1_FAB_2_FCVI | 6,0;6,1;6,4;6,5;8,0;8,1;8,4;8,5 
|===
*DR-Gruppe 2 : QOSH2 FC-VI-Zone für FC-VI-Port A / c*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port |  |  | Verbindung wird hergestellt mit... 


|  |  |  | 6510 | 6520 | G620 |  


| FC_Switch_A_1 | A | 5 | 24 | 48 | 18 | Controller_A_3-Port FC-VI A 


|  |  |  | 25 | 49 | 19 | Controller_A_3-Port FC-VI c 


|  |  |  | 28 | 52 | 22 | Controller_A_4-Port FC-VI A 


|  |  |  | 29 | 53 | 23 | Controller_A_4-Port FC-VI c 


| FC_Switch_B_1 | B | 7 | 24 | 48 | 18 | Controller_B_3-Port FC-VI A 


|  |  |  | 25 | 49 | 19 | Controller_B_3-Port FC-VI c 


|  |  |  | 28 | 52 | 22 | Controller_B_4-Port FC-VI A 


|  |  |  | 29 | 53 | 23 | Controller_B_4-Port FC-VI c 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| QOSH2_MC2_FAB_1_FCVI (6510) | 5,24;5,25;5,28;5,29;7,24;7,25;7,28;7,29 


| QOSH2_MC2_FAB_1_FCVI (6520) | 5,48;5,49;5,52;5,53;7,48;7,49;7,52;7,53 
|===
*DR-Gruppe 2 : QOSH2 FC-VI-Zone für FC-VI-Port b / d*

|===
| FC Switch | Standort | Switch-Domäne | 6510 Anschlüsse | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


| FC_Switch_A_2 | A | 6 | 24 | 48 | 18 | Controller_A_3-Port FC-VI b 


| FC_Switch_A_2 | A | 6 | 25 | 49 | 19 | Controller_A_3-Port FC-VI D 


| FC_Switch_A_2 | A | 6 | 28 | 52 | 22 | Controller_A_4-Port FC-VI b 


| FC_Switch_A_2 | A | 6 | 29 | 53 | 23 | Controller_A_4-Port FC-VI D 


| FC_Switch_B_2 | B | 8 | 24 | 48 | 18 | Controller_B_3-Port FC-VI b 


| FC_Switch_B_2 | B | 8 | 25 | 49 | 19 | Controller_B_3-Port FC-VI D 


| FC_Switch_B_2 | B | 8 | 28 | 52 | 22 | Controller_B_4-Port FC-VI b 


| FC_Switch_B_2 | B | 8 | 29 | 53 | 23 | Controller_B_4-Port FC-VI D 
|===
|===


| Zone in Fabric_2 | Mitgliedsports 


| QOSH2_MC2_FAB_2_FCVI (6510) | 6,24;6,25;6,28;6,29;8,24;8,25;8,28;8,29 


| QOSH2_MC2_FAB_2_FCVI (6520) | 6,48;6,49;6,52;6,53;8,48;8,49;8,52;8,53 
|===
Die folgende Tabelle enthält eine Zusammenfassung der FC-VI-Zonen:

|===


| Fabric | Zonenname | Mitgliedsports 


.3+| FC_Switch_A_1 und FC_Switch_B_1  a| 
QOSH1_MC1_FAB_1_FCVI
 a| 
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5



 a| 
QOSH2_MC1_FAB_1_FCVI ( 6510)
 a| 
5,24;5,25;5,28;5,29;7,24;7,25;7,28;7,29



 a| 
QOSH2_MC1_FAB_1_FCVI (6520)
 a| 
5,48;5,49;5,52;5,53;7,48;7,49;7,52;7,53



.3+| FC_Switch_A_2 und FC_Switch_B_2  a| 
QOSH1_MC1_FAB_2_FCVI
 a| 
6,0;6,1;6,4;6,5;8,0;8,1;8,4;8,5



 a| 
QOSH2_MC1_FAB_2_FCVI (6510)
 a| 
6,24;6,25;6,28;6,29;8,24;8,25;8,28;8,29



 a| 
QOSH2_MC1_FAB_2_FCVI (6520)
 a| 
6,48;6,49;6,52;6,53;8,48;8,49;8,52;8,53

|===


=== Zoning für FibreBridge 6500N-Brücken oder FibreBridge 7500N- oder 7600N-Brücken unter Verwendung eines FC-Ports

Wenn Sie FibreBridge 6500N-Brücken oder FibreBridge 7500N- oder 7600N-Brücken mit nur einem der beiden FC-Ports verwenden, müssen Sie Speicherzonen für die Bridge-Ports erstellen. Sie sollten die Zonen und die zugehörigen Ports verstehen, bevor Sie die Zonen konfigurieren.

Die Beispiele zeigen nur das Zoning für DR-Gruppe 1. Wenn die Konfiguration eine zweite DR-Gruppe umfasst, konfigurieren Sie das Zoning für die zweite DR-Gruppe auf dieselbe Weise unter Verwendung der entsprechenden Ports der Controller und Bridges.



==== Erforderliche Zonen

Sie müssen eine Zone für jede der FC-to-SAS-Bridge-FC-Ports konfigurieren, die den Datenverkehr zwischen Initiatoren auf jedem Controller-Modul und diese FC-to-SAS-Bridge zulässt.

Jede Speicherzone enthält neun Ports:

* Acht HBA-Initiator-Ports (zwei Verbindungen pro Controller)
* Ein Port mit einer FC-to-SAS-Bridge-FC-Port


Die Storage-Zonen verwenden das Standard-Zoning.

Die Beispiele zeigen zwei Brückenpaare, die an jedem Standort zwei Stapelgruppen miteinander verbinden. Da jede Bridge einen FC Port verwendet, gibt es insgesamt vier Storage-Zonen pro Fabric (insgesamt acht).



==== Brückenbenennung

Die Brücken verwenden das folgende Beispiel: Bridge_site_Stack Sammelversetzung in Paar

|===


| Dieser Teil des Namens... | Identifiziert... | Mögliche Werte... 


 a| 
Standort
 a| 
Standort, auf dem sich das Brückenpaar physisch befindet.
 a| 
A oder B



 a| 
Stapelgruppe
 a| 
Nummer der Stapelgruppe, mit der das Brückenpaar verbunden ist.

* FibreBridge 7600N oder 7500N-Brücken unterstützen bis zu vier Stapel in der Stapelgruppe.
+
Die Stack-Gruppe kann maximal 10 Storage Shelves enthalten.

* FibreBridge 6500N Bridges unterstützen nur einen einzelnen Stack in der Stapelgruppe.

 a| 
1, 2, usw.



 a| 
Position in Paar
 a| 
Brücke innerhalb des Brückenpaares.Ein Paar Brücken verbinden sich mit einer bestimmten Stapelgruppe.
 a| 
A oder b

|===
Beispiel für Brückennamen für eine Stapelgruppe auf jedem Standort:

* Bridge_A_1a
* Bridge_A_1b
* Bridge_B_1a
* Bridge_B_1b




==== DR-Gruppe 1 - Stack 1 bei Site_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port von Brocade 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 5 | 2 | Controller_A_1-Port 0a 


| FC_Switch_A_1 | A | 5 | 3 | Controller_A_1-Port 0c 


| FC_Switch_A_1 | A | 5 | 6 | Controller_A_2-Port 0a 


| FC_Switch_A_1 | A | 5 | 7 | Controller_A_2-Port 0c 


| FC_Switch_A_1 | A | 5 | 8 | Bridge_A_1a FC1 


| FC_Switch_B_1 | B | 7 | 2 | Controller_B_1-Port 0a 


| FC_Switch_B_1 | B | 7 | 3 | Controller_B_1-Port 0c 


| FC_Switch_B_1 | B | 7 | 6 | Controller_B_2-Port 0a 


| FC_Switch_B_1 | B | 7 | 7 | Controller_B_2-Port 0c 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,8 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port von Brocade 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 6 | 2 | Port 0b_A_1 


| FC_Switch_A_1 | A | 6 | 3 | Controller_A_1-Port 0d 


| FC_Switch_A_1 | A | 6 | 6 | Port 0b_Controller_A_2 


| FC_Switch_A_1 | A | 6 | 7 | Controller_A_2-Port 0d 


| FC_Switch_A_1 | A | 6 | 8 | Bridge_A_1b FC1 


| FC_Switch_B_1 | B | 8 | 2 | Controller_B_1-Port 0b 


| FC_Switch_B_1 | B | 8 | 3 | Controller_B_1-Port 0d 


| FC_Switch_B_1 | B | 8 | 6 | Port 0b_B_2 


| FC_Switch_B_1 | B | 8 | 7 | Controller_B_2-Port 0d 
|===
|===


| Zone in Fabric_2 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,8 
|===


==== DR-Gruppe 1 - Stack 2 bei Site_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port von Brocade 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 5 | 2 | Controller_A_1-Port 0a 


| FC_Switch_A_1 | A | 5 | 3 | Controller_A_1-Port 0c 


| FC_Switch_A_1 | A | 5 | 6 | Controller_A_2-Port 0a 


| FC_Switch_A_1 | A | 5 | 7 | Controller_A_2-Port 0c 


| FC_Switch_A_1 | A | 5 | 9 | Bridge_A_2a FC1 


| FC_Switch_B_1 | B | 7 | 2 | Controller_B_1-Port 0a 


| FC_Switch_B_1 | B | 7 | 3 | Controller_B_1-Port 0c 


| FC_Switch_B_1 | B | 7 | 6 | Controller_B_2-Port 0a 


| FC_Switch_B_1 | B | 7 | 7 | Controller_B_2-Port 0c 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,9 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port von Brocade 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 6 | 2 | Port 0b_A_1 


| FC_Switch_A_1 | A | 6 | 3 | Controller_A_1-Port 0d 


| FC_Switch_A_1 | A | 6 | 6 | Port 0b_Controller_A_2 


| FC_Switch_A_1 | A | 6 | 7 | Controller_A_2-Port 0d 


| FC_Switch_A_1 | A | 6 | 9 | Bridge_A_2b FC1 


| FC_Switch_B_1 | B | 8 | 2 | Controller_B_1-Port 0b 


| FC_Switch_B_1 | B | 8 | 3 | Controller_B_1-Port 0d 


| FC_Switch_B_1 | B | 8 | 6 | Port 0b_B_2 


| FC_Switch_B_1 | B | 8 | 7 | Controller_B_2-Port 0d 
|===
|===


| Zone in Fabric_2 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,9 
|===


==== DR-Gruppe 1 – Stack 1 an Standort_B

*MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Brocade Switch 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 5 | 2 | Controller_A_1-Port 0a 


| FC_Switch_A_1 | A | 5 | 3 | Controller_A_1-Port 0c 


| FC_Switch_A_1 | A | 5 | 6 | Controller_A_2-Port 0a 


| FC_Switch_A_1 | A | 5 | 7 | Controller_A_2-Port 0c 


| FC_Switch_B_1 | B | 7 | 2 | Controller_B_1-Port 0a 


| FC_Switch_B_1 | B | 7 | 3 | Controller_B_1-Port 0c 


| FC_Switch_B_1 | B | 7 | 6 | Controller_B_2-Port 0a 


| FC_Switch_B_1 | B | 7 | 7 | Controller_B_2-Port 0c 


| FC_Switch_B_1 | B | 7 | 8 | Bridge_B_1a FC1 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,8 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Brocade Switch 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 6 | 2 | Port 0b_A_1 


| FC_Switch_A_1 | A | 6 | 3 | Controller_A_1-Port 0d 


| FC_Switch_A_1 | A | 6 | 6 | Port 0b_Controller_A_2 


| FC_Switch_A_1 | A | 6 | 7 | Controller_A_2-Port 0d 


| FC_Switch_B_1 | B | 8 | 2 | Controller_B_1-Port 0b 


| FC_Switch_B_1 | B | 8 | 3 | Controller_B_1-Port 0d 


| FC_Switch_B_1 | B | 8 | 6 | Port 0b_B_2 


| FC_Switch_B_1 | B | 8 | 7 | Controller_B_2-Port 0d 


| FC_Switch_B_1 | B | 8 | 8 | Bridge_B_1b FC1 
|===
|===


| Zone in Fabric_2 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;8,8 
|===


==== DR-Gruppe 1 - Stack 2 an Standort_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port von Brocade 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 5 | 2 | Controller_A_1-Port 0a 


| FC_Switch_A_1 | A | 5 | 3 | Controller_A_1-Port 0c 


| FC_Switch_A_1 | A | 5 | 6 | Controller_A_2-Port 0a 


| FC_Switch_A_1 | A | 5 | 7 | Controller_A_2-Port 0c 


| FC_Switch_B_1 | B | 7 | 2 | Controller_B_1-Port 0a 


| FC_Switch_B_1 | B | 7 | 3 | Controller_B_1-Port 0c 


| FC_Switch_B_1 | B | 7 | 6 | Controller_B_2-Port 0a 


| FC_Switch_B_1 | B | 7 | 7 | Controller_B_2-Port 0c 


| FC_Switch_B_1 | B | 7 | 9 | Bridge_b_2a FC1 
|===
|===


| Zone in Fabric_1 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,9 
|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1:*

|===
| FC Switch | Standort | Switch-Domäne | Switch-Port von Brocade 6505, 6510, 6520, G620 oder G610 | Verbindung wird hergestellt mit... 


| FC_Switch_A_1 | A | 6 | 2 | Port 0b_A_1 


| FC_Switch_A_1 | A | 6 | 3 | Controller_A_1-Port 0d 


| FC_Switch_A_1 | A | 6 | 6 | Port 0b_Controller_A_2 


| FC_Switch_A_1 | A | 6 | 7 | Controller_A_2-Port 0d 


| FC_Switch_B_1 | B | 8 | 2 | Controller_B_1-Port 0b 


| FC_Switch_B_1 | B | 8 | 3 | Controller_B_1-Port 0d 


| FC_Switch_B_1 | B | 8 | 6 | Port 0b_B_2 


| FC_Switch_B_1 | B | 8 | 7 | Controller_B_2-Port 0d 


| FC_Switch_B_1 | B | 8 | 9 | Bridge_B_1b FC1 
|===
|===


| Zone in Fabric_2 | Mitgliedsports 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,9 
|===


==== Zusammenfassung der Speicherzonen

|===


| Fabric | Zonenname | Mitgliedsports 


.4+| FC_Switch_A_1 und FC_Switch_B_1 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;5,9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1 | 5,2;5,3;5,6;5,7;7,2;7,3;7,6;7,7;7,9 


.4+| FC_Switch_A_2 und FC_Switch_B_2 | MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,8 


| MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;6,9 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,8 


| MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC1 | 6,2;6,3;6,6;6,7;8,2;8,3;8,6;8,7;8,9 
|===


=== Zoning für FibreBridge 7500N-Bridges unter Verwendung beider FC-Ports

Wenn Sie FibreBridge 7500N-Brücken mit beiden FC-Ports verwenden, müssen Sie Speicherzonen für die Bridge-Ports erstellen. Sie sollten die Zonen und die zugehörigen Ports verstehen, bevor Sie die Zonen konfigurieren.



==== Erforderliche Zonen

Sie müssen eine Zone für jede der FC-to-SAS-Bridge-FC-Ports konfigurieren, die den Datenverkehr zwischen Initiatoren auf jedem Controller-Modul und diese FC-to-SAS-Bridge zulässt.

Jede Speicherzone enthält fünf Ports:

* Vier HBA-Initiator-Ports (eine Verbindung für jeden Controller)
* Ein Port mit einer FC-to-SAS-Bridge-FC-Port


Die Storage-Zonen verwenden das Standard-Zoning.

Die Beispiele zeigen zwei Brückenpaare, die an jedem Standort zwei Stapelgruppen miteinander verbinden. Da jede Bridge einen FC Port verwendet, gibt es insgesamt acht Storage-Zonen pro Fabric (insgesamt sechzehn).



==== Brückenbenennung

Die Brücken verwenden das folgende Beispiel: Bridge_site_Stack Sammelversetzung in Paar

|===


| Dieser Teil des Namens... | Identifiziert... | Mögliche Werte... 


 a| 
Standort
 a| 
Standort, auf dem sich das Brückenpaar physisch befindet.
 a| 
A oder B



 a| 
Stapelgruppe
 a| 
Nummer der Stapelgruppe, mit der das Brückenpaar verbunden ist.

* FibreBridge 7600N oder 7500N-Brücken unterstützen bis zu vier Stapel in der Stapelgruppe.
+
Die Stack-Gruppe kann maximal 10 Storage Shelves enthalten.

* FibreBridge 6500N Bridges unterstützen nur einen einzelnen Stack in der Stapelgruppe.

 a| 
1, 2, usw.



 a| 
Position in Paar
 a| 
Brücke innerhalb des Brückenpaares. Ein Paar Brücken verbinden sich mit einer bestimmten Stapelgruppe.
 a| 
A oder b

|===
Beispiel für Brückennamen für eine Stapelgruppe auf jedem Standort:

* Bridge_A_1a
* Bridge_A_1b
* Bridge_B_1a
* Bridge_B_1b




==== DR-Gruppe 1 - Stack 1 bei Site_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505/6510/G610/G620-Anschluss | 6520 Anschlüsse | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port 0a



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
Controller_A_2-Port 0a



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
8
 a| 
8
 a| 
Bridge_A_1a FC1



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
Controller_B_2-Port 0a

|===
|===


| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0c



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2-Port 0c



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
9
 a| 
9
 a| 
9
 a| 
Bridge_A_1b FC1



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2-Port 0c

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,9

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_1_BOT_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610 | 6520 | G620 | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
8
 a| 
8
 a| 
8
 a| 
Bridge_A_1a FC2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Port 0b_B_2

|===
|===


| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610 | 6520 | G620 | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
9
 a| 
9
 a| 
9
 a| 
Bridge_A_1b FC2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_B_2

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,9

|===


==== DR-Gruppe 1 - Stack 2 bei Site_A

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port 0a



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2-Port 0a



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
10
 a| 
10
 a| 
10
 a| 
Bridge_A_2a FC1



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_B_2-Port 0a

|===
|===


| Zone in Fabric_1 h | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_2_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0c



| FC_Switch_A_1  a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2-Port 0c



| FC_Switch_A_1  a| 
A
 a| 
5
 a| 
11
 a| 
11
 a| 
11
 a| 
Bridge_A_2b FC1



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2-Port 0c

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,11

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_A_STK_GRP_2_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
0
 a| 
0
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
4
 a| 
4
 a| 
Port 0b_Controller_A_2



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
10
 a| 
10
 a| 
10
 a| 
Bridge_A_2a FC2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Port 0b_B_2

|===
|===


| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_Controller_A_2



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
11
 a| 
11
 a| 
11
 a| 
Bridge_A_2b FC2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0b\



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_B_2

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,11

|===


==== DR-Gruppe 1 – Stack 1 an Standort_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port 0a



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
8
 a| 
Controller_B_1-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
2
 a| 
Controller_B_2-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
8
 a| 
8
 a| 
6
 a| 
Bridge_B_1a FC1

|===
|===


| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_1_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0c



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
9
 a| 
Controller_B_1-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
3
 a| 
Controller_B_2-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
9
 a| 
9
 a| 
7
 a| 
Bridge_B_1b FC1

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,9

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_1_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Port 0b_Controller_A_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Port 0b_B_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
8
 a| 
8
 a| 
8
 a| 
Bridge_B_1a FC2

|===
|===
| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,8

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_Controller_A_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_B_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
9
 a| 
9
 a| 
9
 a| 
Bridge_A_1b FC2

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,9

|===


==== DR-Gruppe 1 - Stack 2 an Standort_B

*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port 0a



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_A_2-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
6
 a| 
6
 a| 
6
 a| 
Controller_B_2-Port 0a



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
10
 a| 
10
 a| 
10
 a| 
Bridge_B_2a FC1

|===
|===


| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_2_TOP_FC1:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0c



 a| 
FC_Switch_A_1
 a| 
A
 a| 
5
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_A_2-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
7
 a| 
7
 a| 
7
 a| 
Controller_B_2-Port 0c



 a| 
FC_Switch_B_1
 a| 
B
 a| 
7
 a| 
11
 a| 
11
 a| 
11
 a| 
Bridge_B_2b FC1

|===
|===


| Zone in Fabric_2 h | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,11

|===
*DRGROUP 1 : MC1_INIT_GRP_1_SITE_B_STK_GRP_2_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_A_1-Port d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
6
 a| 
6
 a| 
6
 a| 
Port 0b_Controller_A_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
2
 a| 
2
 a| 
2
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
6
 a| 
6
 a| 
6
 a| 
Port 0b_B_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
10
 a| 
10
 a| 
10
 a| 
Bridge_B_2a FC2

|===
|===


| Zone in Fabric_1 | Mitgliedsports 


 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,10

|===
*DRGROUP 1 : MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2:*

|===


| FC Switch | Standort | Switch-Domäne | 6505 / 6510 / G610-Anschluss | 6520 Anschlüsse | G620-Anschluss | Verbindung wird hergestellt mit... 


 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_A_1-Port 0d



 a| 
FC_Switch_A_2
 a| 
A
 a| 
6
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_Controller_A_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
3
 a| 
3
 a| 
3
 a| 
Controller_B_1-Port 0b



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
7
 a| 
7
 a| 
7
 a| 
Port 0b_B_2



 a| 
FC_Switch_B_2
 a| 
B
 a| 
8
 a| 
11
 a| 
11
 a| 
11
 a| 
Bridge_B_2b FC2

|===
|===


| Zone in Fabric_2 | Mitgliedsports 


 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,11

|===


==== Zusammenfassung der Speicherzonen

|===


| Fabric | Zonenname | Mitgliedsports 


 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,8



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,9



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;5,10



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;5,11



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,8



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,9



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC1
 a| 
5,2;5,6;7,2;7,6;7,10



 a| 
FC_Switch_A_1 und FC_Switch_B_1
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC1
 a| 
5,3;5,7;7,3;7,7;7,11



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,8



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,9



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_A_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;6,10



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_A_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;6,11



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_1_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,8



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_1_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,9



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_1_SITE_B_STK_GRP_2_TOP_FC2
 a| 
6,2;6,6;8,2;8,6;8,10



 a| 
FC_Switch_A_2 und FC_Switch_B_2
 a| 
MC1_INIT_GRP_2_SITE_B_STK_GRP_2_BOT_FC2
 a| 
6,3;6,7;8,3;8,7;8,11

|===


=== Konfigurieren des Zoning auf Brocade FC-Switches

Sie müssen die Switch-Ports separaten Zonen zuweisen, sodass der Controller- und Storage-Traffic über Zonen für die FC-VI-Ports und Zonen für die Storage-Ports getrennt wird.

Bei den folgenden Schritten wird das Standard-Zoning für die MetroCluster-Konfiguration verwendet.

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Zoning für FC-VI-Ports"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Zoning für FibreBridge 6500N-Brücken oder FibreBridge 7500N- oder 7600N-Brücken unter Verwendung eines FC-Ports"]

link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Zoning für FibreBridge 7500N-Bridges unter Verwendung beider FC-Ports"]

.Schritte
. Erstellung der FC-VI-Zonen auf jedem Switch:
+
`zonecreate "QOSH1_FCVI_1", member;member ...`

+
In diesem Beispiel wird eine QOS FCVI-Zone mit den Ports 5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5 erstellt:

+
[listing]
----
Switch_A_1:admin> zonecreate "QOSH1_FCVI_1", "5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5"
----
. Konfigurieren Sie die Storage-Zonen auf jedem Switch.
+
Sie können das Zoning für die Fabric von einem Switch in der Fabric konfigurieren. Im folgenden Beispiel wird das Zoning auf Switch_A_1 konfiguriert.

+
.. Erstellen der Storage-Zone für jede Switch-Domäne in der Switch-Fabric:
+
`zonecreate name, member;member ...`

+
In diesem Beispiel wird eine Speicherzone für eine FibreBridge 7500N mit beiden FC-Ports erstellt. Die Zonen enthalten Anschlüsse 5,2;5,6;7,2;7,6;5,16:

+
[listing]
----
Switch_A_1:admin> zonecreate "MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1", "5,2;5,6;7,2;7,6;5,16"
----
.. Konfiguration in der ersten Switch-Fabric erstellen:
+
`cfgcreate config_name, zone;zone...`

+
In diesem Beispiel wird eine Konfiguration mit dem Namen CFG_1 und den beiden Zonen QOSH1_MC1_FAB_1_FCVI und MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1 erstellt

+
[listing]
----
Switch_A_1:admin> cfgcreate "CFG_1", "QOSH1_MC1_FAB_1_FCVI; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1"
----
.. Fügen Sie bei Bedarf Zonen zur Konfiguration hinzu:
+
`cfgadd config_namezone;zone...`

.. Aktivieren der Konfiguration:
+
`cfgenable config_name`

+
[listing]
----
Switch_A_1:admin> cfgenable "CFG_1"
----
.. Konfiguration speichern:
+
`cfgsave`

+
[listing]
----
Switch_A_1:admin> cfgsave
----
.. Validierung der Zoning-Konfiguration:
+
`zone --validate`

+
[listing]
----
Switch_A_1:admin> zone --validate
Defined configuration:
cfg: CFG_1 QOSH1_MC1_FAB_1_FCVI ; MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
zone: QOSH1_MC1_FAB_1_FCVI
5,0;5,1;5,4;5,5;7,0;7,1;7,4;7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2;5,6;7,2;7,6;5,16
Effective configuration:
cfg: CFG_1
zone: QOSH1_MC1_FAB_1_FCVI
5,0
5,1
5,4
5,5
7,0
7,1
7,4
7,5
zone: MC1_INIT_GRP_1_SITE_A_STK_GRP_1_TOP_FC1
5,2
5,6
7,2
7,6
5,16
------------------------------------
~ - Invalid configuration
* - Member does not exist
# - Invalid usage of broadcast zone
----






== Festlegen der ISL-Verschlüsselung auf Brocade 6510- oder G620-Switches

Bei Brocade 6510- oder G620-Switches kann optional die Brocade Verschlüsselungsfunktion auf den ISL-Verbindungen genutzt werden. Wenn Sie die Verschlüsselungsfunktion verwenden möchten, müssen Sie bei jedem Switch der MetroCluster-Konfiguration weitere Konfigurationsschritte durchführen.

.Bevor Sie beginnen
* Sie benötigen Brocade 6510 oder G620 Switches.
+

NOTE: Unterstützung der ISL-Verschlüsselung bei Brocade G620 Switches wird nur ab ONTAP 9.4 unterstützt.

* Sie müssen zwei Schalter aus derselben Fabric ausgewählt haben.
* Sie müssen die Brocade Dokumentation für Ihren Switch und Fabric Operating System Version überprüfen, um die Bandbreiten- und Port-Grenzwerte zu bestätigen.


Die Schritte müssen an beiden Switches in derselben Fabric ausgeführt werden.



=== Virtuelle Fabric wird deaktiviert

Um die ISL-Verschlüsselung einzustellen, muss die virtuelle Fabric auf allen vier in einer MetroCluster-Konfiguration verwendeten Switches deaktiviert werden.

.Schritte
. Deaktivieren Sie die virtuelle Fabric, indem Sie an der Switch-Konsole den folgenden Befehl eingeben:
+
`fosconfig --disable vf`

. Starten Sie den Switch neu.




=== Einstellen der Nutzlast

Nach der Deaktivierung der virtuellen Fabric müssen Sie die Nutzlastgröße oder die Datenfeldgröße auf beiden Switches in der Fabric festlegen.

Die Größe des Datenfelds darf 2048 nicht überschreiten.

.Schritte
. Deaktivieren Sie den Schalter:
+
`switchdisable`

. Konfigurieren und Festlegen der Nutzlast:
+
`configure`

. Stellen Sie die folgenden Schalterparameter ein:
+
.. Legen Sie den Fabric-Parameter wie folgt fest: `y`
.. Legen Sie die anderen Parameter fest, z. B. Domain, WWN-basierte persistente PID usw.
.. Festlegen der Datenfeldgröße: `2048`






=== Festlegen der Authentifizierungsrichtlinie

Sie müssen die Authentifizierungsrichtlinie und die zugehörigen Parameter festlegen.

Die Befehle müssen an der Switch-Konsole ausgeführt werden.

.Schritte
. Legen Sie den Authentifizierungsschlüssel fest:
+
.. Starten Sie den Setup-Prozess:
+
`secAuthSecret --set`

+
Mit diesem Befehl werden eine Reihe von Eingabeaufforderungen initiiert, auf die Sie in den folgenden Schritten reagieren:

.. Geben Sie den weltweiten Namen (WWN) des anderen Switch in der Fabric für den Parameter „Enter Peer WWN, Domain, Switch Name“ ein.
.. Geben Sie den Peer Secret für den Parameter „Enter Peer Secret“ ein.
.. Geben Sie das lokale Geheimnis für den Parameter „Ortsgeheimnis eingeben“ an.
.. Eingabe `Y` Für den Parameter „are you done“.
+
--
Das folgende Beispiel ist das Festlegen des Authentifizierungsgeheimnisses:

[listing]
----
brcd> secAuthSecret --set

This command is used to set up secret keys for the DH-CHAP authentication.
The minimum length of a secret key is 8 characters and maximum 40
characters. Setting up secret keys does not initiate DH-CHAP
authentication. If switch is configured to do DH-CHAP, it is performed
whenever a port or a switch is enabled.

Warning: Please use a secure channel for setting secrets. Using
an insecure channel is not safe and may compromise secrets.

Following inputs should be specified for each entry.

1. WWN for which secret is being set up.
2. Peer secret: The secret of the peer that authenticates to peer.
3. Local secret: The local secret that authenticates peer.

Press enter to start setting up secrets > <cr>

Enter peer WWN, Domain, or switch name (Leave blank when done): 10:00:00:05:33:76:2e:99
Enter peer secret: <hidden>
Re-enter peer secret: <hidden>
Enter local secret: <hidden>
Re-enter local secret: <hidden>

Enter peer WWN, Domain, or switch name (Leave blank when done):
Are you done? (yes, y, no, n): [no] yes
Saving data to key store... Done.
----
--


. Setzen Sie die Authentifizierungsgruppe auf 4:
+
`authUtil --set -g 4`

. Legen Sie den Authentifizierungstyp auf „dhchap“ fest:
+
`authUtil --set -a dhchap`

+
Das System zeigt die folgende Ausgabe an:

+
[listing]
----
Authentication is set to dhchap.
----
. Legen Sie die Authentifizierungsrichtlinie auf ein:
+
`authUtil --policy -sw on`

+
Das System zeigt die folgende Ausgabe an:

+
[listing]
----
Warning: Activating the authentication policy requires either DH-CHAP secrets or PKI certificates depending on the protocol selected. Otherwise, ISLs will be segmented during next E-port bring-up.
ARE YOU SURE  (yes, y, no, n): [no] yes
Auth Policy is set to ON
----




=== Aktivierung der ISL-Verschlüsselung bei Brocade Switches

Nachdem Sie die Authentifizierungsrichtlinie und das Authentifizierungsgeheimnis festgelegt haben, müssen Sie die ISL-Verschlüsselung auf den Ports aktivieren, damit sie wirksam wird.

.Über diese Aufgabe
* Diese Schritte sollten jeweils an der Switch-Fabric durchgeführt werden.
* Die Befehle müssen an der Switch-Konsole ausgeführt werden.


.Schritte
. Verschlüsselung auf allen ISL-Ports aktivieren:
+
`portCfgEncrypt --enable port_number`

+
Im folgenden Beispiel wird die Verschlüsselung auf den Ports 8 und 12 aktiviert:

+
`portCfgEncrypt --enable 8`

+
`portCfgEncrypt --enable 12`

. Schalter aktivieren:
+
`switchenable`

. Stellen Sie sicher, dass die ISL verfügbar ist und funktioniert:
+
`islshow`

. Vergewissern Sie sich, dass die Verschlüsselung aktiviert ist:
+
`portenccompshow`

+
Das folgende Beispiel zeigt, dass die Verschlüsselung auf den Ports 8 und 12 aktiviert ist:

+
[listing]
----

User Encryption
Port  configured     Active
----   ----------    ------
 8      yes          yes
 9      No           No
 10     No           No
 11     No           No
 12     yes          yes
----


Führen Sie in einer MetroCluster-Konfiguration alle Schritte auf den Switches in der anderen Fabric aus.
