---
permalink: install-fc/task_cable_storage_arrays_to_fc_switches_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, storage, arrays, fc, switches, configuration 
summary: Sie müssen Storage-Arrays mit FC-Switches verbinden, damit die ONTAP Systeme in der MetroCluster Konfiguration über mindestens zwei Pfade auf eine bestimmte Array-LUN zugreifen können. 
---
= Verkabelung der Storage Arrays mit FC-Switches in einer MetroCluster Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen Storage-Arrays mit FC-Switches verbinden, damit die ONTAP Systeme in der MetroCluster Konfiguration über mindestens zwei Pfade auf eine bestimmte Array-LUN zugreifen können.

.Bevor Sie beginnen
* Die Speicher-Arrays müssen eingerichtet sein, um ONTAP Array-LUNs zur Verfügung zu stellen.
* Die ONTAP Controller müssen mit den FC-Switches verbunden sein.
* Die ISLs müssen zwischen den FC Switches über die MetroCluster Standorte verkabelt sein.
* Sie müssen diese Aufgabe für jedes Storage Array an beiden MetroCluster-Standorten wiederholen.
* Sie müssen die Controller in einer MetroCluster Konfiguration über FC Switches mit den Storage-Arrays verbinden.


.Schritte
. Verbinden Sie die Speicher-Array-Ports mit FC-Switch-Ports.
+
Verbinden Sie an jedem Standort die redundanten Port-Paare im Storage Array mit FC Switches in alternativen Fabrics. Dies bietet Redundanz in den Pfaden für den Zugriff auf die Array LUNs.



.Verwandte Informationen
* Beim Konfigurieren von Switch Zoning können Sie festlegen, welche Array LUNs in der MetroCluster-Konfiguration von einem bestimmten ONTAP-System angezeigt werden können.
+
link:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.html["Wechseln Sie das Zoning in einer MetroCluster Konfiguration mit Array LUNs"]

* In einer MetroCluster-Konfiguration mit Array-LUNs müssen Sie die Speicher-Array-Ports verbinden, die ein redundantes Port-Paar bilden, mit alternativen FC-Switches.
+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_two_node_mcc_configuration.html["Beispiel für die Verkabelung von Storage Array-Ports mit FC Switches in einer MetroCluster-Konfiguration mit zwei Nodes"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_mcc_configuration.html["Beispiel für die Verkabelung von Storage Array-Ports mit FC-Switches in einer MetroCluster-Konfiguration mit vier Nodes"]

+
link:reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_mcc_configuration.html["Beispiel für die Verkabelung von Storage Array-Ports mit FC-Switches in einer MetroCluster-Konfiguration mit acht Nodes"]


