---
permalink: install-fc/task_verify_the_ha_state_of_components_is_mcc_or_mcc_2n_in_maintenance_mode.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, verify, ha, state, components, maintenance, mode 
summary: 'Bei der Konfiguration eines Storage-Systems in einer MetroCluster Konfiguration müssen Sie sicherstellen, dass der Hochverfügbarkeits- \(HA\)-Status des Controller-Moduls und der Gehäusekomponenten mcc oder mcc-2n lautet, damit diese Komponenten ordnungsgemäß booten.' 
---
= Überprüfen und Konfigurieren des HA-Status von Komponenten im Wartungsmodus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Konfiguration eines Storage-Systems in einer MetroCluster Konfiguration müssen Sie sicherstellen, dass der Hochverfügbarkeits- (HA) -Zustand des Controller-Moduls und der Gehäusekomponenten „mcc“ oder „mcc-2n“ lautet, damit diese Komponenten ordnungsgemäß booten.

.Bevor Sie beginnen
Das System muss sich im Wartungsmodus befinden.

.Über diese Aufgabe
Diese Aufgabe ist für Systeme, die vom Werk empfangen werden, nicht erforderlich.

.Schritte
. Zeigen Sie im Wartungsmodus den HA-Status des Controller-Moduls und des Chassis an:
+
`ha-config show`

+
Der richtige HA-Status hängt von Ihrer MetroCluster-Konfiguration ab.

+
|===


| Anzahl der Controller in der MetroCluster-Konfiguration | DER HA-Status für alle Komponenten sollte... 


 a| 
MetroCluster FC-Konfiguration mit acht oder vier Nodes
 a| 
mcc



 a| 
MetroCluster FC-Konfiguration mit zwei Nodes
 a| 
mcc-2n



 a| 
MetroCluster IP-Konfiguration
 a| 
Mccip

|===
. Wenn der angezeigte Systemzustand des Controllers nicht korrekt ist, setzen Sie den HA-Status für das Controller-Modul ein:
+
|===


| Anzahl der Controller in der MetroCluster-Konfiguration | Befehl 


 a| 
MetroCluster FC-Konfiguration mit acht oder vier Nodes
 a| 
`ha-config modify controller mcc`



 a| 
MetroCluster FC-Konfiguration mit zwei Nodes
 a| 
`ha-config modify controller mcc-2n`



 a| 
MetroCluster IP-Konfiguration
 a| 
`ha-config modify controller mccip`

|===
. Wenn der angezeigte Systemzustand des Chassis nicht korrekt ist, setzen Sie den HA-Status für das Chassis ein:
+
|===


| Anzahl der Controller in der MetroCluster-Konfiguration | Befehl 


 a| 
MetroCluster FC-Konfiguration mit acht oder vier Nodes
 a| 
`ha-config modify chassis mcc`



 a| 
MetroCluster FC-Konfiguration mit zwei Nodes
 a| 
`ha-config modify chassis mcc-2n`



 a| 
MetroCluster IP-Konfiguration
 a| 
`ha-config modify chassis mccip`

|===
. Booten des Node zu ONTAP:
+
`boot_ontap`

. Wiederholen Sie diese Schritte auf jedem Knoten der MetroCluster-Konfiguration.

