---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning 
summary: 'Sie müssen sicherstellen, dass sich die Inter-Switch-Links \ (ISLs\) in derselben Port-Gruppe befinden und das Zoning für die MetroCluster Konfigurationen konfigurieren, um die Switch-Fabrics erfolgreich zu teilen.' 
---
= Sicherstellen, dass sich ISLs in derselben Portgruppe befinden und Zoning konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen sicherstellen, dass sich die Inter-Switch-Links (ISLs) in derselben Port-Gruppe befinden und das Zoning für die MetroCluster-Konfigurationen konfigurieren, um die Switch Fabric erfolgreich zu teilen.

.Schritte
. Wenn sich die ISLs nicht in derselben Portgruppe befinden, verschieben Sie einen der ISL-Ports in dieselbe Port-Gruppe wie die andere.
+
Sie können alle verfügbaren Ports außer 32 bis 45 verwenden, die von der neuen MetroCluster-Konfiguration verwendet werden. Die empfohlenen ISL-Ports sind 46 und 47.

. Befolgen Sie die Schritte unter link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Konfigurieren des Zoning auf Brocade FC-Switches"] Abschnitt zum Aktivieren von Trunking und QoS-Zone.
+
Die Port-Nummern beim Teilen von Fabrics unterscheiden sich von denen im Abschnitt. Verwenden Sie bei der Freigabe die Ports 46 und 47 für die ISL-Ports. Wenn Sie Ihre ISL-Ports verschoben haben, müssen Sie das Verfahren in verwenden link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Konfiguration der E-Ports (ISL-Ports) auf einem Brocade FC-Switch"] Abschnitt zum Konfigurieren der Ports.

. [[ste3_Zones] Folgen Sie den Schritten im link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Konfigurieren der nicht-E-Ports auf dem Brocade-Switch"] Abschnitt zum Konfigurieren der nicht-E-Anschlüsse.
. Löschen Sie nicht die Zonen oder Zonensätze, die bereits in den Backend-Switches (für den 7-Mode Fabric MetroCluster) vorhanden sind, mit Ausnahme der Traffic Isolation (TI)-Zonen in ,Schritt 3.
. Befolgen Sie die Schritte unter link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html["Konfiguration der E-Ports (ISL-Ports) auf einem Brocade FC-Switch"] Abschnitt zum Hinzufügen der vom neuen MetroCluster benötigten Zonen zu den vorhandenen Zonensätzen.
+
Im folgenden Beispiel werden Befehle und eine Systemausgabe zum Erstellen der Zonen angezeigt:

+
[listing]
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----

