---
permalink: install-fc/task_download_and_install_the_cisco_fc_switch_rcf_files.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, download, install, cisco, fc, rcf, files 
summary: Sie müssen die RCF-Datei auf jeden Switch der MetroCluster-Fabric-Konfiguration herunterladen. 
---
= Herunterladen und Installieren der Cisco FC RCF-Dateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Referenz-Konfigurationsdatei (RCF) muss auf jeden Switch in der MetroCluster Fabric-Konfiguration heruntergeladen werden.

.Bevor Sie beginnen
Diese Aufgabe erfordert Dateiübertragungssoftware, wie FTP, Trivial File Transfer Protocol (TFTP), SFTP oder Secure Copy Protocol (SCP), um die Dateien auf die Switches zu kopieren.

.Über diese Aufgabe
Diese Schritte müssen bei jedem der Cisco FC Switches in der MetroCluster Fabric Konfiguration wiederholt werden.

Sie müssen die unterstützte Switch-Softwareversion verwenden.

https://hwu.netapp.com["NetApp Hardware Universe"]

Es gibt vier RCFs, eine für jeden der vier Switches in der MetroCluster Fabric-Konfiguration. Die korrekten RCFs für das verwendete Switch-Modell sind zu verwenden.

|===


| Switch | RCF 


 a| 
FC_Switch_A_1
 a| 
`NX3232_v1.80_Switch-A1.txt`



 a| 
FC_Switch_A_2
 a| 
`NX3232_v1.80_Switch-A2.txt`



 a| 
FC_Switch_B_1
 a| 
`NX3232_v1.80_Switch-B1.txt`



 a| 
FC_Switch_B_2
 a| 
`NX3232_v1.80_Switch-B2.txt`

|===

NOTE: Die angezeigten Ausgaben beziehen sich auf Cisco IP-Switches. Diese Schritte gelten jedoch auch für Cisco FC-Switches.

.Schritte
. Die Cisco FC RCFs stehen unter  https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab["MetroCluster RCF-Download-Seite"] zum Download bereit.
. Die RCFs auf die Switches kopieren.
+
.. Kopieren Sie die RCF-Datei auf den ersten Switch:
+
`copy sftp://__root@FTP-server-IP-address/tftpboot/switch-specific-RCF__ bootflash: vrf management`

+
In diesem Beispiel wird die `NX3232_v1.80_Switch-A1.txt` RCF vom SFTP-Server bei `10.10.99.99` auf den lokalen Bootflash kopiert. Die IP-Adresse Ihres TFTP/SFTP-Servers und der Dateiname der RCF, die installiert werden soll, sind zu verwenden.

+
[listing]
----
IP_switch_A_1# copy sftp://root@10.10.99.99/tftpboot/NX3232_v1.8T-X1_Switch-A1.txt bootflash: vrf management
root@10.10.99.99's password: password
sftp> progress
Progress meter enabled
sftp> get   /tftpboot/NX3232_v1.80_Switch-A1.txt /bootflash/NX3232_v1.80_Switch-A1.txt
Fetching /tftpboot/NX3232_v1.80_Switch-A1.txt to /bootflash/NX3232_v1.80_Switch-A1.txt
/tftpboot/NX3232_v1.80_Switch-A1.txt          100% 5141     5.0KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
IP_switch_A_1#
----
.. Wiederholen Sie den vorherigen Teilschritt für jeden der anderen drei Switches und achten Sie darauf, die passende RCF auf den entsprechenden Switch zu kopieren.


. Auf jedem Switch ist zu überprüfen, ob die RCF im jeweiligen  `bootflash`-Verzeichnis des Switches vorhanden ist:
+
`dir bootflash:`

+
Das folgende Beispiel zeigt, dass die Dateien auf IP_Switch_A_1 vorhanden sind:

+
[listing]
----
IP_switch_A_1# dir bootflash:
                  .
                  .
                  .
       5514    Jun 13 22:09:05 2017  NX3232_v1.80_Switch-A1.txt
                  .
                  .
                  .

Usage for bootflash://sup-local
 1779363840 bytes used
13238841344 bytes free
15018205184 bytes total
IP_switch_A_1#
----
. Die entsprechende RCF vom lokalen Bootflash in die laufende Konfiguration auf jedem Switch kopieren:
+
`copy bootflash:__switch-specific-RCF__.txt running-config`

. Die RCFs werden aus der laufenden Konfiguration in die Startkonfiguration auf jedem Switch kopiert:
+
`copy running-config startup-config`

+
Sie sollten eine Ausgabe wie die folgende sehen:

+
[listing]
----
IP_switch_A_1# copy bootflash:NX3232_v1.80_Switch-A1.txt running-config
IP_switch_A_1# copy running-config startup-config
----
. Schalter neu laden:
+
`reload`

+
[listing]
----
IP_switch_A_1# reload
----
. Wiederholen Sie die vorherigen Schritte auf den anderen drei Switches in der MetroCluster IP-Konfiguration.

