---
permalink: install-fc/task_install_the_license_for_us_array_luns_in_a_mcc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, license, array, luns, configuration 
summary: Sie müssen die V_StorageAttach-Lizenz auf jedem MetroCluster-Knoten installieren, den Sie mit Array LUNs verwenden möchten. Sie können Array-LUNs in einem Aggregat erst verwenden, wenn die Lizenz installiert ist. 
---
= Installieren der Lizenz für die Verwendung von Array-LUNs in einer MetroCluster-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die V_StorageAttach-Lizenz auf jedem MetroCluster-Knoten installieren, den Sie mit Array LUNs verwenden möchten. Sie können Array-LUNs in einem Aggregat erst verwenden, wenn die Lizenz installiert ist.

.Bevor Sie beginnen
* Das Cluster muss installiert sein.
* Sie müssen über den Lizenzschlüssel für die V_StorageAttach Lizenz verfügen.


Sie müssen für jeden Knoten, auf dem Sie die V_StorageAttach-Lizenz installieren möchten, einen separaten Lizenzschlüssel verwenden.

.Schritte
. Installieren Sie die V_StorageAttach-Lizenz.
+
`system license add`

+
Wiederholen Sie diesen Schritt für jeden Clusterknoten, auf dem Sie die Lizenz installieren möchten.

. Vergewissern Sie sich, dass die V_StorageAttach Lizenz auf allen erforderlichen Nodes in einem Cluster installiert ist.
+
`system license show`

+
Die folgende Ausgabe zeigt, dass die V_StorageAttach-Lizenz auf den Knoten von Cluster_A installiert ist:

+
[listing]
----

cluster_A::> system license show
Serial Number: nnnnnnnn
Owner: controller_A_1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage


Serial Number: llllllll
Owner: controller_A_2
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage
----

