---
permalink: install-fc/task_fmc_mcc_transition_cable_the_new_mcc_controllers_to_the_exist_fc_fabrics.html 
sidebar: sidebar 
keywords: cabling, metrocluster, fabric, installation, fc, controllers 
summary: An jedem Controller der Clustered ONTAP MetroCluster-Konfiguration müssen FC-VI-Adapter und HBAs mit spezifischen Ports der vorhandenen FC-Switches verbunden sein. 
---
= Verkabeln Sie die neuen MetroCluster Controller mit den vorhandenen FC-Fabrics
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf jedem Controller in der ONTAP MetroCluster-Konfiguration müssen der FC-VI-Adapter und HBAs mit spezifischen Ports der vorhandenen FC-Switches verkabelt sein.

.Schritte
. FC-VI- und HBA-Ports gemäß der folgenden Tabelle verkabeln:
+
|===


2+| Standort A 2+| Standort B 


| Verbinden Sie diese Site Mit einer Komponente und einem Port... | FC_Switch_A_1-Port... | Verbinden Sie diese Komponente und den Port für Standort B... | FC_Switch_B_1-Port... 


 a| 
Controller_A_1 FC-VI-Port 1
 a| 
32
 a| 
Controller_B_1 FC-VI-Port 1
 a| 
32



 a| 
Controller_A_1 HBA-Port 1
 a| 
33
 a| 
Controller_B_1 HBA-Port 1
 a| 
33



 a| 
Controller_A_1 HBA-Port 2
 a| 
34
 a| 
Controller_B_1 HBA-Port 2
 a| 
34



 a| 
Controller_A_2 FC-VI-Port 1
 a| 
35
 a| 
Controller_B_2 FC-VI-Port 1
 a| 
35



 a| 
Controller_A_2 HBA 1
 a| 
36
 a| 
Controller_B_2 HBA 1
 a| 
36



 a| 
Controller_A_2 HBA 2
 a| 
37
 a| 
Controller_B_2 HBA 2
 a| 
37

|===
. Verkabeln Sie jede FC-SAS-Bridge in der ersten Switch-Fabric mit den FC-Switches.
+
Die Anzahl der Bridges hängt von der Anzahl der SAS-Storage-Stacks ab.

+
|===


2+| Standort A 2+| Standort B 


| Diese Seite mit einer Brücke verbinden... | FC_Switch_A_1-Port... | Diese B-Brücke am Standort verkabeln... | FC_Switch_B_1-Port... 


 a| 
Bridge_A_1_38
 a| 
38
 a| 
Bridge_B_1_38
 a| 
38



 a| 
Bridge_A_1_39
 a| 
39
 a| 
Bridge_B_1_39
 a| 
39

|===
. Verkabeln Sie jede Bridge in der zweiten Switch-Fabric mit den FC-Switches.
+
Die Anzahl der Bridges hängt von der Anzahl der SAS-Storage-Stacks ab.

+
|===


2+| Standort A 2+| Standort B 


| Diese Seite mit einer Brücke verbinden... | FC_Switch_A_2-Port... | Diese B-Brücke am Standort verkabeln... | FC_Switch_B_2-Port... 


 a| 
Bridge_A_2_38
 a| 
38
 a| 
Bridge_B_2_38
 a| 
38



 a| 
Bridge_A_2_39
 a| 
39
 a| 
Bridge_B_2_39
 a| 
39

|===

