---
permalink: install-fc/task_cable_the_isl_between_the_mcc_sites_fabric_config.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, cable, isl, sites 
summary: 'Sie müssen die FC-Switches an jedem Standort über die Glasfaserverbindungen \ (ISLs\) verbinden, um die Switch-Fabrics zu bilden, die die MetroCluster Komponenten verbinden.' 
---
= Verkabelung der ISLs zwischen MetroCluster Standorten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die FC-Switches an jedem Standort über die ISLs (Fiber-Optic Inter-Switch Links) verbinden, um die Switch Fabrics zu bilden, die die MetroCluster Komponenten verbinden.

Dies muss für beide Switch Fabrics geschehen.

.Schritte
. Verbinden Sie die FC Switches an jedem Standort mit allen ISLs. Verwenden Sie dabei die Verkabelung in der Tabelle, die Ihrer Konfiguration und dem Switch-Modell entspricht.
+
** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html["Port-Zuweisungen für FC-Switches bei Verwendung von ONTAP 9.1 und höher"]
** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html["Port-Zuweisungen für FC-Switches bei Verwendung von ONTAP 9.0"]




link:concept_considerations_isls_mcfc.html["Überlegungen für ISLs"]
