---
permalink: install-fc/task_fcsw_configure_the_fc_switches_with_rcf_files_mcc.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, fc, switches, run, configuration, file 
summary: Wenn Sie die Konfiguration von Switches vereinfachen möchten, können Sie Referenzkonfigurationsdateien herunterladen und anwenden, die die vollständigen Switch-Einstellungen für bestimmte Konfigurationen bereitstellen. 
---
= Konfigurieren der FC-Switches durch Ausführen einer Konfigurationsdatei
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die Konfiguration von Switches vereinfachen möchten, können Sie Referenzkonfigurationsdateien herunterladen und anwenden, die die vollständigen Switch-Einstellungen für bestimmte Konfigurationen bereitstellen.

Die Referenzkonfigurationsdateien (RCFs) unterstützen keine Konfigurationen mit acht ISLs. Wenn Sie acht ISLs verwenden, müssen Sie die Switches manuell konfigurieren.

Die RCFs gelten für MetroCluster-Konfigurationen mit zwei, vier und acht Nodes. Diese Dateien konfigurieren die Fabric standardmäßig für die in-Order-Lieferung (IOD).

Die RCF-Download-Seite gibt die Anzahl der Knoten an, die von den verschiedenen Switch-Modellen unterstützt werden.
