---
permalink: install-fc/task_rack_the_hardware_components_in_a_mcc_configuration_with_array_luns.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, rack, hardware, components, array, luns 
summary: Sie müssen sicherstellen, dass die Hardwarekomponenten, die zum Einrichten einer MetroCluster Konfiguration erforderlich sind, wobei die Array-LUNs ordnungsgemäß im Rack verfügbar sind. 
---
= Führen Sie die Hardwarekomponenten in einer MetroCluster-Konfiguration mit Array-LUNs in Racks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen sicherstellen, dass die Hardwarekomponenten, die zum Einrichten einer MetroCluster Konfiguration erforderlich sind, wobei die Array-LUNs ordnungsgemäß im Rack verfügbar sind.

.Über diese Aufgabe
Sie müssen diese Aufgabe an beiden MetroCluster-Standorten ausführen.

.Schritte
. Planen Sie die Positionierung der MetroCluster Komponenten.
+
Die Rack-Fläche hängt vom Plattformmodell der Storage Controller, den Switch-Typen und der Anzahl der Festplatten-Shelf-Stacks in Ihrer Konfiguration ab.

. Richtig gemahlen.
. Die Storage Controller im Rack oder Schrank einbauen.
+

NOTE: AFF Systeme werden mit Array-LUNs nicht unterstützt.

+
https://docs.netapp.com/us-en/ontap-systems/["Installationsverfahren für Ihr AFF oder FAS System"]

. Installieren Sie die FC-Switches im Rack oder Schrank.

