---
permalink: install-fc/task_fmc_mcc_transition_reenable_the_switch_fabric_and_verify_operation.html 
sidebar: sidebar 
keywords: metrocluster, fabric, installation, reenable, switch, fabric, verify, operation 
summary: Sie müssen die FC Switch Fabric aktivieren und sicherstellen, dass die Switches und Geräte ordnungsgemäß funktionieren. 
---
= Aktivierung der Switch Fabric und Überprüfung des Betriebs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die FC Switch Fabric aktivieren und sicherstellen, dass die Switches und Geräte ordnungsgemäß funktionieren.

.Schritte
. Aktivieren Sie die Switches:
+
`switchCfgPersistentEnable`

+
Wenn dieser Befehl nicht verfügbar ist, sollte sich der Switch nach dem im Status aktiviert befinden `fastBoot` Befehl wird ausgegeben.

+
** Im folgenden Beispiel wird der von FC_Switch_A_1 ausgegebene Befehl angezeigt:
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentEnable
----
** Im folgenden Beispiel wird der von FC_Switch_B_1 ausgegebene Befehl angezeigt:
+
[listing]
----
FC_switch_B_1:admin> switchCfgPersistentEnable
----


. Stellen Sie sicher, dass die Switches online sind und alle Geräte ordnungsgemäß angemeldet sind:
+
`switchShow`

+
Im folgenden Beispiel wird der von FC_Switch_A_1 ausgegebene Befehl angezeigt:

+
[listing]
----
FC_switch_A_1:admin> switchShow
----
+
Im folgenden Beispiel wird der von FC_Switch_B_1 ausgegebene Befehl angezeigt:

+
[listing]
----
FC_switch_B_1:admin> switchShow
----
. Führen Sie das dienstprogramm fmc_dc aus, um sicherzustellen, dass das 7-Mode Fabric MetroCluster korrekt funktioniert.
+
Sie können Fehler im Zusammenhang mit Traffic Isolation (TI) Zoning und Trunking ignorieren.

. Wiederholen Sie die Aufgaben für die zweite Switch-Fabric.

