= Überlegungen bei der Verwendung von nicht gespiegelten Aggregaten
:allow-uri-read: 




== Überlegungen bei der Verwendung von nicht gespiegelten Aggregaten

Wenn Ihre Konfiguration nicht gespiegelte Aggregate umfasst, müssen potenzielle Zugriffsprobleme erkennen, die einem Switchover folgen.



== Überlegungen für nicht gespiegelte Aggregate bei Wartungsarbeiten, die einen Stromausfall erfordern

Wenn Sie aus Wartungsgründen eine Umschaltung durchführen möchten, die ein standortweites Herunterfahren erfordert, sollten Sie zuerst alle nicht gespiegelten Aggregate des Disaster-Standorts manuell offline schalten.

Wenn Sie keine nicht gespiegelten Aggregate offline schalten, so können Nodes am verbleibenden Standort aufgrund einer „Panik mit mehreren Festplatten“ möglicherweise ausfallen. Wenn die Umschaltung über nicht gespiegelte Aggregate offline erfolgt oder fehlt, ist die Verbindung zum Storage am DR-Standort verloren. Dies ist das Ergebnis eines Power Shutdowns oder eines Verlusts von ISLs.



== Überlegungen für nicht gespiegelte Aggregate und hierarchische Namespaces

Wenn Sie hierarchische Namespaces verwenden, sollten Sie den Verbindungspfad so konfigurieren, dass alle Volumes in diesem Pfad sich entweder nur auf gespiegelten Aggregaten oder nur auf nicht gespiegelten Aggregaten befinden. Wenn Sie eine Kombination aus nicht gespiegelten und gespiegelten Aggregaten im Verbindungspfad konfigurieren, ist möglicherweise nach der Umschaltung der Zugriff auf nicht gespiegelte Aggregate verhindert.



== Überlegungen für nicht gespiegelte Aggregate und CRS-Metadaten-Volume und Root-Volumes der Daten-SVM

Der Configuration Replication Service (CRS) Metadaten-Volume und Daten-SVM-Root-Volumes müssen sich in einem gespiegelten Aggregat befinden. Sie können diese Volumes nicht in ein nicht gespiegeltes Aggregat verschieben. Wenn sie sich auf einem nicht gespiegelten Aggregat befinden, sind über Switchover und Switchback-Vorgänge verhandelte Vorgänge gegen ein Veto eingelegt. Der Befehl MetroCluster Check gibt eine Warnung aus, wenn dies der Fall ist.



== Überlegungen für nicht gespiegelte Aggregate und SVMs

SVMs sollten nur auf gespiegelten Aggregaten oder nur auf nicht gespiegelten Aggregaten konfiguriert werden. Beim Konfigurieren einer Kombination aus nicht gespiegelten und gespiegelten Aggregaten kann ein Switchover von mehr als 120 Sekunden durchgeführt werden. So kann ein Datenausfall auftreten, wenn die nicht gespiegelten Aggregate nicht online geschaltet werden.



== Überlegungen für nicht gespiegelte Aggregate und SAN

In älteren Versionen als ONTAP 9.9 sollte sich eine LUN nicht auf einem nicht gespiegelten Aggregat befinden. Das Konfigurieren einer LUN auf einem nicht gespiegelten Aggregat kann zu einem Switchover von mehr als 120 Sekunden bei einem Ausfall der Daten führen.
