= 
:allow-uri-read: 


Bestimmte Plattformen verwenden ein VLAN für die MetroCluster IP Schnittstelle. Standardmäßig verwenden alle beiden Ports ein anderes VLAN: 10 und 20.

+ Falls unterstützt, können Sie auch ein anderes (nicht standardmäßiges) VLAN über 100 (zwischen 101 und 4095) mit dem Parameter im Befehl angeben `-vlan-id` `metrocluster configuration-settings interface create` .

+ die folgenden Plattformen unterstützen *nicht* den `-vlan-id` Parameter:

+ ** FAS8200 und AFF A300 ** AFF A320 ** FAS9000 und AFF A700 ** AFF C800, ASA C800, AFF A800 und ASA A800

+ Alle anderen Plattformen unterstützen den `-vlan-id` Parameter.

+ die Standard- und gültigen VLAN-Zuweisungen hängen davon ab, ob die Plattform den Parameter unterstützt `-vlan-id` :

+

[role="tabbed-block"]
====
.Plattformen, die <code>-vlan-</code> unterstützen
--
Standard-VLAN:

* Wenn der `-vlan-id` Parameter nicht angegeben wird, werden die Schnittstellen mit VLAN 10 für die „A“-Ports und VLAN 20 für die „B“-Ports erstellt.
* Das angegebene VLAN muss mit dem im RCF ausgewählten VLAN übereinstimmen.


Gültige VLAN-Bereiche:

* Standard-VLAN 10 und 20
* VLANs 101 und höher (zwischen 101 und 4095)


--
.Plattformen, die <code>-vlan-</code> nicht unterstützen
--
Standard-VLAN:

* Keine Angabe. Für die Schnittstelle muss kein VLAN auf der MetroCluster-Schnittstelle angegeben werden. Der Switch-Port definiert das verwendete VLAN.


Gültige VLAN-Bereiche:

* Alle VLANs werden beim Generieren der RCF nicht explizit ausgeschlossen. Die RCF warnt Sie, wenn das VLAN ungültig ist.


--
====