= 
:allow-uri-read: 


[CAUTION]
====
Wenn der HA-Status des Controller-Moduls und des Chassis falsch ist, können Sie die MetroCluster nicht konfigurieren, ohne den Node neu zu initialisieren. Sie müssen die Einstellung mit diesem Verfahren korrigieren und dann das System mit einem der folgenden Verfahren initialisieren:

* Führen Sie in einer MetroCluster IP-Konfiguration die Schritte in link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_restore_defaults.html["Systemstandardwerte auf einem Controller-Modul wiederherstellen"]aus.
* Führen Sie in einer MetroCluster FC-Konfiguration die Schritte in link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept_configure_the_mcc_software_in_ontap.html#restoring-system-defaults-and-configuring-the-hba-type-on-a-controller-module["Stellen Sie die Systemstandardeinstellungen wieder her und konfigurieren Sie den HBA-Typ auf einem Controller-Modul"]aus.


====
.Bevor Sie beginnen
Vergewissern Sie sich, dass sich das System im Wartungsmodus befindet.

.Schritte
. Zeigen Sie im Wartungsmodus den HA-Status des Controller-Moduls und des Chassis an:
+
`ha-config show`

+
Der richtige HA-Status hängt von Ihrer MetroCluster-Konfiguration ab.

+
|===


| MetroCluster-Konfigurationstyp | HA-Status für alle Komponenten... 


 a| 
MetroCluster FC-Konfiguration mit acht oder vier Nodes
 a| 
mcc



 a| 
MetroCluster FC-Konfiguration mit zwei Nodes
 a| 
mcc-2n



 a| 
MetroCluster IP-Konfiguration mit acht oder vier Nodes
 a| 
Mccip

|===
. Wenn der angezeigte Systemstatus des Controllers nicht korrekt ist, legen Sie den korrekten HA-Status für Ihre Konfiguration auf dem Controller-Modul fest:
+
|===


| MetroCluster-Konfigurationstyp | Befehl 


 a| 
MetroCluster FC-Konfiguration mit acht oder vier Nodes
 a| 
`ha-config modify controller mcc`



 a| 
MetroCluster FC-Konfiguration mit zwei Nodes
 a| 
`ha-config modify controller mcc-2n`



 a| 
MetroCluster IP-Konfiguration mit acht oder vier Nodes
 a| 
`ha-config modify controller mccip`

|===
. Wenn der angezeigte Systemstatus des Chassis nicht korrekt ist, legen Sie den korrekten HA-Status für Ihre Konfiguration auf dem Chassis fest:
+
|===


| MetroCluster-Konfigurationstyp | Befehl 


 a| 
MetroCluster FC-Konfiguration mit acht oder vier Nodes
 a| 
`ha-config modify chassis mcc`



 a| 
MetroCluster FC-Konfiguration mit zwei Nodes
 a| 
`ha-config modify chassis mcc-2n`



 a| 
MetroCluster IP-Konfiguration mit acht oder vier Nodes
 a| 
`ha-config modify chassis mccip`

|===
. Booten des Node zu ONTAP:
+
`boot_ontap`

. Wiederholen Sie dieses gesamte Verfahren, um den HA-Status auf jedem Node in der MetroCluster-Konfiguration zu überprüfen.

