---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Mit jeder Version werden neue Funktionen des ONTAP Mediators bereitgestellt.  Was ist neu? 
---
= Was ist neu in der ONTAP Mediator-Unterstützung für MetroCluster IP?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen MetroCluster IP-Funktionen und Verbesserungen für die ONTAP Mediator-Unterstützung.

Einzelheiten zu den Funktionen und Verbesserungen jeder Version von ONTAP Mediator finden Sie unterlink:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["Was ist neu in ONTAP Mediator?"^] Die

[cols="4,1"]
|===
| ONTAP Mediator-Fähigkeit | Verfügbar ab 


 a| 
Ab ONTAP Mediator 1.12.1 kann eine einzelne, mit HTTPS konfigurierte ONTAP Mediator Instanz die folgenden Konfigurationen gleichzeitig überwachen:

* Maximal zehn Vier-Knoten- oder fünf Acht-Knoten MetroCluster IP Konfigurationen bei Installation auf einem Host mit mindestens 8 CPU-Kernen und mindestens 16GB RAM.
* Eine Vier-Knoten MetroCluster IP Konfiguration und eine SnapMirror active sync Peer-Beziehung, wenn auf einem Host-Betriebssystem mit einer 2-Kern-CPU installiert.


link:../install-ip/concept_mediator_requirements.html#mediator-multiple-mccip["Weitere Informationen zur Unterstützung mehrerer MetroCluster IP-Konfigurationen durch ONTAP Mediator"].
 a| 
ONTAP 9.19.1



 a| 
ONTAP Mediator 1.12 unterstützt die Konfiguration eines ONTAP Mediators, der HTTPS für die Kommunikation in MetroCluster IP-Konfigurationen verwendet. HTTPS bietet erhöhte Sicherheit durch die Verschlüsselung ganzer Sitzungen mit SSL/TLS. Sie können einen ONTAP Mediator installieren, der ausschließlich das HTTPS-Protokoll nutzt. Das SCST-Paket wird bei dieser Installationsmethode nicht installiert. Weitere Informationen zur Installation eines ONTAP Mediators, der ausschließlich das HTTPS-Protokoll verwendet, finden Sie unter link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation["HTTPS- und iSCSI-Installationsoptionen für ONTAP Mediator"^].

link:../install-ip/concept_mediator_requirements.html#select-a-communication-protocol-for-ontap-mediator["Erfahren Sie mehr über die iSCSI- und HTTPS-Protokolle im ONTAP Mediator"].
 a| 
ONTAP 9.19.1



 a| 
IPv6 wird für ONTAP Mediator 1.11 oder höher in MetroCluster IP-Konfigurationen unterstützt.

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Einrichten des ONTAP Mediators für eine MetroCluster -IP-Konfiguration"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 bietet Unterstützung für die Verwaltung von bis zu zehn MetroCluster -IP-Konfigurationen mit einer einzigen ONTAP Mediator-Instanz.

link:../install-ip/concept_mediator_requirements.html["Bereiten Sie die Installation des ONTAP Mediators in einer MetroCluster -IP-Konfiguration vor."]
 a| 
ONTAP 9.18.1



 a| 
Bei einer Abschaltung in der Umgebung wird die mediatorgestützte automatische ungeplante Umschaltung (Mediator-Assisted Automatic ungeplante Switchover, MAUSO) unterstützt.

Wenn ein Standort aufgrund einer Abschaltung in der Umgebung ordnungsgemäß heruntergefahren wird, wird MAUSO ausgelöst.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["So unterstützt ONTAP Mediator automatische ungeplante Switchover"]
 a| 
ONTAP 9.13.1



 a| 
Erste Unterstützung für ONTAP Mediator in MetroCluster-IP-Konfigurationen
 a| 
ONTAP 9.7

|===