---
permalink: releasenotes/mcc-ip-config-platform-support.html 
sidebar: sidebar 
keywords: metrocluster, ip configuration, platform, support 
summary:  
---
= Neuerungen bei der Unterstützung der MetroCluster IP-Plattform
:allow-uri-read: 
:icons: font
:imagesdir: ./media/




== Plattform-Support

[cols="2*"]
|===
| Unterstützte Plattformen in MetroCluster IP-Konfigurationen | Verfügbar ab 


 a| 
AFF A150
 a| 
ONTAP 9.13.1 und höhere ONTAP-Versionen

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
AFF C250, AFF C400, AFF C800
 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA und neuere ONTAP Versionen.



 a| 
AFF A900
 a| 
ONTAP 9.10.1



 a| 
AFF A250
 a| 
ONTAP 9.8



 a| 
FAS500f
 a| 
ONTAP 9.8



 a| 
All-Flash-SAN-Array-Plattformen

In der MetroCluster-Dokumentation gelten die Informationen zu AFF-Modellen auf das entsprechende ASA-System. Beispielsweise gelten alle Kabel und weitere Informationen zum AFF A400 System auch für das ASA AFF A400 System.
 a| 
ONTAP 9.7



 a| 
AFF A320
 a| 
ONTAP 9.6P3



 a| 
AFF A220 UND FAS2750
 a| 
ONTAP 9.6



 a| 
AFF A300 UND FAS8200
 a| 
ONTAP 9.5

|===


== Switch-Support

[cols="2*"]
|===
| Broadcom-IP-Switches | Verfügbar ab 


 a| 
Quanta IX8
 a| 
ONTAP 9.6

|===
[cols="2*"]
|===
| Cisco IP-Switches | Verfügbar ab 


 a| 
Nexus 9336C-FX2
 a| 
ONTAP 9.9.1



 a| 
9336C
 a| 
ONTAP 9.8

|===
[cols="2*"]
|===
| NVIDIA-Switches | Verfügbar ab 


 a| 
Mehrere MC IP-Konfigurationen auf demselben NVIDIA SN2100-Switch
 a| 
ONTAP 9.14.1



 a| 
SN2100
 a| 
ONTAP 9.12.1

|===