---
permalink: releasenotes/mcc-new-features.html 
sidebar: sidebar 
keywords: new metrocluster features 
summary:  
---
= Neuerungen bei MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jede neue Version der Datenmanagement-Software ONTAP 9 verfügt über neue und erweiterte Funktionen, die die Leistungsfähigkeit, Managebarkeit und Performance von ONTAP MetroCluster Konfigurationen verbessern.

Details zu bekannten Problemen, Einschränkungen und Warnungen zu Upgrades, die ONTAP MetroCluster-Konfigurationen betreffen, finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP 9"^]. Sie müssen sich mit Ihrem NetApp Konto anmelden oder ein Konto erstellen, um auf die Versionshinweise zuzugreifen.

[cols="20,65,15"]
|===
| Unterstützte Funktionen in der MetroCluster-Konfiguration | Beschreibung und wo man mehr erfahren kann | Verfügbar ab 


 a| 
Fibrebridge-Firmware-Update mit Anmeldeinformationen
 a| 
Sie können die Firmware auf Fibrebridge Bridges mit Anmeldeinformationen aktualisieren, wenn sie vom Server zum Herunterladen des Firmware-Pakets erforderlich sind.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html["Aktualisieren Sie die Firmware auf einer FibreBridge-Bridge"]
 a| 
ONTAP 9.16.1



 a| 
Unterstützung der SVM-Datenmobilität für die Migration von MetroCluster Konfigurationen
 a| 
ONTAP unterstützt die folgenden MetroCluster SVM-Migrationen:

* Migration einer SVM zwischen einem nicht-MetroCluster HA-Paar und einer MetroCluster IP-Konfiguration
* Migrieren einer SVM zwischen zwei MetroCluster IP-Konfigurationen
* Migration einer SVM zwischen einer MetroCluster FC-Konfiguration und einer MetroCluster IP-Konfiguration


link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["SVM-Datenmobilität"^]
 a| 
ONTAP 9.16.1



 a| 
MD5-Authentifizierungsunterstützung für BGP-Peer-Gruppen
 a| 
ONTAP unterstützt MD5-Authentifizierung auf BGP-Peer-Gruppen zum Schutz von BGP-Sitzungen. Wenn MD5 aktiviert ist, können BGP-Sitzungen nur unter autorisierten Peers eingerichtet und verarbeitet werden, um mögliche Unterbrechungen der Sitzung durch einen nicht autorisierten Schauspieler zu verhindern.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["Konfigurieren Sie Virtual IP (VIP) LIFs"^]
 a| 
ONTAP 9.16.1



 a| 
MetroCluster IP-Unterstützung für End-to-End-Verschlüsselung
 a| 
Die End-to-End-Verschlüsselung wird auf den Systemen AFF A400, FAS8300 und FAS8700 unterstützt, um den Back-End-Datenverkehr, wie NVLOG- und Storage-Replizierungsdaten, zwischen den Standorten einer MetroCluster IP-Konfiguration zu verschlüsseln.

link:../maintain/task-configure-encryption.html["Konfigurieren Sie die End-to-End-Verschlüsselung in einer MetroCluster IP-Konfiguration"]
 a| 
ONTAP 9.15.1



 a| 
Erhöhung der Volume-Begrenzung bei MetroCluster IP Konfigurationen mit vier Nodes auf AFF A800 und AFF C800 Systemen
 a| 
In MetroCluster IP-Konfigurationen mit vier Nodes haben die folgenden Volume-Grenzwerte für AFF A800 und AFF C800 Systeme zugenommen:

* Die maximale Anzahl von FlexVol Volumes pro Aggregat stieg von 200 auf 625.
* Die maximale Anzahl von FlexVol Volumes pro Node stieg von 800 auf 1250.
* Die maximale Anzahl von FlexVol Volumes pro Hochverfügbarkeitspaar (HA) ist von 1600 auf 2500 angestiegen.

 a| 
ONTAP 9.15.1



 a| 
MetroCluster IP-Unterstützung für NVMe
 a| 
Das NVMe/TCP-Front-End-Hostprotokoll wird auf MetroCluster IP-Konfigurationen mit vier Nodes unterstützt.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["SAN-Konfigurationen in einer MetroCluster Umgebung"^]
 a| 
ONTAP 9.15.1



 a| 
Erhöhung der Volume-Begrenzung für MetroCluster IP Konfigurationen mit vier Nodes auf AFF A900 Systemen
 a| 
In MetroCluster IP-Konfigurationen mit vier Nodes haben die folgenden Volume-Einschränkungen für AFF A900-Systeme zugenommen:

* Die maximale Anzahl von FlexVol Volumes pro Aggregat stieg von 200 auf 625.
* Die maximale Anzahl von FlexVol Volumes pro Node stieg von 800 auf 1250.
* Die maximale Anzahl von FlexVol Volumes pro Hochverfügbarkeitspaar (HA) ist von 1600 auf 2500 angestiegen.

 a| 
ONTAP 9.14.1



 a| 
Unterstützung für S3 Objekt-Storage auf gespiegelten und nicht gespiegelten Aggregaten
 a| 
Sie können einen S3-Objekt-Storage-Server auf einer SVM in einem gespiegelten oder nicht gespiegelten Aggregat in MetroCluster IP- und FC-Konfigurationen aktivieren.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["S3-Unterstützung mit MetroCluster"^]
 a| 
ONTAP 9.14.1



 a| 
Unterstützung für die Bereitstellung eines S3-Buckets auf gespiegelten und nicht gespiegelten Aggregaten in einem MetroCluster-Cluster
 a| 
Sie können einen Bucket auf einem gespiegelten oder nicht gespiegelten Aggregat in MetroCluster Konfigurationen erstellen.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets["Erstellung eines ONTAP S3 Buckets auf einem gespiegelten oder nicht gespiegelten Aggregat in einer MetroCluster Konfiguration"^]
 a| 
ONTAP 9.14.1



 a| 
Wechsel von MetroCluster FC zu MetroCluster IP mit einem Shared Switch für MetroCluster IP und Ethernet Attached Storage
 a| 
Mit einem Shared Storage Switch können Sie unterbrechungsfrei von einer MetroCluster FC auf eine MetroCluster IP-Konfiguration umstellen.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Unterbrechungsfreier Übergang von einer MetroCluster FC- zu einer MetroCluster IP-Konfiguration (ONTAP 9.8 und höher)"]
 a| 
ONTAP 9.13.1



 a| 
Unterbrechungsfreier Wechsel von einer MetroCluster FC Konfiguration mit acht Nodes zu einer MetroCluster IP Konfiguration
 a| 
Workloads und Daten lassen sich unterbrechungsfrei von einer bestehenden MetroCluster FC Konfiguration mit acht Nodes auf eine neue MetroCluster IP Konfiguration übertragen.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html["Unterbrechungsfreier Wechsel von einer MetroCluster FC zu einer MetroCluster IP Konfiguration"]
 a| 
ONTAP 9.13.1



 a| 
Upgrades der MetroCluster IP-Konfiguration mit vier Nodes unter Verwendung von Switchover und Switchback
 a| 
Sie können Controller in einer MetroCluster IP Konfiguration mit vier Nodes mithilfe von Switchover und Switchback mit aktualisieren `system controller replace` Befehle.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html["Aktualisieren Sie Controller in einer MetroCluster IP-Konfiguration mit vier Nodes"]
 a| 
ONTAP 9.13.1



 a| 
Die automatische, vom Mediator unterstützte, ungeplante Umschaltung (MAUSO) wird für eine Abschaltung in der Umgebung ausgelöst
 a| 
Wenn ein Standort aufgrund einer Abschaltung in der Umgebung ordnungsgemäß heruntergefahren wird, wird MAUSO ausgelöst.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Wie der ONTAP Mediator die automatische ungeplante Umschaltung unterstützt"]
 a| 
ONTAP 9.13.1



 a| 
Unterstützung von MetroCluster IP-Konfigurationen mit acht Nodes
 a| 
Sie können die Controller und den Speicher in einer MetroCluster IP-Konfiguration mit acht Nodes aktualisieren, indem Sie die Konfiguration auf eine temporäre Konfiguration mit zwölf Nodes erweitern und dann die alten DR-Gruppen entfernen.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html["Aktualisieren einer MetroCluster IP-Konfiguration mit vier Nodes"]
 a| 
ONTAP 9.13.1



 a| 
Konvertierung der MetroCluster IP-Konfiguration in eine MetroCluster Switch-Konfiguration für gemeinsam genutzten Storage
 a| 
Sie können eine MetroCluster IP-Konfiguration in eine MetroCluster Switch-Konfiguration mit gemeinsamem Speicher konvertieren.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html["Ersetzen Sie einen IP-Switch"]
 a| 
ONTAP 9.13.1



 a| 
Die automatische Umschaltung von MetroCluster in einer MetroCluster IP-Konfiguration
 a| 
Sie können die automatische erzwungene Umschaltung von MetroCluster in einer MetroCluster IP-Konfiguration aktivieren. Bei dieser Funktion handelt es sich um eine Erweiterung der MAUSO-Funktion (Mediator-Assisted ungeplante Switchover).

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html["Einschränkungen bei der automatischen Umschaltung"]
 a| 
ONTAP 9.12.1



 a| 
S3 auf einer SVM auf einem nicht gespiegeltes Aggregat in einer MetroCluster IP-Konfiguration
 a| 
Sie können einen S3-Objekt-Storage-Server (ONTAP Simple Storage Service) auf einer SVM in einem nicht gespiegeltes Aggregat in einer MetroCluster IP-Konfiguration aktivieren.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster["S3-Unterstützung mit MetroCluster"^]
 a| 
ONTAP 9.12.1



 a| 
MetroCluster IP-Unterstützung für NVMe
 a| 
Das NVMe/FC-Protokoll wird auf MetroCluster IP-Konfigurationen mit vier Nodes unterstützt.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html["SAN-Konfigurationen in einer MetroCluster Umgebung"^]
 a| 
ONTAP 9.12.1



 a| 
IPsec-Unterstützung für Front-End-Hostprotokolle in MetroCluster-IP- und MetroCluster-Fabric-Attached-Konfigurationen
 a| 
IPsec-Unterstützung für das Front-End-Hostprotokoll (wie NFS und iSCSI) ist in MetroCluster IP- und MetroCluster-Fabric-Attached-Konfigurationen verfügbar.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html["Konfigurieren Sie IP-Sicherheit (IPsec) über die Verschlüsselung über das Netzwerk"^]
 a| 
ONTAP 9.12.1



 a| 
Wechseln Sie von einer MetroCluster FC-Konfiguration zu einer AFF A250- oder FAS500f MetroCluster IP-Konfiguration
 a| 
Sie können von einer MetroCluster FC Konfiguration auf eine AFF A250 oder FAS500f MetroCluster IP Konfiguration umsteigen.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move["Verschieben Sie die lokalen Cluster-Verbindungen"]
 a| 
ONTAP 9.11.1



 a| 
Konsistenzgruppen
 a| 
Konsistenzgruppen werden in MetroCluster-Konfigurationen unterstützt.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups["Konsistenzgruppen in MetroCluster Konfigurationen"^]
 a| 
ONTAP 9.11.1



 a| 
Vereinfachtes Controller Upgrade von Nodes in einer MetroCluster FC-Konfiguration
 a| 
Das Upgrade-Verfahren mit Switchover und Switchback wurde vereinfacht.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Aktualisieren Sie Controller in einer MetroCluster FC Konfiguration mithilfe von Switchover und Switchback"]
 a| 
ONTAP 9.10.1



 a| 
IP-Unterstützung für gemeinsame Links auf Layer 3
 a| 
MetroCluster IP-Konfigurationen können mit IP-gerouteten Back-End-Verbindungen (Layer 3) implementiert werden.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html["Überlegungen für Layer 3-Weitbereichs-Netzwerke"]
 a| 
ONTAP 9.9.1



 a| 
Unterstützung von MetroCluster Konfigurationen mit acht Nodes
 a| 
Permanente Cluster mit acht Nodes werden in IP- und Fabric-Attached MetroCluster-Konfigurationen unterstützt.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Installieren und verkabeln Sie MetroCluster-Komponenten"]
 a| 
ONTAP 9.9.1

|===