---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Mit jeder Version werden neue Funktionen des ONTAP Mediators bereitgestellt.  Was ist neu? 
---
= Was ist neu in ONTAP Mediator Unterstützung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit jeder Version werden neue Verbesserungen am ONTAP Mediator bereitgestellt.  Was ist neu?

Weitere Informationen zur Installation oder Aktualisierung von ONTAP Mediator in Ihrer MetroCluster-Konfiguration finden Sie unter link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html["Bereiten Sie die Installation des ONTAP Mediator-Dienstes vor"^].

[cols="75,25"]
|===


| ONTAP Mediator-Fähigkeit | ONTAP-Version 


 a| 
Bei einer Abschaltung in der Umgebung wird die mediatorgestützte automatische ungeplante Umschaltung (Mediator-Assisted Automatic ungeplante Switchover, MAUSO) unterstützt.

Wenn ein Standort aufgrund einer Abschaltung in der Umgebung ordnungsgemäß heruntergefahren wird, wird MAUSO ausgelöst.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["Wie der ONTAP Mediator die automatische ungeplante Umschaltung unterstützt"]
 a| 
ONTAP 9.13.1



 a| 
Erste Unterstützung für den ONTAP Mediator Service in MetroCluster IP Konfigurationen
 a| 
ONTAP 9.7

|===