---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Mit jeder Version werden neue Funktionen des ONTAP Mediators bereitgestellt.  Was ist neu? 
---
= Was ist neu in der ONTAP Mediator-Unterstützung für MetroCluster IP?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die neuen MetroCluster IP-Funktionen und Verbesserungen für die ONTAP Mediator-Unterstützung.

Einzelheiten zu den Funktionen und Verbesserungen jeder Version von ONTAP Mediator finden Sie unterlink:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html["Was ist neu in ONTAP Mediator?"^] Die

[cols="4,2"]
|===
| ONTAP Mediator-Fähigkeit | Verfügbar ab 


 a| 
IPv6 wird für ONTAP Mediator 1.11 oder höher in MetroCluster IP-Konfigurationen unterstützt.

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["Einrichten des ONTAP Mediators für eine MetroCluster -IP-Konfiguration"]
 a| 
ONTAP 9.18.1



 a| 
ONTAP Mediator 1.11 bietet Unterstützung für die Verwaltung von bis zu zehn MetroCluster -IP-Konfigurationen mit einer einzigen ONTAP Mediator-Instanz.

link:../install-ip/concept_mediator_requirements.html["Bereiten Sie die Installation des ONTAP Mediators in einer MetroCluster -IP-Konfiguration vor."]
 a| 
ONTAP 9.18.1



 a| 
Bei einer Abschaltung in der Umgebung wird die mediatorgestützte automatische ungeplante Umschaltung (Mediator-Assisted Automatic ungeplante Switchover, MAUSO) unterstützt.

Wenn ein Standort aufgrund einer Abschaltung in der Umgebung ordnungsgemäß heruntergefahren wird, wird MAUSO ausgelöst.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html["So unterstützt ONTAP Mediator automatische ungeplante Switchover"]
 a| 
ONTAP 9.13.1



 a| 
Erste Unterstützung für ONTAP Mediator in MetroCluster-IP-Konfigurationen
 a| 
ONTAP 9.7

|===