---
permalink: releasenotes/mcc-mediator-whats-new.html 
sidebar: sidebar 
keywords: metrocluster, mediator, new, release, update, install, 
summary: Mit jeder Version werden neue Funktionen des ONTAP Mediators bereitgestellt.  Was ist neu? 
---
= Was ist neu in ONTAP Mediator Unterstützung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit jeder Version werden neue Verbesserungen am ONTAP Mediator bereitgestellt.  Was ist neu?

[cols="75,25"]
|===


| ONTAP Mediator Version/Funktion | ONTAP-Version 


 a| 
ONTAP Mediator 1.5 ist für die Überwachung von MetroCluster IP-Konfigurationen verfügbar.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie den ONTAP Mediator-Dienst"^]
 a| 
ONTAP 9.12.1



 a| 
Die ONTAP Mediator-Software Version 1.4 wird in MetroCluster IP-Konfigurationen unterstützt.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html["Installieren oder aktualisieren Sie den ONTAP Mediator-Dienst"^]
 a| 
ONTAP 9.11.1



 a| 
Der ONTAP Mediator-Service kann die MetroCluster IP-Konfiguration bei der automatischen ungeplanten Umschaltung unterstützen, indem er ein physisch getrenntes Repository für Statusinformationen bereitstellt.
Konfiguration des ONTAP Mediator-Dienstes für ungeplante automatische Umschaltung
 a| 
ONTAP 9.7

|===