---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks 
summary: Sie sollten sicher sein, dass Sie das richtige Verfahren auswählen, wenn Sie MetroCluster-Hardwarewartungsaufgaben ausführen. 
---
= Hier finden Sie Verfahren für MetroCluster-Wartungsarbeiten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten sicher sein, dass Sie das richtige Verfahren auswählen, wenn Sie MetroCluster-Hardwarewartungsaufgaben ausführen.

.Wartungsverfahren für verschiedene Arten von MetroCluster Konfigurationen
* Wenn Sie über eine MetroCluster-IP-Konfiguration verfügen, lesen Sie die Verfahren in link:task-modify-ip-netmask-properties.html["Wartungsverfahren für MetroCluster IP-Konfigurationen"].
* Wenn Sie über eine MetroCluster FC-Konfiguration verfügen, lesen Sie die Verfahren in link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html["Wartungsverfahren für MetroCluster FC-Konfigurationen"].
* Wenn Sie das Verfahren im Abschnitt für Ihre Konfiguration nicht finden können, lesen Sie die Verfahren unter link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html["Wartungsverfahren für alle MetroCluster Konfigurationen"].


.Alle anderen Wartungsverfahren
Die folgende Tabelle enthält Links zu Verfahren im Zusammenhang mit der MetroCluster-Wartung, die sich nicht in den drei oben aufgeführten Abschnitten befinden:

|===


| Komponente | MetroCluster Typ (FC oder IP) | Aufgabe | Verfahren 


 a| 
ONTAP Software
 a| 
Beides
 a| 
ONTAP-Software-Upgrade
 a| 
https://docs.netapp.com/us-en/ontap/upgrade/index.html["Upgrade, Zurücksetzen oder Downgrade"^]



 a| 
Controller-Modul
 a| 
Beides
 a| 
FRU-Ersatz (einschließlich Controller-Module, PCIe-Karten, FC-VI-Karte usw.)


NOTE: Das Verschieben eines Storage-Controller-Moduls oder einer NVRAM-Karte zu den MetroCluster Storage-Systemen wird nicht unterstützt.
 a| 
https://docs.netapp.com/platstor/index.jsp["Dokumentation zu ONTAP Hardwaresystemen"^]



 a| 
Upgrades und Erweiterungen
 a| 
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster Upgrade und Erweiterung"]



 a| 
Übergang von FC- zu IP-Konnektivität
 a| 
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html["Umstellung von MetroCluster FC auf MetroCluster IP"]



 a| 
Festplatten-Shelf
 a| 
FC
 a| 
Alle anderen Shelf-Wartungsarbeiten Die Standardverfahren können verwendet werden.
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Aufrechterhaltung der Festplatten-Shelfs DS460C DS224C und DS212C"^]



 a| 
IP
 a| 
Alle Shelf-Wartungsarbeiten Die Standardverfahren können verwendet werden.

Wenn Sie Shelfs für ein nicht gespiegeltes Aggregat hinzufügen, lesen Sie http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html["Überlegungen bei der Verwendung von nicht gespiegelten Aggregaten"^]
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html["Aufrechterhaltung der Festplatten-Shelfs DS460C DS224C und DS212C"^]



 a| 
Beides
 a| 
Hot-Hinzufügen von IOM12-Shelfs zu einem Stack von IOM6-Shelfs
 a| 
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Hot-Adding-Shelfs mit IOM12-Modulen werden in einem Shelf-Stack mit IOM6-Modulen ausgeführt"^]

|===