---
permalink: maintain/reference_where_to_find_additional_information_mcc_service_guide.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, additional, information 
summary: Weitere Informationen zur Konfiguration, Bedienung und Überwachung einer MetroCluster Konfiguration finden Sie in der umfangreichen Dokumentation von NetApp. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zur Konfiguration, Bedienung und Überwachung einer MetroCluster Konfiguration finden Sie in der umfassenden Dokumentation von NetApp.

|===


| Informationsdaten | Betreff 


 a| 
link:../index.html["MetroCluster-Dokumentation"]
 a| 
* Alle MetroCluster-Informationen




 a| 
https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["Lösungsarchitektur und Design der NetApp MetroCluster Lösung"^]
 a| 
* Eine technische Übersicht über Konfiguration und Betrieb von MetroCluster
* Best Practices für die Konfiguration von MetroCluster.




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"]
 a| 
* Fabric-Attached MetroCluster-Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der FC-Switches
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html["Installation und Konfiguration von Stretch MetroCluster"]
 a| 
* Stretch-MetroCluster Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html["Installation und Konfiguration von MetroCluster IP"]
 a| 
* MetroCluster IP Architektur
* Verkabelung der MetroCluster IP-Konfiguration
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://www.netapp.com/support-and-training/documentation/["NetApp Dokumentation: Produktleitfäden und Ressourcen"^]
 a| 
* Monitoring der MetroCluster Konfiguration und Performance




 a| 
https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation und Konfiguration der MetroCluster Tiebreaker Software"]
 a| 
* Monitoring der MetroCluster Konfiguration mit der MetroCluster Tiebreaker Software




 a| 
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Kopienbasierte Transition"]
 a| 
* Migration von Daten von 7-Mode Storage-Systemen zu geclusterten Storage-Systemen


|===