---
permalink: maintain/reference_fb_replace_a_power_supply.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, replacing, failed, power, supply, module 
summary: Wenn sich der Status eines Netzteilmoduls auf die Bridge ändert, können Sie das Netzteilmodul entfernen und installieren. 
---
= Hot-Ersetzen eines fehlerhaften Netzteilmoduls
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn sich der Status eines Netzteilmoduls auf die Bridge ändert, können Sie das Netzteilmodul entfernen und installieren.

Sie können den Status eines Netzteilmoduls über die LEDs auf der Bridge anzeigen. Sie können den Status der Stromversorgungsmodule auch über die ExpressNAV GUI und die Bridge-CLI, über serielle Schnittstelle oder per Telnet anzeigen.

* Dieser Vorgang läuft unterbrechungsfrei (unterbrechungsfrei) und dauert etwa 15 Minuten.
* Sie benötigen das Admin-Passwort und den Zugriff auf einen FTP- oder SCP-Server.



NOTE: Das _ATTO FibreBridge Installations- und Bedienungshandbuch_ für Ihre Modellbrücke enthält weitere Informationen zu Management-Schnittstellen.

Sie können auf diesen und andere Inhalte auf der ATTO-Website über den Link auf der Seite ATTO Fibrebridge Beschreibung zugreifen.
