---
permalink: maintain/task_migrating_root_agg_with_adp.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, migrate, root, aggregate, adp, disks, partition, advanced, disk, partitioning 
summary: 'Sie können ein vorhandenes Root-Aggregat mit Advanced Disk Partitioning (ADP) unterbrechungsfrei migrieren.' 
---
= Migrieren Sie ein Root-Aggregat, das in MetroCluster IP-Konfigurationen mit ADP konfiguriert ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Ein vorhandenes Root-Aggregat, das mithilfe von Advanced Disk Partitioning (ADP) arbeitet, kann unterbrechungsfrei migriert werden, wenn dem Root-Aggregat der Speicherplatz knapp wird oder wenn SSDs mit niedriger Kapazität auf SSDs mit hoher Kapazität umsteigen möchten.

.Über diese Aufgabe
* Das lokale HA-Paar muss für Storage Failover aktiviert sein.
* Dieses Verfahren ist unterbrechungsfrei.
* Die Konfiguration sollte sich in einem stabilen Zustand befinden und Daten ohne häufige Unterbrechungen normal bereitstellen.
* Führen Sie während dieses Vorgangs keine Hardware-Upgrades oder andere Vorgänge durch, die zu Unterbrechungen führen könnten.
* Sie können immer nur ein Root-Aggregat migrieren. Versuchen Sie nicht, zwei Root-Aggregate gleichzeitig zu migrieren.


.Schritte
. [[Step_1, überprüfen Sie den Funktionszustand der Konfiguration]]Überprüfen Sie den Funktionszustand der Konfiguration.
+
.. Vergewissern Sie sich, dass die MetroCluster für jedes Cluster im normalen Modus konfiguriert ist:
 +
`metrocluster show`
+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vergewissern Sie sich, dass die Spiegelung auf jedem Knoten aktiviert ist:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Prüfen Sie, ob die MetroCluster-Komponenten ordnungsgemäß sind:
+
`metrocluster check run`

+
[listing]
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----
.. Vergewissern Sie sich, dass es keine Systemzustandsmeldungen gibt:
+
`system health alert show`



. Vergewissern Sie sich, dass das lokale HA-Paar für Storage Failover aktiviert ist:
+
`storage failover show`

+
Die Ausgabe sollte darauf hinweisen, dass ein Takeover für beide Knoten möglich ist:

+
[listing]
----
cluster_A::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------
cluster-01     cluster-02      true     Connected to cluster-02

cluster-02     cluster-01      true     Connected to cluster-01
2 entries were displayed.
----
. Löschen der Spare-Festplatten:
+
`run * disk zero spares`

. Ermitteln Sie die Root-Aggregatgröße:
+
`node run local aggr status -r <root_agg_name>`

+
Im folgenden Beispiel hat das Root-Aggregat zehn Disks in „pool0“ und zehn Disks in „Pool1“.

+
[listing]
----
cluster_A::*> node run local aggr status -r <root_agg_name>
Aggregate <root_agg_name> (online, raid_dp, mirrored, fast zeroed) (block checksums)
  Plex /<root_agg_name>/plex0 (online, normal, active, pool0)
    RAID group /<root_agg_name>/plex0/rg0 (normal, block checksums, max_wdbn 5767167)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      dparity   e2a.11.0.0P3    e2a   11  0   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      parity    e10b.11.3.1P3   e10b  11  1   NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.2P3    e2a   11  2   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.3P3    e2a   11  3   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e2a.11.0.4P3    e2a   11  4   NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.5P3   e10b  11  5   NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.12P3  e10b  11  12  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.13P3  e10b  11  13  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.14P3  e10b  11  14  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.15P3  e10b  11  15  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

  Plex /<root_agg_name>/plex2 (online, normal, active, pool1)
    RAID group /<root_agg_name>/plex2/rg0 (normal, block checksums, max_wdbn 5767167)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      dparity   0m.i2.2L1P3     0m    22  5          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      parity    0m.i1.0L36P3    0m    22  14         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i2.2L18P3    0v    22  12         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i2.3L17P3    0v    22  2          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.0L25P3    0v    22  13         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.0L40P3    0v    22  4          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i1.1L39P3    0m    22  17         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i1.1L46P3    0m    22  15         1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0m.i2.3L13P3    0m    22  0          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      0v.i1.1L26P3    0v    22  1          1 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

cluster_A::*>
----
. Weisen Sie die Container-Festplatten zu.
+
Vergewissern Sie sich vor der Zuweisung der Festplatten, dass jedem Node die empfohlene Anzahl an Ersatzlaufwerken zugewiesen ist. Diese Laufwerke werden vor der Migration des Root-Aggregats partitioniert. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_drive_assignment.html["Überlegungen zur automatischen Laufwerkszuweisung und zu ADP-Systemen in ONTAP 9.4 und höher"].

+
Führen Sie den folgenden Befehl aus, um die Festplatten zuzuweisen:

+
`storage disk assign -disklist 1.11.0,1.11.1,…  -owner cluster-01 -pool 0`

. Identifizieren Sie die Größe der Root-Partition.
+
Die Größe der Stammpartition hängt von der Anzahl der verfügbaren Festplatten für die Partition auf jedem Knoten ab. NetApp empfiehlt, dass mindestens 12 Laufwerke pro Node für die Partition verfügbar sind.

+
Sie können die folgende Tabelle verwenden, um das Root-Aggregat-Layout zu bestimmen:

+
[cols="25,75"]
|===
| Anzahl der zu partitionenden Festplatten | Root-Aggregat-Layout 


| 4 Festplatten pro Node | 2 Datenlaufwerke und 2 Paritätslaufwerke 


| 12 Festplatten pro Node | 8 Datenlaufwerke, 2 Paritätslaufwerke und 2 Ersatzlaufwerke 


| 24 Festplatten pro Node | 20 Datenlaufwerke, 2 Paritätslaufwerke und 2 Spare-Festplatten 
|===
+
Um die Größe der Root-Partition zu ermitteln, teilen Sie die Gesamtzahl der 4-KB-Blöcke gleichmäßig auf alle Datenlaufwerke.

+
Wenn Sie beispielsweise ein Root-Aggregat-Layout mit 8 Datenlaufwerken, 2 Paritätslaufwerken und 2 Spare-Laufwerken mit einer Root-Aggregat-Größe von 112958795 Blöcken haben, müssen Sie 112958795 durch 8 dividieren, um die Größe der Root-Partition zu erhalten.

+
(112958795 / 8) = 14119849.375

+
Nach der Aufrundung dieser Zahl ist die Root-Partitionsgröße 14119850.

. Partitionieren Sie jede Festplatte im Root-Aggregat:
+
`cluster_A*> disk partition -n 3 -i 3 -b <root_partition_size> <disk_id>`

. Weisen Sie die Partitionen zu.
+

NOTE: In Systemen mit ADP werden Aggregate mithilfe von Partitionen erstellt, in denen jedes Laufwerk in die Partitionen P1, P2 und P3 partitioniert wird.

+
.. Weisen Sie die P3-Partition demselben Knoten zu, dem die Container-Festplatte gehört:
+
`storage disk assign -disk <disk_id> -root true -pool 0 -owner cluster-01`

.. Weisen Sie die P1 Partition dem System mit der niedrigeren System-ID-Nummer im HA-Paar zu:
+
`storage disk assign -disk <disk_id> -data1 true -pool 0 -owner cluster-01`

.. Weisen Sie die P2-Partition dem System mit der höheren System-ID-Nummer im HA-Paar zu:
+
`storage disk assign -disk <disk_name> -data2 true -pool 0 -owner cluster-02`

+
Wiederholen Sie diesen Schritt für jede partitionierte Festplatte.



. Bestätigen Sie, dass eine Übernahme möglich ist:
+
`storage failover show`

+
[listing]
----
cluster_A::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ---------------------------
cluster-01     cluster-02      true     Connected to cluster-02

cluster-02     cluster-01      true     Connected to cluster-01
2 entries were displayed.
----
. Migrieren Sie das Root-Aggregat.
+
Führen Sie für jeden Node die Migration durch, indem Sie die Liste der Festplatten in Pool0 und den Ziel-RAID-Typ als Parameter angeben:

+
`system node migrate-root -node cluster-01 -disklist <pool0_disk_list> -raid-type <target_raid_type>`

+
Wenn das Root-Aggregat für „Cluster-01“ beispielsweise aus zehn Festplatten mit „RAID_dp“ besteht, migriert der folgende Befehl das Root-Aggregat:

+
[listing]
----
system node migrate-root -node cluster-01 -disklist 1.11.1.P3,1.11.2.P3,1.11.3.P3,1.11.4.P3,1.11.5.P3,1.11.6.P3,1.11.7.P3,1.11.8.P3,1.11.9.P3,1.11.10.P3 -raid-type raid_dp

Warning: This is a partially automated and guided procedure for migrating the
         root aggregate on the node "cluster-01".
         Negotiated switchover is about to start.
         Warning: This operation will create a new root aggregate and replace
         the existing root on the node "cluster-01". The existing root
         aggregate will be discarded.
Do you want to continue? {y|n}: y

Info: Started migrate-root job. Run "job show -id 51 -instance" command to
      check the progress of the job.
      Once the job is complete, mirror the root aggregate using the "storage
      aggregate mirror" command
----
+

IMPORTANT: Wenn die Anzahl der Festplatten nicht ausreicht, fügen Sie weitere Festplatten hinzu oder wählen Sie einen anderen RAID-Typ.

+
Der Migrationsprozess kann mehrere Minuten dauern. Während der Migration wird der Node mehrmals neu gebootet. Auf den anderen Nodes treten möglicherweise Fehler auf. Sie können diese Fehler einfach ignorieren und warten, bis der Migrationsprozess abgeschlossen ist.

. Überwachen Sie optional den Migrationsfortschritt.
+
Führen Sie vom zweiten Standort aus Folgendes aus:

+
`job show -id 51 -instance`

. Aktivieren Sie die automatische RAID-Partitionierung für alle MetroCluster IP-Knoten erneut:
+
`storage raidlm policy modify -node <node> -policy-name auto_partition_ssds_post_init -policy-type Shared-Disk -is-enable true`

. Überprüfen Sie, ob die Migration erfolgreich war:
+
`run local aggr status -r <root_agg_name>`

+
[listing]
----
cluster_A::*> node run local aggr status -r <root_agg_name>
Aggregate <root_agg_name> (online, raid0, fast zeroed) (block checksums)
  Plex /<root_agg_name>/plex0 (online, normal, active, pool0)
    RAID group /<root_agg_name>/plex0/rg0 (normal, block checksums, max_wdbn 6127616)

      RAID Disk Device  HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------  ------------- ---- ---- ---- ----- --------------    --------------
      data      e2a.11.0.16P3   e2a   11  16  NV:A   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)
      data      e10b.11.3.17P3  e10b  11  17  NV:B   0 SSD-NVM   N/A 23956/6132864     23964/6134912 (fast zeroed)

cluster_A::*>
----
. Wiederholen Sie den Schritt bis <<step_1,Überprüfen Sie den Funktionszustand der Konfiguration>>.

