---
permalink: maintain/task_fb_hot_add_a_disk_shelf_install_7500n.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, hot, add, disk, shelf 
summary: Sie können ein Platten-Shelf während des laufenden Betrieb hinzufügen, wenn Sie die Storage-Kapazität erhöhen möchten, ohne die Performance zu beeinträchtigen. 
---
= Fügen Sie ein SAS-Platten-Shelf zu einem Stack von SAS-Platten-Shelves hinzu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Platten-Shelf während des laufenden Betrieb hinzufügen, wenn Sie die Storage-Kapazität erhöhen möchten, ohne die Performance zu beeinträchtigen.



== Schritt 1: Bereiten Sie das Hot-Add eines SAS-Platten-Shelfs vor

Um das Hot-Hinzufügen eines SAS-Platten-Shelfs vorzubereiten, müssen Sie Dokumente sowie die Festplatten- und Festplatten-Shelf-Firmware herunterladen.

.Bevor Sie beginnen
* Stellen Sie sicher, dass Ihr System eine unterstützte Konfiguration ist und eine unterstützte Version von ONTAP ausführt.
* Überprüfen Sie, ob auf allen Festplattenlaufwerken und Festplatten-Shelfs im System die neueste Firmware-Version ausgeführt wird.
+
Möglicherweise möchten Sie die Festplatten- und Shelf-Firmware in der gesamten MetroCluster Konfiguration aktualisieren, bevor Sie Shelfs hinzufügen.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["Upgrade, Zurücksetzen oder Downgrade"]



.Schritte
. Laden Sie folgende Dokumente von der NetApp Support-Website herunter oder lesen Sie sie:
+
** https://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool"]
** Das _Installation Guide_ für Ihr Festplatten-Shelf-Modell.


. Überprüfen Sie, ob das Festplatten-Shelf, das Sie hinzufügen, unterstützt wird.
+
https://mysupport.netapp.com/matrix["Interoperabilitäts-Matrix-Tool"^]

. Laden Sie die neueste Festplatten- und Festplatten-Shelf-Firmware herunter:
+

NOTE: In diesem Schritt schließen Sie nur den Download-Teil der Anweisungen ab. Sie müssen die Schritte in befolgen<<step_2_hot_add_shelf,Fügen Sie während des laufenden Betrieb ein Platten-Shelf hinzu>>, um das Festplatten-Shelf zu installieren.

+
.. Laden Sie die Festplatten-Firmware herunter, und erstellen Sie eine Kopie der Firmware-Anleitungen für die Festplatte, um sie später zu verwenden.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp Downloads: Festplatten-Firmware"^]

.. Laden Sie die Festplatten-Shelf-Firmware herunter und erstellen Sie eine Kopie der Anleitungen für die Festplatten-Shelf-Firmware, um sie später zu verwenden.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp Downloads: Festplatten-Shelf Firmware"^]







== Schritt 2: Hinzufügen eines Festplatten-Shelfs während des laufenden Betrieb

Gehen Sie wie folgt vor, um einem Stack im laufenden Betrieb ein Festplatten-Shelf hinzuzufügen.

.Bevor Sie beginnen
* Überprüfen Sie, ob das System alle Anforderungen in erfüllt<<prepare_to_hot_add_disk,Bereiten Sie das Hot-Add von SAS-Platten-Shelves vor>>.
* Vergewissern Sie sich, dass Ihre Umgebung eines der folgenden Szenarien erfüllt, bevor Sie ein Shelf während des laufenden Betrieb hinzufügen:
+
** Sie haben zwei FibreBridge 7500N-Bridges mit einem Stack von SAS-Platten-Shelves verbunden.
** Zwei FibreBridge 7600N-Bridges sind mit einem Stack aus SAS-Platten-Shelfs verbunden.
** Sie verfügen über eine FibreBridge 7500N und eine FibreBridge 7600N, die mit einem Stack aus SAS-Platten-Shelfs verbunden ist.




.Über diese Aufgabe
* Dieses Verfahren dient zum Hinzufügen eines Festplatten-Shelfs zum letzten Festplatten-Shelf im Stack.
+
Dieses Verfahren setzt die Annahme ein, dass das letzte Festplatten-Shelf eines Stacks von IOM A mit der Bridge A und von IOM B zu Bridge B verbunden ist

* Hierbei handelt es sich um ein unterbrechungsfreies Verfahren.
* Sie sollten an jedem Standort die gleiche Anzahl an Platten-Shelfs hinzufügen.
* Wenn Sie mehrere Festplatten-Shelfs im laufenden Betrieb hinzufügen, müssen Sie ein Festplatten-Shelf gleichzeitig im laufenden Betrieb hinzufügen.
+
Jedes Paar Brücken FibreBridge 7500N oder 7600N kann bis zu vier Stapel unterstützen.



[CAUTION]
====
Zum Hot-Hinzufügen eines Festplatten-Shelfs müssen Sie die Festplatten-Firmware auf dem Hot-Added Disk Shelf aktualisieren, indem Sie die ausführen `storage disk firmware update` Befehl im erweiterten Modus. Diese Ausführung dieses Befehls kann den Betrieb unterbrechen, wenn die Firmware auf vorhandenen Festplattenlaufwerken im System eine ältere Version ist.

Falls Sie ein SAS-Kabel an den falschen Port anschließen, müssen Sie nach dem Abziehen des Kabels von einem SAS-Port mindestens 120 Sekunden warten, bevor Sie das Kabel an einen anderen SAS-Port anschließen. Wenn Sie dies nicht tun, erkennt das System nicht, dass Sie das Kabel an einen anderen Port verlegt haben.

====
.Schritte
. Richtig gemahlen.
. Überprüfen Sie die Festplatten-Shelf-Konnektivität von der Systemkonsole eines Controllers:
+
`sysconfig -v`

+
Die Ausgabe ähnelt der folgenden Ausgabe:

+
** Jede Bridge in einer separaten Zeile und unter jedem FC-Port, zu dem sie sichtbar ist, führt zum Beispiel: Wenn ein Platten-Shelf zu einer Reihe von FibreBridge 7500N-Bridges hinzugefügt wird, ergibt dies folgende Ausgabe:
+
[listing]
----
FC-to-SAS Bridge:
cisco_A_1-1:9.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100189
cisco_A_1-2:1.126L0: ATTO  FibreBridge7500N 2.10  FB7500N100162
----
** Jedes Festplatten-Shelf in einer separaten Zeile unter jedem FC-Port, zu dem es sichtbar ist:
+
[listing]
----
Shelf   0: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
Shelf   1: IOM6  Firmware rev. IOM6 A: 0173 IOM6 B: 0173
----
** Jedes Laufwerk in einer separaten Zeile unter jedem FC-Port, zu dem es sichtbar ist:
+
[listing]
----
cisco_A_1-1:9.126L1   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
cisco_A_1-1:9.126L2   : NETAPP   X421_HCOBD450A10 NA01 418.0GB (879097968 520B/sect)
----


. Überprüfen Sie, ob die automatische Festplattenzuordnung im System von der Konsole eines der Controller aktiviert ist:
+
`storage disk option show`

+
Die Richtlinie für die automatische Zuweisung wird in der Spalte „Automatische Zuweisung“ angezeigt.

+
[listing]
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----
. Wenn die automatische Festplattenzuordnung im System nicht aktiviert ist oder Festplattenlaufwerke im selben Stack zu beiden Controllern gehören, weisen Sie den entsprechenden Pools Festplattenlaufwerke zu.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["Festplatten- und Aggregatmanagement"]

+
[NOTE]
====
** Wenn Sie einen einzelnen Stack an Platten-Shelfs auf zwei Controller aufteilen, muss die automatische Zuweisung einer Festplatte vor der Zuweisung der Festplatteneigentümer deaktiviert werden. Andernfalls werden die verbleibenden Festplatten beim Zuweisen eines einzelnen Festplattenlaufwerks möglicherweise automatisch demselben Controller und Pool zugewiesen.
+
Der `storage disk option modify -node <node-name> -autoassign off` Befehl deaktiviert die automatische Zuweisung von Festplatten.

** Sie können erst dann Laufwerke zu Aggregaten oder Volumes hinzufügen, nachdem Sie die Festplatten- und Festplatten-Shelf-Firmware aktualisiert haben.


====
. Aktualisieren Sie die Festplatten-Shelf-Firmware auf die aktuelle Version, indem Sie die Anweisungen für die heruntergeladene Firmware verwenden.
+
Sie können die Befehle des Verfahrens über die Systemkonsole eines der beiden Controller ausführen.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp Downloads: Festplatten-Shelf Firmware"]

. Installieren und verkabeln Sie das Festplatten-Shelf:
+

NOTE: Erzwingen Sie keinen Anschluss in einen Port. Die Mini-SAS-Kabel sind codiert; wenn sie korrekt in einen SAS-Port ausgerichtet sind, klickt das SAS-Kabel an ihre Stelle und die Festplatten-Shelf-SAS-Port LNK LED leuchtet grün.für Platten-Shelves setzen Sie einen SAS-Kabelanschluss ein, wobei die Zuglasche nach oben (auf der Oberseite des Anschlusses) ausgerichtet ist.

+
.. Installieren Sie das Festplatten-Shelf, schalten Sie es ein und legen Sie die Shelf-ID fest.
+
Das _Installation Guide_ für Ihr Festplatten-Shelf-Modell enthält detaillierte Informationen zur Installation von Festplatten-Shelfs.

+

NOTE: Sie müssen das Festplatten-Shelf aus- und wieder einschalten und die Shelf-IDs für jedes SAS-Festplatten-Shelf innerhalb des gesamten Storage-Systems eindeutig aufbewahren.

.. Trennen Sie das SAS-Kabel vom Port IOM B des letzten Shelfs im Stack, und schließen Sie es dann wieder an den gleichen Port im neuen Shelf an.
+
Das andere Ende dieses Kabels bleibt mit Brücke B. verbunden

.. Schalten Sie das neue Festplatten-Shelf in Reihe, indem Sie die neuen Shelf-IOM-Ports (von IOM A und IOM B) mit den letzten Shelf-IOM-Ports (von IOM A und IOM B) verkabeln.


+
Das _Installation Guide_ für Ihr Festplatten-Shelf-Modell bietet detaillierte Informationen zum Verkettung von Platten-Shelfs in Reihe.

. Aktualisieren Sie die Festplatten-Firmware von der Systemkonsole auf die aktuellste Version.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp Downloads: Festplatten-Firmware"]

+
.. Wechseln Sie zur erweiterten Berechtigungsebene: +
`set -privilege advanced`
+
Sie müssen mit reagieren `*y*` Wenn Sie dazu aufgefordert werden, den erweiterten Modus fortzusetzen und die Eingabeaufforderung für den erweiterten Modus (*>) anzuzeigen.

.. Aktualisieren Sie die Festplatten-Firmware von der Systemkonsole aus auf die aktuellste Version: +
`storage disk firmware update`
.. Zurück zur Administrator-Berechtigungsebene: +
`set -privilege admin`
.. Wiederholen Sie die vorherigen Unterschritte auf dem anderen Controller.


. Überprüfen Sie den Betrieb der MetroCluster-Konfiguration in ONTAP:
+
.. Prüfen Sie, ob das System multipathed ist:
+
`node run -node <node-name> sysconfig -a`

.. Überprüfen Sie auf beiden Clustern auf alle Zustandswarnmeldungen: +
`system health alert show`
.. Bestätigen Sie die MetroCluster-Konfiguration und den normalen Betriebsmodus: +
`metrocluster show`
.. Führen Sie eine MetroCluster-Prüfung durch: +
`metrocluster check run`
.. Ergebnisse der MetroCluster-Prüfung anzeigen:
+
`metrocluster check show`

.. Prüfen Sie, ob auf den Switches Zustandswarnmeldungen vorliegen (falls vorhanden):
+
`storage switch show`

.. Führen Sie Active IQ Config Advisor aus.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"]

.. Überprüfen Sie nach dem Ausführen von Config Advisor die Ausgabe des Tools und befolgen Sie die Empfehlungen in der Ausgabe, um die erkannten Probleme zu beheben.


. Wenn Sie beim Hinzufügen von mehr als einem Festplatten-Shelf während des laufenden Betrieb die vorherigen Schritte für jedes Festplatten-Shelf wiederholen, das Sie Hot-hinzufügen.

