---
permalink: maintain/task_power_off_an_entire_mcc_fc_configuration.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, power, off, entire, metrocluster, fc, configuration 
summary: Sie müssen die gesamte MetroCluster FC-Konfiguration und alle Geräte ausschalten, bevor die Wartungsarbeiten oder Standortwechsel beginnen können. 
---
= Herunterfahren einer gesamten MetroCluster FC-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die gesamte MetroCluster FC-Konfiguration und alle Geräte ausschalten, bevor die Wartungsarbeiten oder Standortwechsel beginnen können.


NOTE: Ab ONTAP 9.8 beginnt der `*storage switch*` Befehl wird durch ersetzt `*system switch*`. Die folgenden Schritte zeigen das `*storage switch*` Befehl, aber wenn Sie ONTAP 9.8 oder höher ausführen, der `*system switch*` Befehl ist bevorzugt.

. Überprüfen Sie die MetroCluster Konfiguration von beiden Standorten in der MetroCluster Konfiguration.
+
.. Bestätigen Sie die MetroCluster-Konfiguration und den normalen Betriebsmodus. +
`*metrocluster show*`
.. Überprüfen Sie die Verbindung zu den Festplatten, indem Sie auf einem der MetroCluster-Knoten den folgenden Befehl eingeben: +
`*run local sysconfig -v*`
.. Führen Sie den folgenden Befehl aus: +
`*storage bridge show*`
.. Führen Sie den folgenden Befehl aus: +
`*storage port show*`
.. Führen Sie den folgenden Befehl aus: +
`*storage switch show*`
.. Führen Sie den folgenden Befehl aus: +
`*network port show*`
.. Führen Sie eine MetroCluster-Prüfung durch: +
`*metrocluster check run*`
.. Zeigen Sie die Ergebnisse der MetroCluster-Prüfung an: +
`*metrocluster check show*`


. Deaktivieren Sie AUSO, indem Sie die AUSO-Fehlerdomäne in ändern
+
`*auso-disabled*`

+
[listing]
----
cluster_A_site_A::*>metrocluster modify -auto-switchover-failure-domain auso-disabled
----
. Die Änderung wird mit dem Befehl überprüft
+
`*metrocluster operation show*`

+
[listing]
----

	cluster_A_site_A::*> metrocluster operation show
       Operation: modify
           State: successful
      Start Time: 4/25/2020 20:20:36
        End Time: 4/25/2020 20:20:36
          Errors: -
----
. Beenden Sie die Knoten mit folgendem Befehl:
`*halt*`
+
** Verwenden Sie für eine MetroCluster Konfiguration mit vier oder acht Nodes den Parameter:
`*inhibit-takeover*`
+
[listing]
----
system node halt -node node1_SiteA -inhibit-takeover true -ignore-quorum-warnings true
----
** Verwenden Sie für eine MetroCluster-Konfiguration mit zwei Nodes den Befehl:
+
[listing]
----
system node halt -node node1_SiteA -ignore-quorum-warnings true
----


. Schalten Sie die folgenden Geräte am Standort aus:
+
** Storage Controller
** MetroCluster FC-Switches (wenn verwendet und die Konfiguration keine Stretch-Konfiguration mit zwei Nodes bietet)
** ATTO FibreBridges
** Storage Shelfs


. Warten Sie 30 Minuten, und schalten Sie dann die folgenden Geräte am Standort ein:
+
** Storage Shelfs
** ATTO FibreBridges
** MetroCluster FC-Switches
** Storage Controller


. Nachdem die Controller eingeschaltet sind, überprüfen Sie die MetroCluster-Konfiguration von beiden Standorten aus.
+
Um die Konfiguration zu überprüfen, wiederholen Sie Schritt 1.

. Führen Sie Prüfungen der Einschaltzyklus durch.
+
.. Vergewissern Sie sich, dass alle Sync-Source-SVMs online sind: +
`*vserver show*`
.. Starten Sie alle Sync-Source-SVMs, die nicht online sind: +
`*vserver start*`



