---
permalink: maintain/task_upgrade_rcf_files_on_cisco_ip_switches_with_cleanupfiles.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches, cleanupfiles, cisco 
summary: Möglicherweise müssen Sie eine RCF-Datei auf einem Cisco IP-Switch aktualisieren. Beispielsweise ist für ein ONTAP Upgrade oder ein Switch-Firmware-Upgrade eine neue RCF-Datei erforderlich. 
---
= Aktualisieren Sie RCF-Dateien auf Cisco IP-Switches mithilfe von CleanUpFiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise muss eine Referenz-Konfigurationsdatei (RCF) auf einem Cisco IP Switch aktualisiert werden. Beispielsweise erfordern sowohl ein ONTAP Upgrade als auch ein Switch-Firmware-Upgrade eine neue RCF.

.Über diese Aufgabe
* Ab der Version 1.4a von RcfFileGenerator gibt es eine neue Option, die Switch-Konfiguration auf Cisco IP-Switches zu ändern (Upgrade, Downgrade oder Ersetzen), ohne dass eine 'Schreiblöschung' durchgeführt werden muss.
* link:enable-console-logging-before-maintenance.html["Aktivieren Sie die Konsolenprotokollierung"] Bevor Sie diese Aufgabe ausführen.


* Der Cisco 9336C-FX2 Switch verfügt über zwei verschiedene Switch-Speichertypen, die im RCF unterschiedlich benannt sind. Verwenden Sie die folgende Tabelle, um den richtigen Cisco 9336C-FX2-Speichertyp für Ihre Konfiguration zu ermitteln:
+
[cols="3*"]
|===
| Wenn Sie den folgenden Speicher verbinden... | Wählen Sie den Cisco 9336C-FX2-Speichertyp... | Beispiel RCF Banner/MOTD 


 a| 
** Direkt verbundene SAS-Shelfs
** Direkt verbundene NVMe-Shelfs
** NVMe-Shelfs, die mit dedizierten Storage-Switches verbunden sind

 a| 
9336C-FX2 – nur Direct Storage
 a| 
`* Switch    : NX9336C (direct storage, L2 Networks, direct ISL)`



 a| 
** Direkt verbundene SAS-Shelfs
** Mit den MetroCluster IP-Switches verbundene NVMe Shelfs



NOTE: Es ist mindestens ein Ethernet-angeschlossenes NVMe-Shelf erforderlich
 a| 
9336C-FX2 – SAS- und Ethernet-Speicher
 a| 
`* Switch    : NX9336C (SAS and Ethernet storage, L2 Networks, direct ISL)`

|===


.Bevor Sie beginnen
Sie können diese Methode verwenden, wenn Ihre Konfiguration die folgenden Anforderungen erfüllt:

* Es wird die Standard-RCF-Konfiguration angewendet.
* Die  https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RCfFileGenerator"]muss in der Lage sein, die gleiche RCF zu erstellen, die angewendet wird, mit derselben Version und Konfiguration (Plattformen, VLANs).
* Der angewendete RCF wurde nicht von NetApp für eine spezielle Konfiguration bereitgestellt.
* Der RCF wurde vor der Anwendung nicht verändert.
* Die Schritte zum Zurücksetzen des Schalters auf die Werkseinstellungen wurden vor dem Anwenden des aktuellen RCF durchgeführt.
* Nach der Anwendung des RCF wurden an der Switch(Port)-Konfiguration keine Änderungen vorgenommen.
+
Wenn Sie diese Anforderungen nicht erfüllen, können Sie die beim Generieren der RCFs erstellten CleanUpFiles nicht verwenden. Es besteht jedoch die Möglichkeit, die Funktion zu nutzen, um generische CleanUpFiles zu erstellen – die Bereinigung mit dieser Methode basiert auf der Ausgabe von  `show running-config` und gilt als Best Practice.

+

NOTE: Sie müssen die Switches in folgender Reihenfolge aktualisieren: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2. Oder Sie können die Schalter Switch_A_1 und Switch_B_1 gleichzeitig aktualisieren, gefolgt von den Schaltern Switch_A_2 und Switch_B_2.



.Schritte
. link:../install-ip/switch-move-cluster-lifs.html["Die Cluster-LIFs verschieben"] bevor Sie mit dem Upgrade beginnen.
. Die aktuelle RCF-Version sowie die verwendeten Ports und VLANs lassen sich wie folgt feststellen: `IP_switch_A_1# show banner motd`
+

NOTE: Sie müssen diese Informationen von allen vier Switches erhalten und die folgende Informationstabelle ausfüllen.

+
[listing]
----
* NetApp Reference Configuration File (RCF)
*
* Switch : NX9336C (SAS storage, L2 Networks, direct ISL)
* Filename : NX9336_v1.81_Switch-A1.txt
* Date : Generator version: v1.3c_2022-02-24_001, file creation time: 2021-05-11, 18:20:50
*
* Platforms : MetroCluster 1 : FAS8300, AFF-A400, FAS8700
*              MetroCluster 2 : AFF-A320, FAS9000, AFF-A700, AFF-A800
* Port Usage:
* Ports 1- 2: Intra-Cluster Node Ports, Cluster: MetroCluster 1, VLAN 111
* Ports 3- 4: Intra-Cluster Node Ports, Cluster: MetroCluster 2, VLAN 151
* Ports 5- 6: Ports not used
* Ports 7- 8: Intra-Cluster ISL Ports, local cluster, VLAN 111, 151
* Ports 9-10: MetroCluster 1, Node Ports, VLAN 119
* Ports 11-12: MetroCluster 2, Node Ports, VLAN 159
* Ports 13-14: Ports not used
* Ports 15-20: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 10
* Ports 21-24: MetroCluster-IP ISL Ports, VLAN 119, 159, Port Channel 11, breakout mode 10gx4
* Ports 25-30: Ports not used
* Ports 31-36: Ports not used
*

#
IP_switch_A_1#
----
+
In dieser Ausgabe müssen Sie die in den folgenden beiden Tabellen aufgeführten Informationen erfassen.

+
|===


| Allgemeine Informationen | MetroCluster | Daten 


| RCF Version |  | 1.81 


| Switch-Typ |  | NX9336 


| Netzwerktypologie |  | L2-Netzwerke, direkte ISL 


| Storage-Typ |  | SAS-Storage 


.2+| Plattformen | 1 | AFF A400 


| 2 | FAS9000 
|===
+
|===
| VLAN-Informationen | Netzwerk | MetroCluster-Konfiguration | Switchports | Standort A | Standort B 


.4+| VLAN lokaler Cluster .2+| Netzwerk 1 | 1 | 1, 2 | 111 | 222 


| 2 | 3, 4 | 151 | 251 


.2+| Netzwerk 2 | 1 | 1, 2 | 111 | 222 


| 2 | 3, 4 | 151 | 251 


.4+| VLAN-MetroCluster .2+| Netzwerk 1 | 1 | 9, 10 | 119 | 119 


| 2 | 11, 12 | 159 | 159 


.2+| Netzwerk 2 | 1 | 9, 10 | 219 | 219 


| 2 | 11, 12 | 259 | 259 
|===
. [[Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles]] Die RCFs und CleanUpFiles oder generische CleanUpFiles für die aktuelle Konfiguration werden erstellt.
+
Wenn Ihre Konfiguration die in den Voraussetzungen beschriebenen Anforderungen erfüllt, wählen Sie *Option 1*. Wenn Ihre Konfiguration die in den Voraussetzungen beschriebenen Anforderungen nicht erfüllt, wählen Sie *Option 2*.

+
[role="tabbed-block"]
====
.Option 1: Die RCFs und CleanUpFiles erstellen
--
Gehen Sie folgendermaßen vor, wenn die Konfiguration den Anforderungen entspricht.

.Schritte
.. Verwenden Sie den RcfFileGenerator 1.4a (oder höher), um die RCFs mit den in Schritt 1 abgerufenen Informationen zu erstellen. Die neue Version des RcfFileGenerator erstellt einen zusätzlichen Satz von CleanUpFiles, mit denen sich bestimmte Konfigurationen zurücksetzen und der Switch für die Anwendung einer neuen RCF Konfiguration vorbereiten lässt.
.. Vergleichen Sie das Banner motd mit den aktuell angewendeten RCFs. Die Plattformtypen, der Switch-Typ, die Port- und VLAN-Nutzung müssen identisch sein.
+

NOTE: Sie müssen die CleanUpFiles aus derselben Version wie die RCF und für exakt dieselbe Konfiguration verwenden. Die Verwendung einer beliebigen CleanUpFile funktioniert nicht und kann einen vollständigen Reset des Switches erforderlich machen.

+

NOTE: Die ONTAP Version, für die die RCF erstellt wurde, ist irrelevant. Nur die RCF Version ist wichtig.

+

NOTE: Die RCF (auch bei gleicher Version) kann weniger oder mehr Plattformen auflisten. Es sollte überprüft werden, ob die eigene Plattform aufgeführt ist.



--
.Option 2: Erstellen Sie allgemeine CleanUpFiles
--
Gehen Sie folgendermaßen vor, wenn die Konfiguration nicht alle Anforderungen erfüllt.

.Schritte
.. Abrufen der Ausgabe von `show running-config` Von jedem Schalter.
.. Öffnen Sie das RcfFileGenerator-Tool und klicken Sie unten im Fenster auf 'Generic CleanUpFiles erstellen'
.. Kopieren Sie die Ausgabe, die Sie in Schritt 1 von „One“-Schalter in das obere Fenster abgerufen haben. Sie können die Standardausgabe entfernen oder belassen.
.. Klicken Sie auf „CUF-Dateien erstellen“.
.. Kopieren Sie die Ausgabe aus dem unteren Fenster in eine Textdatei (diese Datei ist die CleanUpFile).
.. Wiederholen Sie die Schritte c, d und e für alle Schalter in der Konfiguration.
+
Am Ende dieses Verfahrens sollten Sie vier Textdateien haben, eine für jeden Switch. Sie können diese Dateien auf die gleiche Weise wie die CleanUpFiles verwenden, die Sie mit Option 1 erstellen können.



--
====
. [[Neue RCF-Dateien für die neue Konfiguration erstellen]] Die neuen RCFs für die neue Konfiguration erstellen. Diese Dateien werden auf die gleiche Weise wie im vorherigen Schritt erstellt, jedoch mit der jeweiligen ONTAP und RCF Version.
+
Nach Abschluss dieses Schrittes sollten zwei Sätze von RCFs vorhanden sein, wobei jeder Satz aus zwölf Dateien besteht.

. Laden Sie die Dateien auf den Bootflash herunter.
+
.. Laden Sie die CleanUpFiles herunter, die Sie in <<Create-RCF-files-and-CleanUpFiles-or-create-generic-CleanUpFiles,Die RCFs und CleanUpFiles erstellen oder generische CleanUpFiles für die aktuelle Konfiguration erstellen>> erstellt haben
+

NOTE: Diese CleanUpFile gilt für die aktuell angewendete RCF und *NICHT* für die neue RCF, auf die Sie aktualisieren möchten.

+
Beispiel CleanUpFile für Switch-A1: `Cleanup_NX9336_v1.81_Switch-A1.txt`

.. Laden Sie die von Ihnen in <<Create-the-new-RCF-files-for-the-new-configuration,Die „neuen“ RCFs für die neue Konfiguration erstellen.>> erstellten „neuen“ RCFs herunter.
+
Beispiel RCF für Switch-A1: `NX9336_v1.90_Switch-A1.txt`

.. Laden Sie die CleanUpFiles herunter, die Sie in <<Create-the-new-RCF-files-for-the-new-configuration,Die „neuen“ RCFs für die neue Konfiguration erstellen.>> diesem Schritt erstellt haben. Dieser Schritt ist optional, die Datei kann zukünftig verwendet werden, um die Switch-Konfiguration zu aktualisieren. Sie entspricht der aktuell angewendeten Konfiguration.
+
Beispiel CleanUpFile für Switch-A1: `Cleanup_NX9336_v1.90_Switch-A1.txt`

+

NOTE: Sie müssen die CleanUpFile für die korrekte (passende) RCF-Version verwenden. Wenn Sie eine CleanUpFile für eine andere RCF-Version oder eine andere Konfiguration verwenden, funktioniert die Bereinigung der Konfiguration möglicherweise nicht richtig.

+
Im folgenden Beispiel werden die drei Dateien auf den Bootflash kopiert:

+
[listing]
----
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.81_MetroCluster-IP_L2Direct_A400FAS8700_xxx_xxx_xxx_xxx/Cleanup_NX9336_v1.81_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//NX9336_v1.90_Switch-A1.txt bootflash:
IP_switch_A_1# copy sftp://user@50.50.50.50/RcfFiles/NX9336-direct-SAS_v1.90_MetroCluster-IP_L2Direct_A400FAS8700A900FAS9500_xxx_xxx_xxx_xxxNX9336_v1.90//Cleanup_NX9336_v1.90_Switch-A1.txt bootflash:
----
+

NOTE: Sie werden aufgefordert, Virtual Routing und Forwarding (VRF) anzugeben.



. Übernehmen Sie die CleanUpFile- oder die allgemeine CleanUpFile-Datei.
+
Einige der Konfigurationen werden zurückgesetzt und die Switchports gehen „offline“.

+
.. Vergewissern Sie sich, dass keine ausstehenden Änderungen an der Startkonfiguration vorliegen: `show running-config diff`
+
[listing]
----
IP_switch_A_1# show running-config diff
IP_switch_A_1#
----


. Wenn Sie die Systemausgabe sehen, speichern Sie die laufende Konfiguration in die Startkonfiguration: `copy running-config startup-config`
+

NOTE: Die Systemausgabe zeigt an, dass die Startkonfiguration und die laufende Konfiguration unterschiedlich und ausstehende Änderungen sind. Wenn Sie die ausstehenden Änderungen nicht speichern, können Sie den Switch nicht erneut laden.

+
.. Anwenden der CleanUpFile:
+
[listing]
----

IP_switch_A_1# copy bootflash:Cleanup_NX9336_v1.81_Switch-A1.txt running-config

IP_switch_A_1#
----
+

NOTE: Das Skript kann eine Weile dauern, bis es zur Switch-Eingabeaufforderung zurückkehrt. Es wird keine Ausgabe erwartet.



. Zeigen Sie die laufende Konfiguration an, um zu überprüfen, ob die Konfiguration gelöscht wurde: `show running-config`
+
Die aktuelle Konfiguration sollte Folgendes zeigen:

+
** Es sind keine Klassenkarten und IP-Zugriffslisten konfiguriert
** Es wurden keine Richtlinienzuordnungen konfiguriert
** Es sind keine Service-Richtlinien konfiguriert
** Es werden keine Port-Profile konfiguriert
** Alle Ethernet-Schnittstellen (außer mgmt0 die keine Konfiguration zeigen sollten, und nur VLAN 1 sollte konfiguriert sein).
+
Sollten Sie feststellen, dass eines der oben genannten Elemente konfiguriert ist, ist es möglicherweise nicht möglich, eine neue RCF Konfiguration anzuwenden. Es besteht jedoch die Möglichkeit, zur vorherigen Konfiguration zurückzukehren, indem der Switch neu geladen wird, *ohne* die laufende Konfiguration in die Startup Konfiguration zu speichern. Der Switch wird dann mit der vorherigen Konfiguration gestartet.



. Den RCF anwenden und überprüfen, ob die Ports online sind.
+
.. Der RCF wird angewendet.
+
[listing]
----
IP_switch_A_1# copy bootflash:NX9336_v1.90-X2_Switch-A1.txt running-config
----
+

NOTE: Beim Anwenden der Konfiguration werden einige Warnmeldungen angezeigt. Fehlermeldungen werden in der Regel nicht erwartet. Wenn Sie jedoch mit SSH angemeldet sind, wird möglicherweise die folgende Fehlermeldung angezeigt: `Error: Can't disable/re-enable ssh:Current user is logged in through ssh`

.. Überprüfen Sie nach der Anwendung der Konfiguration, ob die Cluster- und MetroCluster-Ports mit einem der folgenden Befehle online geschaltet werden: `show interface brief`, `show cdp neighbors`, Oder `show lldp neighbors`
+

NOTE: Wenn Sie das VLAN für den lokalen Cluster geändert haben und Sie den ersten Switch am Standort aktualisiert haben, wird der Zustand der Cluster-Zustandsüberwachung möglicherweise nicht als „stabil“ angegeben, da die VLANs der alten und der neuen Konfigurationen nicht übereinstimmen. Nach der Aktualisierung des zweiten Schalters sollte der Status wieder in den Status „gesund“ zurückkehren.

+
Wenn die Konfiguration nicht korrekt angewendet wird oder Sie die Konfiguration nicht beibehalten möchten, können Sie die vorherige Konfiguration wiederherstellen, indem Sie den Switch wieder laden *ohne* die laufende Konfiguration in die Startkonfiguration zu speichern. Der Switch verfügt über die vorherige Konfiguration.



. Speichern Sie die Konfiguration, und laden Sie den Schalter neu.
+
[listing]
----
IP_switch_A_1# copy running-config startup-config

IP_switch_A_1# reload
----
. Alle Cluster-LIFs so anpassen, dass die automatische Rückkehr aktiviert ist:
+
.. Automatische Rückkehr wieder aktivieren:
+
`network interface modify -vserver Cluster -lif * -auto-revert true`

+
[listing]
----
cluster_A::*> network interface modify -vserver Cluster -lif * -auto-revert true

Warning: Changes to a cluster LIF can affect the health of the Cluster. Are you
         sure you want to continue? {y|n}: y
4 entries were modified.

cluster_A::*>
----
.. Alle Cluster-LIFs, die sich derzeit nicht auf ihren Heimatports befinden, werden auf ihre Heimatports zurückgesetzt:
+
`network interface revert -vserver Cluster -lif *`

+
Einige Minuten warten, bis die LIFs zu ihrem Home-Port zurückkehren:

.. Bestätigen Sie, dass sich alle LIFs auf ihren Home-Ports befinden:
+
[listing]
----
cluster_A::*> network interface show -role cluster
            Logical        Status     Network            Current       Current Is
Vserver     Interface      Admin/Oper Address/Mask       Node          Port    Home
----------- -------------- ---------- ------------------ ------------- ------- ----
Cluster
            node_A_1_clus1 up/up      192.168.204.88/18  node_A_1      e4a     true
            node_A_1_clus2 up/up      192.168.204.93/18  node_A_1      e4b     true
            node_A_2_clus1 up/up      192.168.204.96/18  node_A_2      e4a     true
            node_A_2_clus2 up/up      192.168.204.97/18  node_A_2      e4b     true
4 entries were displayed.
----
.. Den Zustand der MetroCluster Knoten überprüfen:
+
`metrocluster node show`

+
[listing]
----
cluster_A::*> metrocluster node show

DR                               Configuration  DR
Group Cluster Node               State          Mirroring Mode
----- ------- ------------------ -------------- --------- --------------------
1     cluster_A
              node_A_1           configured     enabled   normal
              node_A_2           configured     enabled   normal
      cluster_B
              node_B_1           configured     enabled   normal
              node_B_2           configured     enabled   normal
4 entries were displayed.

cluster_A::*>
----



