---
permalink: maintain/task_add_remove_or_change_isl_ports_nondisruptively.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, add, remove, change, isl, ports, nondisruptively 
summary: Unter Umständen müssen ISL-Ports hinzugefügt, entfernt oder geändert werden. Sie können dedizierte ISL-Ports in gemeinsam genutzte ISL-Ports konvertieren oder die Geschwindigkeit der ISL-Ports auf einem Switch ändern. ISLs, die größere Entfernungen zurücklegen, erfordern möglicherweise geringere Geschwindigkeiten, um die Qualität zu verbessern. Möglicherweise müssen auch die Geschwindigkeit der ISL-Ports erhöht werden, um System-Upgrades zu nutzen und ISLs zu einem Cisco IP Switch hinzuzufügen, wenn Hardware hinzugefügt oder aktualisiert wird. 
---
= Unterbrechungsfreies Hinzufügen, Entfernen oder Ändern von ISL-Ports auf Cisco IP-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie ISL-Ports bei Cisco IP-Switches hinzufügen, entfernen oder ändern. Sie können dedizierte ISL-Ports in gemeinsame ISL-Ports konvertieren oder die Geschwindigkeit von ISL-Ports auf einem Cisco IP-Switch ändern.

.Über diese Aufgabe
Wenn Sie dedizierte ISL-Ports in gemeinsam genutzte ISL-Ports konvertieren, stellen Sie sicher, dass die neuen Ports den entsprechen link:../install-ip/concept_considerations_layer_2.html["Voraussetzungen für gemeinsam genutzte ISL-Ports"].

Um die ISL-Konnektivität sicherzustellen, müssen Sie alle Schritte auf beiden Switches ausführen.

Im folgenden Verfahren wird vorausgesetzt, dass Sie eine 10-GB-ISL, die am Switch-Port eth1/24/1 angeschlossen ist, durch zwei 100-GB-ISLs ersetzen, die mit den Switch-Ports 17 und 18 verbunden sind.


NOTE: Wenn Sie einen Cisco 9336C-FX2-Switch in einer gemeinsam genutzten Konfiguration verwenden, die NS224-Shelfs verbindet, erfordert das Ändern der ISLs möglicherweise eine neue RCF-Datei. Sie benötigen keine neue RCF-Datei, wenn Ihre aktuelle und neue ISL-Geschwindigkeit 40 Gbit/s und 100 Gbit/s beträgt. Für alle anderen Änderungen an der ISL-Geschwindigkeit ist eine neue RCF-Datei erforderlich. Wenn Sie beispielsweise die ISL-Geschwindigkeit von 40 Gbit/s auf 100 Gbit/s ändern, ist keine neue RCF-Datei erforderlich, aber wenn Sie die ISL-Geschwindigkeit von 10 Gbit/s auf 40 Gbit/s ändern, ist eine neue RCF-Datei erforderlich.

.Bevor Sie beginnen
Weitere Informationen finden Sie im Abschnitt *Schalter* des link:https://hwu.netapp.com/["NetApp Hardware Universe"^] Überprüfen der unterstützten Transceiver.

link:enable-console-logging-before-maintenance.html["Aktivieren Sie die Konsolenprotokollierung"] Bevor Sie diese Aufgabe ausführen.

.Schritte
. Deaktivieren Sie die ISL-Ports der ISLs auf beiden Switches in der Fabric, die Sie ändern möchten.
+
--

NOTE: Die aktuellen ISL-Ports müssen nur deaktiviert werden, wenn sie zu einem anderen Port verschoben werden oder sich die Geschwindigkeit der ISL ändert. Wenn Sie einen ISL-Port mit derselben Geschwindigkeit wie die vorhandenen ISLs hinzufügen, fahren Sie mit Schritt 3 fort.

--
+
Sie müssen nur einen Konfigurationsbefehl für jede Zeile eingeben und Strg-Z drücken, nachdem Sie alle Befehle eingegeben haben, wie im folgenden Beispiel dargestellt:

+
[listing]
----

switch_A_1# conf t
switch_A_1(config)# int eth1/24/1
switch_A_1(config-if)# shut
switch_A_1(config-if)#
switch_A_1#

switch_B_1# conf t
switch_B_1(config)# int eth1/24/1
switch_B_1(config-if)# shut
switch_B_1(config-if)#
switch_B_1#
----
. Entfernen Sie die vorhandenen Kabel und Transceiver.
. Ändern Sie den ISL-Port nach Bedarf.
+

NOTE: Wenn Sie Cisco 9336C-FX2-Switches in einer gemeinsam genutzten Konfiguration verwenden, die NS224-Shelfs verbindet, und Sie die RCF-Datei aktualisieren und die neue Konfiguration für die neuen ISL-Ports anwenden müssen, befolgen Sie die Schritte unter link:task_upgrade_rcf_files_on_mcc_ip_switches.html["Aktualisieren Sie die RCF-Dateien auf MetroCluster IP-Switches."]

+
[cols="30,70"]
|===


| Option | Schritt 


 a| 
So ändern Sie die Geschwindigkeit eines ISL-Ports:
 a| 
Verkabeln Sie die neuen ISLs entsprechend ihrer Geschwindigkeit an die entsprechenden Ports. Sie müssen sicherstellen, dass diese ISL-Ports für Ihren Switch in der _MetroCluster IP Installation and Configuration_ aufgeführt sind.



 a| 
ISL hinzufügen...
 a| 
Fügen Sie QFSPs in die Ports ein, die Sie als ISL-Ports hinzufügen. Stellen Sie sicher, dass sie in der _MetroCluster IP-Installation und -Konfiguration_ aufgeführt sind und verkabeln Sie sie entsprechend.

|===
. Aktivieren Sie alle ISL-Ports (falls nicht aktiviert) auf beiden Switches in der Fabric und beginnen Sie mit dem folgenden Befehl:
+
`switch_A_1# conf t`

+
Sie müssen nur einen Konfigurationsbefehl pro Zeile eingeben und Strg-Z drücken, nachdem Sie alle Befehle eingegeben haben:

+
[listing]
----
switch_A_1# conf t
switch_A_1(config)# int eth1/17
switch_A_1(config-if)# no shut
switch_A_1(config-if)# int eth1/18
switch_A_1(config-if)# no shut
switch_A_1(config-if)#
switch_A_1#
switch_A_1# copy running-config startup-config

switch_B_1# conf t
switch_B_1(config)# int eth1/17
switch_B_1(config-if)# no shut
switch_B_1(config-if)# int eth1/18
switch_B_1(config-if)# no shut
switch_B_1(config-if)#
switch_B_1#
switch_B_1# copy running-config startup-config
----
. Überprüfen Sie, ob die ISLs und Port-Kanäle für die ISLs zwischen beiden Switches eingerichtet sind:
+
`switch_A_1# show int brief`

+
Die ISL-Schnittstellen in der Befehlsausgabe sollten wie im folgenden Beispiel gezeigt werden:

+
[listing]
----
Switch_A_1# show interface brief
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/17         1       eth  access down    XCVR not inserted        auto(D) --
Eth1/18         1       eth  access down    XCVR not inserted        auto(D) --

------------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                              Speed   Protocol
Interface
------------------------------------------------------------------------------------------
Po10         1       eth  trunk  up      none                                a-100G(D)  lacp
Po11         1       eth  trunk  up      none                                a-100G(D)  lacp
----
. Wiederholen Sie das Verfahren für Stoff 2.

