---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, brocade, fc, switch 
summary: Zum Upgrade oder Downgrade der Firmware auf einem Brocade FC-Switch müssen Sie den Switch mit den spezifischen Brocade Befehlen deaktivieren, die Firmware-Änderung durchführen und überprüfen sowie den Switch neu starten und wieder aktivieren. 
---
= Die Firmware eines Brocade MetroCluster FC Switches kann aktualisiert oder auf eine frühere Version zurückgesetzt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Upgrade oder Downgrade der Firmware auf einem Brocade FC-Switch müssen Sie den Switch mit den spezifischen Brocade Befehlen deaktivieren, die Firmware-Änderung durchführen und überprüfen sowie den Switch neu starten und wieder aktivieren.

.Bevor Sie beginnen
Die folgenden Informationen sollten sorgfältig geprüft werden, bevor dieses Verfahren verwendet wird:

* Ab Fabric OS 10.x unterstützt Brocade für die SNMP-Authentifizierung nur noch SHA-512. ONTAP unterstützt derzeit kein SHA-512, die Unterstützung ist auf SHA-256 beschränkt.
+
Wenn die Firmware Ihres MetroCluster FC-Switches auf Fabric OS 10.x aktualisiert wird, geht die SNMP-Überwachbarkeit von ONTAP verloren. Dies führt zu einem erhöhten Risiko bei der Fehlerbehebung und zum Verlust proaktiver Warnmeldungen.

+
Wenn Sie ein Upgrade auf oder ein Downgrade von Fabric OS 10.x durchführen, müssen die obligatorischen Aufgaben ausgeführt werden, die in link:https://techdocs.broadcom.com/us/en/fibre-channel-networking/fabric-os/fabric-os-software-upgrade/10-0-x/Upgrading-and-Downgrading-Firmware/v24512876.html["Brocade Fabric OS Software Upgrade Leitfaden, 10.0.x – Voraussetzungen für Upgrade oder Downgrade"^] aufgeführt sind.

+

CAUTION: Diese Einschränkungen sollten sorgfältig abgewogen werden, bevor ein Upgrade auf oder ein Downgrade von Fabric OS 10.x oder höher erfolgt.

* Ab Fabric OS 9.0.1 wird SNMPv2 auf Brocade Switches nicht mehr unterstützt. Bei einem Upgrade auf Fabric OS 9.0.1 oder höher ist für die Zustandsüberwachung SNMPv3 zu verwenden. Weitere Informationen finden sich unter link:../install-fc/concept_configure_the_mcc_software_in_ontap.html#snmpv3-mcc-fc["Konfigurieren von SNMPv3 in einer MetroCluster-Konfiguration"].
* Wenn Sie auf Fabric OS 9.2.x oder höher aktualisieren, muss ein Brocade TruFOS-Zertifikat installiert sein. Weitere Informationen finden Sie unter link:https://techdocs.broadcom.com/us/en/fibre-channel-networking/fabric-os/fabric-os-software-upgrade/9-2-x/Obtaining-Firmware/download-prerequisites-new/brocade-trufos-certificates.html["Upgrade-Handbuch für Brocade Fabric OS Software, 9.2.x"^].


.Über diese Aufgabe
Vergewissern Sie sich, dass Sie die folgenden Aufgaben für Ihre Konfiguration überprüft und ausgeführt haben:

* Prüfen Sie, ob Ihre neue Firmware-Version mit Ihrer Lösung kompatibel ist. Siehe die link:https://hwu.netapp.com/["Hardware Universe"^] für weitere Informationen.
* Sie haben die Firmware-Dateien.
* Das System ist ordnungsgemäß verkabelt.
* Es sind alle Pfade zu den Storage Shelfs verfügbar.
* Die Platten-Shelf Stacks sind stabil.
* Die FC-Switch-Fabric ist in einem ordnungsgemäßen Zustand.
* Im System sind keine fehlerhaften Komponenten vorhanden.
* Das System funktioniert normal.
* Sie haben das Admin-Passwort und Zugriff auf einen FTP- oder SCP-Server.
* Die Konsolenprotokollierung ist aktiviert.
+
link:enable-console-logging-before-maintenance.html["Aktivieren Sie die Konsolenprotokollierung"]



Die Switch-Fabric wird während eines Firmware-Upgrades oder Downgrades deaktiviert, wobei die MetroCluster-Konfiguration den Betrieb über die zweite Fabric fortsetzt.

Diese Aufgabe muss nacheinander an jeder Switch-Fabric ausgeführt werden, damit alle Switches dieselbe Firmware-Version ausführen.


NOTE: Dieser Vorgang läuft unterbrechungsfrei ab und dauert etwa eine Stunde.

.Schritte
. Melden Sie sich bei jedem der Switches in der Fabric an.
+
Die Beispiele in den folgenden Schritten verwenden den Schalter `FC_switch_A_1`.

. Deaktivieren Sie jeden der Switches in der Fabric:
+
`*switchCfgPersistentDisable*`

+
Wenn dieser Befehl nicht verfügbar ist, führen Sie den aus `switchDisable` Befehl.

+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
. Laden Sie die gewünschte Firmware-Version herunter:
+
`*firmwareDownload*`

+
Wenn Sie zur Eingabe des Dateinamens aufgefordert werden, müssen Sie das Unterverzeichnis oder den relativen Pfad zur Firmware-Datei angeben.

+
Sie können die ausführen `firmwareDownload` Befehl gleichzeitig auf beiden Switches, aber Sie müssen der Firmware das Herunterladen und Commit ermöglichen, bevor Sie mit dem nächsten Schritt fortfahren.

+
[listing]
----
FC_switch_A_1:admin> firmwaredownload
Server Name or IP Address: 10.64.203.188
User Name: test
File Name: v7.3.1b
Network Protocol(1-auto-select, 2-FTP, 3-SCP, 4-SFTP, 5-HTTP) [1]: 2
Password:
Server IP: 10.64.203.188, Protocol IPv4
Checking system settings for firmwaredownload...
System settings check passed.
----
. Vergewissern Sie sich, dass die Firmware heruntergeladen und auf beiden Partitionen gesetzt wurde:
+
`*firmwareShow*`

+
Das folgende Beispiel zeigt, dass der Firmware-Download abgeschlossen ist, wenn beide Bilder aktualisiert werden:

+
[listing]
----
FC_switch_A_1:admin> firmwareShow
Appl     Primary/Secondary Versions

------------------------------------------

FOS      v7.3.1b

         v7.3.1b
----
. Starten Sie die Switches neu:
+
`*reboot*`

+
Nach Abschluss des Firmware-Downloads führen einige Firmware-Versionen automatisch einen haReboot-Vorgang durch. Der Neustart in diesem Schritt ist auch dann erforderlich, wenn der haReboot durchgeführt wurde.

+
[listing]
----
FC_switch_A_1:admin> reboot
----
. Prüfen Sie, ob die neue Firmware auf eine mittlere Firmware-Ebene oder auf eine endgültige angegebene Version gehört.
+
Wenn der Download auf die mittlere Firmware-Ebene erfolgt, führen Sie die beiden vorherigen Schritte aus, bis das angegebene Release installiert ist.

. Aktivieren Sie die Switches:
+
`*switchCfgPersistentEnable*`

+
Wenn dieser Befehl nicht verfügbar ist, sollte sich der Schalter im befinden `enabled` Status nach dem `reboot` Befehl wird ausgeführt.

+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentEnable
----
. Vergewissern Sie sich, dass die Switches online sind und alle Geräte ordnungsgemäß angemeldet sind:
+
`*switchShow*`

+
[listing]
----
FC_switch_A_1:admin> switchShow
----
. Stellen Sie sicher, dass die Informationen zur Puffernutzung für eine Portgruppe oder alle Portgruppen im Switch ordnungsgemäß angezeigt werden:
+
`*portbuffershow*`

+
[listing]
----
FC_switch_A_1:admin> portbuffershow
----
. Überprüfen Sie, ob die aktuelle Konfiguration eines Ports ordnungsgemäß angezeigt wird:
+
`*portcfgshow*`

+
[listing]
----
FC_switch_A_1:admin> portcfgshow
----
+
Überprüfen Sie die Porteinstellungen, z. B. Geschwindigkeit, Modus, Trunking, Verschlüsselung, Und Komprimierung in der Inter-Switch Link-Ausgabe (ISL). Vergewissern Sie sich, dass die Porteinstellungen vom Firmware-Download nicht betroffen waren.

. Überprüfen Sie den Betrieb der MetroCluster-Konfiguration in ONTAP:
+
.. Überprüfen Sie, ob das System multipathed ist: +
`*node run -node _node-name_ sysconfig -a*`
.. Überprüfen Sie auf beiden Clustern auf alle Zustandswarnmeldungen: +
`*system health alert show*`
.. Bestätigen Sie die MetroCluster-Konfiguration und den normalen Betriebsmodus: +
`*metrocluster show*`
.. Führen Sie eine MetroCluster-Prüfung durch: +
`*metrocluster check run*`
.. Zeigen Sie die Ergebnisse der MetroCluster-Prüfung an: +
`*metrocluster check show*`
.. Überprüfen Sie, ob auf den Switches Zustandswarnmeldungen angezeigt werden (falls vorhanden): +
`*storage switch show*`
.. Nutzen Sie Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"]

.. Überprüfen Sie nach dem Ausführen von Config Advisor die Ausgabe des Tools und befolgen Sie die Empfehlungen in der Ausgabe, um die erkannten Probleme zu beheben.


. Warten Sie 15 Minuten, bevor Sie diesen Vorgang für das zweite Switch-Fabric wiederholen.

