---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install 
summary: Aktualisieren der Firmware auf MetroCluster IP Switches. 
---
= Aktualisieren Sie Firmware auf MetroCluster IP Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie die Firmware auf einem MetroCluster IP Switch aktualisieren.



== Stellen Sie sicher, dass die RCF unterstützt wird

Wenn Sie die ONTAP-Version oder die Switch-Firmware-Version ändern, sollten Sie überprüfen, ob eine Referenzkonfigurationsdatei (RCF) vorhanden ist, die für diese Version unterstützt wird. Wenn Sie das  Tool verwendenlink:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RCfFileGenerator"^], wird die richtige RCF für Ihre Konfiguration generiert.

.Schritte
. Verwenden Sie die folgenden Befehle der Switches, um die Version der RCF zu überprüfen:
+
[cols="30,70"]
|===


| Von diesem Schalter... | Geben Sie diesen Befehl aus... 


 a| 
Broadcom-Switch
 a| 
`(IP_switch_A_1) # show clibanner`



 a| 
Cisco Switch
 a| 
`IP_switch_A_1# show banner motd`



 a| 
NVIDIA SN2100-Switch
 a| 
`cumulus@mcc1:mgmt:~$ nv config find message`

|===
+
Suchen Sie die Zeile in der Befehlsausgabe, die die RCF-Version angibt. Die folgende Ausgabe von einem Cisco-Switch zeigt beispielsweise an, dass die RCF-Version „`v1.80`“ ist.

+
....
Filename : NX3232_v1.80_Switch-A2.txt
....
. Um zu überprüfen, welche Dateien für eine bestimmte ONTAP-Version, einen Switch und eine bestimmte Plattform unterstützt werden, verwenden Sie die link:https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator["RCfFileGenerator für MetroCluster-IP"^]. Wenn Sie die RCF für die Konfiguration generieren können, auf die Sie aktualisieren möchten, wird sie unterstützt.
. Um sicherzustellen, dass die Switch-Firmware unterstützt wird, lesen Sie bitte die folgenden Informationen:
+
** https://hwu.netapp.com["Hardware Universe"]
** https://imt.netapp.com/matrix/["NetApp Interoperabilitätsmatrix"^]






== Aktualisieren Sie die Switch-Firmware

.Über diese Aufgabe
Sie müssen diese Aufgabe nacheinander an jedem der Schalter wiederholen.

link:enable-console-logging-before-maintenance.html["Aktivieren Sie die Konsolenprotokollierung"] Bevor Sie diese Aufgabe ausführen.

[[step_1_fw_upgrade]]
.Schritte
. Überprüfen Sie den Zustand der Konfiguration.
+
.. Vergewissern Sie sich, dass die MetroCluster für jedes Cluster im normalen Modus konfiguriert ist:
+
`metrocluster show`

+
[listing]
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----
.. Vergewissern Sie sich, dass die Spiegelung auf jedem Knoten aktiviert ist:
+
`metrocluster node show`

+
[listing]
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----
.. Prüfen Sie, ob die MetroCluster-Komponenten ordnungsgemäß sind:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run
----
+
Der Vorgang wird im Hintergrund ausgeführt.

.. Nach dem `metrocluster check run` Vorgang abgeschlossen, Ausführen:
+
`metrocluster check show`

+
Nach etwa fünf Minuten werden die folgenden Ergebnisse angezeigt:

+
[listing]
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Vergewissern Sie sich, dass es keine Systemzustandsmeldungen gibt:
+
`system health alert show`



. Installieren Sie die Software auf dem ersten Switch.
+

NOTE: Sie müssen die Switch-Software auf den Switches in der folgenden Reihenfolge installieren: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.

+
Befolgen Sie die Schritte zum Installieren der Switch-Software im entsprechenden Thema, je nachdem, ob der Switch-Typ Broadcom, Cisco oder NVIDIA ist:

+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software["Laden Sie die Broadcom-Switch-EFOS-Software herunter, und installieren Sie sie"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software["Laden Sie die Cisco Switch NX-OS-Software herunter, und installieren Sie sie"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software["Laden Sie die NVIDIA SN2100 Switch Cumulus Software herunter und installieren Sie sie"]


. Wiederholen Sie den vorherigen Schritt für jeden der Schalter.
. Wiederholen <<step_1_fw_upgrade,Schritt 1>> Um den Zustand der Konfiguration zu überprüfen.

