---
permalink: maintain/task_change_speed_of_isl_ports_on_a_cisco_fc_switch.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, change, speed, isl, ports, cisco, fc, switch 
summary: Möglicherweise müssen Sie die Geschwindigkeit der ISL-Ports auf einem Switch ändern, um die Qualität des ISL zu verbessern. ISLs, die größere Entfernungen zurückfahren, müssen möglicherweise ihre Geschwindigkeit senken, um die Qualität zu verbessern. 
---
= Ändern der Geschwindigkeit der ISL-Ports bei einem Cisco FC-Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie die Geschwindigkeit der ISL-Ports auf einem Switch ändern, um die Qualität des ISL zu verbessern. ISLs, die größere Entfernungen zurückfahren, müssen möglicherweise ihre Geschwindigkeit senken, um die Qualität zu verbessern.

.Über diese Aufgabe
* Führen Sie alle Schritte an beiden Switches aus, um die ISL-Konnektivität sicherzustellen.
* link:enable-console-logging-before-maintenance.html["Aktivieren Sie die Konsolenprotokollierung"] Bevor Sie diese Aufgabe ausführen.


.Schritte
. Deaktivieren Sie die ISL-Ports der ISLs, die die Geschwindigkeit bei beiden Switches in der Fabric ändern möchten:
+
`*FC_switch_A_1# config t*`

+
Geben Sie Konfigurationsbefehle ein pro Zeile ein. Beenden Sie mit STRG-Z, nachdem Sie alle Konfigurationsbefehle eingegeben haben.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----
. Ändern Sie die Geschwindigkeit der ISL-Ports an beiden Switches in der Fabric:
+
`*FC_switch_A_1# config t*`

+
Geben Sie Konfigurationsbefehle ein pro Zeile ein. Beenden Sie mit STRG-Z, nachdem Sie alle Konfigurationsbefehle eingegeben haben.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+

NOTE: Geschwindigkeiten für Ports sind 16 = 16,000 Gbit/s, 8 = 8,000 Gbit/s, 4 = 4,000 Gbit/s.

+
Stellen Sie sicher, dass diese ISL-Ports für Ihren Switch im Installations- und Konfigurationshandbuch für _Fabric-Attached MetroCluster_ aufgeführt sind.

. Alle ISL-Ports (falls nicht aktiviert) auf beiden Switches in der Fabric aktivieren:
+
`*FC_switch_A_1# config t*`

+
Geben Sie Konfigurationsbefehle ein pro Zeile ein. Beenden Sie mit STRG-Z, nachdem Sie alle Konfigurationsbefehle eingegeben haben.

+
[listing]
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----
. Überprüfen Sie, ob die ISLs zwischen beiden Switches aufgebaut sind:
+
`*show topology isl*`

+
[listing]
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----
. Wiederholen Sie das Verfahren für die zweite Switch-Struktur.

