---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches 
summary: Möglicherweise müssen Sie eine RCF-Datei auf einem MetroCluster IP-Switch aktualisieren. Beispielsweise ist für ein ONTAP Upgrade oder ein Switch-Firmware-Upgrade eine neue RCF-Datei erforderlich. 
---
= Aktualisieren Sie RCF-Dateien auf MetroCluster IP-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie eine Referenz-Konfigurationsdatei (RCF) auf einem MetroCluster IP Switch aktualisieren. Dies kann zum Beispiel der Fall sein, wenn die auf den Switches verwendete RCF-Version nicht von der ONTAP Version, der Switch-Firmware-Version oder beiden unterstützt wird.

.Bevor Sie beginnen
* Wenn Sie eine neue Switch-Firmware installieren, muss die Switch-Firmware installiert werden, bevor das RCF aktualisiert wird.
* Bevor Sie den RCF aktualisieren, link:task_upgrade_firmware_on_mcc_ip_switches.html["Stellen Sie sicher, dass die RCF unterstützt wird"].
* link:enable-console-logging-before-maintenance.html["Aktivieren Sie die Konsolenprotokollierung"] Bevor Sie diese Aufgabe ausführen.


.Über diese Aufgabe
* Dieses Verfahren unterbricht den Datenverkehr auf dem Switch, auf dem das RCF aktualisiert wird. Der Datenverkehr wird wiederhergestellt, wenn das neue RCF angewendet wird.
* Führen Sie die Schritte jeweils an einem Schalter in der folgenden Reihenfolge aus: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.


.Schritte
. Überprüfen Sie den Zustand der Konfiguration.
+
.. Vergewissern Sie sich, dass die MetroCluster-Komponenten ordnungsgemäß sind:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----


+
Der Vorgang wird im Hintergrund ausgeführt.

+
.. Nach dem `metrocluster check run` Vorgang abgeschlossen, Ausführung `metrocluster check show` Um die Ergebnisse anzuzeigen.
+
Nach etwa fünf Minuten werden die folgenden Ergebnisse angezeigt:

+
[listing]
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----
.. Überprüfen Sie den Status des laufenden MetroCluster-Prüfvorgangs:
+
`metrocluster operation history show -job-id 38`

.. Vergewissern Sie sich, dass es keine Systemzustandsmeldungen gibt:
+
`system health alert show`



. link:../install-ip/switch-move-cluster-lifs.html["Die Cluster-LIFs verschieben"] bevor Sie mit dem Upgrade beginnen.
. Bereiten Sie die IP-Switches auf die Anwendung der neuen RCFs vor.
+
Befolgen Sie die Schritte für Ihren Switch-Anbieter:

+
** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults["Setzen Sie den Broadcom IP-Switch auf die Werkseinstellungen zurück"]
** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults["Setzen Sie den Cisco IP-Switch auf die Werkseinstellungen zurück"]
** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults["Setzen Sie den NVIDIA IP SN2100-Switch auf die Werkseinstellungen zurück"]


. Die IP RCFs können je nach Switch-Hersteller heruntergeladen und installiert werden.
+
** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files["Die Broadcom IP RCFs herunterladen und installieren"]
** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files["Laden Sie die Cisco IP-RCFs herunter, und installieren Sie sie"]
** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files["Laden Sie die NVIDIA IP-RCFs herunter, und installieren Sie sie"]
+

NOTE: Wenn Sie über eine freigegebene L2- oder L3-Netzwerkkonfiguration verfügen, müssen Sie möglicherweise die ISL-Ports an den Zwischen-/Kunden-Switches anpassen. Der Switchport-Modus kann von „Access“ auf „Trunk“ geändert werden. Fahren Sie nur mit dem Upgrade des zweiten Switch-Paares (A_2, B_2) fort, wenn die Netzwerkverbindung zwischen den Switches A_1 und B_1 voll funktionsfähig ist und das Netzwerk ordnungsgemäß ist.



. Die vorherigen Schritte sind für jeden der Switches zu wiederholen.
+

NOTE: Nachdem die Switches im ersten Fabric (Switch_A_1, Switch_B_1) konfiguriert wurden, sind die Schritte zum Verschieben der Cluster-LIFs im zweiten Fabric (Switch_A_2, Switch_B_2) zu wiederholen. Siehe link:../install-ip/task_install_and_cable_the_mcc_components.html["Informationen zur Konfiguration der MetroCluster IP-Switches"].


