---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_cisco_fc_switch_mcc.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, cisco, fc, switch 
summary: Zum Upgrade oder Downgrade der Firmware auf einem Cisco FC-Switch müssen Sie den Switch mit den Cisco-spezifischen Befehlen deaktivieren, das Upgrade durchführen und überprüfen sowie den Switch neu starten und wieder aktivieren. 
---
= Upgrade oder Downgrade der Firmware auf einem Cisco FC Switch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Upgrade oder Downgrade der Firmware auf einem Cisco FC-Switch müssen Sie den Switch mit den Cisco-spezifischen Befehlen deaktivieren, das Upgrade durchführen und überprüfen sowie den Switch neu starten und wieder aktivieren.

* Das System muss ordnungsgemäß verkabelt sein.
* Alle Pfade zu den Storage Shelves müssen verfügbar sein.
* Die Platten-Shelf-Stacks müssen stabil sein.
* Die FC-Switch-Fabric muss sich in einem ordnungsgemäßen Zustand befinden.
* Alle Komponenten im System müssen ordnungsgemäß sein.
* Das System muss ordnungsgemäß ausgeführt werden.
* Sie benötigen das Admin-Passwort und den Zugriff auf einen FTP- oder SCP-Server.


Die Switch-Fabric wird während des Firmware-Upgrades oder Downgrades deaktiviert und die MetroCluster-Konfiguration basiert auf der zweiten Fabric, um den Betrieb fortzusetzen.

Sie müssen diese Aufgabe nacheinander an jeder Switch-Fabric wiederholen, um sicherzustellen, dass alle Switches dieselbe Firmware-Version verwenden.

Sie müssen über die Firmware-Dateien verfügen.


NOTE: Dieser Vorgang läuft unterbrechungsfrei ab und dauert etwa eine Stunde.

.Schritte
. Melden Sie sich bei jedem der Switches in der Fabric an.
+
In den Beispielen werden die Switches FC_Switch_A_1 und FC_Switch_B_1 genannt.

. Bestimmen Sie, ob auf jedem Switch genügend Speicherplatz im Bootflash-Verzeichnis vorhanden ist:
+
`*dir bootflash*`

+
Wenn dies nicht der Fall ist, löschen Sie die unerwünschten Firmware-Dateien mithilfe des `delete bootflash:file_name` Befehl.

. Kopieren Sie die Kickstart- und Systemdateien auf die Switches:
+
`*copy _source_filetarget_file_*`

+
Im folgenden Beispiel die Kickstart-Datei (`m9200-s2ek9-kickstart-mz.5.2.1.bin`) Und die Systemdatei (`m9200-s2ek9-mz.5.2.1.bin`) Befinden sich auf dem FTP-Server 10.10.10.55 in der `/firmware/` Pfad:

+
Im folgenden Beispiel werden die Befehle angezeigt, die für FC_Switch_A_1 ausgegeben wurden:

+
[listing]
----
FC_switch_A_1# copy ftp://10.10.10.55/firmware/m9200-s2ek9-kickstart-mz.5.2.1.bin bootflash:m9200-s2ek9-kickstart-mz.5.2.1.bin
FC_switch_A_1# copy ftp://10.10.10.55/firmware/m9200-s2ek9-mz.5.2.1.bin bootflash:m9200-s2ek9-mz.5.2.1.bin
----
. Deaktivieren Sie alle VSANs auf beiden Switches in dieser Fabric.
+
Gehen Sie folgendermaßen vor, um die VSANs zu deaktivieren:

+
.. Öffnen Sie das Konfigurations-Terminal:
+
`*config t*`

.. Geben Sie Ein: `*vsan database*`
.. Überprüfen Sie den Status der VSANs:
+
`*show vsan*`

+
Alle VSANs müssen aktiv sein.

.. Unterbrechen Sie die VSANs:
+
`*vsan _vsan-num_ suspend*`

+
*Beispiel:* `vsan 10 suspend`

.. Überprüfen Sie den Status der VSANs erneut:
+
`*show vsan*`+ Alle VSANs müssen ausgesetzt werden.

.. Beenden Sie das config-Terminal:
+
`*end*`

.. Speichern Sie die Konfiguration.
+
`*copy running-config startup-config*`

+
Im folgenden Beispiel wird die Ausgabe für FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1# config t
Enter configuration commands, one per line.  End with CNTL/Z.
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 30 information
         name:MC1_FCVI_2_30  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 40 information
         name:MC1_STOR_2_40  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 70 information
         name:MC2_FCVI_2_70  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 80 information
         name:MC2_STOR_2_80  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# vsan 1 suspend
FC_switch_A_1(config-vsan-db)# vsan 30 suspend
FC_switch_A_1(config-vsan-db)# vsan 40 suspend
FC_switch_A_1(config-vsan-db)# vsan 70 suspend
FC_switch_A_1(config-vsan-db)# vsan 80 suspend
FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1#
FC_switch_A_1# show vsan
vsan 1 information
         name:VSAN0001  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 30 information
         name:MC1_FCVI_2_30  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 40 information
         name:MC1_STOR_2_40  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 70 information
         name:MC2_FCVI_2_70  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 80 information
         name:MC2_STOR_2_80  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan
----


. Installieren Sie die gewünschte Firmware auf den Switches:
+
`*install all system bootflash:__systemfile_name__ kickstart bootflash:__kickstartfile_name__*`

+
Im folgenden Beispiel werden die Befehle angezeigt, die für FC_Switch_A_1 ausgegeben wurden:

+
[listing]
----
FC_switch_A_1# install all system bootflash:m9200-s2ek9-mz.5.2.1.bin kickstart bootflash:m9200-s2ek9-kickstart-mz.5.2.1.bin
Enter Yes to confirm the installation.
----
. Überprüfen Sie die Firmware-Version auf jedem Switch, um sicherzustellen, dass die richtige Version installiert ist:
+
`*show version*`

. Aktivieren Sie alle VSANs auf beiden Switches in dieser Fabric.
+
Gehen Sie folgendermaßen vor, um die VSANs zu aktivieren:

+
.. Öffnen Sie das Konfigurations-Terminal:
+
`*config t*`

.. Geben Sie Ein: `*vsan database*`
.. Überprüfen Sie den Status der VSANs:
+
`*show vsan*`

+
Die VSANs müssen ausgesetzt werden.

.. VSANs aktivieren:
+
`*no vsan _vsan-num_ suspend*`

+
*Beispiel:* `no vsan 10 suspend`

.. Überprüfen Sie den Status der VSANs erneut:
+
`*show vsan*`

+
Alle VSANs müssen aktiv sein.

.. Beenden Sie das config-Terminal:
+
`*end*`

.. Konfiguration speichern:
+
`*copy running-config startup-config*`

+
Im folgenden Beispiel wird die Ausgabe für FC_Switch_A_1 angezeigt:

+
[listing]
----
FC_switch_A_1# config t
Enter configuration commands, one per line.  End with CNTL/Z.
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 30 information
         name:MC1_FCVI_2_30  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 40 information
         name:MC1_STOR_2_40  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 70 information
         name:MC2_FCVI_2_70  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:down

vsan 80 information
         name:MC2_STOR_2_80  state:suspended
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:down

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# no vsan 1 suspend
FC_switch_A_1(config-vsan-db)# no vsan 30 suspend
FC_switch_A_1(config-vsan-db)# no vsan 40 suspend
FC_switch_A_1(config-vsan-db)# no vsan 70 suspend
FC_switch_A_1(config-vsan-db)# no vsan 80 suspend
FC_switch_A_1(config-vsan-db)#
FC_switch_A_1(config-vsan-db)# show vsan
vsan 1 information
         name:VSAN0001  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 30 information
         name:MC1_FCVI_2_30  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 40 information
         name:MC1_STOR_2_40  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 70 information
         name:MC2_FCVI_2_70  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id
         operational state:up

vsan 80 information
         name:MC2_STOR_2_80  state:active
         interoperability mode:default
         loadbalancing:src-id/dst-id/oxid
         operational state:up

vsan 4079:evfp_isolated_vsan

vsan 4094:isolated_vsan

FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1#
----


. Überprüfen Sie den Betrieb der MetroCluster-Konfiguration in ONTAP:
+
.. Prüfen Sie, ob das System multipathed ist:
+
`*node run -node _node-name_ sysconfig -a*`

.. Überprüfen Sie auf beiden Clustern auf Zustandswarnmeldungen:
+
`*system health alert show*`

.. Bestätigen Sie die MetroCluster-Konfiguration und den normalen Betriebsmodus:
+
`*metrocluster show*`

.. Durchführen einer MetroCluster-Prüfung:
+
`*metrocluster check run*`

.. Ergebnisse der MetroCluster-Prüfung anzeigen:
+
`*metrocluster check show*`

.. Prüfen Sie, ob auf den Switches Zustandswarnmeldungen vorliegen (falls vorhanden):
+
`*storage switch show*`

.. Nutzen Sie Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"]

.. Überprüfen Sie nach dem Ausführen von Config Advisor die Ausgabe des Tools und befolgen Sie die Empfehlungen in der Ausgabe, um die erkannten Probleme zu beheben.


. Wiederholen Sie diesen Vorgang für die zweite Switch-Struktur.

