---
permalink: maintain/task_do_not_use_for_9_8_and_later_reconfigure_the_fc_switch_layout_for_ontap_9_1_or_later.html 
sidebar: sidebar 
keywords: metrocluster, maintain, service, reconfigure, fc, switch, layout, configured 
summary: 'Wenn das vorhandene FC-Switch-Layout vor ONTAP 9.1 konfiguriert wurde, müssen Sie das Port-Layout neu konfigurieren und die neuesten RCFs (Reference Configuration Files) anwenden. Dieses Verfahren gilt nur für MetroCluster FC-Konfigurationen.' 
---
= Neukonfigurieren eines FC-Switch-Layouts, das vor ONTAP 9.x konfiguriert ist
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das vorhandene FC-Switch-Layout vor ONTAP 9.1 konfiguriert wurde, müssen Sie das Port-Layout neu konfigurieren und die neuesten RCFs (Reference Configuration Files) anwenden. Dieses Verfahren gilt nur für MetroCluster FC-Konfigurationen.

.Bevor Sie beginnen
Sie müssen die in der Fabric-Domäne vorhandenen FC-Switches identifizieren.

Sie benötigen das Admin-Passwort und den Zugriff auf einen FTP- oder SCP-Server.

Sie müssen diese Aufgabe ausführen, wenn Ihr vorhandenes FC-Switch-Layout vor ONTAP 9.1 konfiguriert wurde. Dies ist _nicht_ erforderlich, wenn Sie ein Upgrade von einem vorhandenen Switch-Layout durchführen, das für ONTAP 9.1 oder höher konfiguriert wurde.

.Über diese Aufgabe
Dieser Vorgang läuft unterbrechungsfrei ab und dauert etwa vier Stunden (außer Rack und Stack), wenn Festplatten gelöscht werden.



== Senden einer benutzerdefinierten AutoSupport Meldung vor dem Neukonfigurieren der Switches

Bevor Sie Ihre Switches neu konfigurieren, sollten Sie eine AutoSupport Meldung ausgeben, um den technischen Support von NetApp über laufende Wartungsarbeiten zu informieren. Die Mitteilung des technischen Supports über laufende Wartungsarbeiten verhindert, dass ein Fall eröffnet wird, wenn eine Störung aufgetreten ist.

Diese Aufgabe muss auf jedem MetroCluster-Standort ausgeführt werden.

.Schritte
. Melden Sie sich bei dem Cluster an.
. Rufen Sie eine AutoSupport-Meldung auf, die den Beginn der Wartung angibt:
+
`system node autosupport invoke -node * -type all -message MAINT=__maintenance-window-in-hours__*`

+
Maintenance-Fenster in Stunden gibt die Länge des Wartungsfensters an, mit maximal 72 Stunden. Wenn die Wartung vor dem Vergehen der Zeit abgeschlossen ist, können Sie eine AutoSupport-Meldung mit dem Ende des Wartungszeitraums aufrufen:

+
`system node autosupport invoke -node * -type all -message MAINT=end`

. Wiederholen Sie diese Schritte auf der Partner-Site.




== Überprüfen des Systemzustands der MetroCluster-Konfiguration

Sie sollten den Systemzustand der MetroCluster-Konfiguration überprüfen, um einen ordnungsgemäßen Betrieb zu gewährleisten.

.Schritte
. Vergewissern Sie sich, dass die MetroCluster-Komponenten ordnungsgemäß sind:
+
`metrocluster check run`

+
[listing]
----
cluster_A::*> metrocluster check run

----
+
Der Vorgang wird im Hintergrund ausgeführt.

. Nach dem `metrocluster check run` Vorgang abgeschlossen, Ausführung `metrocluster check show` Um die Ergebnisse anzuzeigen.
+
Nach etwa fünf Minuten werden die folgenden Ergebnisse angezeigt:

+
[listing]
----
-----------
cluster_A::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----
. Um den Status des ausgeführten MetroCluster-Prüfvorgangs zu überprüfen, verwenden Sie den Befehl:
+
`metrocluster operation history show -job-id 38`

. Vergewissern Sie sich, dass es keine Systemzustandsmeldungen gibt:
+
`system health alert show`





== Prüfen auf MetroCluster-Konfigurationsfehler

Sie können das Config Advisor Tool auf der NetApp Support-Website verwenden, um häufige Konfigurationsfehler zu überprüfen.

Config Advisor ist ein Tool zur Konfigurationsvalidierung und Statusüberprüfung. Sie können die Lösung sowohl an sicheren Standorten als auch an nicht sicheren Standorten zur Datenerfassung und Systemanalyse einsetzen.


NOTE: Der Support für Config Advisor ist begrenzt und steht nur online zur Verfügung.

. Laden Sie das Config Advisor Tool herunter.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp Downloads: Config Advisor"^]

. Führen Sie Config Advisor aus, überprüfen Sie die Ausgabe und folgen Sie seinen Empfehlungen, um eventuelle Probleme zu beheben.




== Ständige Deaktivierung der Switches

Sie müssen die Switches in der Fabric dauerhaft deaktivieren, damit Sie seine Konfiguration ändern können.

Sie deaktivieren die Switches, indem Sie die Befehle in der Switch-Befehlszeile ausführen. Die dafür verwendeten Befehle sind keine ONTAP-Befehle.

.Schritte
. Deaktivieren Sie den Switch dauerhaft:
+
** Verwenden Sie den folgenden Befehl, um einen Brocade-Switch dauerhaft zu deaktivieren:
+
`FC_switch_A_1:admin> switchCfgPersistentDisable`

** Verwenden Sie den folgenden Befehl, um einen Cisco-Switch dauerhaft zu deaktivieren:
+
`vsan [vsna #] suspend`







== Bestimmen des neuen Verkabelungslayouts

Sie müssen die Verkabelung der neuen Controller-Module und aller neuen Platten-Shelfs zu den vorhandenen FC-Switches bestimmen.

Diese Aufgabe muss an jedem MetroCluster Standort ausgeführt werden.

.Schritte
. Nutzung https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"^] Um das Verkabelungslayout für Ihren Switch-Typ zu bestimmen, verwenden Sie die Portnutzung für eine MetroCluster-Konfiguration mit acht Nodes.
+
Die Verwendung des FC-Switch-Ports muss mit der in der Anleitung beschriebenen Verwendung übereinstimmen, sodass die RCFs (Reference Configuration Files) verwendet werden können.

+

NOTE: Verwenden Sie dieses Verfahren nicht, wenn die Verkabelung keine RCFs verwenden kann.





== Anwenden von RCF-Dateien und Neuverkabeln der Switches

Sie müssen die entsprechenden RCF-Dateien (Referenzkonfigurationsdateien) anwenden, um Ihre Switches neu zu konfigurieren, damit die neuen Nodes berücksichtigt werden können. Nachdem Sie die RCF-Dateien angewendet haben, können Sie die Schalter neu auftragen.

Die Verwendung des FC-Switch-Ports muss der in beschriebenen Verwendung entsprechen https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installation und Konfiguration von Fabric-Attached MetroCluster"^] Damit die RCFs verwendet werden können.

.Schritte
. Suchen Sie die RCF-Dateien für Ihre Konfiguration.
+
Sie müssen die RCF-Dateien verwenden, die Ihrem Switch-Modell entsprechen.

. Wenden Sie die RCF-Dateien an, folgen Sie den Anweisungen auf der Download-Seite und passen Sie die ISL-Einstellungen nach Bedarf an.
. Vergewissern Sie sich, dass die Switch-Konfiguration gespeichert ist.
. Verbinden Sie die beiden FC-zu-SAS-Brücken mit den FC-Switches, indem Sie das Verkabelungslayout verwenden, das Sie im Abschnitt „`DEterminung des neuen Verkabelungslayouts`“ erstellt haben.
. Vergewissern Sie sich, dass die Ports online sind:
+
** Verwenden Sie für Brocade-Switches den `switchshow` Befehl.
** Verwenden Sie für Cisco Switches das `show interface brief` Befehl.


. Verkabeln Sie die FC-VI-Ports von den Controllern mit den Switches.
. Vergewissern Sie sich von den vorhandenen Nodes, dass die FC-VI-Ports online sind:
+
`metrocluster interconnect adapter show`

+
`metrocluster interconnect mirror show`





== Die Switches dauerhaft aktivieren

Sie müssen die Switches im Fabric dauerhaft aktivieren.

.Schritte
. Dauerhaft aktivieren Sie den Switch:
+
** Verwenden Sie für Brocade-Switches den `switchCfgPersistentenable` Befehl.
** Verwenden Sie bei Cisco Switches das Nein `suspend` Befehl. Der folgende Befehl aktiviert dauerhaft einen Brocade-Switch:
+
[listing]
----
FC_switch_A_1:admin> switchCfgPersistentenable
----
+
Mit dem folgenden Befehl wird ein Cisco Switch aktiviert:

+
[listing]
----
vsan [vsna #]no suspend
----






== Überprüfung von Umschaltung, Reparatur und Wechsel zurück

Sie sollten die Umschalttavorgänge, die Reparatur und den Wechsel der MetroCluster Konfiguration überprüfen.

. Verwenden Sie die Verfahren für die ausgehandelte Umschaltung, Heilung und Umschalttastelle, die in beschrieben sind https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_dr_workflow.html["MetroCluster Management und Disaster Recovery"^].

