---
permalink: maintain/task-modify-ip-netmask-properties.html 
sidebar: sidebar 
keywords: vlan, ip, gateway,netmask, address, network, interface, subnet 
summary: Sie können die folgenden Eigenschaften einer MetroCluster-IP-Schnittstelle, IP-Adresse und -Maske sowie eines Gateways ändern. Sie können jede beliebige Kombination von Parametern zum Aktualisieren verwenden. 
---
= Ändern Sie die Eigenschaften einer MetroCluster-IP-Schnittstelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab ONTAP 9.10.1 können Sie die folgenden Eigenschaften einer MetroCluster IP-Schnittstelle ändern: IP-Adresse und -Maske sowie Gateway. Sie können jede beliebige Kombination von Parametern zum Aktualisieren verwenden.

Möglicherweise müssen Sie diese Eigenschaften aktualisieren, z. B. wenn eine doppelte IP-Adresse erkannt wird oder wenn ein Gateway aufgrund von Änderungen der Routerkonfiguration im Fall eines Layer 3-Netzwerks geändert werden muss.

.Über diese Aufgabe
* Sie können jeweils nur eine Schnittstelle ändern. Es wird eine Verkehrsunterbrechung auf dieser Schnittstelle geben, bis die anderen Schnittstellen aktualisiert und Verbindungen wiederhergestellt sind.
* Verwenden Sie die `metrocluster configuration-settings interface modify` Befehl zum Ändern einer MetroCluster IP-Schnittstelleneigenschaft.
+

NOTE: Mit diesen Befehlen wird die Konfiguration auf einem bestimmten Node für einen bestimmten Port geändert. Um eine vollständige Netzwerkverbindung wiederherzustellen, sind ähnliche Befehle auf anderen Ports erforderlich. Auf ähnliche Weise müssen Netzwerk-Switches auch ihre Konfiguration aktualisieren. Wenn das Gateway beispielsweise aktualisiert wird, wird idealerweise auf beiden Knoten eines HA-Paares geändert, da sie identisch sind. Außerdem muss der mit diesen Nodes verbundene Switch auch sein Gateway aktualisieren.

* Mit den `metrocluster configuration-settings interface show`Befehlen , `metrocluster connection check`und `metrocluster connection show` können Sie überprüfen, ob alle Verbindungen in allen Schnittstellen funktionieren.




== Ändern Sie die IP-Adresse, die Netmask und das Gateway

Führen Sie die folgenden Schritte aus, um die IP-Adresse, die Netzmaske und das Gateway einer MetroCluster IP-Schnittstelle zu ändern.

.Schritte
. Aktualisieren Sie die IP-Adresse, die Netmask und das Gateway für einen einzelnen Node und eine einzelne Schnittstelle:
`metrocluster configuration-settings interface modify`
+
Mit dem folgenden Befehl wird gezeigt, wie die IP-Adresse, die Netmask und das Gateway aktualisiert werden:

+
[listing]
----
cluster_A::* metrocluster configuration-settings interface modify -cluster-name cluster_A -home-node node_A_1 -home-port e0a-10 -address 192.168.12.101 -gateway 192.168.12.1 -netmask 255.255.254.0
(metrocluster configuration-settings interface modify)
Warning: This operation will disconnect and reconnect iSCSI and RDMA connections used for DR protection through port “e0a-10”. Partner nodes may need modifications for port “e0a-10” in order to completely establish network connectivity.
Do you want to continue?" yes
[Job 28] Setting up iSCSI target configuration. (pass2:iscsi13:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
[Job 28] Establishing iSCSI initiator connections.
(pass6:iscsi14:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
(pass8:iscsi15:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
(pass9:iscsi16:0:-1:0): xpt_action_default: CCB type 0xe XPT_DEV_ADVINFO not supported
[Job 28] Job succeeded: Interface Modify is successful.
cluster_A::*> metrocluster configuration-settings interface modify -cluster-name cluster_A -home-node node_A_2 -home-port e0a-10 -address 192.168.12.201 -gateway 192.168.12.1 -netmask 255.255.254.0
(metrocluster configuration-settings interface modify)
Warning: This operation will disconnect and reconnect iSCSI and RDMA connections used for DR protection through port “e0a-10”. Partner nodes may need modifications for port “e0a-10” in order to completely establish network connectivity.
Do you want to continue?" yes
[Job 28] Job succeeded: Interface Modify is successful
----
. [[Schritt2]]Überprüfen Sie, ob alle Verbindungen für alle Schnittstellen funktionieren:
`metrocluster configuration-settings interface show`
+
Mit dem folgenden Befehl wird gezeigt, wie Sie überprüfen können, ob alle Verbindungen für alle Schnittstellen funktionieren:

+
[listing]
----
cluster_A::*> metrocluster configuration-settings interface show
(metrocluster configuration-settings interface show)                                                 DR              Config
Group Cluster Node    Network Address Netmask         Gateway         State
----- ------- ------- --------------- --------------- --------------- ---------
1     cluster_A node_A_2
                 Home Port: e0a-10
                      192.168.12.201  255.255.254.0   192.168.12.1    completed
                 Home Port: e0b-20
                      192.168.20.200  255.255.255.0   192.168.20.1    completed
                node_A_1
                 Home Port: e0a-10
                      192.168.12.101  255.255.254.0   192.168.12.1    completed
                 Home Port: e0b-20
                      192.168.20.101  255.255.255.0   192.168.20.1    completed
      cluster_B node_B_1
                 Home Port: e0a-10
                      192.168.11.151  255.255.255.0   192.168.11.1    completed
                 Home Port: e0b-20
                      192.168.21.150  255.255.255.0   192.168.21.1    completed
                node_B_2
                 Home Port: e0a-10
                      192.168.11.250  255.255.255.0   192.168.11.1    completed
                 Home Port: e0b-20
                      192.168.21.250  255.255.255.0   192.168.21.1    completed
8 entries were displayed.
----


. [[Schritt3]]Überprüfen Sie, ob alle Verbindungen funktionieren:
+
`metrocluster configuration-settings connection show`

+
Mit dem folgenden Befehl wird gezeigt, wie Sie überprüfen können, ob alle Verbindungen funktionieren:

+
[listing]
----
cluster_A::*> metrocluster configuration-settings connection show
  (metrocluster configuration-settings connection show)
DR                    Source          Destination
Group Cluster Node    Network Address Network Address Partner Type Config State
----- ------- ------- --------------- --------------- ------------ ------------
1     cluster_A node_A_2
                 Home Port: e0a-10
                      192.168.10.200  192.168.10.101  HA Partner   completed
                 Home Port: e0a-10
                      192.168.10.200  192.168.11.250  DR Partner   completed
                 Home Port: e0a-10
                      192.168.10.200  192.168.11.151  DR Auxiliary completed
                 Home Port: e0b-20
                      192.168.20.200  192.168.20.100  HA Partner   completed
                 Home Port: e0b-20
                      192.168.20.200  192.168.21.250  DR Partner   completed
                 Home Port: e0b-20
                      192.168.20.200  192.168.21.150  DR Auxiliary completed
                node_A_1
                 Home Port: e0a-10
                      192.168.10.101  192.168.10.200  HA Partner   completed
                 Home Port: e0a-10
                      192.168.10.101  192.168.11.151  DR Partner   completed
                 Home Port: e0a-10
                      192.168.10.101  192.168.11.250  DR Auxiliary completed
                 Home Port: e0b-20
                      192.168.20.100  192.168.20.200  HA Partner   completed
                 Home Port: e0b-20
                      192.168.20.100  192.168.21.150  DR Partner   completed
                 Home Port: e0b-20
                      192.168.20.100  192.168.21.250  DR Auxiliary completed
----

