---
permalink: install-stretch/concept_required_mcc_components_and_naming_conventions_for_two_node_bridge_attached_stretch_configurations_mcc.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, required, hardware, components, naming, conventions, two, node, stretch, bridge 
summary: Bei der Planung der MetroCluster-Konfiguration müssen Sie die erforderlichen und unterstützten Hardware- und Software-Komponenten kennen. Für Einfachheit und Klarheit sollten Sie auch die Namenskonventionen verstehen, die für Komponenten in Beispielen in der gesamten Dokumentation verwendet werden. Ein Standort wird beispielsweise als Standort A bezeichnet, der andere Standort wird als Standort B bezeichnet 
---
= Erforderliche MetroCluster Hardwarekomponenten und Namenskonventionen für über Bridge angeschlossene Stretch-Konfigurationen mit zwei Nodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Planung der MetroCluster-Konfiguration müssen Sie die erforderlichen und unterstützten Hardware- und Software-Komponenten kennen. Für Einfachheit und Klarheit sollten Sie auch die Namenskonventionen verstehen, die für Komponenten in Beispielen in der gesamten Dokumentation verwendet werden. Ein Standort wird beispielsweise als Standort A bezeichnet, der andere Standort wird als Standort B bezeichnet



== Unterstützte Software und Hardware

Hardware und Software müssen für die MetroCluster FC-Konfiguration unterstützt werden.

https://hwu.netapp.com["NetApp Hardware Universe"]

Beim Einsatz von AFF Systemen müssen alle Controller-Module in der MetroCluster Konfiguration als AFF Systeme konfiguriert sein.



== Hardwareredundanz in der MetroCluster Konfiguration

Aufgrund der Hardware-Redundanz in der MetroCluster Konfiguration gibt es an jedem Standort zwei Komponenten. Den Standorten werden die Buchstaben A und B willkürlich zugeordnet und den einzelnen Komponenten werden die Zahlen 1 und 2 willkürlich zugeordnet.



== Bedarf an ONTAP Single-Node Clustern

Für die Stretch-MetroCluster Konfiguration über Bridge sind zwei Single-Node-ONTAP-Cluster erforderlich.

Die Benennung muss innerhalb der MetroCluster Konfiguration eindeutig sein.

Beispielnamen:

* Standort A: Cluster_A
* Standort B: Cluster_B




== Anforderung von zwei Storage Controller-Modulen

Die Bridge-Attached Stretch-MetroCluster-Konfiguration erfordert zwei Storage Controller-Module.

Die Controller müssen die folgenden Anforderungen erfüllen:

* Die Benennung muss innerhalb der MetroCluster Konfiguration eindeutig sein.
* Alle Controller-Module in der MetroCluster Konfiguration müssen dieselbe Version von ONTAP ausführen.
* Alle Controller-Module in einer DR-Gruppe müssen aus dem gleichen Modell sein.
* Alle Controller-Module in einer DR-Gruppe müssen dieselbe FC-VI-Konfiguration verwenden.
+
Einige Controller Module unterstützen zwei Optionen für FC-VI-Konnektivität:

+
** Integrierte FC-VI-Ports
** Eine FC-VI-Karte in Steckplatz 1
+
Ein Mix aus einem Controller-Modul mit integrierten FC-VI-Ports und einem anderen Controller-Modul mit einer zusätzlichen FC-VI-Karte wird nicht unterstützt. Wenn beispielsweise ein Node integrierte FC-VI-Konfiguration verwendet, müssen alle anderen Nodes in der DR-Gruppe auch integrierte FC-VI-Konfigurationen verwenden.





Beispielnamen:

* Standort A: Controller_A_1
* Standort B: Controller_B_1




== Notwendigkeit für FC-to-SAS-Bridges

Die Stretch MetroCluster-Konfiguration über die Bridge erfordert an jedem Standort zwei oder mehr FC-to-SAS-Bridges.

Diese Brücken verbinden die SAS-Platten-Shelfs mit den Controller-Modulen.


NOTE: FibreBridge 6500N-Brücken werden in Konfigurationen mit ONTAP 9.8 und höher nicht unterstützt.

* FibreBridge 7600N und 7500N-Brücken unterstützen bis zu vier SAS-Stacks.
* Jeder Stack kann verschiedene IOM-Modelle verwenden, allerdings müssen alle Shelfs in einem Stack dasselbe Modell verwenden.
+
Die unterstützten IOM-Modelle hängen von der ONTAP-Version ab, die Sie ausführen.

* Die Benennung muss innerhalb der MetroCluster Konfiguration eindeutig sein.


Die vorgeschlagenen Namen, die in diesem Verfahren als Beispiele verwendet werden, identifizieren das Controller-Modul, mit dem die Bridge eine Verbindung herstellt, und den Port.

Beispielnamen:

* Standort A:
+
** Bridge_A_1_``__port-number__``
** Bridge_A_2_``__port-number__``


* Standort B:
+
** Bridge_B_1_``__port-number__``
** Bridge_B_2_``__port-number__``






== Anforderung für mindestens vier SAS-Shelves (empfohlen)

Für die Stretch MetroCluster-Konfiguration über Bridge ist mindestens zwei SAS Shelfs erforderlich. Es werden jedoch zwei Shelves an jedem Standort empfohlen, damit die Festplatteneigentümer auf Shelf-Basis ausgeführt werden können, also insgesamt vier SAS Shelfs.

Es wird mindestens ein Shelf an jedem Standort unterstützt.

Beispielnamen:

* Standort A:
+
** Shelf_A_1_1
** Shelf_A_1_2


* Standort B:
+
** Shelf_B_1_1
** Shelf_B_1_2






== Mischen von IOM12 und IOM 6 Modulen in einem Stack

Ihre Version von ONTAP muss Shelf-Mix unterstützen. Informieren Sie sich im Interoperabilitäts-Matrix-Tool (IMT), ob Ihre Version von ONTAP Shelf-Mischungen unterstützt. https://imt.netapp.com/matrix/["IMT"^]

Weitere Informationen zum Anmischen von Regalen finden Sie unter: https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Hot-Adding-Shelfs mit IOM12-Modulen werden in einem Shelf-Stack mit IOM6-Modulen ausgeführt"^]
