---
permalink: install-stretch/concept_deciding_whether_to_use_this_guide_stretch_mcc_installation_and_configuration_guide.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, stretch, configuration, decide 
summary: 'In dieser Information wird die Installation und Konfiguration der Hardware- und Softwarekomponenten von MetroCluster in einer Stretch-Konfiguration beschrieben \ (auch als optische SAS-MetroCluster-Konfiguration bezeichnet\).' 
---
= Installation und Konfiguration von Stretch MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In dieser Information wird beschrieben, wie Sie MetroCluster Hardware- und Softwarekomponenten in einer Stretch-Konfiguration installieren und konfigurieren (auch als SAS-optische MetroCluster-Konfiguration bezeichnet).

Diese Informationen sollten Sie unter den folgenden Umständen zur Planung, Installation und Konfiguration einer Stretch-MetroCluster-Konfiguration verwenden:

* Sie möchten die Architektur einer Stretch-MetroCluster-Konfiguration verstehen.
* Sie möchten die Anforderungen und Best Practices für die Konfiguration einer Stretch-MetroCluster-Konfiguration kennen.
* Sie möchten die Befehlszeilenschnittstelle (CLI) verwenden, kein automatisiertes Scripting Tool.

