---
permalink: install-stretch/concept_choosing_the_correct_installation_procedure_for_your_configuration_mcc_install.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, correct, procedure, configuration 
summary: Sie müssen das richtige Installationsverfahren basierend darauf auswählen, wie die Speichercontroller mit den Speicherregalen verbunden werden. 
---
= Auswahl des richtigen Installationsverfahrens für Ihre Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das richtige Installationsverfahren basierend darauf auswählen, wie die Speichercontroller mit den Speicherregalen verbunden werden.

|===


| Für diesen Installationstyp... | Verwenden Sie diese Verfahren... 


 a| 
Stretch-Konfiguration mit zwei Nodes und FC-zu-SAS-Bridges
 a| 
. link:task_configure_the_mcc_hardware_components_2_node_stretch_atto.html["Verkabelung einer Stretch MetroCluster Konfiguration mit zwei über Bridge angebundenen Nodes"]
. link:concept_configuring_the_mcc_software_in_ontap.html["Konfigurieren der MetroCluster-Software in ONTAP"]




 a| 
Stretch-Konfiguration mit zwei Nodes und Direct-Attached SAS-Verkabelung
 a| 
. link:task_configure_the_mcc_hardware_components_2_node_stretch_sas.html["Verkabelung einer Stretch MetroCluster Konfiguration mit zwei Nodes über SAS"]
. link:concept_configuring_the_mcc_software_in_ontap.html["Konfigurieren der MetroCluster-Software in ONTAP"]


|===