---
permalink: install-stretch/concept_considerations_when_removing_mcc_configurations.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, considerations, remove, configurations 
summary: 'Sie können die MetroCluster-Konfiguration von allen Nodes einer Disaster Recovery \(DR\)-Gruppe entfernen. Nach dem Entfernen der MetroCluster-Konfiguration sollten alle Festplatten-Konnektivität und Interconnects auf einen unterstützten Zustand eingestellt werden. Wenden Sie sich an den technischen Support, wenn Sie die MetroCluster Konfiguration entfernen müssen.' 
---
= Überlegungen beim Entfernen von MetroCluster-Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die MetroCluster-Konfiguration von allen Nodes einer Disaster Recovery-Gruppe (DR) entfernen. Nach dem Entfernen der MetroCluster-Konfiguration sollten alle Festplatten-Konnektivität und Interconnects auf einen unterstützten Zustand eingestellt werden. Wenden Sie sich an den technischen Support, wenn Sie die MetroCluster Konfiguration entfernen müssen.


IMPORTANT: Die Konfiguration von MetroCluster kann nicht rückgängig gemacht werden. Dieses Verfahren sollte nur mit Unterstützung durch den technischen Support erfolgen. Wenden Sie sich an den technischen Support von NetApp und verweisen Sie auf den entsprechenden Leitfaden für Ihre Konfiguration im link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_remove_nodes_from_a_MetroCluster_configuration_-_Resolution_Guide["Entfernen von Knoten aus einer MetroCluster Konfiguration - Auflösungsleitfaden."^]
