---
permalink: install-stretch/reference_sas_optical_mc_configuring_a_stretch_mcc_system_with_sas_disk_shelves_and_sas_optical_cables.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, install, cable, components, two, node, sas, stretch, attached, configuration 
summary: Die Storage-Controller müssen mit den Storage-Medien und miteinander verbunden werden. Die Storage-Controller müssen außerdem mit dem Daten- und Management-Netzwerk verbunden sein. 
---
= Installation und Verkabelung von MetroCluster Komponenten für Stretch-Konfigurationen mit zwei Nodes über SAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Storage-Controller müssen mit den Storage-Medien und miteinander verbunden werden. Die Storage-Controller müssen außerdem mit dem Daten- und Management-Netzwerk verbunden sein.



== Bevor Sie mit einem Verfahren in diesem Dokument beginnen

Vor Abschluss dieser Aufgabe müssen die folgenden Gesamtanforderungen erfüllt werden:

* Vor der Installation müssen Sie sich zunächst mit Überlegungen und Best Practices zur Installation und Verkabelung von Platten-Shelfs für Ihr Festplatten-Shelf-Modell vertraut machen.
* Alle MetroCluster Komponenten müssen unterstützt werden.
+
https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"]

+
Im IMT können Sie im Feld Storage-Lösung die Auswahl Ihrer MetroCluster Lösung verwenden. Verwenden Sie den * Component Explorer*, um die Komponenten und die ONTAP-Version auszuwählen, um Ihre Suche zu verfeinern. Klicken Sie auf *Ergebnisse anzeigen*, um die Liste der unterstützten Konfigurationen anzuzeigen, die den Kriterien entsprechen.





== Über diese Aufgabe

* Die Begriffe Node und Controller werden synonym verwendet.

