---
permalink: install-stretch/reference_information_gathering_worksheet_for_fc_to_sas_bridges_2_node_atto.html 
sidebar: sidebar 
keywords: metrocluster, stretch, installation, worksheet, fc, sas, bridges, information 
summary: Bevor Sie mit der Konfiguration von MetroCluster-Standorten beginnen, sollten Sie die erforderlichen Konfigurationsinformationen erfassen. 
---
= Arbeitsblatt zur Informationssammlung für FC-to-SAS-Bridges
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie mit der Konfiguration von MetroCluster-Standorten beginnen, sollten Sie die erforderlichen Konfigurationsinformationen erfassen.



[[site-a-fc-to-sas-bridge-1-fcbridgea1a]]
== Standort A, FC-to-SAS-Bridge 1 (FC_Bridge_A_1a)

Jeder SAS-Stack benötigt mindestens zwei FC-to-SAS-Bridges.

Jede Bridge stellt eine Verbindung zu Controller_A_1_ her``__port-number__`` Und Controller_B_1_``__port-number__``.

|===


| Standort A | Ihr Wert 


 a| 
Bridge_A_1a-IP-Adresse
 a| 



 a| 
Bridge_A_1a-Benutzername
 a| 



 a| 
Bridge_A_1a-Passwort
 a| 

|===


[[site-a-fc-to-sas-bridge-2-fcbridgea1b]]
== Standort A, FC-to-SAS-Bridge 2 (FC_Bridge_A_1b)

Jeder SAS-Stack benötigt mindestens zwei FC-to-SAS-Bridges.

Jede Bridge stellt eine Verbindung zu Controller_A_1_ her``__port-number__`` Und Controller_B_1_``__port-number__``.

|===


| Standort A | Ihr Wert 


 a| 
Bridge_A_1b IP-Adresse
 a| 



 a| 
Bridge_A_1b Benutzername
 a| 



 a| 
Bridge_A_1b Passwort
 a| 

|===


[[site-b-fc-to-sas-bridge-1-fcbridgeb1a]]
== Standort B, FC-to-SAS-Bridge 1 (FC_Bridge_B_1a)

Jeder SAS-Stack benötigt mindestens zwei FC-to-SAS-Bridges.

Jede Bridge stellt eine Verbindung zu Controller_A_1_`__Port-Nummer_` und Controller_B_1_`__Port-Nummer__` her.

|===


| Standort B | Ihr Wert 


 a| 
Bridge_B_1a-IP-Adresse
 a| 



 a| 
Bridge_B_1a-Benutzername
 a| 



 a| 
Bridge_B_1a-Passwort
 a| 

|===


[[site-b-fc-to-sas-bridge-2-fcbridgeb1b]]
== Standort B, FC-to-SAS-Bridge 2 (FC_Bridge_B_1b)

Jeder SAS-Stack benötigt mindestens zwei FC-to-SAS-Bridges.

Jede Bridge stellt eine Verbindung zu Controller_A_1_`__Port-Nummer_` und Controller_B_1_`__Port-Nummer__` her.

|===


| Standort B | Ihr Wert 


 a| 
Bridge_B_1b IP-Adresse
 a| 



 a| 
Bridge_B_1b Benutzername
 a| 



 a| 
Bridge_B_1b Passwort
 a| 

|===