---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html 
sidebar: sidebar 
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, additional, information, miscellaneous, guide 
summary: Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster finden Sie in der umfangreichen Dokumentation von NetApp. 
---
= Wo Sie weitere Informationen finden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Weitere Informationen zur Konfiguration und zum Betrieb von MetroCluster erhalten Sie hier.



== MetroCluster und sonstige Informationen

|===


| Informationsdaten | Betreff 


 a| 
link:../index.html["MetroCluster-Dokumentation"]
 a| 
* Alle MetroCluster-Informationen




 a| 
https://www.netapp.com/pdf.html?item=/media/13482-tr4375pdf.pdf["Technischer Bericht 4375 zu NetApp MetroCluster für ONTAP 9.3"^]
 a| 
* Eine technische Übersicht über Konfiguration und Betrieb von MetroCluster
* Best Practices für die Konfiguration von MetroCluster.




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html["Installation und Konfiguration von Fabric-Attached MetroCluster"]
 a| 
* Fabric-Attached MetroCluster-Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der FC-Switches
* Konfigurieren der MetroCluster in ONTAP




 a| 
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html["Installation und Konfiguration von Stretch MetroCluster"]
 a| 
* Stretch-MetroCluster Architektur
* Verkabelung der Konfiguration
* Konfiguration der FC-to-SAS-Bridges
* Konfigurieren der MetroCluster in ONTAP




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html["Installation und Konfiguration von MetroCluster IP"]
 a| 
* MetroCluster IP Architektur
* Verkabelung der Konfiguration
* Konfigurieren der MetroCluster in ONTAP




 a| 
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html["Installation und Konfiguration der MetroCluster Tiebreaker 1.21 Software"]
 a| 
* Monitoring der MetroCluster Konfiguration mit der MetroCluster Tiebreaker Software




 a| 
Active IQ Unified Manager-Dokumentation https://www.netapp.com/support-and-training/documentation/["NetApp Dokumentation: Produktleitfäden und Ressourcen"^]
 a| 
* Monitoring der MetroCluster Konfiguration und Performance




 a| 
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html["Kopienbasierte Transition"]
 a| 
* Migration von Daten von 7-Mode Storage-Systemen zu geclusterten Storage-Systemen


|===