---
permalink: manage/task_heal_the_configuration_in_a_mcc_ip_configuration_ontap_9_4_and_earlier.html 
sidebar: sidebar 
keywords: heal, aggregate, preparation, switchback, operation, configuration, metrocluster, ip, ontap 
summary: Sie müssen die Aggregate heilen, um den Switchback-Betrieb zu ermöglichen. 
---
= Reparieren der Konfiguration in einer MetroCluster IP-Konfiguration (ONTAP 9.4 und früher)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Aggregate heilen, um den Switchback-Betrieb zu ermöglichen.


NOTE: Auf MetroCluster IP-Systemen mit ONTAP 9.5 wird die Reparatur automatisch durchgeführt, und Sie können diese Aufgaben überspringen.

Vor der Durchführung des Heilverfahrens müssen die folgenden Bedingungen vorliegen:

* Eine Umschaltung muss durchgeführt worden sein und der überlebende Standort muss Daten bereitstellen.
* Storage-Shelfs am Disaster-Standort müssen hochgefahren, funktionsfähig und zugänglich sein.
* ISLs müssen verfügbar sein und in Betrieb sein.
* Nodes im verbleibenden Standort dürfen sich nicht im HA-Failover-Status befinden (beide Nodes müssen in Betrieb sein).


Diese Aufgabe bezieht sich ausschließlich auf MetroCluster IP-Konfigurationen, bei denen ONTAP Versionen vor 9.5 ausgeführt werden.

Dieses Verfahren unterscheidet sich von dem Heilverfahren für MetroCluster FC-Konfigurationen.

.Schritte
. Schalten Sie jedes Controller-Modul am Standort ein, der umgeschaltet wurde, und lassen Sie ihn vollständig booten.
+
Wenn vom System die LOADER-Eingabeaufforderung angezeigt wird, führen Sie den aus `boot_ontap` Befehl.

. Durchführen der Heilungsphase des Root-Aggregats: `metrocluster heal root-aggregates`
+
[listing]
----
cluster_A::> metrocluster heal root-aggregates
[Job 137] Job succeeded: Heal Root-Aggregates is successful
----
+
Wenn das Heilen vetoed ist, haben Sie die Möglichkeit, den befehl MetroCluster-Root-Aggregate heilen mit dem Parameter --override-vetoes erneut auszuführen. Wenn Sie diesen optionalen Parameter verwenden, überschreibt das System alle weichen Vetos, die die Heilung verhindern.

. Synchronisieren Sie die Aggregate neu: `metrocluster heal aggregates`
+
[listing]
----
cluster_A::> metrocluster heal aggregates
[Job 137] Job succeeded: Heal Aggregates is successful
----
+
Wenn das Heilen vetoed ist, haben Sie die Möglichkeit, den befehl MetroCluster Heal mit dem Parameter --override-vetoes erneut auszugeben. Wenn Sie diesen optionalen Parameter verwenden, überschreibt das System alle weichen Vetos, die die Heilung verhindern.

. Bestätigen Sie den Abschluss des Heal-Vorgangs, indem Sie den Befehl „MetroCluster Operation show“ im gesunden Cluster ausführen:
+
[listing]
----

cluster_A::> metrocluster operation show
  Operation: heal-aggregates
      State: successful
 Start Time: 7/29/2017 20:54:41
   End Time: 7/29/2017 20:54:42
     Errors: -
----

